### ISSUE TITLE
Emulate OPL4 minimum loop size

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1000]
The OPL4 makes noises when the loop size of a wave is too small. I think it overshoots the end address, perhaps? On openMSX it doesn’t do this. I’ve made four tests, where the loop size is 0, 1, 2, 3 and 4, and recorded the output on a real OPL4. On openMSX, these all sound the same, the sound cuts off in the final part like in the second half of the recording.

See the attached [opl4loops.zip](https://github.com/openMSX/openMSX/files/96546/opl4loops.zip) for test VGMs, a recent build of VGMPlay which can play it, and the real OPL4’s output. You can diff the VGMs to easily see the differences, and open one in Audacity as raw signed 8-bit to listen to the samples. These samples are not rearranged when the VGM is loaded.

**Comment by MBilderbeek** [comment]
This is probably included in the fixes for  #1114.

**Comment by MBilderbeek** [comment]
@grauw can you please confirm the latest Git code has this fixed?

**Comment by MBilderbeek** [comment]
Thanks a lot for testing! Fixed with 6453d5c606f9b12691f6b22831e233d54dfa12c2
If you find any regressions due to these fixes, please let us know.
