### ISSUE TITLE
UI Threading bug causing OpenMSX android crash immediately after first menu on Android 5.0.1

### ISSUE THREAD

**Issue by dragontamer8740** [openMSX/openMSX#1005]
Just want to post my experience. This happens with both nightly builds and 0.12 stable.

I am on said phone at the moment so forgive my bad log posting. Also note that I am rooted (using superuser, not superSU).

I suck at using locgat, so if this is not enough to go on, I've made a backup of my entire logcat output. Let me know when you need more info.

I think it should be enough though, since it clearly looks like an issue with threading. I have threading turned off in the settings, btw.

```
I/ActivityManager(  807): Start proc org.openmsx.android.openmsx for activity org.openmsx.android.openmsx/.MainActivity: pid=19671 uid=10211 gids={50211, 9997, 1028, 1015} abi=armeabi
E/AndroidRuntime(19671): FATAL EXCEPTION: Thread-2069
E/AndroidRuntime(19671): Process: org.openmsx.android.openmsx, PID: 19671
E/AndroidRuntime(19671): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/AndroidRuntime(19671):    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6247)
E/AndroidRuntime(19671):    at android.view.ViewRootImpl.recomputeViewAttributes(ViewRootImpl.java:2877)
E/AndroidRuntime(19671):    at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1292)
E/AndroidRuntime(19671):    at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1292)
E/AndroidRuntime(19671):    at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1292)
E/AndroidRuntime(19671):    at android.view.View.setSystemUiVisibility(View.java:17970)
E/AndroidRuntime(19671):    at org.openmsx.android.openmsx.DimSystemStatusBar$DimSystemStatusBarHoneycomb.dim(MainActivity.java:1302)
E/AndroidRuntime(19671):    at org.openmsx.android.openmsx.MainActivity$1.run(MainActivity.java:296)
E/AndroidRuntime(19671):    at java.lang.Thread.run(Thread.java:818)
I/ActivityManager(  807): Process org.openmsx.android.openmsx (pid 19671) has died
W/InputMethodManagerService(  807): Got RemoteException sending setActive(false) notification to pid 19671 uid 10211
```

**Comment by andete** [comment]
just as a comment, 0.12.0 runs fine on my Nexus 6P (non-rooted)

**Comment by dragontamer8740** [comment]
Really? what OS verstion?

Clearly a threading issue based on the log, at least in 5.0.1. I've not tampered with /system/bin or /system/lib so I don't think it likely that the rooting is causing issues.

To clarify, it crashes after saying "no need to download". That's all it says.

My debian box is offline at the moment - I would like to try to fix it myself but I only have access to cygwin and the android SDK/NDK for windows, sadly... (and not eclipse or any IDE's). Hoping to get this fixed so I can scratch my Final Fantasy MSX2 itch... Always used openMSX on my PC after my FS-A1 died, and FMSX does horribly with sound and the android port isn't actually free (in the stallman sense)

another edit: Just tried 0.11, same deal.

**Comment by awulms** [comment]
Can you please validate what setting you have selected for “separate video thread...“  in device configuration/video settings?

dragontamer8740 notifications@github.com schreef op 28 februari 2016 18:48:26 CET:

> Just want to post my experience. This happens with both nightly builds
> and 0.12 stable.
> 
> I am on said phone at the moment so forgive my bad log posting. Also
> note that I am rooted (using superuser, not superSU).
> 
> I suck at using locgat, so if this is not enough to go on, I've made a
> backup of my entire logcat output. Let me know when you need more info.
> 
> ```
> I/ActivityManager(  807): Start proc org.openmsx.android.openmsx for
> activity org.openmsx.android.openmsx/.MainActivity: pid=19671 uid=10211
> gids={50211, 9997, 1028, 1015} abi=armeabi
> E/AndroidRuntime(19671): FATAL EXCEPTION: Thread-2069
> E/AndroidRuntime(19671): Process: org.openmsx.android.openmsx, PID:
> 19671
> E/AndroidRuntime(19671):
> android.view.ViewRootImpl$CalledFromWrongThreadException: Only the
> original thread that created a view hierarchy can touch its views.
> E/AndroidRuntime(19671):   at
> android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6247)
> E/AndroidRuntime(19671):   at
> android.view.ViewRootImpl.recomputeViewAttributes(ViewRootImpl.java:2877)
> E/AndroidRuntime(19671):   at
> android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1292)
> E/AndroidRuntime(19671):   at
> android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1292)
> E/AndroidRuntime(19671):   at
> android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1292)
> E/AndroidRuntime(19671):   at
> android.view.View.setSystemUiVisibility(View.java:17970)
> E/AndroidRuntime(19671):   at
> org.openmsx.android.openmsx.DimSystemStatusBar$DimSystemStatusBarHoneycomb.dim(MainActivity.java:1302)
> E/AndroidRuntime(19671):   at
> org.openmsx.android.openmsx.MainActivity$1.run(MainActivity.java:296)
> E/AndroidRuntime(19671):   at java.lang.Thread.run(Thread.java:818)
> I/ActivityManager(  807): Process org.openmsx.android.openmsx (pid
> 19671) has died
> W/InputMethodManagerService(  807): Got RemoteException sending
> setActive(false) notification to pid 19671 uid 10211
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/openMSX/openMSX/issues/1005

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MBilderbeek** [comment]
Note that on Android 5.0.2 (non-rooted) on a Motorola Moto-E 2015, it works fine too (tried 0.12.0). I don't see "No need to download". Just the button "Change device configuration" and after that openMSX just starts up.

**Comment by dragontamer8740** [comment]
Well it's failing here, so either it's because of android 5.0.1 or the fact that it's a rooted device. I have no issues with any other apps I try to run. Could someone please look into the actual threading bug I reported? It could be something device-specific there, right? Threading is kinda black magic to me.

It seems mostly self-explanatory here, though, right? http://stackoverflow.com/questions/5161951/android-only-the-original-thread-that-created-a-view-hierarchy-can-touch-its-vi

Note that I'm using the APK from openmsx.org,google play's gives the same issue.

Also, I do get to the "change device configuration" prompt. It fails after that.

Now it's not saying "no need to download" after I disable downloading apllication data. It just says "initializing..." and then drops dead.

**Comment by andete** [comment]
I run android 6.0.1 on my Nexus 6P.

**Comment by awulms** [comment]
Op 29-02-16 om 04:33 schreef dragontamer8740:

> Well it's failing here, so either it's because of android 5.0.1 or the
> fact that it's a rooted device. I have no issues with any other apps I
> try to run. Could someone please look into the actual threading bug I
> reported? It could be something device-specific there, right?
> Threading is kinda black magic to me.
> 
> Hi,

Can you please during start-up tap the button "Change device
configuration", then select "Video settings" and within the Video
settings menu if the option "Separate thread for video..." is checked?

Reverse that setting and then retry if openMSX still crashes.

Thanks and kind regards,
Alex

**Comment by dragontamer8740** [comment]
I have already said that that box was NOT checked. Same thing happens if I do check it though (crashes).

**Comment by MBilderbeek** [comment]
Note that you do need to Download the application data. It will install the necessary data files (it doesn't download anything, confusingly enough).

The threading issue you speak of seems to happen inside the 'commandergenius' part, i.e. the SDL port for Android, in the Java code. In other words: it's not code we wrote.
Combined with the fact that it works for everyone else, I wonder whether it could be some local issue on your system. Do other apps based on commandergenius work properly?

**Comment by dragontamer8740** [comment]
You'd need to point me to an app based on commandergenius. I am pretty sure I haven't got any, unless retroarch uses it (retroarch works).

**Comment by dragontamer8740** [comment]
Update: aDosBox crashes as well. It's probably commandergenius.

**Comment by MBilderbeek** [comment]
As this is not an openMSX issue and a new issue was filed in the commandergenius project (as mentioned above), I'm closing this issue.
