### ISSUE TITLE
[bug] Incorrect VDP on Spectravideo_SVI-728.xml

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1009]
The Spectravideo_SVI-728.xml currently has the VDP set to TMS9129. But the ROM set in the file is for the american model:

Spectravideo_SVI-728bios.rom:             MSX BIOS+BASIC. version=MSX1, VDP.DR=0x98, VDP.DW=0x98, charset=International, date format=M-D-Y, vfreq=60Hz, keyboard=International, basic=International
sha1sum: ea6a82cf8c6e65eb30b98755c8577cde8d9186c0

This results in music played 16.6% slower in MSX-BASIC.

Please set the VDP to TMS9128.

**Comment by sdsnatcher** [comment]
BTW, maybe it's interesting to add the info about the country in the XML file, since it's very rare to find an american MSX model.

**Comment by MBilderbeek** [comment]
Thanks for all of this. I'll check with my own two SVI-728's what ROMs they have and update the configs as soon as I get to it.

**Comment by MBilderbeek** [comment]
OK, here's what I got for my 2 SVI-728's: both have the same ROM as the one you mentioned. For both, MSXMEM2 reports: charset=International, date format=M-D-Y, vfreq=60Hz, keyboard=International, basic=International.
Still, as far as I know, both are PAL models; at least my CRT showed color with the composite out (with NTSC models I get black/white). The VDP's in these systems have a large cooler on it, which I do not want to remove, so I can't tell what the exact VDP is. ident.bas thinks it's a TMS91xx, but that doesn't help :) (The TMS4416 VRAMs support this, by the way.) My suspicion: the ROM is lying about the display frequency.

I put all the hardware info I found in the config file.

**Comment by sdsnatcher** [comment]
It's easy to test: run Knightmare. If it runs 16.6% slower than on an NTSC machine, then the VDP is the TMS9x29 and they shipped the machine with the wrong BIOS.

**Comment by MBilderbeek** [comment]
Well, as I said, the fact that it gives a color image says it all, doesn't it? It's PAL. But I'll run Knightmare on a Philips and on one of my SVI-728's :)

**Comment by MBilderbeek** [comment]
Also Leonard comments:

```
<l_oliveira> it is PAL, no?
<l_oliveira> if it were NTSC it would be using a 9118 and no video encoder (a lot cheaper)
<l_oliveira> 9118 outputs NTSC straight from one pin on the VDP
<l_oliveira> so does 9918
<l_oliveira> so if you see TMS4416 chips near the VDP it's safe bet it's a TMS91xx
<l_oliveira> about the clock crystal on the analog board it's the 4.3Mhz for the color encoder
```

**Comment by MBilderbeek** [comment]
I checked on one of the SVI-728 with this program:

```
10 time=0
20 A$=INPUT$(1)
30 print time
```

and timed it with my phone on 10 seconds. I got 502. So it's definitely 50Hz and the BIOS is wrong. I'll document it in the XML file.
