### ISSUE TITLE
implement OPL3 or OPL4-fm and OPM channels volume expressions in _soundchip_utils.tcl

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1018]
toggle_vu_meters works fine for the PSG, SCC, OPLL and OPL4-wave channels, but it doesn't show either the OPL3 or the OPL4-fm channels.

**Comment by MBilderbeek** [comment]
That's correct. The script says:
@todo:
- frequency expressions for (some of?) the drum channels are not correct
- implement volume for MoonSound FM (tricky stuff)
- actually, don't use regs to calc volume but actual wave data (needs openMSX changes)

Apparently it's tricky, but I don't remember why...

If you have the formulas for the volume per channel (see the rest of _soundchip_utils.tcl), I'd be happy to add it :)

**Comment by sdsnatcher** [comment]
For the SCC and the OPLL, is the wave data used to calculate the volumes, or just the register data? If it's just the register data, I don't see any reason why the OPL3 should be treated differently...

**Comment by MBilderbeek** [comment]
Only the register data. As I said, I don't remember why, but apparently there was something tricky about the OPL3/4. Note that for the OPM it's also not implemented.

**Comment by m9710797** [comment]
I don't really understand the command about the opl3 FM stuff being tricky (even though I might have written that comment myself??). What's _probably_ meant is that just looking at the registers might not give a very accurate volume level (because of the operator envelope stuff). But the exact same thing is true for the OPLL chip. So we could do something similar for OPL3 (it jut won't be very accurate, just like the OPLL VU-meter isn't very accurate).

**Comment by MBilderbeek** [comment]
I just realized perhaps the tricky stuff was due to how the channels can be configured, with either 4 operators or 2 operators. That was probably it...

**Comment by sdsnatcher** [comment]
Humm. But does the script even support the AM synthesis mode of the OPL1?

In AM mode, what you have in fact is that the channel is broken into two single-op sub-channels. 

In AM mode, the VU bar for that channel should be split in two, each "sub channel" with its own volume.

For the 4-ops modes of the OPL3, the formula is similar:

4op-mode1, aka FM-FM: the last operator contains the volume.

4op-mode2, aka AM-FM: here you have two sub-channels. One with a single operator and other with 3 operators.

4op-mode3, aka FM-AM mode: this one is exactly the same as the 2op-mode2. It's a
backwards compatibility mode that allows the programmer to use these two channels with 2op instruments even while the chip is set to 4op mode.

4op-mode4, aka AM-AM. This mode feature 2 channels with a single operator, plus a 2op channel. It's equivalent to two 2op channels with the same configuration. This is also a backwards compatibility mode that allows smart programmers to use 2-op instruments while the chip is still set to 4-op mode.

The rule of the thumb is that the volume of any (sub)channel will always be set by the last operator of that chain of operators.

More info can be found here:
http://www.fit.vutbr.cz/~arnost/opl/opl3.html

**Comment by MBilderbeek** [comment]
As the script is simple, none of that is easy to support, hence 'tricky'.

**Comment by sdsnatcher** [comment]
Well, there are to ways to deal with it:

1) Easy: Just treat the OPL3/OPL4-fm as a 18 channel OPL1, and ignore the other modes. (just as the single-op mode of the OPL1 is currently being ignored). The script for the OPL1 is already working for the MSX-Audio and would need minimal rework for the OPL3/OPL4-fm.

2) Complete: treat the OPL1 as a 18 channel device (18 operators), where some pairs can be combined into 2-op channels, be either instrument channels, or the bass drum channel. That's exactly how the chip works internally.

Similarly, the OPL3/OPL4-fm would be considered a 36 channel (36 operators) device, where some of them can be combined into either of these:
- 2op-mode: 2-op channels, just like the OPL1 above
- 4op-mode: 
  - 1 4-op channel
  - 1 single-op channel + 1 3-op channel
  - Two 2-op channels
  - 2 single-op channels + one 2-op channel

**Comment by MBilderbeek** [comment]
I think we'll not pursue this script further. We now have sound-level output in the new GUI, see a63e23f5c771f02d158c9c6d6c12eaaafb2296d9. So closing this issue.
