### ISSUE TITLE
[bug] "set cmdtiming broken" now has just a marginal speed gain

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1019]
Until openMSX-0.9.1, when "set cmdtiming broken" was enabled, the blitter had a huge performance gain. Blits where done instantly, as said in the manual. This allowed me to test and fix timing routines that relied too much in the slow blitting speed to work properly.

But on openMSX-0.12.0, when the "set cmdtiming broken" is enabled there's just a marginal speed gain. It's not enough to detect most of the bugs I used to detect.

For example, Mon Mon Monster has a bug where the player will go back and forward into the same door multiple times if the blitter and CPU speed are too fast, making it difficult for the player to stay in the desired side of the door. This was only possible to be detected on openMSX-0.9.1.

**Comment by m9710797** [comment]
I just checked: "set cmdtiming broken" does still result in infinitely fast vdp command execution. Verified both by stepping through the openMSX code with gdb and by running a small BASIC prog (with and without cmdtiming=broken).

Is it possible there's another reason why the mon-mon bug isn't detected anymore? Or could you provide a clearer testcase where you see commands aren't executed infinitely fast anymore?

**Comment by sdsnatcher** [comment]
I created two videos to show the performance difference. They show the issue better than a million words.    :)

Mon3ster openMSX-0.9.1
https://youtu.be/9Q5otnfEDFU

Mon3ster openMSX-0.12.0
https://youtu.be/PpIunbxEGvk

Notice that the screen transitions are much snappier on 0.9.1, and the door bug shows up because of that. OTOH, the blitter is much slower on 0.12.0. This shows up in all screen transitions and the door bug doesn't happen.

Note: Youtube is too slow to show the flickering that happens on screen for the door bug on openMSX-0.9.1. But in a nutshell, it switches from one side of the door to the other a 60Hz. Getting out at the desired side becomes almost random.

Curiously enough I discovered another problem: openMSX-0.9.1 had no speed issues to record the video. OTOH, openMSX-0.12.0 had a huge speed impact while the video was being recorded. The emulation became very sluggish until I issued the "record -stop" command.

**Comment by sdsnatcher** [comment]
And here's a crop of just the last part of the openMSX-0.9.1 video that Youtube can't show properly. The door bug can be seen better in this one.

[Mon3ster_openMSX-0.9.1.zip](https://github.com/openMSX/openMSX/files/212059/Mon3ster_openMSX-0.9.1.zip)

**Comment by m9710797** [comment]
Should be fixed now. See commit f0e1dfbe6 for details.

**Comment by sdsnatcher** [comment]
Thanks!
