### ISSUE TITLE
autotyped RUN"CAS:" via .cas loading from Catapult appears as RUN*CAS+* on japanese machines

### ISSUE THREAD

**Issue by ghost** [openMSX/openMSX#1023]
i tried to open .cas files via Catapult, and the autotyped RUN"CAS:" appears as RUN_CAS+_ (Panasonic and Sanyo machines), and as RUN@CAS@ from Gradiente machines (except Expert 1.0)

<keyboard_type>jp_jis</keyboard_type> appears from the line 42 of /usr/share/openmsx/machines/Panasonic_FS-A1WSX.xml , and the file /usr/share/openmsx/unicodemaps/unicodemap.jp_jis exists

i'm using the version 0.12.0 from Ubuntu 16.04 repository 

please let me know what is needed for helping to find out what happens... - thanks! :)

**Comment by m9710797** [comment]
We verified (on IRC) that the "type" command misbehaves in the same way. While for me on the same MSX machines it's working perfectly.
nitrofurano also mentioned that on Dutch or Brazilian machines auto-typing does work as expected.

**Comment by ghost** [comment]
thanks, @m9710797 ! :)

**Comment by MBilderbeek** [comment]
I also cannot reproduce the problem... what could be the cause of this? Any idea?

**Comment by MBilderbeek** [comment]
Is this a case in which we should let the autorun_cassettes feature listen to the new default_type_proc setting, or should we simply find out the cause of this issue?
I can only think of wrong unicodemaps being used....

**Comment by NYYR1KK1** [comment]
I'm not sure, but I think this can be used as a workaround:
set default_type_proc type_via_keybuf

**Comment by MBilderbeek** [comment]
@ghost Can you still reproduce this on a current development build?

Oh, he wasn't ghost. That's just the place holder for deleted users. Apparently it was nitrofurano. Will try to reach him.

**Comment by MBilderbeek** [comment]
Note that I contacted Paulo Silva, but we didn't get to a conclusion yet (in 2019). I am now trying to revive the discussion :)

**Comment by MBilderbeek** [comment]
I got into contact, he retested and was not able to reproduce it any longer. So I am closing this issue as fixed.
