### ISSUE TITLE
[bug] Incorrect RGB palette on Fujitsu FM-X

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1025]
I checked with Werner, and the Fujitsu FM-X RGB output connector can be directly connected to any RGB monitor just like any other MSX model that has RGB output, but the important difference is that the FM-X outputs a very distinct palette as seen in this attachment:

http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/890f77af/8da7/attachment/DSC01437.JPG

The image shows the result of my colorbar test program while the FM-X was connected to a standard RGB monitor:

```
10 COLOR15,0,0:DEFINTA-Z
20 SCREEN2
30 OPEN"grp:"FOR OUTPUT AS#1
40 FOR Y=0 TO 2
50 FOR X=0 TO 5
60 READ C
70 LINE(X*42,Y*64)-(X*42+41,Y*64+63),C,BF
80 IF C=15 OR C=7 OR C=11 OR C=3 OR C=14 THEN COLOR1 ELSE COLOR15
90 PSET(X*42+11,Y*64+2),C:PRINT#1,USING "##";C
100 NEXT X,Y
110 COLOR 15
120 BEEP:A$=INPUT$(1)
130 END
140 '
150 DATA 12,2,3:' Greens
160 DATA 4,5,7:' Blues
170 DATA 6,8,9:' Reds
180 DATA 13,13,14:' Purple & gray
190 DATA 1,14,15: 'Grays
200 DATA 0,10,11:' Yellows
```

Please note that there's no need to emulate any hardware related to the FM-7 to support this distinct palette that the FM-X has. Since openMSX always emulates machines as they were connected to a RGB monitor, I believe it's relevant to implement the correct palette for this machine.

How come the FM-X has a distinct palette while it clearly has a TMS9928 VDP? Because it has an additional circuit that rework the palette for the same one used in the Fujitsu FM-7. It's encoded in 3-bit RGB.

This seems to be the 24-bit RGB equivalent to the palette output by the FM-X on its RGB conector:

0=0,0,0
1=0,0,0
2=0,255,0
3=0,255,0
4=0,0,255
5=0,0,255
6=255,0,0
7=0,255,255
8=255,0,0
9=255,0,0
10=255,255,0
11=255,255,0
12=0,255,0
13=255,0,255
14=255,255,255
15=255,255,255

More info and more images from the FM-X can be seen in the following link (credits to WernerKai):
https://plus.google.com/photos/112629367302659371233/albums/6044264433100733969

**Comment by sdsnatcher** [comment]
Some additional info: When used on the CVBS output, the FM-X seems to have a 16-color palette very close to the CGA or the ZX-Spectrum.

**Comment by MBilderbeek** [comment]
Do you still want to investigate that CVBS palette? You're saying it's different than any other? Do you know what kind of encoding circuit is used for it? (Is it unique or not? You already made a partial overview of encoder circuits if I remember correctly.)

I guess you suggest to use that RGB output as output for this machine, so with that crippled palette?

This is what I get if I implement it as you suggested:
![openmsx2356](https://cloud.githubusercontent.com/assets/12675978/15338784/b604f81c-1c81-11e6-998e-e5eb26ac8dda.png)

**Comment by sdsnatcher** [comment]
I don't have this machine, so I'll only be able to investigate the CVBS palette further if some owner helps. Werner accepted to take some more pictures of this output, but I guess he still couldn't find free time for that yet.

The following picture of the CVBS output was taken by Werner suggests that it features a different palette from any other machine and even from its own RGB output. But, as I mentioned, further investigation is necessary before any conclusions.
![Picture taken from the CVBS output](https://lh4.googleusercontent.com/-p4i5diujEYk/VCylr9C80sI/AAAAAAAAFkU/wYXCBWJBB9U7ZJ1G7QHYPwH-h9QbjY05wCL0B/w640-h480-no/DSC01637.JPG)

Indeed, from the pictures of the analog board from Werner's machine I can have a idea of how the circuit works.  The circuit is undoubtfully unique.

Yes, I'm suggesting to use this "crippled" palette, just because that's is what this machine outputs to RGB monitors.

And this wouldn't be the first time openMSX emulates some awkward/crippled aspect one some specific machine, isn't it? Why would it be different in this case? Just because of the weird aesthetics? Then we should blame Fujitsu for such bizarre idea.      ;)

> This is what I get if I implement it as you suggested

Nice! It matches perfecly the picture taken from the very same utility run on the real machine, see:
![Colorbar from the real FM-X RGB output](https://lh4.googleusercontent.com/-X68aVPgdAeA/U-gL8tgcZqI/AAAAAAAAE-k/9Z1VxsXjon4zVYHmnLyPzW-5Q7BiNb5gACL0B/w640-h480-no/DSC01436.JPG)

**Comment by MBilderbeek** [comment]
For the CVBS palette, you may want to open a new ticket, if you ever get the data. But I guess it's far less interesting.
