### ISSUE TITLE
Openmsx can not find savestate that ends with ".rom XXXX.oms" via OSD menu

### ISSUE THREAD

**Issue by WildPenquin** [openMSX/openMSX#1029]
Hi,

OpenMSXes OSD is somehow confused if the state base name ends with .rom (perhaps it thinks the . is a wildcard?).

I had loaded transball-en.rom (via catapult) and made a savestate. Openmsx keeps looking for transball-en.oms, although the right file name is "transball-en.rom 0001.oms". I can load the file manually from console - but even then, autocompletion fails: tab tries to complete "transball-en " - without escaping "\" !. For other files with spaces, it uses the "\" correctly.

This is on Arch Linux. I can provide logs if needed / if you can not reproduce this.

**Comment by MBilderbeek** [comment]
Thanks for reporting! But I think we already fixed this, see bug #1010.

You could compile openMSX from git (it's easy!) and that should have it fixed.
