### ISSUE TITLE
Android: only supports scale_factor 1, which gives blurry images

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1032]
The Android port has hardcoded scale_factor 1, which means TEXT80 and screen 6 and 7 images become blurry.

Perhaps it should be possible to change scale_factor, possibly after which the app needs to be restarted?

**Comment by MBilderbeek** [comment]
With the current Android SDL port, the app crashes when changing screen mode while the app is running. I don't expect this to get fixed soon.
I also don't know how to switch mode after restarting the app. (That may require some hacky code with persistence files etc.)

What we can do is instead of hardcoding the scale_factor to 1, to hardcode it to factor 2. With this TEXT80 looks good at least, and you also get scanlines and stuff.

On my reasonably new phone (Xiaomi Redmi 4 Prime) this works fine and it is still running at 60fps even at the toughest conditions (turboR/V9990/Moonsound). But perhaps this will break the app for people with some (older) Android devices, either the display may go weird or it becomes too slow.

What do you think?

**Comment by MBilderbeek** [comment]
Thanks! Can you also check whether you can build the latest Android code? It will be necessary if you want to upload a signed binary to Google Play for next release.

One of these days I'll then switch it to 2x... until we get some evidence we shouldn't :)

**Comment by awulms** [comment]
Good point. I migrated last year from suse to kubuntu and must setup again the android development environment. Hope that will go smooth

On August 23, 2018 9:58:44 PM UTC, Manuel Bilderbeek <notifications@github.com> wrote:
>Thanks! Can you also check whether you can build the latest Android
>code? It will be necessary if you want to upload a signed binary to
>Google Play for next release.
>
>One of these days I'll then switch it to 2x... until we get some
>evidence we shouldn't :)
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openMSX/openMSX/issues/1032#issuecomment-415584566

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by MBilderbeek** [comment]
The sooner you try, the better. It has become much harder and much less trivial to setup. I'll do my utmost to help you with that. I already tried to update the Compilation Guide, but I know there are still parts missing.

**Comment by MBilderbeek** [comment]
I'm considering this ticket done for now. @awulms please contact me about setting up the development environment. I think we'd like to release soonish.
