### ISSUE TITLE
Unable to set mapper type for roms in Android port

### ISSUE THREAD

**Issue by artrag** [openMSX/openMSX#1036]
There is no visible way in Android to select the mapper of a rom plugged in a slot.

**Comment by MBilderbeek** [comment]
Yeah, do you have a suggestion on how to offer it in the OSD menu?
Note that the OSD menu is quite limited in what it can do...

The Android port is mostly targeted at casual gaming and for that the mapper type is usually not needed, as most of it is in the database...

**Comment by artrag** [comment]
Why not adding a selection menu 'set mapper's after load rom?
It could also go in the hardware menu, so to not crowd the main menu
AR

**Comment by MBilderbeek** [comment]
That would be possible, but is it logical to find it there? When should the selected mapper type be reset? (It's not easily visible which mapper type is selected if it's in the other submenu...)

**Comment by MBilderbeek** [comment]
How about showing a pop-up to select the mapper type if the just selected ROM was not found in the database? The UI would have the auto-detected mapper type as default value.

Would that work?

**Comment by MBilderbeek** [comment]
OK, I just implemented a mapper selection dialog in case the ROM is not in the database. Thanks to Wouter for his commit and comments.

See commit 06deacd2972a85b2c5f7e567a67fb91a1805aaaf
