### ISSUE TITLE
[bug] openMSX-debugger looses connection with openMSX on view->VDP->Bitmapped VRAM

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1037]
openMSX-debugger is loosing its connection with openMSX when the menu view->VDP->Bitmapped VRAM is requested.

Tested with:

openMSX-0.13.0
openMSX-debugger 0.10.0-246-g339557cc
openMSX-debugger 0.9.0-12821

System: Mac OS-X 10.10.5

**Comment by MBilderbeek** [comment]
Does it happen for any type of MSX you're running in any kind of screen mode?
(I can't reproduce the issue here...)

**Comment by sdsnatcher** [comment]
I tested in the following machines: 
- Sanyo PHC-70FD
- Sony HB-F1XDJ
- Sony HB-F1XD

And in the following screen modes, where available: 5, 7, 8 and 12.

**Comment by MBilderbeek** [comment]
Well, I really can't reproduce it... is there some condition it which it does _not_ happen?
If you run the debugger from a terminal, what are the last messages you see?

**Comment by sdsnatcher** [comment]
Until now there's no condition where it doesn't happen.

This is what I get from the terminal when I connect it to openMSX emulating
a HB-F1XD in screen-5:

$
/Applications/Emulators/MSX/openMSX_Debugger.app/Contents/MacOS/openmsx-debugger

screenMode: 5

vram to start decoding: 0

screenMode: 5

vram to start decoding: 0

screenMode: 5

vram to start decoding: 0

Also tried with a Panasonic FS-A1WSX and got the same results.

On Tue, Aug 30, 2016 at 2:04 PM, Manuel Bilderbeek <notifications@github.com

**Comment by sdsnatcher** [comment]
I just published a video of the problem [here](https://youtu.be/P5FtebY8wxs).

**Comment by MBilderbeek** [comment]
Hmm, I see this:

```
$ openmsx-debugger 
Gtk-Message: Failed to load module "canberra-gtk-module"

screenMode: 5
vram to start decoding: 0

screenMode: 5
vram to start decoding: 0

screenMode: 5
vram to start decoding: 0

lines acording to the bits 128,: 212

screenMode: 5
vram to start decoding: 0

border acording to the regs 0,: 0

color 0 is pallet regs 0,: 0
screenMod according to the bits: 12
visible page according to the bits: 0

void BitMapViewer::on_showPage_currentIndexChanged( int 0);
vramAddress 0

screenMode: 5
vram to start decoding: 0

screenMode: 5
vram to start decoding: 0
```

Perhaps it's a Mac (Qt on Mac?) specific issue?

I can't really debug this without reproducing it or you being able to build openMSX and the debugger (which is simple by the way).

**Comment by MBilderbeek** [comment]
Can you confirm it still works with 0.12.0 using the same debugger and MSX program?

**Comment by sdsnatcher** [comment]
Just tested the same debugger with openMSX-0.12.0 and it works fine.

On Wed, Aug 31, 2016 at 4:01 PM, Manuel Bilderbeek <notifications@github.com

**Comment by MBilderbeek** [comment]
So, this problem needs to be bisected. For that we need someone with a Mac who can compile openMSX.

**Comment by niekvlessert** [comment]
Hi, I've been bisecting, OpenMSX commit c5d0c13 (Properly fix controlled shutdown of accept thread) seems to cause this problem. When using the commit before that one it works fine.

**Comment by mthuurne** [comment]
Thanks a lot to Niek for bisecting and testing!
