### ISSUE TITLE
openMSX crashes after loading starfighters LD

### ISSUE THREAD

**Issue by seanyoung** [openMSX/openMSX#1042]
Since git commit 8e3ddd088d12cc52d8ea76e6b7dd7bdade5818d5, openmsx crashes shortly after statup. This is the command line:

openmsx -machine Pioneer_PX-7 -laserdisc starfighters.ogv

Stack trace:
gdb) bt
#0  0x0000000000a47fa8 in _mm_loadr_ps (__P=0x7ffff7e0dfd0)
    at /usr/lib/gcc/x86_64-redhat-linux/6.2.1/include/xmmintrin.h:938
#1  openmsx::calcSseStereo<true> (buf_=0x1635520, tab=0x7ffff7e0e050, len=40, 
    out=0x7fffffff4250) at src/sound/ResampleHQ.cc:475
#2  0x0000000000a49d23 in openmsx::ResampleHQ<2u>::calcOutput (this=0x160ced0, 
    pos=2.72554731, output=0x7fffffff4250) at src/sound/ResampleHQ.cc:579
#3  0x0000000000a49a37 in openmsx::ResampleHQ<2u>::generateOutput (
    this=0x160ced0, dataOut=0x7fffffff4240, hostNum=628, time=...)
    at src/sound/ResampleHQ.cc:663
#4  0x0000000000a51f90 in openmsx::ResampledSoundDevice::updateBuffer (
    this=0x1649f80, length=628, buffer=0x7fffffff4240, time=...)
    at src/sound/ResampledSoundDevice.cc:40
#5  0x00000000008b2818 in openmsx::LaserdiscPlayer::updateBuffer (
    this=0x1649f80, length=628, buffer=0x7fffffff4240, time=...)
    at src/laserdisc/LaserdiscPlayer.cc:741
#6  0x0000000000a19653 in openmsx::MSXMixer::generate (this=0x159e940, 
    output=0x7fffffff57d0, time=..., samples=628) at src/sound/MSXMixer.cc:529
#7  0x0000000000a18528 in openmsx::MSXMixer::updateStream (this=0x159e940, 
    time=...) at src/sound/MSXMixer.cc:177
#8  0x0000000000a1ac37 in openmsx::MSXMixer::executeUntil (this=0x159e940, 
    time=...) at src/sound/MSXMixer.cc:774
#9  0x0000000000543fd4 in openmsx::Scheduler::scheduleHelper (this=0x159e6d0, 
    limit=..., next=...) at src/Scheduler.cc:112
#10 0x00000000005f73f9 in openmsx::Scheduler::schedule (this=0x159e6d0, 
    limit=...) at src/Scheduler.hh:67
#11 0x00000000005f8c81 in openmsx::CPUCore<openmsx::Z80TYPE>::execute2 (
    this=0x15c9cd0, fastForward=false) at src/cpu/CPUCore.cc:2585
#12 0x00000000005f83fa in openmsx::CPUCore<openmsx::Z80TYPE>::execute (
    this=0x15c9cd0, fastForward=false) at src/cpu/CPUCore.cc:2538
#13 0x00000000006b7457 in openmsx::MSXCPU::execute (this=0x15c73c0, 
    fastForward=false) at src/cpu/MSXCPU.cc:114
#14 0x000000000049a144 in openmsx::MSXMotherBoard::execute (this=0x15c2620)
    at src/MSXMotherBoard.cc:477
#15 0x00000000004ffe74 in openmsx::Reactor::run (this=0x7fffffffdbd0, 
    parser=...) at src/Reactor.cc:532
#16 0x000000000054b1b0 in openmsx::main (argc=5, argv=0x7fffffffe0a8)
    at src/main.cc:152
#17 0x000000000054b427 in main (argc=5, argv=0x7fffffffe0a8) at src/main.cc:181

**Comment by MBilderbeek** [comment]
You're using the HQ resampler. I guess it's related to that. It doesn't crash here, with HQ resampler, but the sound quality is horrible. So something definitely broke!

**Comment by m9710797** [comment]
I can reproduce the crash. I'll fix it.
Thanks for bisecting and for the detailed bug report.

Wouter
