### ISSUE TITLE
Add extension XML for ASCII MSX-Write Kanji

### ISSUE THREAD

**Issue by rderooy** [openMSX/openMSX#1045]
With this Extension XML I can successfully use Kanji on a Japanese MSX with no Kanji built-in.
The same ROM is also used by the Sanyo PHC-77, so I used the same file naming as mars2000 did in his Sanyo_PHC-77.xml file.

[ASCII_MSX-Write.xml.txt](https://github.com/openMSX/openMSX/files/599424/ASCII_MSX-Write.xml.txt)

**Comment by MBilderbeek** [comment]
This is the same font ROM as in the Konami EC-702 extension. That makes this extension practically identical to the Konami EC-702 extension.

But what I really want to know: which real hardware is this extension modeling? As far as I know, ASCII MSX-Write does not have a Kanji font ROM.

**Comment by rderooy** [comment]
Yes, ASCII MSX-Write has a JIS1 font and MSX-JE
https://www.msx.org/wiki/ASCII_MSX-Write

And MSX-Write II has JIS1 and JIS2 together with MSX-JE
https://www.msx.org/wiki/ASCII_MSX-Write_II

I was going to also submit the MSX-Write II, but for some reason I am not able to get it to print the higher JIS2 characters.

Perhaps your thinking of the ASCII MSX-DOS2 cartridges, which have the KANJI BASIC v2, but not the JIS fonts.

**Comment by MBilderbeek** [comment]
Does it have it built in then? Because if that's the case, the extension should also contain the program ROM. I actually didn't find any evidence that these cartridges include the kanji font ROM. Did you?

**Comment by rderooy** [comment]
Ok, so two things.

As to proof that these cartridges include JIS fonts, I refer you to http://bubrhythm.net/Retorhythm/msx-write2.html which is linked to from the MSX-Write II page. It says that the cartridge adds JIS1, JIS2 and MSX-JE. I don't have a similar solid reference for the original MSX-Write, but I think that the information I found that it has JIS1 and MSX-JE is probably correct.

Unfortunately I don't know how to check for MSX-JE functionality.

The ROM downloads for MSX-Write contain both a Kanji ROM, and a program ROM while there is just one cartridge. So yes it contains both.

sha1sum MSXWRIT1.ROM 
4180544158a57c99162269e33e4f2c77c9fce84e  MSXWRIT1.ROM

I also tried to see, based on its sha1sum, if the same Kanji-ROM was used elsewhere, but could not find any such matches.

**Comment by MBilderbeek** [comment]
How do you know that this 512kB ROM contains the font too? I tried to compare 8kB blocks of this ROM with other kanji font ROMs, but there wasn't a single match.

**Comment by MBilderbeek** [comment]
I just found out that the font rom is in GoodMSX1 and GoodMSX2 and the font ROM is separate from the 512kB ROM.

i have the same problem as you described for the MSX Write II. The program seems to hang up why trying to use MSX-JE to type the kanji.

**Comment by MBilderbeek** [comment]
Fixed with commits:
63aae5a712a36e6aba888a7a0c5140563c53dc79 to add support for ASCII8 mapper with 32kB SRAM (that fixes Japanese MSX-Write II)
6e72eb148cda5d9205fad6ed58410d323111a3a0 to add Japanese MSX-Write II
bdbffa8eb353a4fa96a67eecc54e756baf033dfc to add Japanese MSX-Write

Thanks for reporting!

**Comment by rderooy** [comment]
FYI, the HAL Halnote cartridge should also work as a Kanji-ROM and MSX-JE to my understanding, but trying to use it from BASIC failed also. Also, it is listed on the Wiki as being undumped, but the ROM can easily be found with a quick google search. There are two packages online, one with one disk and one with two disks. The ROM is identical in both cases. Not sure if one package is just missing a disk or if there where two releases as some of the pictures I found only show one disk.

**Comment by MBilderbeek** [comment]
The ROM can be found and the mapper is emulated. But i wasn't able to find a font ROM for it. There is only one set of images that show the Halnote PCB and those are quite low resolution. So it is very hard to say what is on that cartridge without better info.

Note that Halnote works fine including kanji on a European MSX2. So it does seem to have fonts included. The program doesn't seem to write to the standard kanji ROM I/O port, so it doesn't even try to detect whether it's present, it seems. (But perhaps that happens differently, I don't now... The BIOS also writes to it.)

**Comment by rderooy** [comment]
Yes that is what I also noticed, and was wondering about. Looking at the pictures the cartridge also does not seem to have any switches to enable/disable any functions. It does however have a battery, so it will have some SRAM, but other then that the pictures are not a lot of help.
