### ISSUE TITLE
MSX-Audio playback corruption (Impaccen en Wegwezen demo)

### ISSUE THREAD

**Issue by oh-ren** [openMSX/openMSX#1055]
[Impaccen en Wegwezen](https://www.msx.org/downloads/demos/disks/impaccen-en-wegwezen)

This occurs after the tune playing during the sea/shark scene repeats for the 3th time (glitching etc., can't miss 😉)
Can't test on real HW.

**Comment by MBilderbeek** [comment]
Just checked this on real hardware and the same happens. So, it's yet again a bug in the MSX software :) It's also happening with MSX-MUSIC (e.g. a plain turboR).

There were also some other Impact demos with severe issues in music playback.

**Comment by oh-ren** [comment]
Thanks for verifying! 👍
(Can we document these issues somewhere? (MRC wiki perhaps?))
