### ISSUE TITLE
Add command line option to execute Tcl console commands

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1058]
If you want to let openMSX do stuff from the command line (e.g. in batch/script context) you now need to create an extra temp file with commands and use the -script command line parameter to let them be executed.

To avoid that extra file, a new command line parameter could be used that contains Tcl script to be executed at the same time as when the script file would be executed.

E.g. something like:
`openmsx -exec "record start; after time 201 {record stop}"`
Escaping that will be hell, of course... but it's doable and gives a bit of a cleaner and more powerful CLI.

**Comment by mthuurne** [comment]
Another option could be to allow "-" as the script file name and when used, read the script from stdin. That would avoid problems with escaping.

**Comment by MBilderbeek** [comment]
That would indeed be a good solution as well.

**Comment by MBilderbeek** [comment]
Wouter implemented this in 2b793844c57fc1983050c355953565beff1ed984
