### ISSUE TITLE
Incorrect selected page being reported by the IDE extension

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1063]
The IDE extension is reporting an incorrect selected page number on openMSX-debugger.

For example, when the page-7 is selected, openMSX-debugger shows that the page 224 is selected.

This causes problems if I press F5 to quickly add a breakpoint on a debugging session.

Tested on:
- openMSX-0.13.0-dev171
- openMSX-debugger-0.1.0-unknown
- Mac OS-X 10.10.5

(note: openMSX-debugger is reporting that weird version number on its about box)

**Comment by sdsnatcher** [comment]
BTW, it also causes the breakpoints to be also triggered at incorrect pages.

**Comment by MBilderbeek** [comment]
You're right, this is a bug in openMSX. I'll try to fix it soon.

**Comment by MBilderbeek** [comment]
Fixed with commit 36e39c503932a15443c39bce59a22695bac0e404
Thanks to Wouter for helping out!
