### ISSUE TITLE
Colecovision

### ISSUE THREAD

**Issue by artrag** [openMSX/openMSX#1064]
Would it be possible to configure a specific msx machine in order to emulate the CBS Colecovision and its SGM extension? 
I've been editing the hardwareconfig.xml for a while without success but I think that the majority of the work is already there (the SN76489A is already emulated in some msx extensions).
So maybe only controllers are missing.

**Comment by MBilderbeek** [comment]
I don't know what the exact differences are between MSX and Colecovision, but I can't imagine it wouldn't take some extra effort, like was the case for SVI-3x8.... There is quite a different mapping of chips into the hardware. Also the SN76489A is not emulated in openMSX.

**Comment by MBilderbeek** [comment]
By the way, see #117 .

**Comment by MBilderbeek** [comment]
Update: Colecovision support is implemented (although there are some problems with reverse still). The SGM is not implemented.

**Comment by artrag** [comment]
http://www.colecovision.dk/sem.htm?refreshed

a good description of SGM is there

**Comment by MBilderbeek** [comment]
I only see technical details about the RAM:

> Some of you programmers are well aware, ColecoVision work RAM is limited to 1KB, mapped from 6000h to 63FFh, and then mirrored to 6400h until 7FFFh (so 8 times).
> The ColecoVision also includes 8KB of BIOS routines, mapped from 0000h to 1FFFh.
> 
> The SGM expands the work RAM from 1KB to 32KB as a maximum.
> 
> Here is how:
> 
> 24KB can be mapped from 2000h to 7FFFh. When mapped, the internal 1 KB of RAM is no longer accessible. All legacy software still works normally under this mode.
> However, since the SGM must also be compatible with the ADAM, the 24 KB of extra RAM is NOT enabled by default.
> In order to use that expanded memory in a ColecoVision system, the programmer must first enable it.
> But before doing so, you also need to make sure the module isn’t attached to an ADAM system, otherwise there may be a memory conflict with potential for damaging the ADAM and/or the SGM.
> So the first step is to check if the 24 KB are already available. If they are, then you have an ADAM system, and the SGM expanded memory should NOT be enabled.
> If no memory is found (in the 2000h-5FFF range), then it is a ColecoVision system and the expanded memory can be enabled.
> To do so, set bit0 in I/O port 53h to 1, like this (in assembly): LD A,00000001b ; OUT(53h),A
> 
> You can also map 8 KB of RAM (for a total of 32 KB) to address range 0000h-1FFFh. However, when doing so, the ColecoVision BIOS will be disabled.
> RAM and BIOS can be mapped back and forth, though. To map RAM to the BIOS area, simply set bit1 in I/O port 7Fh to “0”.
> In order to keep full compatibility with ADAM systems, all bits in I/O port 7Fh must be set to specific values, though. Here is how you should set the port: if you want the BIOS, set the port to “0001111b”.
> If you want RAM instead, set the port to “0001101b” (see example above on how to do that in Assembly). Make sure you respect those values, or your game may not work on ADAM systems.

But as far as I understand, there is also a version with AY8910. That is not described at all.

Or am I mistaken and is only the SGM with only RAM used?
Are there ROM files available to test?

**Comment by artrag** [comment]
All versions of SGM have an AY8910

- Programmable AY Sound Generator for the 2 versions:
x
The sound in the 2 version of the Super Game Module is provided by the AY-3-8910 PSG.
The same used with almost all MSX computers and many other computers and arcade machines from the '80s.

The main reason is to allow more faithful ports of MSX and the most Z 80 based arcade games.
The people who created the ColecoVision made a bad mistake with the CV PSG. The CV PSG isn’t bad at all, but they clocked it too high.
Because of that, we are limited to frequencies above 110 Hz, which means, that deep bass sounds can not be produced by the ColecoVision.

So that is why the Space Invaders Collection marching sound in SIC isn’t as deep as you remembered it, or some music stuff sounds so “high” in the frequency range.
The new PSG corrects that, and goes beyond what the Texas ColecoVision PSG can do, with volume envelope and better noise generator.
The AY helps by offering a wider frequency range and by increasing the total number of channels available.

Additionally both PSGs can be used simultaneously, and all sound is routed to the RF output.
(A/V mods can still work if the sound source is taken from the output of the sound mix, just before the RF input).

**Comment by artrag** [comment]
another place to gather info is here
http://www.opcodegames.com/sgm/sgm.html

**Comment by artrag** [comment]
and here too
http://atariage.com/forums/topic/244875-cv-memory-map-and-programming-info/

**Comment by MBilderbeek** [comment]
That first link has no new info, as far as I can see, but the second link says:


> The Super Game Module AY-3-8912 is mapped in ports 50H (address), 51H (data) and 52H (read data)

So, I guess with that we have all info needed to emulate it.

Can you provide some ROM files to test the implementation of the emulation?

**Comment by artrag** [comment]
Actually my own game is using SGM and a megamapper, so if this latter is not supported, my rom is almost useful. I have to see if Oscar Toledo has a test rom using only SGM.

Anyway, I know I'm asking a lot, but the most interesting SGM productions are on mapped ROM that use the mega cart (mega mapper) whose size are 128/256/512/1024KB. 
Would it be possible to implement also this ?
Going to look for a test rom for SGM only in the meanwhile.

**Comment by artrag** [comment]
[MegaCart FAQ V1-2.pdf](https://github.com/openMSX/openMSX/files/2118720/MegaCart.FAQ.V1-2.pdf)

This is the megacart description. Still looking for an SGM only rom

**Comment by MBilderbeek** [comment]
Well, that all doesn't look very complex. Give me some test ROMs (with and without MegaCart) and I'll do my best.

**Comment by artrag** [comment]
One is in your mail which uses SGM and megacart
I'm looking for other examples.

**Comment by artrag** [comment]
Here plenty of games using sgm and megacart


http://atariage.com/forums/topic/273502-team-pixelboy-news-bulletin-december-25th-2017/page-1

**Comment by MBilderbeek** [comment]
OK, current openMSX version has a ColeoVision with built in SGM emulated, see 9d5080d. The  MegaCart is next on my TODO list.
By the way, what is the SGC? Should that also be emulated? If yes please point me the the details of that one as well.

**Comment by mthuurne** [comment]
What does the real SGM hardware do when the BIOS is disabled and the SGM RAM is disabled as well: does it put RAM in 0x0000-0x1FFF or is that memory area empty then?

**Comment by MBilderbeek** [comment]
MegaCart is now also implemented. If your ROM file is 128/256/512/1024kB, MegaCart will be automatically used as mapper. Otherwise, specify the ColecoMegaCart as mapper type.

@artrag please test and confirm it's all useful for you.

**Comment by artrag** [comment]
Thanks! Should I test the last build from here ?
http://openmsx.fixato.net/builds/windows/x64/

**Comment by MBilderbeek** [comment]
@artrag Yes, please.

**Comment by artrag** [comment]
SUCCESS! My Uridium port to Colecovision works perfectly.
It opens the way to cross developing for both msx and colecovision at the same time!!

**Comment by MBilderbeek** [comment]
@artrag Great to hear that! Please report if you find any problems in the emulation.

I'll close this ticket now.

**Comment by artrag** [comment]
The SGM test cartridge by Oscar Toledo works fine
His game, Princess Quest (256Kb) works fine as well

**Comment by MBilderbeek** [comment]
Thanks for the update!

**Comment by MBilderbeek** [comment]
@artrag What does the real SGM hardware do when the BIOS is disabled and the SGM RAM is disabled as well: does it put RAM in 0x0000-0x1FFF or is that memory area empty then?

**Comment by artrag** [comment]
I have no idea, but I guess that the area stays empty.
I will ask to Oscar Toledo btw

**Comment by MBilderbeek** [comment]
OK, thanks, then we have implemented it correctly. Case closed, I guess :)
