### ISSUE TITLE
CUE/Bin CD image support

### ISSUE THREAD

**Issue by MauricioBraga** [openMSX/openMSX#1065]
Currently openMSX only support ISO CD images, but ISO format doesn't support multitrack cds (one example of a multitrack CD is Knightmare Gold). CUE / BIN is a better cd image format that supports multitrack cds, and it is necessary to be able to run Knightmare CD in openMSX.

**Comment by MBilderbeek** [comment]
As it boils down to #1060 - let's close this a duplicate.

**Comment by MauricioBraga** [comment]
I believe it shouldn't be closed, since although the ultimate goal can be the same, this one (#1065) is a first step towards #1060 . Adding .cue / bin support won't by itself play audio tracks, but it will allow to run (although without sound) the CD game Knigthmare Gold that, at this moment, can't be run (in his CD format) even without sound, since the iso format isn't able to store this game.
