### ISSUE TITLE
Is the National CF-3300 drive really single-sided?

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1073]
The current xml file for this machine has the <singlesided/> inside, forcing this drive to be single-sided.

But are you sure it is really single-sided? Because all advertisements about the CF-3300 and all articles about this machine on Japanese magazines of the time state that it has a 720KB drive.

I attached one advertising and one review article here so you can check yourselves. To make your life easier, I took the liberty to highlight the locations where either "1MB unformatted" or "720KB formatted" are mentioned.

![national_cf-3300_2dd_drive_01_advertising](https://user-images.githubusercontent.com/13080763/29235191-2e6ec03a-7ed3-11e7-94df-cc0c9dceba56.jpg)
![national_cf-3300_2dd_drive_02_review](https://user-images.githubusercontent.com/13080763/29235192-2eac072e-7ed3-11e7-82b3-651e674a2e52.jpg)

**Comment by MBilderbeek** [comment]
Perhaps... or are they talking about the external drive connector?
We got these configs from a reliable source (atarulum, from Japan, I believe)... I guess we need someone with more knowledge of Japanese, a manual or an owner of the system to be sure.

Several other sources mention single sided too. Let's ask on msx.org...

**Comment by sdsnatcher** [comment]
Tip: You can [use the Google Translate app in your smartphone to read the Japanese text](https://www.youtube.com/watch?v=sRxs7s9zvB0). It decrypts the text impressively well, even when reading from the computer screen!  Be sure to frame one column of the text at a time, because it doesn't support multiple columns (yet?).

This is the translation of the 1st column of the advertising:

> MSX first 1 MB, double sided drive adoption. Nice to meet you, a 3.5-inch floppy disk built-in King Kong This information is many, fast, accurate enough. Therefore, adopting double sided drive. Memory capacity is 720 kB, high capacity for two single-sided drive. The amount of data handled is different. Besides, it drastically shortens Rod save time. For example, when loading nine grams of BASIC with 10 kB, it takes about 110 seconds for tape, about 2 seconds for a disc. The access time is different. Besides, the road mist is almost zero. The accuracy is different. In addition, a floppy disk drive expansion terminal (coming soon for our company), reset switch etc are also equipped.


Side note: While Sony machines were nicknamed "Hit-bits", National machines were nicknamed "King Kongs". It's not a translation error. This is why there's a picture of a gorilla in every National MSX advertising of that time. They only stopped being called "King kong" when Matsushita changed the brand from National to Panasonic.

**Comment by MBilderbeek** [comment]
And this is what gdx wrote on MRC:

> [quote=gdx]This user (see link below) have a CF-3300. The drive seems to be original and when this guy can format on 2 sides and even single or double track.
> 
> https://ameblo.jp/ver05729/entry-12169069443.html
> 
> In addition the MSX2 Technical Hand book below says that CF-3300 have a 2DD Drive.
> 
> http://ngs.no.coocan.jp/doc/wiki.cgi/TechHan?page=3%BE%CF+BASIC%A4%CE%C6%E2%C9%F4%B9%BD%C2%A4[/quote]

All of this seems to be evidence that it really is a 2DD. I'll change it accordingly.
