### ISSUE TITLE
The National FS-1300 has a TMS9918 VDP

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1078]
Currently, the National FS-1300 XML file has a TMS99x8A VDP set for this machine.

I asked Daniel Ravazzi and he kindly took some pictures of this machines internals, and it shows that it has a TMS9918 VDP inside. Check the attached pictures.

![national_fs-1300_01](https://user-images.githubusercontent.com/13080763/29498947-a57a8aaa-85dc-11e7-8ed1-22e8e891ae78.jpeg)
![national_fs-1300_02](https://user-images.githubusercontent.com/13080763/29498949-a5b2e7c4-85dc-11e7-9ce3-25d394dba7be.jpeg)
![national_fs-1300_03](https://user-images.githubusercontent.com/13080763/29498948-a5b0500e-85dc-11e7-8c42-b319c1e1821d.jpeg)
![national_fs-1300_04](https://user-images.githubusercontent.com/13080763/29498950-a5b5d3b2-85dc-11e7-9e9b-f64bbdc95ca5.jpeg)

**Comment by MBilderbeek** [comment]
Thanks to both of you!
