### ISSUE TITLE
Correct YM2164 OPP emulation for the SFG-05

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1081]
The SFG-05 has an YM2164 OPP rather than an YM2151 OPM, its ROM is specific to that sound chip as well and not compatible with the YM2151.

As per [1][2], the specific differences of the YM2164 OPP which need to be implemented are:

1. The test register is at register 9 rather than register 1 (used for the LFO reset function).
2. Timer B has a period of 2048 cycles rather than 1024 cycles.

Additionally, the SFG-05 ROM sets registers 0-7 of the YM2164 to 10H, at this point in time I don’t know what their function is.

[1] https://www.msx.org/forum/msx-talk/hardware/yamaha-sfg-05-cx5me?page=2#comment-320974
[2] http://map.grauw.nl/resources/sound/yamaha_ym2164.php

**Comment by MBilderbeek** [comment]
[OPP.patch.txt](https://github.com/openMSX/openMSX/files/7034569/OPP.patch.txt)

@m9710797 @grauw  Please review attached patch...

**Comment by grauw** [comment]
LGTM 👍. My only remark would be if you considered using YM2164 instead of OPP as variant name.

(I assume you’ve tested with the cases in #1369.)

**Comment by MBilderbeek** [comment]
I haven't tested with these cases, as I couldn't find the files the OP
used... Can you help testing or do you know where to get the files?

Op di 24 aug. 2021 03:03 schreef Laurens Holst ***@***.***>:

**Comment by MBilderbeek** [comment]
I have updated the patch, but I still can't test it. I only have a basic program for FM Music Macro (1) and that one runs fine without the changes as well. Note that this program doesn't run properly on a FM Music Macro II (with or without the changes).

So, please tell me how to test this myself @grauw and @kumokosi ....
[YM2164.patch.txt](https://github.com/openMSX/openMSX/files/7041942/YM2164.patch.txt)
[musicmacro2.zip](https://github.com/openMSX/openMSX/files/7041943/musicmacro2.zip)

**Comment by grauw** [comment]
Nice improvements on the patch.

Is this line intentional or debug output which slipped in?

```
std::cerr << "OPP? " << std::boolalpha << (variant == YM2151::Variant::YM2164) << std::endl;
```

**Comment by MBilderbeek** [comment]
@grauw Oops, I'll remove that, sorry :) But, can you help me to find out how to test it?
[YM2164.patch.txt](https://github.com/openMSX/openMSX/files/7041982/YM2164.patch.txt)

**Comment by grauw** [comment]
I see that is the program listed in the FM Music Macro manual after I typed half of it as well :). I don’t have any other listing that I can type in so I hope @kumokosi can pitch in with his test program.

Otherwise when I have a little more time I could write a separate timer frequency test program.

**Comment by gzaffin** [comment]
From [1]
Registers changed by OPP
It was only confirmed that the $09 LFO SYNC register was moved from $01. Other functional differences were realized by software.

From the results of the analysis of the registers of OPZ, it is assumed that the register $01 was moved to $09 in order to change the role of the register $00-$07 at the time of OPP. In the FB-01, registers $00-$07 are only written to the same value ($10) at initialization, but this means that $00-$07 are registers with the same role and can be regarded as the same channel volume registers as OPZ.

The following is a description of the differences in the register map changed by OPP.

$00-$07: [-VVV VVVV] Channel Volume
$09: [---- --S-] LFO SYNC

Translated with www.DeepL.com/Translator (free version)

[1][Registers changed by OPP](http://sr4.sakura.ne.jp/fmsound/opp.html)

**Comment by MBilderbeek** [comment]
So, the timer may not be different after all?

Anyway, this is the latest patch (almost identical as previous).
[YM2164.patch.txt](https://github.com/openMSX/openMSX/files/7086234/YM2164.patch.txt)

**Comment by gzaffin** [comment]
Yes timer B difference is confirmed multiple times. See, just for reference, [Tiny-Yarou youtube video test SFG-01 SFG-05 side by side](https://youtu.be/x86TMrdWCS0).

**Comment by MBilderbeek** [comment]
So, that difference isn't part of "Other functional differences were realized by software."?

@gzaffin Anyway, do you have a way to test the patch?

**Comment by grauw** [comment]
Ah yes @gzaffin I’ve seen that before. However I still need to confirm it. Should be easy to patch VGMPlay with some test keyboard controls to manipulate these register values and see if they affect the volume and how.

@MBilderbeek The timer is for sure as described, as is the test register, I’ve confirmed this myself when I created the article for the MSX Assembly Page. You will also find that when you compare the SFG-01 to SFG-05 upgrade ROM to the SFG-05 ROM, this is what is patched.

**Comment by MBilderbeek** [comment]
@grauw Well, OK, so the patch can be pushed when we can somehow confirm it works as intended. I hope someone can help with this.
