### ISSUE TITLE
Request option for fullscreen resolution separate from scale factor

### ISSUE THREAD

**Issue by arromdee** [openMSX/openMSX#1089]
On Linux.  If I use scale of 4X, I get a window which is 1280x960.  Fine so far.

If I then go into fullscreen, my monitor puts me into 1280x960 mode and shows me the same thing I had so far.

This would be good, except most monitors, including mine, don't do such modes very well.  I would like a way to specify the resolution of fullscreen mode.  For instance, I could specify that the fullscreen resolution is 1920x1080.  Then when I use a scale of 4X, fullscreen would show me a 1920x1080 screen with a 1280x960 piece in the middle containing the MSX display.  That would reduce the blurring caused by the fact that the monitor doesn't do 1280x960 mode very well.

Also, an option to put LEDs in the area outside the MSX screen area.

**Comment by mthuurne** [comment]
I was considering that when we move to SDL2, we could use non-exclusive fullscreen mode instead of the current exclusive fullscreen mode. In non-exclusive mode the openMSX output would be shown in a screen-filling borderless window rather than taking over the entire video output. This means the resolution of the desktop is used, which is most likely set to the native resolution of the screen. Another advantage is that switching from/to non-exclusive fullscreen mode is much faster and more fluent than switching to exclusive fullscreen mode.

**Comment by oh-ren** [comment]
@mthuurne Possible to make this an option (i.e. support both modes)?

@arromdee Not sure what the situation is regarding your graphics abilities (GPU, drivers, etc.) but (at least) for both (non-ancient) Radeon & Nvidia cards it should be possible to apply **GPU scaling** which should/could give you exactly what you're looking for (driver settings).

**Comment by arromdee** [comment]
Thanks, that actually did work.

For anyone else reading this:

xrandr --output DVI-1 --set "scaling mode" "Center" --mode 1280x960 --panning 1280x960
(or whatever the output name)
where "Center" is not only case sensitive but fails silently if you get the case wrong.

I still think it should be an option, however (and doing it this way would make it impossible to show the LEDs outside the window).

Edit: Also, when I do it this way, switching from fullscreen back to windowed crashes more than half the time.

**Comment by MBilderbeek** [comment]
@arromdee @oh-ren Please try full screen with the latest development version (3f390b404486f3c082a83914f29e294dc1308fb4 or later).
It should work much better now.

**Comment by MBilderbeek** [comment]
@arromdee @oh-ren I assume this issue is now resolved in the latest development build. If not, please reopen this ticket.

**Comment by fragmental** [comment]
I tried the 2019-08-26 412 windows build from https://openmsx.fixato.net/builds/windows/x64/ and I think it's better?  But the integer scaling is still lost when going to fullscreen.
