### ISSUE TITLE
Support for undocumented V99x8 register 1 bit 2

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1091]
Apparently, this undocumented bit has at least the following effects on V9938 and V9958:
- Seems to change the clock source for the blink/page switch counter decrease from VSYNC to HSYNC.
- Seems to make the registers EO and IL at R#9 irrelevant. Whatever is in there, the VDP behaves as if both bits are 1

Test software: 
- http://msx2.org/Cadari/VDP.dsk
- https://pastebin.com/FEzBbcgA

See https://www.msx.org/forum/msx-talk/emulation/new-online-msx-emulator?page=47
See https://github.com/ppeccin/WebMSX/commit/b930be072e24c90e1356ce6f00fe5fdbbe2014ae

**Comment by MBilderbeek** [comment]
Implemented via 0117dfd2f3daf66def88468af2b756bc8bfd2676

Thanks to @ducasp and @m9710797 .

**Comment by MBilderbeek** [comment]
Thanks to the Wayback machine I was able to find back the vdp.dsk.... attached. Supposed to run on V9958.

[vdp.dsk.gz](https://github.com/user-attachments/files/30282592/vdp.dsk.gz)

The pastebin is this:
```basic
10 SCREEN 5
20 COLOR 0,0:VDP(1)=116
30 COLOR 15:VDP(14)=28
40 SETPAGE 0,1:CLS:SETPAGE 1:CIRCLE(120,106),100
50 GOTO 50
```

On my GT in Z80  mode it produces the same as in openMSX: 

https://github.com/user-attachments/assets/c6ec46f1-8f39-4318-ada7-850f24804ce2

**Comment by grauw** [comment]
> Seems to make the registers EO and IL at R#9 irrelevant. Whatever is in there, the VDP behaves as if both bits are 1

That’s not true. The following test program results in flickering horizontal bands on a real MSX.

```basic
10 COLOR 15,1,1:SCREEN 5
20 SET PAGE 1,1:COLOR ,15:CLS
30 VDP(10)=VDP(10) OR 4
40 VDP(14)=&H11
50 VDP(1)=VDP(1) OR 4
60 I$=INPUT$(1):COLOR 15,4,4
```

It displays `page AND blink AND EO`, just like when the “caldari” bit is not set.

I think the IL flag is irrelevant to the behaviour since the only thing it does is slightly change the field timing so that monitors display it as interlaced rather than progressive.

**Comment by grauw** [comment]
p.s. I also confirmed that R#9 EO flag function and S#2 and S#6 EO status flags are not affected by the “caldari” bit.

Vibecoded test program: [vdpcaldari.zip](https://github.com/user-attachments/files/30287038/vdpcaldari.zip)
