### ISSUE TITLE
Silence playing OPL1 and MSX-AUDIO on MoonSound in VGMPlay

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1092]
It stops working after 00000011B is written to the register 05H of bank 2 (NEW / NEW2). Also does not start working again if I write 0 afterwards. Works on the real machine.

Note MSX-AUDIO playback on VGMPlay (w/o samples) is a new feature I submitted today, and the initialisation has also been reworked recently and it’s no longer working since I did that. But if you don’t want to compile latest, you can test on the 1.2 release as well by playing an OPL3 song first and then an OPL1 one.

**Comment by m9710797** [comment]
Can you (or someone else) provide more detailed instructions for how to
reproduce this? I'm not familiar with vgmplay nor do i have any song for it.

I (very) quickly looked at the source code of the OPLx emulation. At first
sight it seems that bit 0 in register 5/bank 2 can be switched on and back
off again. The most important effect of this bit is that it prevents writes
to other registers of bank 5. But switching the bit back off does not reset
the initial values of those registers. At least that's how it's currently
implemented, I'm not sure if the real hw behaves the same (but comments in
the code do suggest this).

Bit 1 in register 5 / bank 2 is special. Turning this bit on only has
effect once (until the next reset). Again, that's how it's currently
emulated, I'm not sure if that's also what the real hw does.

Wouter

**Comment by MBilderbeek** [comment]
@grauw Can you create a VGM of the whole 'session'? That makes it easier to reproduce and investigate.

**Comment by grauw** [comment]
Fyi, just retested, still reproducible.

**Comment by grauw** [comment]
Correction: not reproducible.

I recently introduced an issue in VGMPlay (which I just reverted) which caused me to think this was reproducible.

Odd thing is, I tried openMSX 0.14 with the repro steps in my first post, and there too I haven’t been able to reproduce it. So idk. Closing.
