### ISSUE TITLE
Music Module I/O port mirroring

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1093]
The MIDI and DAC I/O ports of the Music Module are mirrored:

00H-01H ACIA Write -> mirrored on 08H-09H, 10H-11H, 18H-19H
04H-05H ACIA Read -> mirrored on 0CH-0DH, 14H-15H, 1CH-1DH
0AH DAC Write -> mirrored on 08H-0FH, 18H-1FH

Pretty horrible pollution of the address space (esp. the ACIA read which will cause bus conflicts), but it is as it is.

Test the ACIA Read mirroring by ?INP:

10 FOR I=0 TO 31:PRINT HEX$(I);":";HEX$(INP(I));", ";:NEXT I

Test the DAC write (disabled by default) mirroring as follows:

10 OUT &HC0,&H18:OUT &HC1,1:OUT &HC0,&H19:OUT &HC1,1
20 FOR I=0 TO 31
30 PRINT HEX$(I)
40 OUT I,0:OUTI,255:IF INKEY$="" GOTO 40
50 NEXT I

I haven’t tested the ACIA Write but l_oliveira told me the chip select logic is the same (A3/A4 not connected) and it’s analogous with the read.

**Comment by m9710797** [comment]
I don't know about the context of this feature request, just wanted to comment on

    "... I don't think our I/O tag supports mirroring with 'gaps' in the range ...".

It is possible, not within a single <io> tag, but it is allowed to repeat that tag. And all those tags are taken into account. For an example see the ASCII_Japanese_MSX-Write_II.xml extension (it's not used for mirroring there, but the mechanism is the same).

**Comment by grauw** [comment]
I don’t think any software uses these mirrors to access the Music Module, however when other hardware is accessed on one of these I/O ports mirrored by the Music Module, it would work on openMSX but could cause problems on a real machine because it conflicts with the Music Module. So it’s a potential programming pitfall, and also it would be good in general if this mirroring is “documented” in the openMSX implementation as well.

For me iirc I ran into this because I had a crash on the real machine but not in openMSX, because VGMPlay is accessing OPNA hardware on I/O ports 14H-17H. Emulating this improves openMSX as a software development platform.

**Comment by MBilderbeek** [comment]
Leonard says:
<l_oliveira> okay, A4 and A3 are ignored for ACIA and DAC
<l_oliveira> DAC will mirror at ports 0x02, 0x0A, 0x12 and 0x1A
<l_oliveira> two bits = four addresses

**Comment by grauw** [comment]
> @grauw Hmm, did you realize that port 8 and 9 are then used for both ACIA Write and DAC Write? That seems unlikely! Are you sure about this?

Yep I’m sure.

They’re not both “used”, 00H-01H is used for the ACIA write, and 0AH is used for the DAC write. But their mirrors indeed overlap. Note that the mirrors aren’t intended to be used by users, rather it is a bad choice of cheap design to cut component cost at the cost of consuming nearly the entire first 20H of the I/O address space.

> Leonard says:
> <l_oliveira> okay, A4 and A3 are ignored for ACIA and DAC
> <l_oliveira> DAC will mirror at ports 0x02, 0x0A, 0x12 and 0x1A
> <l_oliveira> two bits = four addresses

That’s not correct, I just verified the mirroring I reported originally on my real Music Module:

    OUT &HC0,&H18:OUT&HC1,1:OUT &HC0,&H19:OUT&HC1,1  ' Enable DAC output
    O=&H0A:OUT O,0:OUT O,255

Enter both these lines and you will hear a click when the DAC responds. Then change the address value O to test different ports.

**Comment by MBilderbeek** [comment]
OK, an update from him, he confirms what you wrote:
<l_oliveira> A7, A6,A5 must be low and A3 high
<l_oliveira> A0, A1 and A4 don't care
<l_oliveira> 0001 1000 -> 18   0000 1000 -> 08
<l_oliveira> 0001 1011 -> 1B   0001 1111 -> 1F
<l_oliveira> if you doesn't use the mirrors and have the DAC disabled while using the ACIA there won't be any problems lol
< Quibus > l_oliveira: so Grauw's info was fully correct and there indeed is overlap?
<l_oliveira> yes he's right
