### ISSUE TITLE
[bug] Can't bind function keys higher than F15

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1096]
Depending on the Apple keyboard model that the user has, function keys can go up to F19. But the bind command refuses to accept any function key higher than F15.

**Comment by mthuurne** [comment]
SDL1 only has key symbols up to F15. In SDL2 they go all the way up to F24, so once we're on SDL2 we should be able to easily fix this, but not before then.

**Comment by MBilderbeek** [comment]
@sdsnatcher Can you confirm this is solved with the latest development build? Those are on SDL2.

**Comment by MBilderbeek** [comment]
Never mind... SDL2 may support it, but we didn't implement these in openMSX (yet).

**Comment by MBilderbeek** [comment]
@sdsnatcher OK, should be implemented now... please confirm.

**Comment by sdsnatcher** [comment]
Restested with openmsx-0.15.0-657, and it now works perfectly. You can close this bug.

**Comment by MBilderbeek** [comment]
Thanks for confirming, in the meantime I had already closed it :) I solved it about a year ago.
