### ISSUE TITLE
Can't load WAV at 2400 baud with 1200 baud header, real MSX works

### ISSUE THREAD

**Issue by Wierzbowsky** [openMSX/openMSX#1099]
When I try to load a WAV file created with 2400 baud rate via the cassette interface, the emulated MSX (tried several different machines) doesn't detect the audio stream. When I use the audio file made with 1200 or 3600 baud rate, everything is fine. I tested my 2400 baud rate file on a real MSX and it worked without a problem. 
So here are the WAV and MP3 files for reproducing the bug. You can use the BLOAD"CAS:",R command for loading the file WAV file, it's a TESTRAM.ROM.

http://podrezov.com/temp/testram.zip

**Comment by MBilderbeek** [comment]
Can you also provide the tools to create these wavs?

**Comment by Wierzbowsky** [comment]
You can use any tool that creates a WAV/MP3 out of a ROM file: Caslink3, MicroWaver, etc.
http://podrezov.com/caslink3.htm
http://cax.narod.ru/msx/packed/index.html

**Comment by MBilderbeek** [comment]
Did you try the following:
1. in openMSX, load testram.bin from a disk
2. in openMSX save testram.bin to cassette at 2400 baud
3. In openMSX load that wav file

I'd like to try it myself too, but I couldn't find testram.bin. Where can I find it?

**Comment by Wierzbowsky** [comment]
The ROM file is here:
http://podrezov.com/testram/testram.zip

Caslink made 2400 baud WAV files that always worked in OpenMSX until the last version.

**Comment by MBilderbeek** [comment]
But I can't bload a ROM file...

We didn't change anything about the WAV loading in openMSX in the last few years. Can you check in which version they still worked exactly?

**Comment by Wierzbowsky** [comment]
I made a BIN file out of this ROM:
http://podrezov.com/testram/TESTRAM.BIN

When I save it as WAV file in the emulator, then I can load it. I will keep digging on my end. No matter what options I try for 2400 baud, the emulator doesn't detect it. 1200 and 3600 baud work with all settings.

**Comment by Wierzbowsky** [comment]
Funny enough, the CAS file, that is made out of the WAV file that doesn't get recognized by OpenMSX, works correctly. There could, of course, be a problem with my 2400 WAV file and I keep looking for the problem. But the real MSX accepts this file without a problem.

[testram_wav.zip](https://github.com/openMSX/openMSX/files/1777728/testram_wav.zip)

**Comment by MBilderbeek** [comment]
Does the real MSX also accept the WAV file generated by openMSX?

**Comment by Wierzbowsky** [comment]
I need to try. The WAV file that is created from CAS file is different than mine. And it works with OpenMSX. So the problem could be in my WAV file indeed.

**Comment by Wierzbowsky** [comment]
Please reject this ticket. Seems that I found a 19 year old bug that only the emulator can reveal. On real MSXs the files worked just fine.

**Comment by MBilderbeek** [comment]
Well, the fact that it does load on real MSX still indicates that there is something wrong with the interpretation of the WAV on openMSX side. Can you explain in detail what the difference is between the wavs? What is the bug in your code that caused openMSX to not load the WAV? Perhaps it gives some insight.

**Comment by Wierzbowsky** [comment]
According to the investigation my 2400 baud WAV files had the headers with lower frequencies - 1200 baud, but the data was sent at 2400 baud rate. For some reason the real MSX machines are able to detect and load the data at a higher frequency even though the headers were for the slower data rate. I made a fix and put the Caslink v3.1 online. With this fix the headers are correctly encoded for 2400 baud files and OpenMSX now loads them. Attached is the example of the same BIN file correctly encoded at 2400 baud.

[testram_2400_real.zip](https://github.com/openMSX/openMSX/files/1778517/testram_2400_real.zip)

I also realized that my initial assessment of the 3600 baud data rate was wrong. The real data rate for the files that Caslink creates is around 3000 baud. I made necessary changes to the UI and readme. Looks like some things only get revealed after 20 years. :)

**Comment by Wierzbowsky** [comment]
There's also the opposite situation, when a file that loads on OpenMSX doesn't get loaded on a real computer. An example is attached.

[testram_3000_normal.zip](https://github.com/openMSX/openMSX/files/1778942/testram_3000_normal.zip)

**Comment by MBilderbeek** [comment]
@Wierzbowsky Can you tell me in which real MSX this wav file worked? Pedro Gimeno tried it on his VG 8020/40 and it behaved the same like in openMSX: the header isn't picked up, so the MSX ignores the file.

I guess I can better close this now then after all, but I hope you can still somehow show me that it works on your real MSX :)

**Comment by Wierzbowsky** [comment]
Just loaded the WAV file from my previous post to my YIS-805 MSX2 a few times in a row from my Samsung S7 phone. The computer may be picky, so it takes a few tries to set the volume on the phone correctly. Then everything will be loaded from the first attempt.

This file also works correctly with OpenMSX now.
