### ISSUE TITLE
Joystick seems stuck even though no (emulated) joystick connected

### ISSUE THREAD

**Issue by WildPenquin** [openMSX/openMSX#1101]
OpenMSX thinks joystick is in up+right position every time I start it, even if I have no joystick attatched, even if Joystick Port 1 is "--Empty--". I need to toggle joystick port 1 to something else and then back to "--Empty--", which will work around the issue untill I restart the emulated MSX.

What's going on, have I encountered a weird bug? 

This is on Linux, Arch to be specific:
```$ pacman -Qs openmsx
local/openmsx 0.14.0-1
    The MSX emulator that aims for perfection.
local/openmsx-catapult 0.14.0-2
    Front-end for openMSX: the MSX emulator that aims for perfection.
```

I have no other input devices attached besides a mouse and a keyboard (and joystick port 1 should be --Empty-- according to catapult!

**Comment by MBilderbeek** [comment]
According to Catapult, but also according to openMSX? 
Please open the console (press F10) and type: `plug` and tell us the output. Perhaps it's an issue with Catapult not showing what's plugged in properly.

**Comment by WildPenquin** [comment]
"plug" console command shows that joystick1 is plugged in "port 1" although --empty-- is selected at boot. Weird!

**Comment by WildPenquin** [comment]
That actually explains what is happening. My Corsair K95 RGB Platinum is seens as a 25 axis game controller by the Kernel (the G1-G6 buttons and other special keys tweak some of the axis .. axises, what's the plural?). In any case, all axis are stuck at -32676 per default, which equals to up+left (or is that right, I'm not actually sure).

So this is actually combination of two issues: joystick1 is plugged in although the user has  chosen not to and some weird keyboards with no real / complete Linux support are seen ... weirdly by the Kernel.

**Comment by MBilderbeek** [comment]
There is a script that tries to plug in logical stuff (`autoplug.tcl`). E.g. if your system has a joystick (joystick1), it will plug it in joystick port A. This is intentional and supposed to be a convenience feature.
Apparently there is a bug in Catapult that it doesn't show this... We could make this report a bug report to address that bug in Catapult.

**Comment by WildPenquin** [comment]
That sounds like a bug in catapult.

However, I'm not sure the behaviour of the script, i.e. plugging in all found controllers, is always desired. At least on Linux, there are several devices which are reported as joysticks, but actually are not. For example, my Macbook Pro has a gravity sensor, and the Kernel sees this as a two-axis joystick. This has never caused problems for me, but that could be just because I've played on a flat surface.

Suppose I was playing boulder dash (trough the keyboard) on a train or need to tilt the Macbook for whatever reason ... poor Rockford!

But, if Catapult would reflect this at least the user will see what is going on. But, also there should be an easy way to disable the script (perhaps there already is?). I can see that in most cases it probably is a convenience, and agree the script should be on per default.

**Comment by MBilderbeek** [comment]
Can you check in the latest development code of Catapult whether this is fixed now? I fixed displaying the plugged in devices at start-up in wxcatapult@35add0943ed4500e19414a0402cd7e82671e4663.

**Comment by WildPenquin** [comment]
Hi Manuel,

I tried with newest Catapult, and it seems that my Corsair K95 special keys are not plugged in as a joystick anymore! Has the auto-plugging script been changed, too? I checked, and the Linux Kernel still sees a /dev/input/js0 device form my keyboard (and the equivalent event devices are there, too). 

I changed the plugged in joystick device manually trough OpenMSX OSD, and that did register also in Catapults UI.

**Comment by MBilderbeek** [comment]
Thanks for testing!

I only changed Catapult itself. There were some bugs.

The auto-plug script has not really been changed.

If I understood you correctly, you confirm that this issue is fixed, so I'm closing the ticket. Please reopen if I misunderstood.
