### ISSUE TITLE
Disabling sprites should not be instant

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1104]
[tiletile.rom.zip](https://github.com/openMSX/openMSX/files/1965032/tiletile.rom.zip)
[tiletile.rom.zip](https://github.com/openMSX/openMSX/files/1965033/tiletile.rom.zip)

In openMSX, disabling sprites is instant. However on the real V9958, it waits until the end of the line, just like disabling display.

Test ROM: [tiletile.rom.zip](https://github.com/openMSX/openMSX/files/1964947/tiletile.rom.zip) (V9958 only)

To test, walk down a ways to bring the sprite halfway into the dialog box. Notice that in openMSX the bottom line of the sprite starts flickering (tested on turboR btw). This is the sprites which are being disabled mid-way through the line. If you walk left, the bottom sprite line will become visible. If you walk right (or left through the border), it will disappear.

On a real MSX, the bottom sprite line always stays visible.

**Comment by m9710797** [comment]
Hmm, I tried to implement this ... I postpone updating the 'sprite-enabled-status' till the start of the next line, but for some reason the turbor boot-logo hangs after this change. I've no idea why yet. (Maybe something related to sprite collisions???)

Feel free to try/review/fix the attached patch.
[spriteEnabled.patch.txt](https://github.com/openMSX/openMSX/files/1977434/spriteEnabled.patch.txt)

**Comment by m9710797** [comment]
Just though of something but won't have time to try it out for several days, so I'm documenting it here...

Maybe the sprite-collision and/or sprite-overflow checks are enabled/disabled immediately but the sprite rendering status is kept constant for the whole line?

**Comment by grauw** [comment]
The patch has a little bug, the initial value of spriteEnabled should be true.

In the boot screen the SPD bit is never changed from its default value (0=enabled), and thus execSetSprites() is never invoked to set it to its proper value.

**Comment by m9710797** [comment]
Thanks again!  Fix pushed.
