### ISSUE TITLE
Carnivore 2 shown as not working in Catapult

### ISSUE THREAD

**Issue by Vampier** [openMSX/openMSX#1110]
Carnivore 2 shown as not working in Catapult despite working when loading as -ext from the CLI or from the console. 

[Gmail - Catapult for Windows.pdf](https://github.com/openMSX/openMSX/files/2159902/Gmail.-.Catapult.for.Windows.pdf)

**Comment by MBilderbeek** [comment]
Fixed in wxCatapult revision 57d1def1b4097c4e7ca1681ca1ab563db532de6c
