### ISSUE TITLE
bug compilation on linux ubuntu 64 bits openmsx

### ISSUE THREAD

**Issue by retrocant** [openMSX/openMSX#1111]
I'm compiling the latest version that has been published openmsx in github, but when compiling I get a bug in the compilation. attached message.
![crash-linux-blipbuffer](https://user-images.githubusercontent.com/23484201/42366983-ebbed9ea-8102-11e8-9435-cd5303e5b11a.png)

**Comment by m9710797** [comment]
I'll look into this (later today).
Which compiler are you using and which version?
Since recently we require a c++14 capable compiler (gcc-6 or above should
be fine, though I'm doing most of my tests with gcc-7 or gcc-8).

Wouter

**Comment by m9710797** [comment]
Quick update:
When I compile with gcc-5 i get the same error. gcc-6, 7, or 8 work fine.
Later this weekend I'll try to figure out exactly what's going wrong with
gcc-5 and possible fix/workaround it. Or else document that the minimal
required gcc version is now gcc-6.

Wouter

**Comment by MBilderbeek** [comment]
Strange, I was able to build openMSX with g++-4.9 in the Android toolchain without problems. 4.8 did not work, though.
