### ISSUE TITLE
OPL4 fixes by ValleyBell

### ISSUE THREAD

**Issue by niekvlessert** [openMSX/openMSX#1114]
VGMRips soundchip guru ValleyBell did some nice fixes on the OPL4 emulation in VGMPlay. I think those should be ported to OpenMSX since they solve a bunch of longstanding bugs in the emulation. Thanks go to Meits and Abeker for pointing them out and to Meits for providing recordings.

Here are the bugs I've collected:

- The applause thing. When creating a track in MBWave just playing applause the original hardware will make the sound fade pretty soon. OpenMSX will play the applause forever.
- The cymbal thing. When creating a track in MBWave playing the cymbal it's easy to hear the different swelling times on original hardware and OpenMSX.
- The Lizard Star sound effect using a OPL4 glitch explained here: https://www.msx.org/news/challenges/en/gmc-19-salamander-starfield-omega
It's simply not played on OpenMSX.
- The Bombaman Boss Approaching 1 sound effect; same as Lizard Star
- The Bombaman Boss Approaching 6 volume decreasing going to slow on OpenMSX.

And many more volume related things.

All bugs happened in VGMPlay as well.

Because of my reporting ValleyBell created a very nice tool that creates VGM files based on csv input like those:

#Mode   Octave  AR      D1R     D1L     D2R     RR      RC      PRVB
Env     0       4       15      8       15      15      15      0

With that it's possible to create really specific tests for certain parts of the emulation. So a lot of vgm files where created (in the end mostly by ValleyBell himself) to test. When comparing recordings from Meits and l_oliveira on real hardware using Grauw's MSX vgmplay and wave files generated with the regular vgmplay a lot of issues surfaced and were fixed as well. ValleyBell reported that the emulation was simply not like the spec in some areas, and the real hardware was.

With ValleyBell's patches the emulation seems the same in all areas, but all previous mentioned differences between real hardware and the emulation are gone.

I tried for a bit to patch ymf278.cc myself, but I figured I'd never do it good enough, so I would like to report the following URL so you can implement the changes yourself. If you want of course. :)

https://github.com/ValleyBell/libvgm/compare/f80f621ffcee...afded2ea8d41

ValleyBell himself reported his changes like this in there:

Improvements:
- added TL interpolation, recordings show that internal TL levels are 0x00..0xFF
- fixed ADSR speeds
- correct clamping of intermediate Rate Correction values
- emulation of "loop glitch" (going out-of-bounds by playing a sample faster than it the loop is long)
- made calculation of sample position cleaner and closer to how the HW works
- increased output resolution from TL (0.375 db) to envelope (0.09375 db)
- fixed volume table - 6 db steps are done using bit shifts, steps in between are multiplicators
- made octave -8 freeze the sample

**Comment by niekvlessert** [comment]
There's news:

The implementation in VGMPlay now contains some of the fixes as well. But it's better to look at libvgm, it's more complete and better documented.
https://github.com/vgmrips/vgmplay/commit/4f907be463fce4245e474d79784f6f01307e60f7

And now there's damping as well. :)
https://github.com/ValleyBell/libvgm/blob/master/emu/cores/ymf278b.c#L456-L470

**Comment by MBilderbeek** [comment]
@niekvlessert can you confirm the Bombaman issues are fixed in the current openMSX development tree?
