### ISSUE TITLE
Reverse issue with GFX9000

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1117]
When playing the demo of Life on Earth, a V9990 game for MSX2, graphics corruption occurs when reversing.

Originally reported here: https://www.msx.org/comment/reply/55292/343491

> You can download a playable demo, with the box art and manual from this link:
> http://s000.tinyupload.com/?file_id=53121941076909248742

I'll attach the ROM file for convenience.
[LOEDEMO.rom.gz](https://github.com/openMSX/openMSX/files/2320859/LOEDEMO.rom.gz)

**Comment by m9710797** [comment]
I think it's fixed. But can someone double check? It fixes some corruption, but I'm not sure all corruption is fixed. IOW I can't make the graphics glitch anymore when using reverse, but maybe I'm not testing the right things.

**Comment by MBilderbeek** [comment]
I couldn't reproduce my test case either, but I challenged the people who found the issue on MSX.org...

**Comment by m9710797** [comment]
Fix confirmed by 'Iamweasel'.
