### ISSUE TITLE
[Feature] Better Tape image support [sf#88]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#112]
**Reported by zabado78 on 2004-09-21 10:41 UTC**
I think openMSX must support the TZX for tape images,
as worldofspectrum does. It's better than Cas or Wav
format and also we can preserve those tape games
released for the MSX-1. For example, The caps project
(http://www.caps-project.org/\) will preserve all Amiga
disc images, they have a file format to do it(IPF) and
they are doing perfect images of disks(read more in
their page about), and in the future they will support
others disk systems(i hope the MSX is in their list).
But for tape images, there's worldofspectrum, doing the
same, and their file format is the TZX(wich can support
MSX tape images), but there isn't a Msx emulator out
there with support for this. Can openMSX be the first?.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-08-25 09:30 UTC**
see also http://www.msx.org/forum/msx-talk/openmsx/why-not-tsx-formata-msx-tapes for more details, opinions and other discussion on this topic.

**Comment by MBilderbeek** [comment]
Although this ticket is way older, I'm closing it as the discussion seems to be going on now in #1076 .
