### ISSUE TITLE
[MacOS] No video output building with XCode 10.1

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1126]
When running openMSX built with XCode 10.1 I get a window with no video output. Everything is working, I hear sound and key clicks, just a blank window:

<img width="752" alt="schermafbeelding 2018-11-24 om 14 40 21" src="https://user-images.githubusercontent.com/772052/48968943-ec48fe00-eff6-11e8-961e-9607bb90959c.png">

The 0.14.0-293-a6644b41e build I made a couple of months ago works fine though.

The problem looks exactly like the one [mentioned here](https://github.com/kovidgoyal/kitty/issues/887). It seems openGL is now always rendered on a layer even if wantsLayer is set to NO. I think [this comment](https://github.com/kovidgoyal/kitty/issues/887#issuecomment-432013674) is the most relevant there.

Because the old version still works, this seems to have to do with the XCode version, and [here](https://stackoverflow.com/questions/52509427/mac-mojave-opengl) someone also “fixed” the same issue by downgrading to XCode 9.4.1. It seems to have to do with [this note about Layer-Backed Views](https://developer.apple.com/documentation/macos_release_notes/macos_mojave_10_14_release_notes/appkit_release_notes_for_macos_10_14#3014921) in the AppKit 10.14 release notes. Not sure if the MacOS version is relevant, but I’m on MacOS 10.14 (upgraded at the same time as XCode).

Adding <setting id="renderer">SDL</setting> to settings.xml, or setting it blindly from the console, or changing the scale factor to 3x and back all did not seem to have any effect (other than resizing the window for the latter). I was hoping that might have triggered one of those update calls they mentioned.

Anyway I know little about MacOS rendering, so I have no clue how go from this information to a fix :).

**Comment by MBilderbeek** [comment]
Does dragging the window help to get something rendered on it?
You said that if you use the SDL renderer you still don't get graphics. That seems to imply that it's not related to OpenGL. Are you sure the command to set the SDL renderer was correctly executed?

Can you confirm that it works by downgrading Xcode to 9.4.1?

Did you find threads of projects which are using SDL that ran into this and solved it?

Is there something printed in the terminal if you start it from there? Or some other kind of error message available?

**Comment by FiXato** [comment]
I'm not sure which version niekniek compiles on, but can you run his latest builds without issues? http://openmsx.fixato.net/builds/mac/x86_64/

**Comment by MBilderbeek** [comment]
@NiekVlessert Which XCode (and OS) are you compiling on?

**Comment by grauw** [comment]
> Does dragging the window help to get something rendered on it?

Nope.

> You said that if you use the SDL renderer you still don't get graphics. That seems to imply that it's not related to OpenGL. Are you sure the command to set the SDL renderer was correctly executed?

Pretty sure. I don’t know how SDL renders, but it still needs to composite at some point?

> Can you confirm that it works by downgrading Xcode to 9.4.1?

I could but it’s quite a hassle, I think we can assume it’s got to do with the new Xcode version.

> Did you find threads of projects which are using SDL that ran into this and solved it?

I find:

* https://discourse.libsdl.org/t/macos-10-14-mojave-issues/25060/4
* https://github.com/ggez/ggez/issues/478
* https://bugzilla.libsdl.org/show_bug.cgi?id=4272 ◀️

> Is there something printed in the terminal if you start it from there? Or some other kind of error message available?

Nothing.

> I'm not sure which version niekniek compiles on, but can you run his latest builds without issues? http://openmsx.fixato.net/builds/mac/x86_64/

Yes, that one works.

**Comment by niekvlessert** [comment]
I'm on macos 10.13.6. I haven't installed the full xcode, just the command line tools. No IDE. Can't use the normal way to see the version.

xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

This might be the xcode version;

pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 10.1.0.0.1.1539992718

**Comment by grauw** [comment]
Workaround to get openMSX to display the video output: minimize window and restore it. 

When you go to fullscreen it stops working again. Also doesn’t work when renderer is set to SDL.

As can be seen in the SDL bugzilla link above, the issue was fixed in SDL2 about 6 weeks ago. There’s no backport to SDL1.2 yet.

**Comment by MBilderbeek** [comment]
As we are now on SDL2, this issue can be closed, right? Please reopen if I'm mistaken.

**Comment by D15C0DE** [comment]
The compilation guide still mentions this.

**Comment by MBilderbeek** [comment]
@grauw @niekvlessert Can you guys please confirm that the XCode issue is solved now that we're on SDL2?
If yes, then I didn't close this for nothing and the Compilation Guide's warning can be removed as suggested by @D15C0DE .

**Comment by grauw** [comment]
Yes, confirmed fixed. I’ve been building my own builds again.

**Comment by MBilderbeek** [comment]
So, the latest version (10.x??) of XCode can be used, right? The whole remark in the Compilation Guide can be removed? Or is there still something to be said about the XCode version to use?

**Comment by niekvlessert** [comment]
Yes, overhere it compiles fine with 10.x

So afaik nothing to report on that.

Regards,

Niek

**Comment by grauw** [comment]
Ditto. I’m on XCode 11.1 currently.
