### ISSUE TITLE
Expected floating-point number but got...

### ISSUE THREAD

**Issue by plainspooky** [openMSX/openMSX#1132]
I'm using the 0.14.0 version of OpenMSX (Ubuntu 18.04's package) and it always shows the message on STDOUT::

`expected floating-point number but got ""`

It didn't affect normal execution, it's just like a message warning message.

**Comment by m9710797** [comment]
Hi,

Obviously that shouldn't happen ;)
We should investigate what triggers this. I can think of two possible reasons.

1) An invalid value in the settings.xml file.
Try deleting (or maybe better renaming) your ~/.openMSX/share/settings.xml file. This should restore all settings to their default value. (It's unlikely but maybe you have settings defined in /usr/share/openmsx/settings.xml).

2) This error triggers from some of the Tcl scripts that are run when openMSX starts.
Figuring out which script exactly triggers it is a bit harder. I'll prepare something for this later this evening (I'm at work right now).

**Comment by MBilderbeek** [comment]
I believe this issue was fixed somewhere along 0.15.0 development. Can you try with 0.15.0, somehow?

**Comment by MBilderbeek** [comment]
Apparently this issue got fixed with 6fe1310e4c75681fa79ea454e73a202c0bd75eb0

Please let me know if you can somehow confirm this, and feel free to comment. I'll close it in the meantime.
