### ISSUE TITLE
MSX2+/TR with external disk interface get diska and diskb swapped

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1135]
If you boot an MSX2+ or MSX Turbo-R with an extra external interface attached, the diska and diskb console commands (and command line switches) will be swapped.

Tested on openMSX-0.1.15 on Mac OS-X 10.14

Steps to reproduce:

1) Create two disk images

DISK1.DSK containing only a file named "DISK1.TXT" 
DISK2.DSK containing only a file named "DISK2.TXT" 

2) Boot a Panasonic FS-A1GT with a Sony HBD-F1 connected on its 1st slot

3) Cpen the console and type
diska DISK1.DSK
diskb DISK2.DSK

4) Close the console and type on BASIC

FILES"A:"
FILES"B:"

Results: Note that FILES"A:" will show DISK2.TXT and " FILES"B:" will show "DISK1.TXT". This is the exact opposite of that will be shown on a real A1GT under the same conditions.

**Comment by m9710797** [comment]
OpenMSX makes no attempt to match hardware disk names (diska, diskb, ...) with drive letters assigned by the MSX.

Another scenario where this goes wrong is when you e.g. insert the 'ide' extension. Depending on how many partitions there are on your harddisk image, the internal disk drive may get assigned the letter B, C, D, ...

The assignment is also different depending on whether you boot the MSX with the CTRL or SHIFT key pressed.

When using an alternative operating system on the MSX machine (like symbos?) the drive assignment might yet be different from what the normal MSX software does.

So I agree that the original scenario described in this issue may seem like a bug (or at least surprising). But it's not clear how to 'fix' it. Moreover I don't believe the general case is fixable. Assigning drive names in slot-order (not so easy to implement) will fix the original scenario, but it won't fix the first two (more common?) scenarios I just described.

Currently openMSX assigns drives names:
 - First to the drives in the machine itself (in the order they appear in the machine xml configuration).
 - Next to the extension(s), in the order those extension are specified on the command line.

(Detail: it's also possible to insert additional extensions when the MSX is already running.)

**Comment by sdsnatcher** [comment]
Yes, indeed other scenarios can also influence the order of the driver letter assignment. But at least from my experience, the IDE seems to behave like the real MSX.

But it's better to focus on the original scenario, since the IDE uses specific command line switches (-hda, -hdb etc), and AFAIK only floppies use -dska, -dskb etc

I think that the catch is exactly here:

> Currently openMSX assigns drives names:
> 
> First to the drives in the machine itself (in the order they appear in the machine xml configuration).
> Next to the extension(s), in the order those extension are specified on the command line.

While the MSX will assign the drives by their slot precedence.

So, probably it would suffice if openMSX assigned the drive letters the same simple way that the MSX does: by ordering them by their slot/subslot number.

> (Detail: it's also possible to insert additional extensions when the MSX is already running.)

This is probably the trickiest emulation scenario. While this possible on a real MSX with a slot expander that has enable switches, the MSX only searches for the disk interfaces on boot. So any hot plugged interfaces will be just ignored until a (sw or hw) reset is done. 

OTOH, openMSX couldn't reassign the drive letters until a reset is done, but while it does know about hw resets, probably it has absolutely no control over software resets.

**Comment by MBilderbeek** [comment]
Exactly because of that last point, I don't think we can improve the situation as it is now. 
It would be possible to assign them initially by slot precedence, but this order won't be reliable when new devices are plugged in at boot time. So there will never be a guarantee it is the same as the MSX drive letters. 
Also, what about 'virtual' MSX drives? I think that if you connect 2 disk interfaces, both will always use 2 drive letters, but if these interfaces both only have one drive, drive letters B and D will be reserved, but not used. 
And what about booting with CTRL?

I propose we close this ticket, as there is no way to really improve things, AFAICS.

**Comment by MBilderbeek** [comment]
No comments anymore, closing. Feel free to comment or reopen even if necessary.
