### ISSUE TITLE
[macOS] Crash when closing openMSX while console is open

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1136]
I just got the following crash when I closed openMSX with CMD-Q:

[openmsx_2018-12-29-011519_Laurenss-MacBook-Pro.crash](https://github.com/openMSX/openMSX/files/2715934/openmsx_2018-12-29-011519_Laurenss-MacBook-Pro.crash.txt)

Running openMSX-0.15.0-117-gd8f4cd8a4 [opt]. I’ll run with a debug build for a while to see if I can reproduce with a better stack trace.

**Comment by m9710797** [comment]
Crash was probably introduced in ea7d554a4f1 which removed a workaround for an old bug in libstdc++. Though it turns out that libc++ has the same problem. See commit message for more details.
