### ISSUE TITLE
'-setting' with relative path segfaults

### ISSUE THREAD

**Issue by immetoo2** [openMSX/openMSX#1137]
To reproduce;

`cd /tmp`
`copy cp /opt/openMSX/share/settings.xml .`
`openmsx -setting settings.xml`
`Segmentation fault`
`openmsx -setting ./settings.xml`
`Segmentation fault`
`openmsx -setting /tmp/settings.xml`
`works`

Fails on both debian version 0.14.0 and current master.

**Comment by m9710797** [comment]
I can reproduce this. I'll try to fix it soon.
