### ISSUE TITLE
throttle in settings file does not work

### ISSUE THREAD

**Issue by immetoo2** [openMSX/openMSX#1138]
When using the settings file to disable throttle it gets ignored
`<setting id="throttle">off</setting>`

**Comment by m9710797** [comment]
Not all settings are saved. `throttle` is an example of a setting that is not saved, and thus it's also not loaded from settings.xml. Other examples of settings that are not saved are `pause` and `mute`.
E.g. suppose you're running openMSX at full speed (you pressed F9) or you paused or muted openMSX (you pressed PAUSE or F11). Then you exit openMSX. Next time you start openMSX you probably want to run at normal speed again.

**Comment by immetoo2** [comment]
That fine, just was wondering why i couldn't move this from tcl to settings.
