### ISSUE TITLE
[Feature] Remember position in ROM / Disk image load menu

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1163]
When you have loaded a ROM or Disk image and want to load another one it would be helpful imho if openMSX would be at the position of the previously loaded item.

So let's say I just loaded Disk A from a game (with many disks in the directory) and have to now set Disk B there would be no need to scroll through the whole list again. This behaviour is already present in the Change Machine menu, where the menu goes to the active machine in the list and not the top of the list).

**Comment by MBilderbeek** [comment]
Good idea, I just implemented it! Thanks!
