### ISSUE TITLE
When starting openMSX with a CAS file and shift pressed during boot RUN"CAS*" is typed

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1165]
Don't ask me why, but I was load Zanac A.I. from CAS file on a National CF-3300 (MSX1 with a disk drive). During loading the game stopped and instructed me to remove the disk drive or boot with shift pressed. I did the latter (of course) and noticed that openMSX than typed RUN"CAS*" instead of RUN"CAS:" so it used the shifted character somehow... Not a big deal of course but still not the expected behaviour (imho)

**Comment by sdsnatcher73** [comment]
The name of the CAS file was "Zanac (1987)(Eaglesoft)(NL)[RUN'CAS-'].cas"

**Comment by MBilderbeek** [comment]
When you hold shift whilst openMSX is typing RUN"CAS:", that shift will be taken into account. So, just release the shift key right after the beep and the typing will be OK.

Please try it.

I'm not sure if we can let openMSX ignore user input whilst performing a type command. Perhaps that would be a final solution.

**Comment by sdsnatcher73** [comment]
Yes I did that and it works. I think during (scripted) type at least any modifiers (shift/ctrl/kana/graph/code anything else?) should be ignored... Again not a big deal for now

**Comment by NYYR1KK1** [comment]
My recommended workaround for now:
set default_type_proc type_via_keybuf

**Comment by MBilderbeek** [comment]
This issue is now fixed, thanks to Wouter. See bf64bd86be186fe3366d1aad52c6211426cd7239. Thanks!
