### ISSUE TITLE
Duplicate machine entries on MacOS

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1167]
On MacOS when switching machine through the UI the list contains many duplicate machines (for which only 1 .xml is in the share/machines folder). See screenshots.

Duplicate National CF-3300:
<img width="752" alt="duplicate_cf3300" src="https://user-images.githubusercontent.com/26295777/59748155-c2994200-927a-11e9-848a-ba41579b0031.png">
Duplicate Panasonic FS-A1GT and FS-A1WSX:
<img width="752" alt="duplicate_atgt_a1wsx" src="https://user-images.githubusercontent.com/26295777/59748164-c75df600-927a-11e9-85ee-f46c0dff261a.png">
Duplicate Philips NMS-8250:
<img width="752" alt="duplicate_nms8250" src="https://user-images.githubusercontent.com/26295777/59748172-cc22aa00-927a-11e9-8c86-6179d22140e2.png">

**Comment by sdsnatcher73** [comment]
Apparantly proc get_filtered_configs in _osd_menu.tcl is supposed to filter out symlinked machine configuration files but that is not working:

These are the symlinks that are created on MacOS:
lrwxr-xr-x    1 peter  staff     20 Jun 19 10:14 msx1.xml -> National_CF-3300.xml
lrwxr-xr-x    1 peter  staff     17 Jun 19 10:14 msx1_eu.xml -> Toshiba_HX-10.xml
lrwxr-xr-x    1 peter  staff     16 Jun 19 10:14 msx2.xml -> Sony_HB-F900.xml
lrwxr-xr-x    1 peter  staff     20 Jun 19 10:14 msx2_eu.xml -> Philips_NMS_8250.xml
lrwxr-xr-x    1 peter  staff     22 Jun 19 10:14 msx2plus.xml -> Panasonic_FS-A1WSX.xml
lrwxr-xr-x    1 peter  staff     21 Jun 19 10:14 turbor.xml -> Panasonic_FS-A1GT.xml

This is the procedure that probably works fine on linux but not on MacOS:

```
/ Returns list of machines/extensions, but try to filter out duplicates caused
/ by symlinks (e.g. turbor.xml -> Panasonic_FS-A1GT.xml). What this does not
/ catch is a symlink in the systemdir (so link also pointing to the systemdir)
/ and a similarly named file in the userdir. This situation does occur on my
/ development setup, but it shouldn't happen for regular users.
proc get_filtered_configs {type} { ... }
```

**Comment by sdsnatcher73** [comment]
confirmed fixed

**Comment by MBilderbeek** [comment]
Funny, it never worked properly, from the initial implementation in 2014...
Glad it's fixed now. Thanks for the confirmation.

Op do 20 jun. 2019 11:33 schreef peterhanraets <notifications@github.com>:
