### ISSUE TITLE
Add Dir-as-disk function for SCSI/IDE harddrive, CF or SD cards

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1168]
Dir-as-disk is really great for floppies and it would be even greater if we could use it with SCISI or IDE hdd or Carnivore2 CF or MegaFlashROM SCC+ SD. These now require image files and just 'mounting' a directory to an MSX (through the mentioned extensions) would make life so much easier.

As an alternative (or first implementation) you could just create a completely virtual extension (one that does not exist as a real MSX cartridge) but would just act as a HDD towards the MSX (of course only if this would be easier than the initial idea).

**Comment by MBilderbeek** [comment]
See #1061, closing this one as duplicate. Feel free to add comments there.
