### ISSUE TITLE
[Feature] Support for SVI-3x8, Colecovision and Sega SG-1000 [sf#93]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#117]
**Reported by andete on 2004-10-07 15:46 UTC**
As openMSX has become more and more mature it in essence is 
a very nice emulator development platform (think MESS, or 
maybe not :) ), which currently only supports the MSX systems. 

Maybe this should somehow be kept in mind and the possibility 
to use openMSX as a base for emulator machines like BBC, 
C64, ... should be made more obvious. 

Just some wild ideas, please kickstart your flamethrowers!

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2005-04-03 12:13 UTC**
Logged In: YES 
user_id=78178

We have decided not to do this, but we do want to support
the SVI-3x8, Colecovision and maybe the Sega SG-1000. That's
why I'm changing this RFE to reflect that.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2005-04-03 12:13 UTC**
- **priority**: 1 --> 5
- **summary**: openMSX as emulator development platform --> Support for SVI-3x8, Colecovision and Sega SG-1000

**Comment by MauricioBraga** [comment]
Hmmm, ZX Spectrum could be considered as well, since it is too close to a MSX (so close we have lots of games ported to MSX). :)

**Comment by MBilderbeek** [comment]
We already support all of these, so closing this issue. (ZX-Spectrum is tracked in #1152 .)
