### ISSUE TITLE
Building staticbindist on macOS Catalina fails during retrieval of 3rd party dependencies

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1189]
I just installed macOS Catalina and tried to build from source:

peter@macbook openMSX % make staticbindist
Using Python: python3
/Library/Developer/CommandLineTools/usr/bin/make -f build/main.mk run-3rdparty \
		OPENMSX_TARGET_CPU=x86_64 \
		OPENMSX_TARGET_OS=darwin \
		OPENMSX_FLAVOUR=opt \
		3RDPARTY_FLAG=true \
		PYTHON=python3
Using Python: python3
/Library/Developer/CommandLineTools/usr/bin/make -f build/3rdparty.mk \
		BUILD_PATH=derived/x86_64-darwin-opt-3rd/3rdparty \
		OPENMSX_TARGET_CPU=x86_64 \
		OPENMSX_TARGET_OS=darwin \
		_CC=clang _CFLAGS=" -arch x86_64 -mmacosx-version-min=10.7 -stdlib=libc++ -m64  -O3 -DNDEBUG -ffast-math -fomit-frame-pointer" \
		_LDFLAGS=" -arch x86_64 -mmacosx-version-min=10.7 -stdlib=libc++ -m64" \
		WINDRES=windres \
		LINK_MODE=3RD_STA \
		PYTHON=python3
mkdir -p derived/3rdparty/download
python3 build/download.py http://downloads.sourceforge.net/freetype/freetype-2.9.1.tar.gz derived/3rdparty/download
build/download.py:16: DeprecationWarning: DownloadURLOpener style of invoking requests is deprecated. Use newer urlopen functions/methods
  _urlOpener = DownloadURLOpener()
Downloading freetype-2.9.1.tar.gz: FAILED.             
[Errno socket error] [Errno socket error] [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
make[2]: *** [derived/3rdparty/download/freetype-2.9.1.tar.gz] Error 1
make[1]: *** [run-3rdparty] Error 2
make: *** [3rdparty] Error 2
peter@macbook openMSX %

**Comment by mthuurne** [comment]
This seems to be a [packaging issue](https://stackoverflow.com/questions/57630314/ssl-certificate-verify-failed-error-with-python3-on-macos-10-15?noredirect=1) with the way Apple ships Python 3. Hopefully they will fix it soon.

**Comment by mthuurne** [comment]
I pushed a fix for the `DeprecationWarning` that is shown in your log. However, this is unlikely to have any effect on the SSL problem.

**Comment by sdsnatcher73** [comment]
If I copy over a previous build dir from Mojave the build goes through but there is an issue at the end:
hdiutil: internet-enable: verb not recognized
Usage: hdiutil <verb> <options>
<verb> is one of the following:
help            	flatten
attach          	imageinfo
detach          	isencrypted
eject           	makehybrid
verify          	mount
create          	mountvol
compact         	unmount
convert         	plugins
burn            	resize
info            	segment
checksum        	pmap
chpass          	udifderez
erasekeys       	udifrez
unflatten       	
make[1]: *** [bindist] Error 1
make: *** [staticbindist] Error 2

**Comment by sdsnatcher73** [comment]
After installing python3 through brew the build runs fine, so it is definitely an issue with the python3 packaged with macOS Catalina.

**Comment by mthuurne** [comment]
I can't find any documentation about hdiutil's `internet-enable` verb being removed, so I don't know if the option was removed entirely or renamed.

**Comment by mthuurne** [comment]
Niek did a quick test and the "internet enabled" flag doesn't seem to do anything anymore, so I removed setting that from the build. See b967c0d3.

**Comment by MBilderbeek** [comment]
@peterhanraets can you please confirm whether this is fixed?

**Comment by sdsnatcher73** [comment]
Yes this is fixed
