### ISSUE TITLE
On MacOS c-bios ROMS are in machines as well as systemroms 

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1199]
I was cleaning up my systemroms folder (because there are many duplicate roms shared by many machines), but I noticed that the openMSX.app I build from source has many c-bios roms:

This is what is in share/machines:
cbios_basic.rom
cbios_logo_msx2+.rom
cbios_main_msx1_br.rom
cbios_main_msx2+.rom
cbios_main_msx2+_jp.rom
cbios_main_msx2_eu.rom
cbios_sub.rom
cbios_disk.rom
cbios_logo_msx2.rom
cbios_main_msx1_eu.rom
cbios_main_msx2+_br.rom
cbios_main_msx2.rom
cbios_main_msx2_jp.rom
cbios_logo_msx1.rom
cbios_main_msx1.rom
cbios_main_msx1_jp.rom
cbios_main_msx2+_eu.rom
cbios_main_msx2_br.rom
cbios_music.rom

Then there is a folder cbios-old in share/systemroms which has 54 gzipped roms. I think these could be removed and the files in share/machines should actually be in share/systemroms/cbios folder.

**Comment by sdsnatcher73** [comment]
A quick test removing the cbios-old folder from share/systemroms and moving the roms in share/machines to share/sytemroms/cbios and then trying out all C-BIOS machines reveals they all still work.

**Comment by m9710797** [comment]
Maybe I'm mistaken, but ...
Don't we keep those old cbios roms for backwards compatibility for with older savestates/replays?

**Comment by mthuurne** [comment]
Yes, the old C-BIOS ROMs are there to make sure old save states will still load. They should not be removed.

**Comment by mthuurne** [comment]
About the location of the current (last release) C-BIOS ROMs: while I agree that the `systemroms` folder is a more logical location than `machines`, moving the files might cause fallout in installation and packaging scripts that are expecting the files at the old location. At the moment, I don't see a pressing reason to move the files, so I'll close this issue for now. If at some point in the future there is a clear advantage to moving the ROMs, we can do so then.
