### ISSUE TITLE
Bug with Z88DK BIOS test

### ISSUE THREAD

**Issue by AxelStone** [openMSX/openMSX#1200]
Hello, following code generated in Z88DK using ASMLIB from Nestor, fails. It should reproduce a BEEP but it generates buggy sound:

```
#include <stdio.h>
#include <arch/msx/asm.h>

#define BEEP   0x00C0 // Sounds the buffer

Z80_registers regs;

void beep() {
	BiosCall(BEEP,&regs,REGS_NONE);	
}

int main()
{
   beep();
   return 0;
}

```

In real MSX or Zemmix Neo it sounds right.

**Comment by MBilderbeek** [comment]
Thanks for reporting! Can you please provide the resulting COM or ROM file so we can easily test this without additional steps needed?

**Comment by AxelStone** [comment]
Sure, sorry for forget it, here it goes. 

More info: with some machines like Panasonic A1-WSX it works, but with Philips NMS8245 for example doesn't work. I haven't tried all possibles configurations, so I don't know what could be producing the error.

Thanks for your support.
[bios.zip](https://github.com/openMSX/openMSX/files/3888726/bios.zip)

**Comment by MBilderbeek** [comment]
Thanks. Please tell me on which real MSX you tried to run it and where it sounded right.

**Comment by AxelStone** [comment]
Hello Manuel, I tested in my 2 real MSXs:

- Panasonic A1-WSX (curiously in OpenMSX with this config also sounds well)
- Zemmix Neo, it's a very good implementation of MSX.

I can get HB75P to test too, let me know if you want me to test on it.

**Comment by MBilderbeek** [comment]
Yes, please compare your HB75P with the openMSX HB-75P.

In general, it's a good idea to compare the same MSX model, when comparing real with emulated MSX. If they behave the same, the emulation is OK.

**Comment by m9710797** [comment]
Can you describe what you mean with "buggy sound"?  Perhaps make a recording of it?
Could it simply be the "set beep" setting (stored in the clock chip) that is different between the machines?

**Comment by AxelStone** [comment]
Hello, answering to both:

- Sounds ok in real HB75P
- Buggy sound is it sounds different if you perform for example BEEP command from Basic. The sound is quite scratchy, like interferences.
 Regards.

**Comment by MBilderbeek** [comment]
To me it sounds OK on any emulated machine. How does it sound to you on an emulated HB-75P?

Can you record the 'right' and 'buggy' sounds using the openMSX soundlog command?

**Comment by m9710797** [comment]
I tested as well on several emulated msx machines (including a HB75P). Each time the program produced the same sound as the BEEP command in MSX BASIC. (I even tried a few different SET BEEP settings, also works without problems).
@AxelStone : so a recording would indeed be useful.

**Comment by AxelStone** [comment]
Hello guys, it's quite strange, in realtime I don't get the right sound, but the recorded video sounds as expected. Perhaps could be something related to sound buffer?

**Comment by MBilderbeek** [comment]
Yes, this means it's not an emulation problem.

Which OS are you on?

Can you check these settings:
https://openmsx.org/manual/commands.html#samples
https://openmsx.org/manual/commands.html#resampler

Before changing any, please let us know which values you are using with these settings.

Also, one strange thing is that the MSX model you're emulating isn't related to these settings. So I would expect that the 'bad' sound would reproduce also on any machine, if you try often enough. Can you double check that, please?

**Comment by MBilderbeek** [comment]
@AxelStone Any news or update you can give us?

**Comment by AxelStone** [comment]
Hello @MBilderbeek @m9710797 , first of all sorry for delay. I've performed more tests and I think I found the problem: the sound is buggy when performed from FDD. I've tried to copy same file to HDD and it sounds perfect in any MSX configuration. Right now I don't have available MSX with FDD, but if you are interested I can try to check is it happens in real MSXs using FDD instead of SD, I can get one.

My config is:
- Windows 10 running on old latop (4Gb RAM)
- set samples : 2048
- set resampler : blip

Best regards.

**Comment by MBilderbeek** [comment]
Yes, please confirm on real MSX with FDD. Looking forward to the results.

**Comment by AxelStone** [comment]
Hello @MBilderbeek @m9710797 , test performed on real MSX with FDD, this are the results:

* Real VG8235 using FDD: ok
* OpenMSX using folder as disk: sound buggy
* OpenMSX using dsk image: sound buggy,

Hope this helps you. Best regards.

**Comment by MBilderbeek** [comment]
Ah, do you have 'fullspeedwhenloading' setting enabled? If yes, try after disabling it.

**Comment by AxelStone** [comment]
Hello @MBilderbeek , disabled and now it works as expected. I didn't remember even the existence of this parameter.

Thanks for your support.

**Comment by MBilderbeek** [comment]
OK, great, thanks for letting me know :) I suddenly remembered that the speed-up for loading stops a little bit after the loading finished, so it may have some effect if you have sound directly after it. You gave some good hints though :)
