### ISSUE TITLE
Boosted MSX-AUDIO (MSX-AUDIO BIOS 1.3) doesn't work anymore after memory alignment requirement change

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1205]
The Boosted MSX-AUDIO extension (which is also used in Acid Test machines) doesn't work anymore after the memory alignment requirements were changed.
These configs rely on specifying parts as ROM and parts as RAM (RAM work area) for the device.

**Comment by grauw** [comment]
I bisected, this broke in f5be4ee94 [6/7] Fill RomBlocks Rcache.

Also,  amusing that this is issue #1205 :D.

**Comment by MBilderbeek** [comment]
This got fixed in 3c01257b9a620b7c1920248a6b3de4e62362912f.
