### ISSUE TITLE
Video and audio not in sync in Android version of OpenMSX

### ISSUE THREAD

**Issue by ghost** [openMSX/openMSX#1210]
Just tried OPL4 emulation in the Android version of OpenMSX and the video output is around 0.5 sec faster than the audio output. I noticed this when using MoonBlaster for MoonSound.
Playback is smooth (60 FPS constant), but not in sync.

I also tried all other sound chips like PSG, SCC, MSX-MUSIC and MSX-AUDIO and it seems to affect all audio output. Maybe the sound buffer is the problem? I would like to disable the sound buffer, but this isn't possible?

I also tried Windows version of OpenMSX and this one works fine.

This is very annoying. Please fix. Thank you.

**Comment by MBilderbeek** [comment]
You could try to reduce the sound buffer with the `samples` setting, see https://openmsx.org/manual/commands.html#samples When starting up the Android version, there is also a menu to make Android specific changes. You can also take a look there whether you can play with settings. (I don't know by heart what it looks like.)

**Comment by ghost** [comment]
Hi, thanks for the suggestion, but it still doesn't work as it should be.
Maybe other people can try as well?
Set samples gave 2560 as result in console. Lowered to 600 and buffer size to smallest when starting up Android app. The settings 'Medium' and 'Large' didn't work for me. App crashes when trying to start.

**Comment by MBilderbeek** [comment]
What was the effect of what you did (Smallest buffer size in the SDL settings)?

**Comment by ghost** [comment]
The effect was no interruptions and smooth playback, but about 0.5 sec ahead the video output.
Adjusting set samples will generate interruptions and jerky playback.
However, when changing the resampler to 'fast' it seems somewhat better.
Android is probably a little bit slower than Windows I guess, but still a nice port!
Maybe you guys can compare both versions with (OPL4) playback to see the difference.

**Comment by MBilderbeek** [comment]
Now that I take a better look on my phone, indeed, the sound lags behind a bit. (I tried the key click when typing a character in MSX-BASIC.) As the buffer of SDL is by default already on "Very small (fast devices, less lag)" and lowering the samples setting in openMSX gives more noise, I am not sure what we can do about it.
Did you already try some values lower than 2560 but higher than 600 for the samples setting? I'm using 512 on my Linux PC, but on Windows it's default on 1024, if I'm not mistaken.

**Comment by ghost** [comment]
Okay, thanks for testing.
Yes, I tried other sample settings. 1024 gives noise, 1280 seems to be better (half of 2560).
Maybe we can do another approach for Android? Add some waitstates for VDP to get in sync again with audio? Ofcourse the emulation speed must stay a 100%.
Anyway, I hope it can be fixed.

**Comment by MBilderbeek** [comment]
I don't know the cause of it and these workarounds would be at the wrong place (emulation is exactly in sync, but somewhere later, after openMSX is done with it, things get delayed, I think).
@m9710797 Any idea what we can try?

**Comment by mthuurne** [comment]
There is a chance this problem is specific to SDL 1.2. Maybe it's more efficient to first focus on getting SDL2 running on Android and then check whether the problem still exists?

**Comment by ghost** [comment]
@mthuurne What's the status of this ticket? I would like to get rid of this annoying issue, thanks ;-)

**Comment by mthuurne** [comment]
We don't have a working SDL2 build for Android yet. It might be a while before we do, unless someone (not me) steps up and makes it their priority.

**Comment by retrofan1979** [comment]
Okay, thanks. Maybe someone is willing to help you guys to update this nice port of OpenMSX. Please let me know if there's some progress in the (near) future.

**Comment by ghost** [comment]
Hi guys, maybe this could fix the problem with audio delay on Android with SDL 1.2:
https://android-developers.googleblog.com/2018/10/introducing-oboe-c-library-for-low.html
Coming from this thread: https://discourse.libsdl.org/t/sdl-mixer-accuracy/25160

**Comment by MBilderbeek** [comment]
Having read that: what is the setting of the `frequency` setting? Perhaps you can try 441000, 48000 or some other value that perhaps matches with your device.
When you change it, you may want to retune the samples setting (as small as you can get it before you get choppy sound (overflows)).

Well, never mind. I tried it on my phone and it all doesn't matter. 

So, our hope is SDL2. Get someone to help us with that :)
Only when we are able to build openMSX for Android again, with SDL2, we can pursue this further. We will really no longer develop openMSX based on SDL1.2.

**Comment by ghost** [comment]
Maybe this tutorial is useful for you: https://discourse.libsdl.org/t/building-sdl2-0-9-in-android-studio-3-2-in-windows/25454

**Comment by retrofan1979** [comment]
Maybe this tutorial is useful for you:
https://discourse.libsdl.org/t/building-sdl2-0-9-in-android-studio-3-2-in-windows/25454

**Comment by MBilderbeek** [comment]
So, @retrofan1979 and I today tested setting samples setting back to a lower value and now it does seem to matter quite a bit. 768 seems to be doing a lot better than the default 2560. Which is what I expected already the first time I suggested it. But for some reason now it does matter!?

**Comment by ghost** [comment]
I did the test on Android TV 9.0 Pie which seems to have less lag. Earlier I tested Android TV 8.0 Oreo. Maybe the audio libraries are updated for Pie?

**Comment by retrofan1979** [comment]
I also changed sample frequency from 22050 to 48000. I will do some more tests tomorrow.

**Comment by ghost** [comment]
I did a final test and both 768 and 1024 seems to work fine. I think the preferable default value for Android version is 1024 to get rid of that annoying audio lag and don't have random interruptions.
