### ISSUE TITLE
Windows x64 Debug build makes an error about xstring.

### ISSUE THREAD

**Issue by meesokim** [openMSX/openMSX#1211]
Microsoft Visual C++ (Visual Studio 2019) Runtime Library

Program:
...install\openmsx.exe
File: c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xstring
Line: 1045

Expression: cannot subtract incompatible string_view iterators

For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts.

UnicodeKeymap.cc  has the problem code line.
/** Returns the next token in the given string.
  * The token and any separators preceding it are removed from the string.
  */
static string_view nextToken(string_view& str)
{
	skipSep(str);
	auto tokenBegin = str.begin();
	while (!str.empty() && str.front() != '\n' && !isSep(str.front())) {
		// Pop non-separator character.
		str.remove_prefix(1);
	}
	**return string_view(&*tokenBegin, str.begin() - tokenBegin);**
}

**Comment by m9710797** [comment]
Hi, thanks for reporting this.
I'd like to ask for some clarifications..
Is this a build error or a runtime error? Which openMSX version is this (e.g. the 0.15 release, or a later snapshot release? (which one?))

The code looks fine to me, and it works without problems for me (on Linux with gcc). But'll try to add a workaround for windows/visual studio.

**Comment by meesokim** [comment]
It's a runtime error actually. There is no build time error and also I pulled the latest source code from this github repository.

**Comment by MBilderbeek** [comment]
@meesokim Is this still happening with the latest code?

**Comment by MBilderbeek** [comment]
@meesokim  Please reopen if it does. After 1 year I see no response, so assuming it's fixed now.
