### ISSUE TITLE
[Bug] v9990 bmxl and bmlx command P1

### ISSUE THREAD

**Issue by GhostwriterP** [openMSX/openMSX#1212]
Hi Guys,
Please find attached test case, demonstrating the functionality of bmxl and bmlx on v9990 in P1 mode.
I think that, in spite the abbreviation may suggest in the manual, both these commands operate on a pixel level and is not a "byte" move. I also suspect this is the case for all screen modes e.g. 16bit, 8bit, 4bit or 2bit mode, but attached test only focuses on the p1 mode.

After initiation:
- vram clearing
- outing linear data to vram in a "interleaved" manner, even bytes are stored at 20000h and odd bytes at 60000h.
- setting up sprites and color palette

The test executes the following steps (apart from scrolling):

1 - copy normal (arg=0) to rectangular block from linear with bmxl to plane A. This frame is shown on plane A layer (dark group walking to the right) and top sprite.
I put deliberate 1 pixel offset on DX to show this goes wrong in openMSX but is shown correct on real v9990.

2 - copy rectangular block from plane A to linear with bmlx, but with (arg=4) i.e. x flipping, to address 22000h (even) and 62000h (odd). 
The flipping appears to be done correctly on openMSX but could be coincidence (?) - note is show currently incorrect in step 3 because source is result from step 1.
Here it should also be noted that on real v9990 the write mask should allow for writing to both planes for bmlx to function correctly (reg#46 = 255 and reg#47 = 255) - otherwise bytes get masked out. On openMSX the writemask does however not seem to matter or have affect.

3 - copy linear from 22000h to plane B using regular bmxl showing the frame on plane B (dark group walking to the left).

4 - copy x flip  (arg=4) to rectangular block from linear with bmxl to plane A (second from the top)
5 - copy y flip  (arg=8) to rectangular block from linear with bmxl to plane A (third)
6 - copy xy flip  (arg=12) to rectangular block from linear with bmxl to plane A (bottom one)

Of course of real v9990 it looks all OK, unfortunately I do not have a picture.

Have fun!

[p1_bmxl_bmlx_test.zip](https://github.com/openMSX/openMSX/files/4061058/p1_bmxl_bmlx_test.zip)

**Comment by GhostwriterP** [comment]
It appears I meshed up some input data for vram clearing (lmmv) and bmlx destination, which is corrected in the attached zip.

Now the background should be clear and uniform dark purple without a black grid around the beasts on plane B.  And bmlx address is corrected to 22000h instead of 202h :)

[p1_bmxl_bmlx_test - update.zip](https://github.com/openMSX/openMSX/files/4073277/p1_bmxl_bmlx_test.-.update.zip)

**Comment by MBilderbeek** [comment]
So, this is what happens in openMSX:
![beast](https://user-images.githubusercontent.com/12675978/132755470-f2fb35dd-75cc-4f81-881b-00ba62341fc2.png)
On real machine, the 'beasts' do not look so jagged, but smooth, like the 3rd one in openMSX. So, the case of the 3rd one is apparently implemented correctly, but the case of the other ones is not.

@GhostwriterP So, you think it's bytes vs pixels? How can you explain the 3rd from the top is working correctly in openMSX?

I confirmed that on real hardare, all looks fine and smooth. This is a photo I took, please ignore the lamp reflections :)

![IMG_20210909_221253](https://user-images.githubusercontent.com/12675978/132756174-4275cee5-35f7-4943-9229-b3354227a4cd.jpg)

**Comment by GhostwriterP** [comment]
The third one is a plain y flip copy, hence the pixels in a byte do not required to be swapped. If however you would increase or decrease the X destination coordinate by 1 pixel (_change line 136:  ld de,16+31:128+1     ;y flip_), it will go wrong in openMSX just like the first.

As on real v9990 the destination X does not require to byte aligned (and neither does the rectangle width for that matter) I believe this command works on pixels level indeed. At least in P1 it does for sure.

**Comment by MBilderbeek** [comment]
After this change it looks like this:
![beast](https://user-images.githubusercontent.com/12675978/132948923-88ef6254-fda3-4c8a-972a-3a859abc26e8.png)
Much better at least :) 

@GhostwriterP  Can you confirm this is the full solution and if not, please reopen?

**Comment by MBilderbeek** [comment]
By the way, this is how it runs on hardware: https://youtu.be/kEcSrNUiVAI
