### ISSUE TITLE
Mirror areas of the Konami mappers are not emulated

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1213]
This is perhaps partly duplicate of #1149 , but still... gdx writes:

> I noticed that mirrors of the ASCII mappers are not emulated. (These are the same mirrors as for 32KB ROMs, see link below.)
> https://www.msx.org/wiki/ROM_mappers#ASC8_.28ASCII.29

> Here is an example that uses a mirror:
> https://mon-partage.fr/f/Xq66Asmd/
> That is a multiROM patched to also use joystick in the menu and to run Sparkie, but as it use mirrors to run, it don't work on OpenMSX and BlueMSX. (Works fine on real MSX with a MAB from Repro-factory if the cartridge is inserted in a primary slot)

> These mirrors are present on all 32kB ROMs (4000h-BFFFh) I have, and also on all Konami megaroms.
> Grauw wrote: Do games with real ASCII8 mappers mirror?
> 
> I think this is the case for all Roms that use the /CS12 signal.
> 
> I verified now on a Megasram made with an original Megarom, and the mirrors are also present.
> New link for the megarom test:
> https://mon-partage.fr/f/y97esInT/
> (I had forgotten to remove unnecessary routine.)

Originally posted here: https://www.msx.org/news/en/openmsx-0150-released#comment-372646

Attached the ROM. To test, select Sparkie in the menu.
[MULTIROM-tst.zip](https://github.com/openMSX/openMSX/files/4061328/MULTIROM-tst.zip)

**Comment by happppp** [comment]
For ASCII mapper type game cartridges, there is no memory mirroring on page 0 or page 3 on the ones I tested. BiFi also confirms this.

As for unofficial flashrom or megaram cartridges, I don't know.

**Comment by gdx-msx** [comment]
> For ASCII mapper type game cartridges, there is no memory mirroring on page 0 or page 3 on the ones I tested. BiFi also confirms this.
> 
> As for unofficial flashrom or megaram cartridges, I don't know.

I'm sure the mirrors are there at least for the majority of official game cartridges as the Konami Megaroms and 32kB Roms. I think this is the case for all Roms that use the /CS12 signal. I don't think it depends on the MSX used.

Even if this is not the case for all cartridges, it is still better to emulate these mirrors because they do not interfere and that allows us to make the Roms work like the one in example.

**Comment by MBilderbeek** [comment]
Why not test on an original ASCII 8kB cartridge? Simply dump the slot the cartridge is in?

You can also open the cartridge and check whether the /CS12 signal is actually used. @happppp didn't you do this in the past?

**Comment by MBilderbeek** [comment]
I got the following info from BiFi:

> The /CS12 signal is ONLY for 32K ROMs. It causes to put first 16K of a physical ROM into page 2 by setting bit 15, the other 15 bits are directly connected to the ROM.
> The ASCII mapper uses the /SLTSL signal which may give it access to the full 64K range, but the chip won't return anything in those pages.
> The /CS1 signal is for up to 16K in page 1, /CS2 is for up to 16K in page 2, /CS12 is for 32K in pages 1 and 2, and /SLTSL is for the entire 64K range. Those are the only ranges the cartridge slot has.
> The Konami SCC mapper does happen to mirror pages 1 and 2 in 3 and 0 respectively. The non-SCC one mirrors 1 and 2 in 0 and 3 respectively. 
>  gdx said he only used that megasram to test with, but that one is probably modified to mirror in page 0 and 3 as well, contrary to every unmodified ASCII mapper original title I have doesn't do page 0 and 3 mirroring at all.

**Comment by gdx-msx** [comment]
I verified with Hydlide 3 and Daisenryaku: No mirror!
With my ESE-RAM made with Garakuta: Mirrors are present.
With 8K and 16K MABs: Mirrors are present.
I don't remember with which cartridges I tested before but cartridges with mirrors seem less numerous than I thought, and it is probably independent of the mapper.

Edit:
I Verified with a Konami SCC (Gekitotsu Pennant Race 2): mirror of the page 1 is on page 3, and mirror of the page 2 is on page 0. (same as ESE-RAM and MABs)

**Comment by MBilderbeek** [comment]
@gdx-msx 
What is a MAB again?

What exactly do you mean with page here? An 8kB page or a 16kB page? Can you be clearer on what you mean?

**Comment by gdx-msx** [comment]
Mirrors are confirmed with original Konami SCC cartridges and even with the Konami Sound cartridge.

A MAB is that:
https://www.ebsoft.fr/shop/en/home/16-mab-8k-mapper.html
https://www.ebsoft.fr/shop/en/home/17-mab-16k-mapper.html

**Comment by MBilderbeek** [comment]
According to BiFi:
> Konami SCC: 0000-3FFF is always the same as page 2, C000-FFFF is always the same as page 1.
> Konami: 0000-3FFF is always the same as page 1, C000-FFFF is always the same as page 2.

That can be implemented.

**Comment by MBilderbeek** [comment]
Oh, wait, this was already put in #1149 so this is now fully a duplicate. Closing as such.
