### ISSUE TITLE
Daewoo DPC-180 RAM

### ISSUE THREAD

**Issue by rderooy** [openMSX/openMSX#1216]
It seems the amount of RAM defined for the Daewoo DPC-180 may be incorrect. The openMSX XML file is defined for 32kB while it seems like it had 64kB.

Have a look at the wiki update
https://www.msx.org/wiki/index.php?title=Daewoo_DPC-180

**Comment by MBilderbeek** [comment]
@rderooy How sure are we about this? Is there a source known of this informatin?

 can't find the source of the original config, I added it in 2004 and in that time I wasn't as careful about mentioning sources as I am now.

**Comment by rderooy** [comment]
@MBilderbeek Well, I don't have one, otherwise I would have added some better pictures to the wiki ;-)
Gdx added to the wiki that the magazines indicated it to have 80kB of RAM. Perhaps you can ask him for a pointer to that (presumably Korean) ad.

**Comment by rderooy** [comment]
On this page: https://bbs.ruliweb.com/hobby/board/300431/read/16012090
There is an image of an ad with the DPC-100, DPC-180 and DPC-200. And it indeed lists 80KB for the DPC-180.
But I don't know if that is an ad from Daewoo themselves, or just a reseller.

**Comment by MBilderbeek** [comment]
This looks convincing....
![daewoo1](https://user-images.githubusercontent.com/12675978/78462458-7bc5ed00-76d2-11ea-8b54-d212ae7d0994.jpg)
