### ISSUE TITLE
Victor HC-95A will not boot due to invalid machine config

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1221]
invalid memory specification for device MSX RS-232 should be aligned on at least 0x0100.

Issue is in the size of the rom memory for the RS-232 and disk rom (it tries to exclude the I/O registers which I believe is not done for any other memory mapped I/O that falls inside the ROM area.

Probably a check was introduced somewhere on this alignment but this machines config needs adaptation...

**Comment by MBilderbeek** [comment]
First attempt to fix this is attached, but unfortunately it's not allowed by openMSX. @m9710797 Can you please take a look at this regression?
[HC95A_mem_range.patch.txt](https://github.com/openMSX/openMSX/files/4429720/HC95A_mem_range.patch.txt)

**Comment by MBilderbeek** [comment]
Was already fixed in b43b958e5cbf5ae405edead34123b7e16853a4fa on  Sat Apr 25 13:38:57 2020 +0200.
