### ISSUE TITLE
8bitdo M30 2.4G controller isn't recognised via USB

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1228]
The 8bitdo M30 2.4G controller connected via USB isn't being recognized by openMSX.

Only recently the SDL guys have added support for [many of the 8bitdo controllers via USB](http://hg.libsdl.org/SDL/log/default/src/joystick/SDL_gamecontrollerdb.h), and the [M30 2.4G is one of them](http://hg.libsdl.org/SDL/rev/1e585115ed86).

So probably it's just a matter of using the latest version of SDL?

Tested on openMSX-0.15.0-657, on macOS 10.14.6.

**Comment by MBilderbeek** [comment]
We are already using the latest release 2.0.10.

Op za 22 feb. 2020 15:16 schreef sdsnatcher <notifications@github.com>:

**Comment by sdsnatcher** [comment]
What could be possibly causing this problem then?

**Comment by MBilderbeek** [comment]
Check out the dates of these commits and the date of the 2.0.10 release...

**Comment by sdsnatcher** [comment]
Ah, ok. It will probably be part of the future release 2.0.11 then.

**Comment by MBilderbeek** [comment]
In the meantime 2.0.12 is released. From the WhatsNew.txt:

> * Added support for many game controllers, including:
>         * 8BitDo FC30 Pro
>         * 8BitDo M30 GamePad
>         * BDA PS4 Fightpad
>         * HORI Fighting Commander
>         * Hyperkin Duke
>         * Hyperkin X91
>         * MOGA XP5-A Plus
>         * NACON GC-400ES
>         * NVIDIA Controller v01.04
>         * PDP Versus Fighting Pad
>         * Razer Raion Fightpad for PS4
>         * Razer Serval
>         * Stadia Controller
>         * SteelSeries Stratus Duo
>         * Victrix Pro Fight Stick for PS4
>         * Xbox One Elite Series 2

After the release we'll move to the new SDL 2.0.12 and this issue will be resolved. You could test drive this by already migrating yourself. What you should do can be seen in commit 4ee7920bfbbdcd7b5a26a3e5d9dabbf9bba8f6ae
