### ISSUE TITLE
Detect VDP writes with interrupts enabled

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1232]
I'm not sure if I would file this as a bug report or support request, but here it goes.

I'm trying to set up a watchpoint to check if an I/O port is being written with the interrupts enabled. (in this example it's the VDP, but it could be the PSG or OPLn)

I expected that the following command would be able to catch it:

debug set_watchpoint write_io 0x99 {[ expr [ reg iff ] > 0 ]}

But, to my surprise, the watchpoint is being triggered on all 2nd VDP writes. Usually they have an EI instruction just before them, but it's well known that the interrupts would only be enabled after a delay of 1 instruction.

Yet, somehow the watchpoint is being triggered. I'm not sure if this is a bug, or if I should have configured my watchpoint differently.

Tested on openMSX-0.15.0-657 on macOS 10.14.6.

To reproduce the bug, just type that watchpoint on the console and boot any MSX2+ machine. The watchpoint will be triggered at many points of the BIOS.

Last, I would like to suggest that maybe openMSX should issue warnings (similar to the PSG I/O direction and VRAM access speed warnings) by default to writes to the VDP, PSG and OPLn with interrupts enabled, since this is known to cause a lot of headaches.

**Comment by m9710797** [comment]
Hi,

Check the documentation of the "CPU regs" debuggable (ok, this is not obvious but the 'reg' command is implemented using this debuggable):
`> debug desc "CPU regs"`
`...`
`The last position (27) contains the IFF1 and IFF2 flags in respectively`
`bit 0 and 1. Bit 2 contains 'IFF1 AND last-instruction-was-not-EI', so`
`this effectively indicates that the CPU could accept an interrupt at`
`the start of the current instruction.`

So if you replace your expression '{[expr [reg iff] > 0]}' with '{[reg iff] & 4} it should work.

Side note: the 'expr' command in your expression is redundant: Tcl has 2 main 'contexts': expressions and commands. For the watchpoint-condition we expect an expression. In an expression-context you can use square-brackets to substitute the result of a command. So the inside of the square brackets is evaluated in command-context. But the command you give is 'expr', and that command will take it's arguments and evaluate those as an expression.

We could ship this as an example developer-tool, but I don't think it's a good idea to enable this by default. For developers it's often useful, but for regular end-users these warnings are only annoying. We even got complaints about the (enabled by default) warnings on invalid PSG port directions. Also e.g. we also don't enable UMR warnings by default. In this specific case I think there are rare but valid use cases where you can have interrupts enabled while still accessing IO ports (e.g. custom ISR where you know you won't access that device, or maybe VDP IRQ generation is disabled).

**Comment by m9710797** [comment]
Closing for now. But feel free to re-open if you think we should take action on this.

**Comment by sdsnatcher** [comment]
Thank you! This works like a charm!

Ok, I agree that it's a good idea to ship it as an example developer-tool, in order to not annoy normal users.

> or maybe VDP IRQ generation is disabled

This is the sole point where I beg to disagree. Right now I'm fighting with a software that was coded with that exact premise (Philips Video Graphics). If anything other than the VDP that generates interrupts is connected to the system (RS-232 mouse, Light-pen, OPLn etc), the thing just comes down burning in flames.    😆

It's not robust programming, so it's just not a good software coding practice.

**Comment by m9710797** [comment]
> This is the sole point where I beg to disagree. ...

The answer I gave yesterday was not very clear or even misleading (I don't fully agree with it myself when I re-read it today). The point I wanted to make was more about "having this warning enabled by default" instead of about "good coding practices".

Unfortunately there is too much MSX software that technically contains bugs, but that does happen to work fine in the majority of the cases (e.g. because all present non-VDP devices have IRQ generation disabled by default). As a developer of new MSX software you want to know about these issues, but as a user of 20-30 year old software you don't want to see warnings about this.

**Comment by MBilderbeek** [comment]
Looks like it wasn't closed, so I'll close it instead :)
