### ISSUE TITLE
Invalid PPI mode callback

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1234]
Currently, the I8255.cc file only prints the following warning when an invalid PPI mode is selected:
"Invalid PPI mode selected. This is not yet correctly emulated. On a real MSX this will most likely hang."

Since this is an illegal condition, it would be a nice help for developers to have a callback for this issue, similar to the umrcallback and vdpcmdinprogresscallback.

**Comment by mthuurne** [comment]
I agree that having a callback to put for example a `debug break` statement on would make a lot of sense.

Since this seems to be a recurring pattern, would it be useful to create a generic mechanism for reporting and handling the situation where MSX software triggers illegal or undefined behavior?

**Comment by m9710797** [comment]
@sdsnatcher: Good idea. And was easy to implement. Did that just now.

@mthuurne: For now I've implemented it in a similar way as our other callbacks. Did you have something more specific in mind with that "generic mechanism"?

(Closing for now. Feel free to re-open.)

**Comment by mthuurne** [comment]
We currently have one setting (hook) for each behavior we want to report. Instead, we could have a single hook and pass a string that identifies the undefined/illegal behavior. That would allow for example a debugger to intercept all possible events with a single handler.
