### ISSUE TITLE
The Japanese Sony HB-10 has a TMS9118 VDP

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1235]
The Sony_HB-10.xml file has a TMS99X8A VDP configured, but this machine has a TMS9118 VDP.

**Comment by sdsnatcher** [comment]
I also noticed that the TMS9118 palette is different from the TMS9918A, but they should be the same.

**Comment by MBilderbeek** [comment]
Hi, thanks! Do you have a source for that info, like an image of the HB-10 PCB?

About the palettes: everything should be as discussed in #1024 .... was there a mistake made at that time? Can you check please?

**Comment by sdsnatcher** [comment]
I own both an HB-10 and HB-20P (as you can see here in an old picture I took)

![IMG_2302](https://user-images.githubusercontent.com/13080763/77251695-91e1a100-6c2e-11ea-9d97-29acc51e0b7f.JPG)


The motherboard is the same on all three siblings (those two and the HB-10P). The differences are:

1. Jumpers to allow the selection of a TMS9118 or a T6950 VDP
2. Jumpers for the PAL mode: they allow an external clock generator for the Z80
3. Missing components for the CVBS output on the HB-20P (I added those to mine copying the components of the HB-10)

As a consequence of (1):

- Only VDPs with normal DIP spacing are supported
- This PCB only supports VDPs that use 4416 DRAMs
- The PCB has no place for a TV-Encoder chip, so only those with built-in CVBS output can be used

IOW, only the TMS9118 and T6950 fulfil all these requirements.


I don't have any pictures of the HB-10 motherboard right now, and since the machine is in storage it's not very easy to take it ATM. I'll add a picture to the MSX-Wiki whenever possible, ok?

**Comment by sdsnatcher** [comment]
> About the palettes: everything should be as discussed in #1024 .... was there a mistake made at that time? Can you check please?

If you check the history on #1024, you'll see that I already had mentioned there that the TMS9918 and TMS9118 feature the same saturated orangish palette. Probably the info was just missed at the time?

And it's indeed funny to play MSX1 games on this machine. Everything look like carrots and cabbages.    😂

**Comment by MBilderbeek** [comment]
From this code I think both have the saturation by default on 100%:
```
	// Current general defaults for saturation:
	// - Any MSX with a TMS9x18 VDP: SatPr=SatPb=100%
	// - Other machines with a TMS9x2x VDP and RGB output:
	//   SatPr=SatPr=100%, until someone reports a better value
	// - Other machines with a TMS9x2x VDP and CVBS only output:
	//   SatPr=SatPb=54%, until someone reports a better value
	// At this point we don't know anything about the connector here, so
	// only the first point can be implemented. The default default is
	// still 54, which is very similar to the old palette implementation

	int defaultSaturation = 54;

	std::string versionString = config.getChildData("version");
	if (versionString == "TMS99X8A") version = TMS99X8A;
	else if (versionString == "TMS9918A") {
		version = TMS99X8A;
		defaultSaturation = 100;
	} else if (versionString == "TMS9928A") version = TMS99X8A;
	else if (versionString == "T6950PAL") version = T6950PAL;
	else if (versionString == "T6950NTSC") version = T6950NTSC;
	else if (versionString == "T7937APAL") version = T7937APAL;
	else if (versionString == "T7937ANTSC") version = T7937ANTSC;
	else if (versionString == "TMS91X8") version = TMS91X8;
	else if (versionString == "TMS9118") {
		version = TMS91X8;
		defaultSaturation = 100;
	} else if (versionString == "TMS9128") version = TMS91X8;
	else if (versionString == "TMS9929A") version = TMS9929A;
	else if (versionString == "TMS9129") version = TMS9129;
	else if (versionString == "V9938") version = V9938;
	else if (versionString == "V9958") version = V9958;
```
and otherwise the palette is also the same. See VDP.cc/hh.
