### ISSUE TITLE
Shader warnings on some drivers

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1236]
A user reported deprecation warnings in our shaders:

![image](https://user-images.githubusercontent.com/12675978/77260371-d51c2e00-6c87-11ea-98e3-301f61cc53e7.png)

**Comment by bengalack** [comment]
I was the affected user. It turns out that I used old shader-files, so it was all a user error. This issue can be closed.

**Comment by MBilderbeek** [comment]
Closing as explained by @bengalack .
