### ISSUE TITLE
Drag and drop support for DSK and ROM files

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1239]
I think it would make openMSX more user friendly if the main window would allow dropping of DSK and ROM files. The simplest implementation could insert into drive A/slot 1 always. A more advanced implementation could present an OSD after a dropped file to ask which drive/slot the file shouLd be inserted. For ROMs a reset could follow like when selecting a ROM from OSD.

This way people can use their systems’ Explorer/Finder to navigate the file system rather than the OSD.

**Comment by sdsnatcher73** [comment]
I think if openMSX would listen to https://wiki.libsdl.org/SDL_DropEvent then on such event determine type (through the known extensions so cart for .ROM, .MX1, .MX2 and disk for .DSK, .DI1, .DI2, .FD?) this could be quite easy to implement

**Comment by MBilderbeek** [comment]
You should now be able to drop files on the openMSX main window. The recognized extensions are the same as those recgnized by openMSX. This still needs to be expanded to have this synchronized with the OSD menu. That is for later.

@peterhanraets Can you help testing a bit?

**Comment by sdsnatcher73** [comment]
Would love to test but the MacOS build seems to be broken since commit 0c25956... But don't think that commit is what broke it, maybe an MacOS update (there was an additional update for 10.15.4 recently)

**Comment by MBilderbeek** [comment]
@peterhanraets We didn't know it was broken...  (It builds fine on Niek's build machine and the GitHub macOS build seems to be broken in some way we don't understand.) 
Can you give us all the details please, so we can take a look? I bet @m9710797  knows what this might be about.

**Comment by sdsnatcher73** [comment]
It is a bit odd. I actually got a new MacBook yesterday and cloned a clean repo and that build fine. Today I pulled the latest master (eager to try this feature) but it did not build. I had an update after unboxing the machine, not sure if I built before or after the update. I also switched to Xcode for the build from the command line tools (because I need it for building HexFiend). Anyway I cloned a new clean repo and that did build fine. So I decided to update my fork and try to update the workflows (removing the caching part which I suspect breaks things when the base image for the container used by GitHub changes). It is building now.... If that goes fine I'll do the same for the Linux and Windows workflows and create a pull request.

Anyway first impression of the feature is: I love this!!!

**Comment by MBilderbeek** [comment]
OK, please let me know if you find any issues. Wouter and I already did some fixes and updates.

And thanks for the PR regarding the automatic builds. It seems to work fine now! :)

**Comment by sdsnatcher73** [comment]
So this does seem to work very well. One thing that I figured when testing is about dir to disk functionality. Currently if I drop a folder on openMSX it (understandably) does not know how to handle the dropped 'file'. Maybe you could extend the feature with a dropped folder being handled as dir 2 disk (and the disk menu could appear if there are 2 drives).

**Comment by sdsnatcher73** [comment]
I managed to find an issue if the dropped file is in a folder with spaces (and probably some other characters).

**Comment by MBilderbeek** [comment]
I added the dir-as-disk feature.

The issue with spaces should already have been resolved in 007a38bbea6293fa24af07c37d200446ce161c48 - are you sure you are running the latest code? At least, I couldn't reproduce the issue with the latest code.

**Comment by sdsnatcher73** [comment]
Might not have been running latest release, just downloaded 735 and that works fine with the spaces and also dir 2 disk works as expected. I got an error trying to build on my own machine again and had to remove the entire derived dir and do a full rebuild, which than builds fine.

This is the error I get:
Compiling DeviceFactory.cc...
In file included from src/DeviceFactory.cc:7:
In file included from src/MSXPPI.hh:31:
In file included from src/input/Keyboard.hh:4:
In file included from src/input/KeyboardSettings.hh:4:
src/events/Keys.hh:4:10: fatal error: 'SDL_stdinc.h' file not found
#include <SDL_stdinc.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[1]: *** [derived/x86_64-darwin-opt-3rd/obj/DeviceFactory.o] Error 1
make: *** [staticbindist] Error 2

maybe an include dir is set when the 3rd party is built but not if it is detected as already built?

**Comment by sdsnatcher73** [comment]
I found an issue with mounting disk images through OSD. On MacOS I cannot browse through a folder structure anymore because when I want to enter a directory (by pressing Enter) it is mounted as dir2disk

**Comment by MBilderbeek** [comment]
@peterhanraets Thanks for reporting! I think I fixed it... can you retry, please?

**Comment by sdsnatcher73** [comment]
Yes this seems fixed now.

I did find another issue with filenames containing [some text] in the filename. In my case:

L'Heritage - Panique a Las Vegas (1987)(Infogrames)(FR)(es)[a][aka Inheritance, The].dsk

If I drop this disk it works fine. If drop another disk afterwards I get an error "Error executing hotkey command. invalid command a" where the first word inside [] is interpreted as being the command.

For the disk L'Heritage - Panique a Las Vegas (1987)(Infogrames)(FR)[needs MSX-DOS] the command is needs.

**Comment by MBilderbeek** [comment]
@peterhanraets Thanks for reporting. Should be fixed now as well. Anything else? :)

**Comment by sdsnatcher73** [comment]
That is indeed fixed now, I have not encountered anything else so far.
