### ISSUE TITLE
Assertion failure loading ROM of size 0

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1244]
When I load a ROM file whose size is 0, openMSX crashes with the following assertion:

    $ openmsx bin/tiletile.rom
    Assertion failed: (idx >= 0 && idx < size()), function operator[], file src/utils/span.hh, line 305.
    zsh: abort      openmsx bin/tiletile.rom

**Comment by m9710797** [comment]
Should be fixed in 6e4427377b5. Thanks for reporting!
