### ISSUE TITLE
Can't get command disable_reversebar to work when it is part of the startup-script

### ISSUE THREAD

**Issue by bengalack** [openMSX/openMSX#1248]
Using version from 21.04.2020.

command "disable_reversebar" in a file using -script does not work. Using it (and enable_reversebar) from F10-command-line works.

**Comment by m9710797** [comment]
Just checked: you're right, this doesn't work.
I looked up the reason for this: at the time your script runs the reverse bar is not yet enabled, so your "disable_reversebar" command runs but has no effect. (There's a reason why the reversebar is enabled so late in the boot process, but I won't go into that now).

But you can of course use the setting "auto_enable_reverse", with possible values
* "off": reverse system fully disabled
* "on": reverse system enabled, but no reverse bar
* "gui": reverse system enabled, including the reverse bar
(By default) this setting is saved, so you only have to set it once.

If you want to override this setting just for one openMSX session, you can use a script like this:
  set save_settings_on_exit false
  set auto_enable_reverse on
The first line makes sure that the alternate settings are not made permanent (including 'save_settings_on_exit' itself). The second line enables the reverse setting but not the reverse bar. So you can still use PgUp/PgDown to move forward/backward in time. Set the value to "off" to also disable these hotkeys.

Does this answer your question? I'm closing this ticket for now, but feel free to re-open.

**Comment by bengalack** [comment]
Ok.

I just figured that I leave this in my script:

after time 1 "disable_reversebar"

and this works adequately for me.

Thanks :-)
