### ISSUE TITLE
Feature request: skin set 3

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1252]
This is an ooooold feature request that doesn't seem to have been migrated from SF.

This is a new barebones skin set3 (just a small mod of set2) that aligns all LEDs at the lower part of the screen border. This is the most useful config for me, since it doesn't overlay anything over the MSX active screen area.

Nowadays, everytime I download a new build of openMSX to test, I have to modify the skin set2 to have this effect.

[set3.zip](https://github.com/openMSX/openMSX/files/4570474/set3.zip)

**Comment by MBilderbeek** [comment]
#5 is the thing it came into. But thanks for reminding me... Adding it.

**Comment by MBilderbeek** [comment]
eb89aad46e40e0065cc94121d73e926c80810f94 fixes this and #5.
