### ISSUE TITLE
When switching to fullscreen on Pioneer PX-7, the videosource is changed

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1254]
Not sure of any other situations this may occur (I tried on FS-A1GT on basic screen that had no issue).

Reproduce steps:
1. Start openMSX
2. Change Machine to Pioneer PX-7 and let it boot into it's menu
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/26295777/81263525-17cf7500-9040-11ea-9e9a-b3b60673c695.png">

3. Switch to full screen (the screen switches but the menu is not displayed only the color blue, not one of 15,4,7 it seems)
![image](https://user-images.githubusercontent.com/26295777/81264571-ee174d80-9041-11ea-96a9-b2030885d7ed.png)

4. Switch back from full screen, screen stays blue
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/26295777/81263608-45b4b980-9040-11ea-8b53-da8d121f0bf3.png">

**Comment by MBilderbeek** [comment]
When this blue screen is shown, try to open the console and type: set
videosource
What is the output?

What happens if you set it to "MSX"?

**Comment by sdsnatcher73** [comment]
Okay it somehow switches to LaserDisc (which I get as output from the console). If I set it to MSX the screen returns.

**Comment by MBilderbeek** [comment]
Note that I can't reproduce this on Linux. I just keep the MSX videosource....

**Comment by sdsnatcher73** [comment]
It also happens on Windows

**Comment by sdsnatcher73** [comment]
Can I perform some logging/debugging? Found this just coincedentally because of the other messages regarding full screen and PX-7 crashing (which it is not in my case)

**Comment by sdsnatcher73** [comment]
This actually happens with 0.15.0 release build on Windows (Windows 10 May 2020 release x64 in my case) as well (not tested on MacOS yet)

**Comment by MBilderbeek** [comment]
OK, thanks, that's valuable information, as it indicates this is not a regression, but an old issue.

**Comment by MBilderbeek** [comment]
I can reproduce it with Wine running the MinGW build.

**Comment by MBilderbeek** [comment]
OK, I can now also reproduce it on Linux, but only like this:
1. start up openMSX (default machine is NOT Pioneer_PX-7)
2. open console and type: machine Pioneer_PX-7
3. set fullscreen on

If I directly start with the Pioneer_PX-7 via the commandline -machine option, I cannot reproduce this issue.

I added some logging in the VideoSourceSetting:
This is when I start up with my default machine (Boosted MSX2 EN):
```
$ openmsx
Setting to source with id 1
Setting source to id 1: Video9000
Setting source to id 1: Video9000
Setting source to id 1: Video9000
Setting source to id 1: Video9000
```
Then I change to the Pioneer PX-7 machine with the machine command in the console:
```
No Video9000 videosource
Setting to source with id 4
Setting source to id 4: MSX
Setting source to id 4: MSX
Setting source to id 4: MSX
No Video9000 videosource
Setting to source with id 2
Setting source to id 2: MSX
Setting source to id 2: MSX
Setting source to id 2: MSX
No Video9000 videosource
No MSX videosource
No GFX9000 videosource
No Laserdisc videosource, get source with highest id
Setting to source with id 0
Setting source to id 0: none
Setting source to id 0: none
```
And then I go to fullscreen:
```
Setting source to id 4: MSX
No Video9000 videosource
No MSX videosource
No GFX9000 videosource
No Laserdisc videosource, get source with highest id
Setting to source with id 0
Setting source to id 0: none
Setting source to id 0: none
No Video9000 videosource
No MSX videosource
No GFX9000 videosource
Setting to source with id 6
Setting source to id 6: Laserdisc
Setting source to id 6: Laserdisc
Setting source to id 6: Laserdisc
```
See attached patch. Apparently the Laserdisc video source is there, but the MSX video source isn't there yet. And then the video source becomes (and stays) Laserdisc.

See my very quick and dirty logging patch attached.
[loggingvideosource.patch.txt](https://github.com/openMSX/openMSX/files/4659362/loggingvideosource.patch.txt)

**Comment by MBilderbeek** [comment]
When I extend this with logging when the videosources are registered, I see this in the last section:
```
Setting source to id 4: MSX
No Video9000 videosource
No MSX videosource
No GFX9000 videosource
No Laserdisc videosource, get source with highest id
Setting to source with id 0
Setting source to id 0: none
Setting source to id 0: none
Registering videosource Laserdisc
No Video9000 videosource
No MSX videosource
No GFX9000 videosource
Setting to source with id 6
Setting source to id 6: Laserdisc
Setting source to id 6: Laserdisc
Registering videosource MSX
Setting source to id 6: Laserdisc
```
I can't find how this works in the code... 
Looks like VideoSources are registered via the constructor of VideoSourceActivator. Only VideoLayer has such a member, which is initialized in the constructor, so each VideoLayer registers a VideoSource. But the only VideoLayers are Video9000, PostProcessor and GL/FB PostProcessor (what is Video9000 doing in that list??). Apparently FBPostProcessor is the VideoLayer of the Laserdisc, which is in the end created by the LaserDiscPlayer. 

Anyway, apparently these are recreated when switching to fullscreen (which means a renderer switch (why?)). The whole VideoSystem is reinstantiated, after which all "VideoSystemChangeListeners get notified, and they then recreate their rendeers.
Apparently the LaserDiscPlayer was sooner registered than the VDP as a VideoSystemChangeListener. I guess it's instantiation order. So, why is PioneerLDControl instantiated sooner than the VDP when running the machine command?

**Comment by m9710797** [comment]
The order in which the VideoLayer are destroyed/recreated in not defined (it's deterministic, but we don't guarantee any particular order) (see src/video/Display.hh:94). Switching MSX machine (this also creates VideoLayers) can indeed cause a different ordering.

But the ordering is not the issue here. Even with the other order there would be a bug: then toggling fullscreen would activate the MSX videosource, but maybe the user selected the laserdisc source and expects that source to remain unchanged.

The real fix would be to do a lot less work on a fullscreen toggle. So only recreate the actual output surface(*) and leave all other rendering stuff intact. Though that's quite a large change and we shouldn't do this close before a release.

(*) With the function SDL_SetWindowFullscreen() it's even possible to also keep the same output surface. Though I vaguely remember this didn't always work? (Maybe in SDL1?) (Maybe with openGL?)

**Comment by MBilderbeek** [comment]
@peterhanraets Can you confirm this is fixed with the latest development build?

**Comment by MBilderbeek** [comment]
@peterhanraets ?

**Comment by sdsnatcher73** [comment]
I can't test this as macOS build still has non working video...

**Comment by sdsnatcher73** [comment]
Yes this is fixed!
