### ISSUE TITLE
CAPS lock blinking on macOS

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1261]
This looks like the same thing as the very old issue #304. 

The blinking is caused by the MSX seeing that the CAPS lock button is still pressed.

The workaround for this was removed in d18b9360d4da90879e9a0c5df39dd476ab656085 I think. Perhaps we need it back?

@grauw wrote in an e-mail:
Here some event logs.

**ACTION**: Start openMSX -command "set kbd_trace_key_presses true", with CAPS LOCK key off. Wait for Basic.

Nothing.
**ACTION**: Press CAPS LOCK key (turns on).

> Key pressed, unicode: 0x0000, keyCode: 0x0012d, keyName: CAPSLOCK
> Changing CAPS lock state according to SDL request
OpenMSX caps led is blinking.

**ACTION**: Release CAPS LOCK key.

Nothing logged.

OpenMSX caps led is blinking.

**ACTION**: Press CAPS LOCK key (turns off).
> Key released, keyCode: 0x40012d, keyName: CAPSLOCK,RELEASE
> Changing CAPS lock state according to SDL request

OpenMSX caps led stops blinking. Remains either at the current state, on or off depending on timing.

**ACTION**: Release CAPS LOCK key.

Nothing.

OpenMSX caps led is unchanged.

**ACTION**: Change window focus from openMSX to the terminal while openMSX caps led is off.

Nothing.

OpenMSX caps led is unchanged.

**ALTERNATE ACTION**: I change window focus from openMSX to the terminal while openMSX caps led is on (= does not match keyboard caps light).

> Resyncing host and MSX CAPS lock
> Key pressed, unicode: 0x0000, keyCode: 0x0012d, keyName: CAPSLOCK
> Changing CAPS lock state according to SDL request
> Sending fake CAPS release
> Key released, keyCode: 0x0012d, keyName: CAPSLOCK
> Changing CAPS lock state according to SDL request

OpenMSX caps led turns off.

--------

**ACTION**: Start openMSX -command "set kbd_trace_key_presses true", with CAPS LOCK key on. Wait for Basic.

> Resyncing host and MSX CAPS lock
> Key pressed, unicode: 0x0000, keyCode: 0x0012d, keyName: CAPSLOCK
> Changing CAPS lock state according to SDL request
> Sending fake CAPS release
> Key released, keyCode: 0x0012d, keyName: CAPSLOCK
> Changing CAPS lock state according to SDL request
The log appeared after “Main RAM” appeared under the MSX logo.

OpenMSX caps led is off.

**ACTION**: Press CAPS LOCK (turns off).

Nothing happens.

OpenMSX caps led is off.

**ACTION**: Change focus from openMSX to terminal.

> Resyncing host and MSX CAPS lock
> Key pressed, unicode: 0x0000, keyCode: 0x0012d, keyName: CAPSLOCK
> Changing CAPS lock state according to SDL request
> Sending fake CAPS release
> Key released, keyCode: 0x0012d, keyName: CAPSLOCK
> Changing CAPS lock state according to SDL request
OpenMSX caps led turns on.

**Comment by grauw** [comment]
So commenting out the CapsLockAligner code to reduce the noise; I get these events when I press CAPS LOCK twice:

> Key pressed, unicode: 0x0000, keyCode: 0x0012d, keyName: CAPSLOCK
> Changing CAPS lock state according to SDL request
> Key released, keyCode: 0x40012d, keyName: CAPSLOCK,RELEASE
> Changing CAPS lock state according to SDL request

Additionally, when I un-focus openMSX while CAPS LOCK is on, I get the same Key released event:

> Key released, keyCode: 0x40012d, keyName: CAPSLOCK,RELEASE
> Changing CAPS lock state according to SDL request

And when I then when I go back to openMSX and press CAPS LOCK again to turn it off, no key pressed event is fired.

The OS only provides a ["caps flag changed" event](https://developer.apple.com/library/archive/qa/qa1519/_index.html), which happens on key pressed.

SDL2 apparently implements this as a key pressed event on caps enable, and key released event on caps disable. I also suspect the un-focus event is synthesized by SDL2.

See also [this StackOverflow post](https://stackoverflow.com/questions/12536356/how-to-detect-key-up-or-key-release-for-the-capslock-key-in-os-x) which suggests that there is not really a better way to observe the individual press and release events.

**Comment by grauw** [comment]
The caps lock behaviour is fixed since 5cd0378441.

However I did notice that the code and commit comments reference the wrong issue: #1212.

**Comment by MBilderbeek** [comment]
Thanks for testing! Closing then.

**Comment by grauw** [comment]
I do notice that when I press caps during a period where the MSX misses the press (like while it’s booting), the caps state can get (and stays) inverted compared to what macOS thinks. Not sure that’s something that anything can be done about.
