### ISSUE TITLE
Console font looks fuzzier than with 0.15.0

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1262]
As reported by ren [here](https://www.msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=17): the console font renders more blurry than with 0.15.0, comparison [here](https://msx.retrodb.net/openmsx/issues/20200513-consoleaa/single.html). 

Pedro Gimeno bisected it to FreeType changing from the v35 to the v40 engine: 
< PGimeno> ok, it was definitively broken between 2.6.3 and 2.7.0
< PGimeno> This is the commit that broke it: http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=7a13dc008b9128a785c30471103b53136b05b5de
< PGimeno> ok, found a workaround: FREETYPE_PROPERTIES=truetype:interpreter-version=35 openmsx ; # works even with a modern freetype

@madig This is an example when the v35 seems to give better results than the v40 with BitStream Vera TTF font...
`Vera.ttf: TrueType Font data, 17 tables, 1st "OS/2", 22 names, Macintosh, Copyright (c) 2003 by Bitstream, Inc. All Rights Reserved.Bitstream Vera SansBitstreamVeraSans-
`
Is this a matter of 'getting used to', as you wrote in [your article](https://www.freetype.org/freetype2/docs/subpixel-hinting.html) about this change?

**Comment by mthuurne** [comment]
Note that we're actually using the "VeraMono" variant of the font for the OSD console.

**Comment by madig** [comment]
The comparison picture shows the expected difference between v35 and v40. I personally prefer the smoother v40 results, but you are free to use the `FREETYPE_PROPERTIES=truetype:interpreter-version=35` setting to stay with the v35 look. AFAIK, there are no plans to remove v35, so you can just set it and carry on.

**Comment by MBilderbeek** [comment]
I like @mthuurne's suggestion on IRC: 
< mth> we could set the envvar if it's not set already
< mth> that gives the user the opportunity to override
< mth> since it's subjective which version is better
< mth> I do prefer the sharp (old) version
< Quibus> me too

**Comment by m9710797** [comment]
@MBilderbeek asked me to state my preference on this ticket, so here it is:

To me both versions look fine. I have no strong preference for either (maybe a slight preference for v40). So I prefer to not override this property. That's also easier for us to maintain. E.g. when in the future FreeType adds a newer interpreter mode, I'd hate to lose out on that because we insisted on the old v35 mode.
