### ISSUE TITLE
Add automatic CAS to WAV translation for Spectravideo 318/328 CAS files

### ISSUE THREAD

**Issue by Rakki1** [openMSX/openMSX#1264]
Feature request: implement CAS to WAV translation in openMSX for Spectravideo 318/328. Tried to load CAS files with Spectravideo SVI-328 on the emulator but it doesn't work out of the box. 

Noticed also discussion about the same problem years ago:
https://www.msx.org/forum/msx-talk/openmsx/svi-328-can-not-read-svi-cas-file-on-some-platforms

Reverse engineering is already done and documented [here](https://wiki.kasettilamerit.fi/wiki/index.php/Spectravideo).

**Comment by MBilderbeek** [comment]
Done by @m9710797 in bb2f1193ed2f3d2b44ece1d7453830edcc0f950c.
