### ISSUE TITLE
openMSX leaves temporary files in /tmp each startup

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1265]
I haven't rebooted in a while and I noticed that there are now a lot of temporary files on /tmp left behind by openMSX:

```
ls -l /tmp/openmsx.[TAB]
openmsx.1037462/ openmsx.142733/  openmsx.1788587/ openmsx.2037608/ openmsx.524033/
openmsx.1046680/ openmsx.143220/  openmsx.1788611/ openmsx.2042390/ openmsx.524115/
openmsx.1046893/ openmsx.1436896/ openmsx.1788642/ openmsx.2042487/ openmsx.524183/
openmsx.1086358/ openmsx.1508187/ openmsx.1788665/ openmsx.2084627/ openmsx.524231/
openmsx.1086494/ openmsx.1544250/ openmsx.1789255/ openmsx.2119574/ openmsx.524315/
openmsx.1091340/ openmsx.1550189/ openmsx.1790050/ openmsx.2178028/ openmsx.524361/
openmsx.1091378/ openmsx.1550826/ openmsx.1818483/ openmsx.2192492/ openmsx.524445/
openmsx.1091518/ openmsx.1554326/ openmsx.1821259/ openmsx.2192549/ openmsx.524565/
openmsx.1091758/ openmsx.1554370/ openmsx.1821347/ openmsx.2192877/ openmsx.524941/
openmsx.110031/  openmsx.1554794/ openmsx.1821533/ openmsx.2192964/ openmsx.5392/
openmsx.1100361/ openmsx.1554873/ openmsx.1821760/ openmsx.2192983/ openmsx.549495/
openmsx.110413/  openmsx.1554921/ openmsx.1822134/ openmsx.2193407/ openmsx.550127/
openmsx.110436/  openmsx.1555120/ openmsx.1822172/ openmsx.2193525/ openmsx.5509/
openmsx.1104753/ openmsx.1555599/ openmsx.1822309/ openmsx.2193791/ openmsx.554514/
openmsx.1115025/ openmsx.1557405/ openmsx.187955/  openmsx.2194865/ openmsx.555903/
openmsx.1115112/ openmsx.1558001/ openmsx.1885757/ openmsx.2194889/ openmsx.560496/
openmsx.1115181/ openmsx.1569053/ openmsx.1892008/ openmsx.2342478/ openmsx.565940/
openmsx.1115348/ openmsx.1569109/ openmsx.1893889/ openmsx.2342722/ openmsx.569229/
openmsx.1115409/ openmsx.1570722/ openmsx.189859/  openmsx.2342857/ openmsx.569338/
openmsx.1115465/ openmsx.1571174/ openmsx.189937/  openmsx.2342922/ openmsx.569937/
openmsx.1115601/ openmsx.1571302/ openmsx.190063/  openmsx.2343604/ openmsx.570385/
openmsx.1115627/ openmsx.1573877/ openmsx.190164/  openmsx.2347216/ openmsx.570852/
openmsx.1115644/ openmsx.1576308/ openmsx.190266/  openmsx.2347776/ openmsx.571103/
openmsx.1115677/ openmsx.1584811/ openmsx.190516/  openmsx.2348054/ openmsx.581360/
openmsx.1115703/ openmsx.1585135/ openmsx.190681/  openmsx.2348098/ openmsx.581617/
openmsx.1121527/ openmsx.1585419/ openmsx.190750/  openmsx.2348314/ openmsx.581847/
openmsx.1121625/ openmsx.1585581/ openmsx.190929/  openmsx.2348387/ openmsx.586989/
openmsx.1126582/ openmsx.1586022/ openmsx.191089/  openmsx.2348469/ openmsx.587016/
openmsx.1127233/ openmsx.1587168/ openmsx.191731/  openmsx.2348923/ openmsx.587087/
openmsx.1127318/ openmsx.1587348/ openmsx.192659/  openmsx.2418555/ openmsx.587591/
openmsx.1127420/ openmsx.1610246/ openmsx.192701/  openmsx.2419653/ openmsx.591818/
openmsx.1128649/ openmsx.1611149/ openmsx.192738/  openmsx.2419893/ openmsx.597267/
```
These folders contain TrueType font data:
```
$ file /tmp/openmsx.1217783/314rfg 
/tmp/openmsx.1217783/314rfg: TrueType Font data, 17 tables, 1st "OS/2", 22 names, Macintosh, Copyright (c) 2003 by Bitstream, Inc. All Rights Reserved.Bitstream Vera SansBitstreamVeraSans-
```

And in `/tmp/openmsx-manuel/`I also see quite some stale socket files:
```
ocket.1086358  socket.1115465  socket.1127233  socket.2348923  socket.524033
socket.1086494  socket.1115601  socket.1127420  socket.276454   socket.524115
socket.1091378  socket.1115627  socket.139166   socket.277678   socket.524231
socket.1091518  socket.1115677  socket.139310   socket.343828   socket.524315
socket.1091758  socket.1115703  socket.142440   socket.344699   
socket.1115025  socket.1121527  socket.142733   socket.344805   
socket.1115348  socket.1121625  socket.144709   socket.346492   
socket.1115409  socket.1126582  socket.145489   socket.346536  
```
This is the discussion we had about these non-socket temp files:

apr 11 2020 22:33:16 < wouterv>  i think openmsx decompresses files there for APIs that can't handle compressed files  (like SDL_ttf)
apr 11 2020 22:33:38 < Quibus>   it's not cleaned up
apr 11 2020 22:33:42 < wouterv>  maybe this isn't always cleaned up on crash?
apr 11 2020 22:33:56 < Quibus>   I hardly had crashes and I see dozens of these folders
apr 11 2020 22:34:11 < wouterv>  i never saw such files, but then my /tmp is auto cleaned on reboot
apr 11 2020 22:34:27 < Quibus>   Mine as well
apr 11 2020 23:19:05 < mth>      Quibus: yes, I have /tmp/openmsx.<number> dirs
apr 11 2020 23:19:58 < mth>      containing a TTF font
apr 11 2020 23:20:12 < Quibus>   mth: right, that's what I mean
apr 11 2020 23:20:19 < mth>      note that SDL itself has an I/O abstraction, but I don't know if SDL_ttf can read from that
apr 11 2020 23:21:19 < mth>      TTF_OpenFontRW() might be what we need
apr 11 2020 23:21:59 < mth>      https://www.libsdl.org/projects/SDL_ttf/docs/SDL_ttf.html#SEC15
apr 11 2020 23:23:01 < Quibus>   for what?
apr 11 2020 23:23:40 < mth>      to read a compressed font file without having to create a temporary file
apr 11 2020 23:24:08 < mth>      that's the reason for the files in /tmp, afaik
apr 11 2020 23:24:47 < Quibus>   ah
apr 11 2020 23:24:49 < mth>      we have for example share/skins/Vera.ttf.gz in git
apr 11 2020 23:49:19 < p_gimeno> are the 47K saved worth the use of .gz? for perspective, ConsoleBackground6.png alone uses 255K
apr 11 2020 23:53:29 < p_gimeno> I have one of these stray dirs in my /tmp
apr 11 2020 23:56:56 < mth>      maybe it's not so needed anymore, but this was a decision we made almost 20 years ago when disk space and download speed was quite a bit lower
apr 11 2020 23:57:27 < mth>      still, we need zlib anyway, so we might as well use it
apr 11 2020 23:58:19 < mth>      ah, not quite that long ago, it seems: 2008
apr 11 2020 23:58:27 < mth>      I think we had a pre-rendered font earlier
apr 11 2020 23:58:44 < mth>      we might want to add a CJK font at some point, those can be quite large

I finally got around to make an issue for this :)

**Comment by m9710797** [comment]
I could reproduce the part about the font files. I fixed that.

But I cannot reproduce the stale sockets. Could it be that those are left behind because of actual openMSX crashes?

**Comment by MBilderbeek** [comment]
Yes, that's possible. I think we can close this ticket now.
