### ISSUE TITLE
Copy/paste between system clipboard and OpenMSX console (F10)

### ISSUE THREAD

**Issue by oboroc** [openMSX/openMSX#1276]
Hi folks, I'm not sure if this was requested before. I looked up and didn't find anything.

I want to be able to copy/paste stuff from some web page to OpenMSX console, or copy stuff from the console and paste it outside.

Please let me know if you need more details. I'm on Windows 10 2004 x64 and I use release 0.15.

**Comment by m9710797** [comment]
Hi oboroc,

Copy/paste to openMSX has recently been implemented:
- Paste in the openMSX console: CTRL-V
- Paste in the emulated MSX itself: CTRL+META+V
Though for this to work you need to run a development version of openMSX. Or wait for the next official release (hopefully within one or two months).

Copy/paste from openMSX has not been implemented yet. One practical problem with this is that there's currently no mechanism to select text on the MSX screen or in the openMSX console. For the console you could maybe use the 'save_to_file' utility as a workaround. Type 'help save_to_file' in the console for more details.

Wouter


BTW: I'm closing this issue. But feel free to reopen when needed.
