### ISSUE TITLE
Build issue of 0.16 on MacOS

### ISSUE THREAD

**Issue by S0urceror** [openMSX/openMSX#1283]
When making a standard configure/build on macOS Catalina with required libraries present.
```
➜ make -j8
Using Python: python3
Found libraries:
  ALSA:             no
  GLEW:             version unknown
  libogg:           version unknown
  libpng:           version 1.6.37
  libtheora:        version unknown
  libvorbis:        version unknown
  OpenGL:           version 2.1
  SDL2:             version 2.0.12
  SDL2_ttf:         version 2.0.15
  Tcl:              version 8.6.10
  zlib:             version 1.2.11
Components overview:
  Emulation core:   yes
  GL renderer:      yes
  Laserdisc:        yes
  ALSA MIDI:        no
Build configuration:
Up to date: derived/x86_64-darwin-opt/config/Version.ii
  Platform: x86_64-darwin
  Flavour:  opt
  Compiler: clang++
  Subset:   full build
```
I get:
```
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      openmsx::FileOperations::getSystemDataDir() in FileOperations.o
      openmsx::MidiInCoreMIDI::MidiInCoreMIDI(openmsx::EventDistributor&, openmsx::Scheduler&, unsigned int) in MidiInCoreMIDI.o
      openmsx::MidiOutCoreMIDI::MidiOutCoreMIDI(unsigned int) in MidiOutCoreMIDI.o
  "_CFStringCompare", referenced from:
      openmsx::FileOperations::getSystemDataDir() in FileOperations.o
  "_CFStringCreateWithCharactersNoCopy", referenced from:
      openmsx::FileOperations::getSystemDataDir() in FileOperations.o
  "_CFStringGetBytes", referenced from:
      StringOp::fromCFString(__CFString const*) in StringOp.o
  "_CFStringGetCStringPtr", referenced from:
      StringOp::fromCFString(__CFString const*) in StringOp.o
  "_CFStringGetLength", referenced from:
      StringOp::fromCFString(__CFString const*) in StringOp.o
  "_FSCloseIterator", referenced from:
      openmsx::FileOperations::getSystemDataDir() in FileOperations.o
  "_FSCompareFSRefs", referenced from:
      openmsx::FileOperations::getSystemDataDir() in FileOperations.o
  "_FSGetCatalogInfo", referenced from:
      openmsx::FileOperations::getSystemDataDir() in FileOperations.o
```
This can be resolved by adding the following to platform-darwin.mk.
```
# Link against CoreMIDI.
LINK_FLAGS+=-framework CoreMIDI -framework CoreFoundation -framework CoreServices -framework ApplicationServices
```

**Comment by MBilderbeek** [comment]
@mthuurne What do you think?

**Comment by mthuurne** [comment]
It seems that in the past linking to these frameworks indirectly (for example through SDL) was enough, but now we actually need to link explicitly to every library that we make calls to. I have to admit that is cleaner.

`CFRelease` and `CFString` are part of `CoreFoundation`, the `FS` calls are part of `CoreServices`. So do we actually need `ApplicationServices` for anything?

The comment would have to be updated as well, something like "Link against system libraries."

When looking up the documentation of the missing symbols, I noticed that the `FS` calls are deprecated. So at some point we'll have to replace that code. I'm not looking forward to that, since I don't have a Mac anymore to test on.

**Comment by S0urceror** [comment]
Maybe I can be of help. It won't be too difficult to replace the deprecated FS calls with the appropriate functions in Foundation/CoreFoundation. This way we also guarantee it continues to work on APFS volumes and 64-bits systems. And in the future for Apple Silicon.

**Comment by mthuurne** [comment]
That would certainly be appreciated.

In the mean time, could you test whether the adding only `CoreFoundation` and `CoreServices` to `LINK_FLAGS` (so skipping `ApplicationServices`) fixes the build issue?

**Comment by S0urceror** [comment]
No, without ApplicationServices I get:

Undefined symbols for architecture x86_64:
  "_GetCurrentProcess", referenced from:
      openmsx::FileOperations::getSystemDataDir() in FileOperations.o
  "_GetProcessBundleLocation", referenced from:
      openmsx::FileOperations::getSystemDataDir() in FileOperations.o

By the way these are also deprecated functions.
