### ISSUE TITLE
Stutters in the sound when using moonsound or moonblaster software

### ISSUE THREAD

**Issue by GreyFoxN** [openMSX/openMSX#1288]
Only happens with moonsound and moonblaster software.
I installed 0.15.0 again to test it and with that version i encountered no issues.

**Comment by MBilderbeek** [comment]
Hi, thanks for reporting.

Can you give an example of how we can reproduce this issue?

So, which software are you running exactly, on which emulated hardware? What is your host system (OS)? Which settings are you using, e.g. for 'samples' and 'frequency'?
What is your host PC CPU usage when the stuttering appears? Which frame rate is openMSX running when it happens? (Use toggle_fps to check.)

**Comment by Vampier** [comment]
Try openMSX 16.0 and let us know if it still happens

**Comment by GreyFoxN** [comment]
Sorry for the late reaction, its been a busy week.
I reinstalled 16.0 again today.. And the stutters still occur.
An example of software i encountered the stutters with is: the moonblaster tracker MBWAVE v1.16.
When the stutters occur there is a slight fps drop, it goes from 60 to 56/57.
I tried many msx's Manuel, they all have the same problem. But this report is based on the emutalion of the nms8245 with the moonsound extension active.
I'm running on win10 64bit. My CPU (ryzen 5 2600x) does not seem to be affected by the stutter. Its usage is 4% when using open msx and does not change when the stutter occurs.

If you want i can send you the exact software and song i used to test it.
FYI; using the same software and songs on a real msx and on openMSX 0.15.0 works just fine !!

**Comment by MBilderbeek** [comment]
How often do you get the stutters? Is there a pattern in it?

**Comment by GreyFoxN** [comment]
If there is a pattern i haven't noticed it yet.
While playing a song it happens every 15/20 secs

**Comment by MBilderbeek** [comment]
So, how often does it stutter?

And does it stutter when you record to video/audio?

**Comment by MBilderbeek** [comment]
Which settings are you using, e.g. for 'samples' and 'frequency'?

**Comment by MBilderbeek** [comment]
@GreyFoxN Your reply, please...

**Comment by MBilderbeek** [comment]
No response from submitter @GreyFoxN ... closing as we can't do anything about it without responses.
