### ISSUE TITLE
Typo in flatpak

### ISSUE THREAD

**Issue by bodhi-baum** [openMSX/openMSX#1297]
When starting flatpak there is at the fronpage of openMSX: "Emulate all espects of the MSX with high accuracy." Where "espects" should be "aspects", I assume.

**Comment by MBilderbeek** [comment]
@rderooy Can you pick this up? The flatpak isn't even merged in our repo yet, as far as I know...

**Comment by rderooy** [comment]
That was actually copied from the Fedora openMSX RPM package. I fixed it in the flathub repo. https://github.com/flathub/org.openmsx.openMSX

I had created a PR against openMSX some time ago to merge some of this stuff, but that is still sitting there.

**Comment by MBilderbeek** [comment]
Sorry about that, but our build and packaging specialist @mthuurne is too busy at the moment to take a look at it. I'm sure that when he'll find the time he'll take a look. I understand that in the meantime, people can still use your package on flathub, so that's good.

**Comment by MBilderbeek** [comment]
This issue has been dealt with then, so let's close it. Pretty funny to have an issue reported on something that wasn't even merged yet :)

**Comment by rderooy** [comment]
Just to be clear. You will always need https://github.com/flathub/org.openmsx.openMSX with at least the yaml file if you want to have a flathub hosted flatpak.
