### ISSUE TITLE
No Dingux OpenMSX 0.16 release

### ISSUE THREAD

**Issue by a-dekker** [openMSX/openMSX#1302]
I noticed there is no Dingux OpenMSX release of 0.16. Is it just forgotten, or does it mean 0.15 be the last ".opk" release?

**Comment by MBilderbeek** [comment]
No, it was not forgotten. Unfortunately the toolchain of OpenDingux is too old to be able to compile openMSX. It provides g++ 4.9.1 (it's from 2014), but openMSX requires g++ 7 or higher, as it makes use of C++14 and C++17 language features.

When the OD community updates the toolchain, we can supply builds for OD again.

**Comment by mthuurne** [comment]
There is also the issue that the default SDL2 backend for kms/drm will always use the GPU. For openMSX, that means worse performance, since the GPU can't do anything meaningful (we don't need fancy scaling for 320x240) while it does increase the bandwidth demands on the slow RAM of the GCW Zero, as well as using more power.

**Comment by a-dekker** [comment]
Not the most positive news regarding my just purchased RG350M handheld, but thankfully 0.15 seems to work fine in general.

**Comment by mthuurne** [comment]
There is a lot of development activity on OpenDingux recently, so the toolchain issue is likely to be sorted out soon, if it isn't already (does the [snapshot](https://zcrc.me/opendingux/2020/10/13/we-have-nighties.html) have up-to-date compilers?). The SDL2 issue might take a bit longer, but that doesn't mean it won't be addressed.

**Comment by MBilderbeek** [comment]
It does seem to have it: `mipsel-gcw0-linux-uclibc-g++.br_real (Buildroot 2019.11-4439-g3cc2bed04a) 10.2.0`

**Comment by MBilderbeek** [comment]
@mthuurne Is there an official new release of the toolchain that I could install? Or what do you recommend regarding this?

**Comment by a-dekker** [comment]
As for a link to the toolchain, also see https://github.com/openMSX/openMSX/issues/1363#issuecomment-869493674
