### ISSUE TITLE
Keyboard layout of some Japanese machines

### ISSUE THREAD

**Issue by mars2000you** [openMSX/openMSX#1303]
When updating the MRC Wiki with the keyboard layout of all MSX machines, I've noticed a few mistakes in the openMSX xml files:
* Pioneer PX-7, PX-V60 and UC-V102 : the Japanese keyboard layout is JIS, not jp_ansi (JP50on)
* Sanyo MPC-25FD: the Japanese keyboard layout is JP50on, not JIS

Note: You can check that on the available pictures.

**Comment by MBilderbeek** [comment]
Thanks! Looks like you're right, but I couldn't find a picture of the keyboard of the UC-V102. Can you point me to one?

Regarding the Sanyo, jltursan said it was JIS for his machine on https://www.msx.org/forum/msx-talk/trading-and-collecting/msx-junk-sale?page=1 so I asked him again to make a pic.

**Comment by mars2000you** [comment]
It's indeed difficult for the UC-V102, but it's the same keyboard as for Japanese Mitsubishi machines (as the UC-V102 was actually manufactured by Mitsubishi).  

With exception of the very rare Mitsubishi ML-TS1, all Japanese Mitsubishi MSX  computers have a JIS keyboard.

**Comment by mars2000you** [comment]
Check this Yahoo auction: https://page.auctions.yahoo.co.jp/jp/auction/f471657366

A picture of the keyboard (with reference UK-V101) can be seen. It confirms the JIS layout for the Pioneer UC-V102.
