### ISSUE TITLE
Audio samples sound distorted 

### ISSUE THREAD

**Issue by sndpl** [openMSX/openMSX#1308]
This music demo load samples in memory and plays them, but after a while the sample sound distorted. It's like if it's fast forwarding the sample. The problem only occurs in the dev version (i'm now on macos 16.0.213-gfc40889d7), in 16.0 it does work correct. Also tested on real msx with the same disk image, but also plays correct.

When you test this disk make sure the fullspeedwhenloading is off, else you get a lot more distorted samples :)

[MC Hammer Music Demo - Disk A.dsk.zip](https://github.com/openMSX/openMSX/files/5724396/MC.Hammer.Music.Demo.-.Disk.A.dsk.zip)

**Comment by m9710797** [comment]
Thanks for the report!

I was able to bisect it to this commit:
    commit 945f4ec69e4bc87b1b2ccbca0127e9c2ffd1b597 (HEAD)
    Author: m9710797 <vermaelen.wouter@gmail.com>
    Date:   Sat Aug 15 09:46:13 2020 +0200
        Tweak calculation of ResampledSoundDevice::emuClock speed

The commit is fairly small. So *probably* not too difficult to figure out what's going wrong. But I ran out of time and I already wanted to show the progress. I'll hopefully continue soon (tomorrow?)

**Comment by m9710797** [comment]
I fixed this in 5706f6160b67.
It works for me now, but please verify.

**Comment by sndpl** [comment]
@m9710797 thanks for the quick fix! I can verify that it works perfect! also checked with another demo of the same author (using the same technique) and that also works good again.
