### ISSUE TITLE
openMSX not responding while calculating checksum for SD/HDD images

### ISSUE THREAD

**Issue by Dalekamistoso** [openMSX/openMSX#1315]
I would be great that "calculating checksum" process while while openmsx loads is showed in main window (via updating program title bar with percentage) instead of making openmsx in a false "frozen program state" as temporary solution, but option makes non visible if you start full screen mode.

So I propose the best solution is showing in the OSD a percentage counter like "Loading image... 0~100%"  so it will be visible even in full screen mode.

**Comment by m9710797** [comment]
Hi, thanks a lot for reporting!

It was always the intention that it worked like that. But about a year ago it got broken :(
We still printed the progress messages, but because of a bug we didn't redraw the screen anymore, so the messages didn't show up.

I fixed it in revision ca95ac844ca.
