### ISSUE TITLE
[Feature] semi-auto GFX9000 switch [sf#108]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#132]
**Reported by manuelbi on 2005-03-05 18:16 UTC**
It would be cool to have an option to turn on a
semi-auto GFX9000 switch, which reacts on the enable
bit (or whatever it's called) in the GFX9000. It's not
bad it if doesn't always work, it will still make the
user's life easier! :)
There are several other things that could be used as
triggers (e.g.: action on the GFX9000 or MSX screen).

**Comment by MBilderbeek** [comment]
Obsoleted by the Video9000 extension. Closing.
