### ISSUE TITLE
Garbled, distorted sound with the new NukeYKT core in Turbo-R configurations.

### ISSUE THREAD

**Issue by mrparn** [openMSX/openMSX#1320]
**Description:** I tried the new Quick ADX Player Ver. 2 by Mstz80ax on OpenMSX and got garbled and distorted sound, but only when I tried it on emulated Turbo-R machines.

**Emulator version:** OpenMSX 16.0

**Steps to reproduce:** Simply download the tool [here](https://www.msx.org/downloads/quick-adx-player-ver2), put it in an empty directory with some MSX-DOS boot files (it doesn't matter whether it's DOS1 or DOS2) and use this directory as a boot disk for any Turbo-R machine (it doesn't matter which one). Use `QAP.COM` with any `.ADX` file and the result will be the same: distorted, garbled OPLL sound.

**What I found out:** QAP's selling point is to be able to use an external FM-PAC together with the internal sound source to make stereo sound, so I also made some testing with the fmpac extension, and the results were the same on any Turbo-R machine, but it worked fine on every other machine I tried. So I created a new Turbo-R machine and a new FM-PAC extension configurations, but removing the `<ym2413-core>` tag from the XML files. By using these two configurations together, the sound wasn't garbled or distorted anymore. By using only one of these two configurations, the sound source associated to it wasn't garbled or distorted while the other sound source became garbled and distorted again.

**On real hardware:** I couldn't personally test this, but Mstz80ax told me it worked fine on real hardware. He had a friend of his test in another machine to double-check it.

**Final thoughts:** I believe this has something to do with how fast data is being sent to the emulated OPLL. Maybe it's a bug on NukeYKT, or maybe it's some still imperfect Turbo-R emulation.

**Comment by MBilderbeek** [comment]
I tried it on openMSX and on my real GT, but it sounds identical to me. I tried with the attached disk image. Result can be seen here: https://youtu.be/ghxljTWOBcU 
[qaptest.dsk.gz](https://github.com/openMSX/openMSX/files/5826876/qaptest.dsk.gz)

**Comment by mrparn** [comment]
This is what I'm getting: https://youtu.be/hHXILilu-8Y

I got the same exact results by using your disk image. Could it be that some other setting is interacting in an unexpected way?

**Comment by mrparn** [comment]
I'm very ashamed to say the problem was with one of my settings, indeed. Long time ago I changed the R800 default speed to do some testing and forgot to reset it back. I had just completely forgotten about it. I'll close this issue. I'm sorry for any inconvenience I may have caused.

**Comment by m9710797** [comment]
Hi mrparn,
Nothing to be ashamed about. I'm glad it's resolved. And thanks for reporting anyway.
I also like the level of detail in your initial report (much better than some of the other reports we get).

**Comment by MBilderbeek** [comment]
Yes, I also wanted to say that! Thanks for taking the trouble to report here and in such detail! Many people just complain somewhere else, which generally doesn't lead to anything getting fixed... You did it exactly right!
