### ISSUE TITLE
All-black screenshot with SDL renderer

### ISSUE THREAD

**Issue by mcolom** [openMSX/openMSX#1321]
When taking a screenshot ("screenshot filename" command in the terminal) with the SDL renderer, an all-back PNG file is written instead of the actual screenshot.

It seems that commit e5e0c8e67dabe5c62f4df7bd2028da062111fe5f is the one which causes the problem.
The commit just before (f539f79e1c361d32bb774c6c77165994ec907b37) saves screenshots correctly.

**Comment by m9710797** [comment]
Fixed in 021a94a522976.
Thanks for reporting. And it was really helpful that you could pinpoint the exact commit that broke it, thanks.
