### ISSUE TITLE
Question: Compiled openMSX doesn't work anymore

### ISSUE THREAD

**Issue by Fubukimaru** [openMSX/openMSX#1324]
Hello!

I'm using Manjaro Linux (Archlinux based) and since the last OS update the compiled emulator is not working.

It runs and then shows this and gets stuck:
![stuck](https://user-images.githubusercontent.com/17855785/107118046-b95d4e80-687e-11eb-889b-8518d90f6ce6.png)

When doing make I get the following:
```
Found libraries:
  ALSA:             version 1.2.4
  GLEW:             version unknown
  libogg:           version unknown
  libpng:           version 1.6.37
  libtheora:        version unknown
  libvorbis:        version unknown
  OpenGL:           version 4.6
  SDL2:             version 2.0.14
  SDL2_ttf:         version 2.0.15
  Tcl:              version 8.6.11
  zlib:             version 1.2.11
```
I assume that these `unknown` are not correct. Any clue on this issue?

Thanks

**Comment by MBilderbeek** [comment]
The unknown is normal. Did you fully recompile after the OS update?

**Comment by Fubukimaru** [comment]
Yes. First I started using the Archlinux `AUR` packages (https://aur.archlinux.org/packages/openmsx and https://aur.archlinux.org/packages/openmsx-git) and then I compiled it directly cloning the repo.

Is there any way I could get more information from openmsx?

**Comment by MBilderbeek** [comment]
Can you open the console with F10?
Can you also try with Catapult to control openMSX remotely?

**Comment by Fubukimaru** [comment]
Hello! 

Sorry for the delay. Magically it fixed itself. Probably due to another system upgrade I did.

I'm closing this. Thanks for your support!
