### ISSUE TITLE
Make openmsx.exe a GUI application (but still allow --help to output to a calling console)

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1325]
openMSX on Windows is built as a console application instead of a windowed application. Not sure about why this was done, I suspect to be able to print the --help output. On macOS and on Linux starting the application from whatever menu is present just brings up the openMSX window. On Windows it brings up a Command Prompt window as well (which I personally find annoying, if I want console output I can start it from the Command Prompt / Terminal as on other OS's). Either way it is inconsistent with other Desktop OS platforms supported by openMSX.

With a minor change to platform-mingw32.mk (and probably openmsx.vcproj) the resulting executable is no longer a console applictation. With a small addition to main.cc we can attach to the calling console (if present) and print to it, this way openmsx.exe --help will work.

I will create a pull request for the mingw builds, for the visual studio build it will probably be sufficient to change <SubSystem>Console</SubSystem> to <SubSystem>Windows</SubSystem>.

**Comment by MBilderbeek** [comment]
As we merged the pull request, I guess we can close this issue :) Thanks!
