### ISSUE TITLE
Introduce a plugin system for DSK/DMK/CAS/TSX/ROM handling

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1334]
Maybe it is an idea to come up with a plugin system for handling MSX media. This way a TSX plugin could for example be developed outside main openMSX development branch, but it could still work with the official release (if the plugin is built against the release's API). Existing media handlers could be transformed to plugins as well (and server as basis for new plugins).

Just a thought...

**Comment by m9710797** [comment]
It's a good idea, though a lot of work to realize in practice. E.g. it's hard to implement plugins in a cross-platform way. Or even if the plugins themselves aren't portable, implementing the plugin-mechanism itself in a portable way is not easy. And then you still need to define stable APIs.

So a good idea, but I'm not motivated to work on this myself. But I can help review patches. For now I'm closing this issue, but feel free to reopen if you have more info and/or are willing to drive the implementation.
