### ISSUE TITLE
Broken hardware menu item when creating a new machine tab if the machine does not have internal firmware

### ISSUE THREAD

**Issue by Dalekamistoso** [openMSX/openMSX#1342]
All versions seems affected by this bug also the latest build:

When you are using a machine with internal software in firmware enabled or not (for example TurboR or Panasonic 2+ WX) and then you open a new machine tab without that feature it the emulator returns you the following error:

warning: Error executing hot key command: can't read "::firmwareswitch": No setting 'firmwareswitch' on current machine.

And the "hardware" menu item shows an empty menu box (only in the tabs of the machines without firmware), this disables the hardware menu..

The tabs with machines that have internal firmware are unaffected of this issue.

I attach you a screenshot of the bug:

![issue1](https://user-images.githubusercontent.com/67012746/113843927-4ac04280-9794-11eb-9690-62825ca9bf37.png)

**Comment by MBilderbeek** [comment]
![firmwareswitch](https://user-images.githubusercontent.com/12675978/113869155-adbfd280-97b0-11eb-9157-5df744c89fb2.png)
Very strange, the setting exists but says 'proxy'.

**Comment by m9710797** [comment]
I haven't investigated this issue yet, but here's already some background info:

Some settings are MSX machine instance specific, the 'firmwareswitch' setting is an example of such a setting. These machine-specific settings are named 'machine1::firmwareswitch' (or some other machine-instance-name or other setting name). But for convenience we also create a setting 'firmwareswitch' (so without the machine prefix). This convenience setting delegates to the appropriate machine-specific setting, depending on which machine instance is currently active.

Apparently something goes wrong when the 'firmwareswitch' setting is used, but the active machine instance does not have the corresponding setting. I'll try to make time this evening to investigate what exactly.  (Possibly we need a different way to detect the existence of a 'firmwareswitch' .. maybe only checking that the setting 'firmwareswitch' exists isn't good enough .. maybe we should check that it's actually readable without triggering an error ??)

**Comment by MBilderbeek** [comment]
Yeah, something like that I was also thinking about. But I didn't understand the 'proxy proxy' stuff in the first place. So let's first see why that is happening. I would have expected that the 'firmwareswitch' setting wouldn't exist if the current machine doesn't have such a setting in its namespace.
