### ISSUE TITLE
Won't launch on Debian Buster: /lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by openmsx)

### ISSUE THREAD

**Issue by bferguson3** [openMSX/openMSX#1346]
The most recent version of GLIBC_XX on Debian Buster is 3.4.25.

Aseprite has this exact same issue. Is there a way to link .25 to .26, or make this dynamically linked library's version number not hard-coded?

**Comment by MBilderbeek** [comment]
Which code are you running and how did you compile it?
Or are you running the Debian package? If yes, which version?

We don't put any library version in our code, as far as I know.

**Comment by bferguson3** [comment]
...which code?
I built from master with these steps:
sudo apt-get install libglew-dev libogg-dev libtheora-dev libvorbis-dev libsdl2-ttf-dev tcl-dev
git clone https://github.com/openmsx/openmsx --recursive
cd openmsx
./configure
make
I am on raspberry pi. I tried installing just now from apt-get with the same error.

**Comment by bferguson3** [comment]
Good news - this looks like an issue with the version of the stdc++ library itself.
I changed line 94 in main.mk to:
`LINK_FLAGS:=-pthread -static-libstdc++`
this statically links libstdc++ only. Not sure what other systems this will be necessary on, maybe just Debian Buster for now.

**Comment by MBilderbeek** [comment]
@mthuurne Is there something we can do here?

**Comment by mthuurne** [comment]
This sounds like a bug in the distro, where the headers and the binary of the C++ standard library don't match.

In theory we could add a workaround for it, but unless it's easy to pinpoint exactly which systems need the workaround, I'd rather not do that.

**Comment by MBilderbeek** [comment]
I can say that it compiles in testing. Did the packager patch this for Buster? No, because you said the package has the same error. @bferguson3 Please file a bug against Debian! The package from the distro should of course work. Use `reportbug openmsx`

**Comment by mthuurne** [comment]
> I can say that it compiles in testing. Did the packager patch this for Buster? No, because you said the package has the same error. @bferguson3 Please file a bug against Debian! The package from the distro should of course work. Use `reportbug openmsx`

The problem might be specific to ARM; it's a platform with a lot less eyeballs on it than x86-64.

**Comment by bferguson3** [comment]
It's been driving me a little mad because it's hard to say where the issue
is.

I'm at the tip of everything on Raspbian, which AFAIK is parallel to Debian
Buster x86_64. The strings contained in the most recent available
libstdc++6 stop at 4.25. I have no idea where the 4.26 is even coming from.

The library is dynamically linked so it seems to make sense that it would
happen on the apt distro as well, if it's a bug in the actual library.

**Comment by mthuurne** [comment]
Did you compile openMSX with the system standard compiler, or with a more recent version of GCC? What does `which g++` return? And if that points to a symlink, where does that link to?

What the versions of `libstdc++`, both the runtime and the development package?

What does `ldd` print when run on the `openmsx` binary?

**Comment by MBilderbeek** [comment]
@bferguson3 Please provide the requested information, otherwise there's nothing we can do about this.

**Comment by bferguson3** [comment]
Hi,
This is an issue with glibc on debian buster.

There is nothing you can do.

**Comment by MBilderbeek** [comment]
OK, thanks for letting us know. Closing....
