### ISSUE TITLE
Is it possible to add a separate OPL3 option for the VGM recording function

### ISSUE THREAD

**Issue by denjhang** [openMSX/openMSX#1349]

**Comment by MBilderbeek** [comment]
Can you explain a bit why you would like to have this?

@niekvlessert Can you comment?

**Comment by niekvlessert** [comment]
Right now the recorder script does not support OPL3, since I don't know about any player/music/game that is using it. If you have a few examples I can look into it. It will take me some time to make this, so I will require a valid use case, I'm not sure there is one, Google doesn't give me a lot?

**Comment by denjhang** [comment]
I regard the current Moonsound as OPL3+24ch. PCM. In fact, the function I need is to record the vgm that only uses the OPL3 part of Moonsound to a separate OPL3 chip.

**Comment by denjhang** [comment]
Is what I said reasonable? I don't understand the real difference between opl4 and opl3.
In fact, if I can record a separate OPL3 VGM, then these music will be easy to get some self-made hardware players to play(There are many such open source hardware.), or other hardware with OPL3 sound card to play(E.g. SB16, SB PRO). Because the hardware drive circuit of OPL3 is much simpler than OPL4, usually OPL3 only needs a single-chip microcomputer to drive, but OPL4 can only be done with cpld or fpga.

**Comment by denjhang** [comment]
@niekvlessert

**Comment by niekvlessert** [comment]
According to Wikipedia the YMF278B device has a FM part which is actually an OPL3. Then there's the OPL4 part; 24 channel sample synthesis. There are trackers for both parts; MBWAVE and MBFM.  Recording for both modes of the device are supported by the current script. I guess the VGM files recorded from MBFM can be played on a OPL3.

**Comment by MBilderbeek** [comment]
Implemented by @pvmm via fa0087c7c8388b2d7cecd2cb347be56b51ea0e4c
