### ISSUE TITLE
Meridian is not working properly

### ISSUE THREAD

**Issue by denjhang** [openMSX/openMSX#1350]
![截图未命名210412011148](https://user-images.githubusercontent.com/61811583/114327643-7e241800-9b6c-11eb-841c-75b0f6b3600e.jpeg)
I don't know if this is a problem with openmsx.
In the uploaded image, I wrote a simple script that will automatically open meridian after booting.
[meridian.zip](https://github.com/openMSX/openMSX/files/6293149/meridian.zip)

**Comment by MBilderbeek** [comment]
Your disk image works fine for me, so I'm not sure what's going on.... Also using the Panasonic FS-A1GT.
![meridian](https://user-images.githubusercontent.com/12675978/114452580-e7da0b80-9bd8-11eb-9171-03e6610077f4.png)

**Comment by denjhang** [comment]
I want to know the following, which ext devices do you use?

**Comment by MBilderbeek** [comment]
I was (only) using Moonsound as extension.

**Comment by denjhang** [comment]
Very strange phenomenon, when I canceled the following extensions and only used moonsound, it worked normally.
megaram 2mb
gfx9000
slotexpander

**Comment by MBilderbeek** [comment]
Even with these enabled, it seems to work fine for me. Anyway, I don't think this points to an issue in openMSX, so I'm closing this issue.
