### ISSUE TITLE
C-BIOS 0.29 has ENASLT bug.

### ISSUE THREAD

**Issue by Suzumizaki** [openMSX/openMSX#1356]
C-BIOS has the bug about ENASLT to select extended-slot.
Please update them on next release of openMSX.

Detail and solution(very simple):
https://sourceforge.net/p/cbios/bugs/22/?limit=25#5837

**Comment by MBilderbeek** [comment]
This is a C-BIOS bug. Perhaps @mthuurne is willing to take a look at it? But anyway, I don't want to track C-BIOS bugs in this tracker.
