### ISSUE TITLE
SFG-05's OPP(YM2164) playing/interval speed issue?

### ISSUE THREAD

**Issue by kumokosi** [openMSX/openMSX#1369]
As grauw has already reported, in " Correct YM2164 OPP emulation for the SFG-05 #1081", SFG-05 is not emulated correctly according to play/interval speeds.

I found OpenMSX's SFG-05 is approximately 2 time faster than real MSX.
I tried it with CX7M/128 BIOS on OpenMSX 17.0 for x64, these results and videos are below(twitter post).

[1]FM Music Macro II(YAMAHA YRM-51) sample song on real CX7M/128 w/SFG-05 + SONY HBK-30. There is no problem with playing speed.

https://twitter.com/kumokosi/status/1421448264906285059

[2]FM Music Macro II sample song CX7M/128 w/SFG-05 + SONY HBK-30, emulated by OpenMSX 17.0(x64 ver). Playing speed is too fast. It seems that, OPP's interval timing is not processed correctly (approximately 2x faster than normal OPM?)

https://twitter.com/kumokosi/status/1421449510379659267

[3]FM Music Macro II sample song CX7M/128 w/"SFG-01"(custom settings), emulated by OpenMSX 17.0(x64 ver). (This combination does not allow FDD, so this program is loaded via cas file.) Playing speed seems normal but many notes omitted

https://twitter.com/kumokosi/status/1421472304198868992

SFG's 4 operator-FM sound chips(OPM/OPP) are very attractive resource for MSX scene. I hope these are emulated correctly and achieve MSX musics more.
Thanks.

**Comment by MBilderbeek** [comment]
Hi, thanks for the report. Can you provide the sample file you used to reproduce the issue?

**Comment by MBilderbeek** [comment]
@m9710797 Would it be a good idea to port NukeYKT's OPM emulator to openMSX? See https://github.com/nukeykt/Nuked-OPM
However, I'm not sure whether it also supports OPP (it doesn't mention anything about it). Also, I can't find back the frequencies as mentioned by @grauw in #1081 ... can you help?

**Comment by MBilderbeek** [comment]
@m9710797 We may also be helped by these implementations: https://github.com/aaronsgiles/ymfm (which are used in MAME nowadays). They do explicitly support OPM vs OPP.

**Comment by MBilderbeek** [comment]
@kumokosi Can you please provide the sample file you used to reproduce the issue?

**Comment by D15C0DE** [comment]
MAME's new ymfm emulators do not handle access timing though. That's a distinct advantage of NukeYKT's work.

**Comment by grauw** [comment]
The timer B period for YM2164 OPP should be relatively easy to fix in the existing core. It is just changing the timer division by a factor of 2 based on the chip type. Also the test register should be moved to the new address while we’re at it.

The currently known information is listed here:

http://map.grauw.nl/resources/sound/yamaha_ym2164.php

The primary unknown remaining that still needs to be investigated are the 8 registers on YM2164 OPP addresses 0-7, but I am not aware of any software that uses them (other than the SFG-05 MBIOS ROM initialising them to certain default values).

I don’t think the Nuked core supports YM2164 OPP at the moment (neither does the MAME one), so it alone would not fix this issue, although it of course has other accuracy benefits and there too it should be relatively easy to add. It’s nice to see that more and more Nuked cores are becoming available covering the sound chips used on MSX.

On the topic of access timing (not the subject of this bug), note that on the Yamaha SFG there is afaik also a wait circuit present, so on Z80 iirc no additional waits need to be inserted by the code despite the YM2151 OPM / YM2164 OPP being quite slow comparatively. Although I’ve still been able to access it too fast on R800, so it’s not entirely fool-proof.

**Comment by MBilderbeek** [comment]
@grauw  I took a quick look at the code, but I couldn't even find that timer B period in the code. But that's probably just me.

**Comment by grauw** [comment]
In `EmuTimer.cc` you can find `EmuTimer::createOPM_2`. I think you need to make an OPP version of that with the `freq_denom` argument changed from `64 * 2 * 16` to `64 * 2 * 32` (or otherwise `* 8`).
