### ISSUE TITLE
Top odd (so using interlacing) line in display area is always black

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1372]
As reported by NYYRIKKI on https://msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=56:
> I just noticed on Windows version of openMSX (tested on version 0.15.0)
When deinterlace is turned off (`set deinterlace false`) the very first line of odd screen* is black instead of having background color.
How to test: `SCREEN 0,,,,,1:COLOR 1,15,15`

> *) with "odd screen" I mean `(VDP(-2)AND2)=2 `

> Seems that renderer or scale factor does not matter, the color problem is always visible.

> Even frame:
> ![image](https://user-images.githubusercontent.com/12675978/130366839-fc2a9d50-681d-4e60-a0c4-39ceed080afe.png)
> Odd frame:
>![image](https://user-images.githubusercontent.com/12675978/130366870-76097459-0b6d-4f06-8a5b-29340c0fb845.png)

**Comment by MBilderbeek** [comment]
Wouter wrote to me in Dutch (translated here):

> This behaviour has been implemented in
>   src/video/DoubledFrame.cc:33
>See also the comments in DoubledFrame.hh

> Apparently we choose explicitly to add black lines (in practice 0 or 1 lines).
> An alternative is to repeat the first line of the input frame.

> More background info:
> openMSX only renders 240 lines of the MSX image (just enough to show them in a 320x240 window). In reality (and depending on PAL/NTSC) the VDP generates more lines.
> If the output window is 640x480 (or bigger) then we show each MSX line twice.
> When interlace is enabled, we show for odd (or even?) frames the output one half MSX line (so one full host line) lower.
> Together we thus have 239 doubled lines and one half line at the top and bottom of the frame. So in principle you need information of 241 lines, but we only render 240 MSX lines.

> In prinicple we could change the code to render 241 MSX lines, but that's a relatively large change in the current code.
> And in practice, this extra lien will almost always be a border line, so it will look identical to the next line (also a border line).
> So I propose we just repeat that border line.

So, next step is to see whether that looks better than a black line.

**Comment by MBilderbeek** [comment]
The problem seems to be gone indeed with this patch:
```
diff --git a/src/video/DoubledFrame.cc b/src/video/DoubledFrame.cc
index c29426e51..aa1bb8e57 100644
--- a/src/video/DoubledFrame.cc
+++ b/src/video/DoubledFrame.cc
@@ -25,14 +25,11 @@ unsigned DoubledFrame::getLineWidth(unsigned line) const
 const void* DoubledFrame::getLineInfo(
 	unsigned line, unsigned& width, void* buf, unsigned bufWidth) const
 {
-	static constexpr uint32_t blackPixel = 0; // both 16bpp and 32bpp
 	int t = line - skip;
-	if (t >= 0) {
-		return field->getLineInfo(t / 2, width, buf, bufWidth);
-	} else {
-		width = 1;
-		return &blackPixel;
+	if (t < 0) {
+		t = 0;
 	}
+	return field->getLineInfo(t / 2, width, buf, bufWidth);
 }
 
 } // namespace openmsx

```

**Comment by NYYR1KK1** [comment]
Yes, this sounds like working workaround. Thanks!
