### ISSUE TITLE
LaserDisc playback colors got broken during openMSX 17.0 development

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1375]
Tried this on Windows and MacOS with both 17.0 release and latest dev build. The playback works but the color palette is all wrong (purple-ish).

**Comment by MBilderbeek** [comment]
You are right, it's indeed broken.

This is on openMSX:
![rbl_openmsx](https://user-images.githubusercontent.com/12675978/132396282-2d475a0e-4d4a-46a9-85dc-8646fe056376.png)
and this is on MPlayer:
![Screenshot from 2021-09-07 20-52-11](https://user-images.githubusercontent.com/12675978/132396317-dfb37994-56d9-4c24-a53b-95481840d8e6.png)
Looks like red and blue have been swapped?

**Comment by MBilderbeek** [comment]
Image looks normal on openMSX 16.0.

**Comment by MBilderbeek** [comment]
Some quick bisecting with binaries I still had:

Good:
./openmsx-18-g84fac54d3
./openmsx-37-g5f5b32ead
./openmsx-42-g23f86822d
bad:
./openmsx-387-gc19dd4072
./openmsx-207-ge60f676ae
./openmsx-105-gfb970bc2e
./openmsx-54-g95662d760
./openmsx-47-g36345233c
./openmsx-44-g3f0670647

In these versions, the GL stuff was rewritten to use OpenGL 2.1 instead of 3.3. It must have been broken there. And indeed, switching to SDL renderer also shows that that one is working fine.

@m9710797 Can you please take a look?

**Comment by m9710797** [comment]
Should be fixed in revision: f6d5e6c7c9e14a07f93f130acfa6ce19acd02454.

**Comment by sdsnatcher73** [comment]
It does not seem to work if openMSX is started with SDLGL-PP being the active renderer. If I switch from SDL to SDLGL-PP it does work. I also tested V9990 (wasn't on the checklist of the commit), that seems to still work fine but when switching renderer with v9990 active the screen turns grey and you have to reset the MSX (not sure if this was introduced with this fix or was already the case).

**Comment by m9710797** [comment]
(I'm re-opening this issue.)

Hi,

Thanks a lot for verifying.
Unfortunately I can't reproduce the issues you mention. Here's what I tried:

1) Make sure SDLGL-PP is the default renderer. Then start openMSX like this:
     `openmsx -machine Pioneer_PX-V60 badlands.ogv`
For me everything works fine, with the correct colors.

2) Run some V9990 software. While the V9990 screen is being shown. Execute the commands
  `set renderer SDL`    and     `set renderer SDLGL-PP`
But after switching (back and forth) everything keeps working as expected (with the correct colors).

Did I misunderstand the issues you saw? Can someone else reproduce these issues?
For that 2nd issue it would indeed be useful if you could find out if it's caused by the recent fix (that would surprise me).

Thanks.

**Comment by sdsnatcher73** [comment]
Yes it is exactly like that. I tried earlier on MacOS and now on Windows. I added SDLGL-PP specifically into settings.xml and verified with set renderer after startup that it was active. Loaded a game and the colors are incorrect, issued set renderer SDL and the colors are good, issued set renderer SDLGL-PP colors remain correct.

**Comment by sdsnatcher73** [comment]
The v9990 issue is reproducable on MacOS and Windows. The following steps can reproduce:

1. Download curry demo (possibly also happens with other v9990 software).
2. Start openMSX with FS-A1GT
3. Issue set renderer SDL
3. Insert Sunrise GFX9000
4. Insert curry.dsk and restart the machine
5. Issue set videosource GFX
6. Wait for the white screen to change to black and show loading info.
6. Issue set renderer SDLGL-PP
7. Screen turns grey
8. set videosource MSX
9. screen stays grey
10. set videosource GFX9000
11. GFX9000 output is visible again

This tested on openMSX 17.0-183 on MacOS and Windows as well as openMSX 17.0 on Windows. Once the screen is grey switching renderer has no effect. It does not matter which renderer was active at the beginning. This probably warrants a new issue.

**Comment by MBilderbeek** [comment]
The V9990 issue is that after a renderer switch the videosource is reset to the default value. This is #1143 .

I also can't reproduce the color issue anymore. SDLGL-PP is the default for me and I get the correct colors now when running a laserdisc game. I was running simply this from the command line:
`$ openmsx -machine Pioneer_PX-7 -laserdisc rolling_blaster.ogv `
But also after starting and loading it works fine. 

It almost sounds like you're not running the right binary...

**Comment by sdsnatcher73** [comment]
If I were running the wrong binary it would return to wrong colors after switching from SDL to SDLGL-PP but it does not. The difference is I am not running Linux.

**Comment by sdsnatcher73** [comment]
Also behaviour seems different when started from CLI or changing machine through OSD

From CLI:
1. Execute /Applications/openMSX.app/Contents/MacOS/openmsx -machine Pioneer_PX-7 -laserdisc ~/Downloads/astron_belt.ogv 
2. Colors are bad (default is SDLGL-PP in settings.xml)
3. Execute set renderer SDL
4. Colors are good
5. Execute set renderer SDLGL-PP
6. Colors go bad

From UI:
1. Start openMSX.app from Launchpad
2. Change machine to Pioneer PX-7 through OSD
3. Insert astron_belt.ogv from OSD
4. Press 1
5. Press CALLLD + enter
6. Colors are bad (default is SDLGL-PP in settings.xml)
7.  Execute set renderer SDL
4. Colors are good
5. Execute set renderer SDLGL-PP
6. Colors REMAIN good

**Comment by sdsnatcher73** [comment]
Are you running staticbindist build on Linux or shared library build??

**Comment by MBilderbeek** [comment]
I always run shared library builds.

**Comment by sdsnatcher73** [comment]
Windows and MacOS are typically staticbindist builds. Did any of the 3rd party libraries get an update on your system to a version higher than what the build system uses for staticbindist? (not sure if that is the cause but it may be)

**Comment by sdsnatcher73** [comment]
[Recording with openMSX started from command line](https://www.icloud.com/iclouddrive/0uk0t_8kBC6shSP5loUCwoBCg#openMSX_LaserDisc_1)
[Recording with openMSX started regularly](https://www.icloud.com/iclouddrive/0caVv_AgzX6keAylECZyvUXQA#openMSX_LaserDisc_2)

**Comment by MBilderbeek** [comment]
What are your other settings like `scale_factor` and `scale_algorithm`? I was testing with `scale_factor` 4 and the `simple` `scale_algorthm`.

**Comment by sdsnatcher73** [comment]
`
<!DOCTYPE settings SYSTEM 'settings.dtd'>
<settings>
  <settings>
    <setting id="scale_algorithm">RGBtriplet</setting>
    <setting id="osd_rom_path">/Users/peter/Sources/SD/MSX/SOFTWARE/GAME/KONAMI</setting>
    <setting id="default_machine">Panasonic_FS-A1GT</setting>
    <setting id="osd_ld_path">/Users/peter/Downloads</setting>
    <setting id="invalid_psg_directions_callback">psgdirectioncallback</setting>
    <setting id="blur">0</setting>
    <setting id="scanline">0</setting>
    <setting id="samples">882</setting>
    <setting id="invalid_ppi_mode_callback">ppimodecallback</setting>
    <setting id="master_volume">100</setting>
    <setting id="di_halt_callback">dihaltcallback</setting>
    <setting id="osd_disk_path">/Users/peter/Sources/SD/MSX/SOFTWARE/DEMO</setting>
    <setting id="vsync">false</setting>
    <setting id="horizontal_stretch">272.0</setting>
  </settings>
  <bindings/>
</settings>
`

**Comment by MBilderbeek** [comment]
Try to change the `scale_algorithm` to `simple`, it is now on `RGBTriplet`, which is a bit of a special thing (I once created it just for fun), which isn't really intended for serious usage.
RGBTriplet was meant to be used on factor 3. Probably already works a lot better then.

**Comment by sdsnatcher73** [comment]
That fixed It indeed.

**Comment by MBilderbeek** [comment]
OK, then the original issue was indeed fixed, right?

**Comment by MBilderbeek** [comment]
@sdsnatcher73 Can you make these videos available again? The links aren't working anymore. @m9710797 was going to check if he could see what's wrong with the RGBTriplet scaler. It looks like it has a problem that wasn't known to us before (the switching between renderers shouldn't have affected it.)

**Comment by sdsnatcher73** [comment]
Videos are restored from recycle bin ;) Let me know when you are done. Should also be reproducible now on Linux, right?

**Comment by MBilderbeek** [comment]
@sdsnatcher73 Can you reproduce the isuses at 3x scale factor?

**Comment by sdsnatcher73** [comment]
At 3x the issue is not present with RGBtriplet (actually now RGBtriplet seems to do something whilst it doesn't seem to do anything at 2x, other than distort the colors)

After looking again it seems like RGBtriplet is only active on the laserdisc source and not the MSX source... Can this be true?

After some more testing it seems RGBtriplet is NOT active when I first start openMSX, it only gets activated when the superimposed LaserDisc source is added. If I then reset the machine it remains active also on the MSX source (this seems not always the case).

**Comment by sdsnatcher73** [comment]
[Video showing the above](https://www.icloud.com/iclouddrive/04fGS-h3Ur7jgA5oyVPTYNEVA#openMSX_LaserDisc_3)

**Comment by MBilderbeek** [comment]
Heh, I tried to change my settings to "RGBTriplet" and 3x" and started openMSX, but I see the RGBTriplet directly being active in BASIC. But in your video it is indeed as if it's doing nothing at all. Is this with both renderers the case?

By the way, as the manual says, RGBTriplet is only meant to be used on 3x scaling. It doesn't do anything in other factors, except on SDLGL-PP, where it does some sort of attempt. But apparently not very successfully.

**Comment by sdsnatcher73** [comment]
If I force SDL in settings.xml RGBtriplet works right away.
