### ISSUE TITLE
openmsx 0.17.0-RC1 OPL4 VGM recording lost "OPL4 PCM RAM" block.

### ISSUE THREAD

**Issue by denjhang** [openMSX/openMSX#1377]
When recording music that only applies to Moonsound PCM in 0.17.0-RC1, I found that the recorded music could hardly be played normally, and I found serious problems when doing VGM trimming. I didn't seem to have this problem when I used the 0.16 version before.
You can look here, I described the matter in detail.
https://vgmrips.net/forum/viewtopic.php?f=17&t=3769

**Comment by MBilderbeek** [comment]
The script is written by Niek, I asked him to comment.

By the way, any reason why you are using RC1, and not the final release? (It won't matter, probably, but it is strange.)
Are you sure you are using the scripts that belong to that version exactly?

By the way, I can't view that forum without an account.

**Comment by denjhang** [comment]
I can be sure that the problem is 0.17.0-RC1. Because currently I installed 0.16.0 on another computer and re-recorded these VGMs, I found no problems.

**Comment by denjhang** [comment]
I use 0.17.0-RC1 because I am too lazy to update the software (the network is too bad), and this version was used half a year ago.

**Comment by denjhang** [comment]
[soot.zip](https://github.com/openMSX/openMSX/files/7253394/soot.zip)
The file in this compressed package is a music disk. To play music, enter the command:
msp external.ltm

**Comment by denjhang** [comment]
[sootsound-demo.zip](https://github.com/openMSX/openMSX/files/7253402/sootsound-demo.zip)
This compressed package is a VGM I recorded with 0.17.0-rc1. It should be noted that arpsyn01.vgm uses 0.16.0, and this file is successfully trimmed, while the others use 0.17.0-rc1 and cannot be trimmed ( It seems that it cannot be played back correctly in the vgm player).

**Comment by ValleyBell** [comment]
denjhang uploaded this to the topic on vgmrips earlier today:
[aekrus-openmsx.zip](https://github.com/openMSX/openMSX/files/7340311/aekrus-openmsx.zip)

When exporting the VGMs to text, it gets more obvious that something has changed:

aekrus-openmsx 0.16.vgm:
```
VGMData:
0x00000100: 67 66 87    Data Block - Type 87: YMF278B RAM
                        Data Length: 0x000A0000
                        ROM Size: 0x000A0000    Data Start: 0x00000000
0x000A010F: D0 01 05 03 YMF278B:        Port 1 OPL3 Mode: Enable, OPL4 Mode: Enable
0x000A0113: D0 00 01 20 YMF278B:        Port 0 Waveform Select: Enable
0x000A0117: D0 01 05 03 YMF278B:        Port 1 OPL3 Mode: Enable, OPL4 Mode: Enable
0x000A011B: 61 01 00    Wait:   1 samples (   0.02 ms)  (total  1 (00:00.00))
0x000A011E: D0 01 04 00 YMF278B:        Port 1 4-Op Mode: Ch 0-3: Disable, Ch 1-4: Disable, Ch 2-5: Disable, Ch 9-12: Disable, Ch 10-13: Disable, Ch 11-14: Disable
0x000A0122: 61 01 00    Wait:   1 samples (   0.02 ms)  (total  2 (00:00.00))
0x000A0125: D0 00 BD 00 YMF278B:        Port 0 AM Depth: 1.0, Vibrato Depth: 7 cent, Rhythm Mode Disable
```

aekrus-openmsx 0.17.0rc1.vgm
```
VGMData:
0x00000100: D0 00 01 20 YMF278B:        Port 0 Waveform Select: Enable
0x00000104: D0 01 05 03 YMF278B:        Port 1 OPL3 Mode: Enable, OPL4 Mode: Enable
0x00000108: 61 01 00    Wait:   1 samples (   0.02 ms)  (total  1 (00:00.00))
0x0000010B: D0 01 04 00 YMF278B:        Port 1 4-Op Mode: Ch 0-3: Disable, Ch 1-4: Disable, Ch 2-5: Disable, Ch 9-12: Disable, Ch 10-13: Disable, Ch 11-14: Disable
0x0000010F: 61 01 00    Wait:   1 samples (   0.02 ms)  (total  2 (00:00.00))
0x00000112: D0 00 BD 00 YMF278B:        Port 0 AM Depth: 1.0, Vibrato Depth: 7 cent, Rhythm Mode Disable
```

It looks like in openmsx 0.17, it doesn't dump the OPL4 RAM block at all, nor does it put the "OPL3 Mode: Enable" initialization command in.
(The command right before the "Wait" command is probably the OPL4 command that starts the log, thus it is not part of the VGM logger's initialization.)

It looks like openmsx 0.17 rc1 discards all VGM initialization commands but the last one.
The missing "Data Block - Type 87" block causes VGMPlay 0.50 and any trimming tools to discard all OPL4 RAM writes, as it assumes that there is no OPL4 RAM present.
(VGMPlay 0.40.x defaults to 512 KB RAM, so it still works there, even though it is not supposed to work.)

**Comment by MBilderbeek** [comment]
The last change in the VGM recorder script was before the 16.0 release. So the difference is not caused by changes in the script. That means it must be caused by changes in openMSX.

I checked the script a bit and found this part:
```
                set moonsound_ram [concat [machine_info output_port 0x7E] {wave RAM}]
                if {[lsearch -exact [debug list] $moonsound_ram] >= 0} {
                        set moonsound_ram_size [debug size $moonsound_ram]
```
In the variable `moonsound_ram` there should be the name of the debuggable that contains the sample RAM of the OPL4.

If I execute this code in the console I get this:
`concat [machine_info output_port 0x7E] {wave RAM}`
I get
`{Sunrise MoonSound} wave RAM`
That seems to be wrong, it should be `{Sunrise MoonSound wave RAM}`, or even without the {}. Something is going wrong with escaping?

Taking a deeper look: the output of `machine_info output_port` seems to be a Tcl list, even if there's only a single value returned. This changed in 4b5455849987570218ff24a47b8e972e9b19d595 and the script doesn't seem to have been updated for this interface change.

I'm updating the scripts in a commit. @m9710797 can you review?

**Comment by MBilderbeek** [comment]
@ValleyBell @denjhang Can you confirm with the latest code or development build? It's labeled 204-g542cd1039 (a later version is also fine of course).

**Comment by MBilderbeek** [comment]
@ValleyBell Thanks for pointing to the details, this helped a lot to find out what was going wrong.

**Comment by denjhang** [comment]
> @ValleyBell @denjhang Can you confirm with the latest code or development build? It's labeled 204-g542cd1039 (a later version is also fine of course).

Is there a binary file for me to use in the development build? Please give me a link.

**Comment by ValleyBell** [comment]
It is easy to find:
https://openmsx.org/ -> Development builds: FiXato's openMSX Builder site -> Builds: Windows
