### ISSUE TITLE
"ext fmpac" does not work from config ("-script" parameter) file

### ISSUE THREAD

**Issue by bengalack** [openMSX/openMSX#1380]
My FM-PAC detection routine "suddenly" couldn't find (external) FMPAC. I couldn't find much wrong, so I moved the "ext fmpac" out of the config-file, and replaced with "-ext fmpac" on the command line. Then it worked.

I tested "the game we don't mention" the same way. That game wont play FM-music either when the ext fmpac is in the config-file. Is this a known issue?

May not matter, but my detection routine runs from a (mega-)ROM-file and the machine used was Philips_NMS_8250/Philips_NMS_8255. Detection is done immediately on startup.

openmsx 17.0

**Comment by MBilderbeek** [comment]
What do you mean with "the config file"?

Op zo 24 okt. 2021 07:55 schreef bengalack ***@***.***>:

**Comment by bengalack** [comment]
sorry for being unclear: the config in this case, the contents of the "-script" file. -script as in command line parameter

**Comment by MBilderbeek** [comment]
Can you show us the full content of the file you passed with the -script
parameter?

Op zo 24 okt. 2021 08:38 schreef bengalack ***@***.***>:

**Comment by bengalack** [comment]
Current content of the script is:

```
set throttle off
#ext msxdos2
#ext ram512k
ext fmpac
#ext MegaFlashROM_SCC+_SD
#ext slotexpander
plug joyporta keyjoystick1
#plug joyporta joystick1

#diska Debug/bin
#diskb Tools

#cartf "Debug/bin/tll.rom" -romtype ASCII16
carta "Debug/bin/saga.rom" -romtype ASCII16

#carta "/Users/palha/OneDrive/Documents/openMSX/share/software/NEMESIS3.ROM"

#carta "/Users/palha/source/repos/MSX ROM Application1/Debug/bin/MSXAPP.ROM"
#carta "/Users/palha/Google Drive/msx/msx/Super Mario World v1.1 - Noramos (2021).rom"

#diska "/Users/palha/Google Drive/msx/msx/psycho_world/Psycho_world.dsk"
#diska "/Users/palha/Google Drive/msx/msx/hydefos/Hydefos (1989)(Hertz)(ja)(Disk 1 of 2).dsk"

#diska /Users/palha/Dropbox/msx/BennyRoger_20210322/tll6
#diskb "/Users/palha/Google Drive/msx/msx/moonblaster-1.4.dsk"
set fullspeedwhenloading on
#load_icons none
load_icons set1 bottom

ext debugdevice
set debugoutput stdout
debug set_watchpoint read_io 0x2E

set scale_factor 4
set scale_algorithm simple
set blur 0
set noise 0
set scanline 12
set speed 100
set limitsprites on
#toggle_info_panel
#source vars.tcl
#source openmsx.tcl

#after time 15 "set throttle on"
after time 7 "set throttle on"

after time 1 "disable_reversebar"

```

it is run with:
`"\Program Files\openMSX\openmsx.exe" -machine Philips_NMS_8250 -script .\openMSX_emul_start_config.txt`

**Comment by MBilderbeek** [comment]
If you start up with this script, but without your own ROM (saga.rom), can you do _FMPAC in BASIC? That will confirm whether the command worked or not.

**Comment by MBilderbeek** [comment]
Ah, I already understand what's going on. The script says:
1. ext fmpac
2. carta your.rom

The first line puts the FM-PAC in the first available slot. The 2nd line puts your.rom in slot A. But the first available slot for FM-PAC was slot A. So it is immediately replaced by the ROM cartridge.

**Comment by m9710797** [comment]
Hi, I didn't look at the script. I only saw this thread after MBilderbeek already figured out the problem. I only want to add a suggestion for a solution. Either:
- Specify an explicit slot-name for both the 'ext' and 'cart' commands. E.g. "exta fmpac" and "cartb your.rom". With this option you have control over what goes where.
- Leave out the slot-name for both: "ext fmpac" and "cart your.rom". In this case openMSX will choose the slots for you.

As MBilderbeek already said: I you mix these two approaches you can get unexpected results.

**Comment by bengalack** [comment]
Thank you. This makes perfect sense, and I should have known!
