### ISSUE TITLE
Failed to configure using Buildroot

### ISSUE THREAD

**Issue by dmanlfc** [openMSX/openMSX#1387]
Hi, I cannot build OpenMSX using Buildroot

When ./configure is called this is the log...

Probing system:
Compiler works: /x86_64/host/bin/x86_64-buildroot-linux-gnu-g++ -m64 (LC_ALL=C.UTF-8)
Found function: ftruncate
Found function: mmap
Found function: posix_memalign
Found function: nftw
ALSA: Found header
ALSA: Found lib
GL: Found header
GL: Found lib
GLEW: Found header
GLEW: Found lib
OGG: Found header
OGG: Found lib
PNG: Found header
PNG: Found lib
SDL2: Found header
SDL2: Found lib
SDL2_TTF: Found header
SDL2_TTF: Found lib
TCL: Found header
linker command: /x86_64/host/bin/x86_64-buildroot-linux-gnu-g++ derived/x86_64-linux-opt/config/TCL.o -o derived/x86_64-linux-opt/config/TCL.bin -m64
/x86_64/host/lib/gcc/x86_64-buildroot-linux-gnu/11.2.0/../../../../x86_64-buildroot-linux-gnu/bin/ld: derived/x86_64-linux-opt/config/TCL.o:(.data+0x0): undefined reference to `Tcl_CreateInterp'
collect2: error: ld returned 1 exit status
return code from linker: 1
TCL: Missing lib
THEORA: Found header
THEORA: Found lib
VORBIS: Found header
VORBIS: Found lib
ZLIB: Found header
ZLIB: Found lib

**Comment by mthuurne** [comment]
It looks like the TCL link flags are missing from that linker command line. What did openMSX"s probe write to `derived/tcl-search.log` and `derived/x86_64-linux-opt/config/probed_defs.mk`?

**Comment by dmanlfc** [comment]
`derived/tcl-search.log` =
Looking for Tcl...
No suitable versions found.
Unable to determine whether Tcl installation has shared or static library.

`derived/x86_64-linux-opt/config/probed_defs.mk.failed` <- Note: 'failed'

# Automatically generated by build system.
# Non-empty value means found, empty means not found.
HAVE_ALSA_H:=true
HAVE_ALSA_LIB:=true
ALSA_CFLAGS:=
ALSA_LDFLAGS:=-lasound
HAVE_GL_H:=true
HAVE_GL_LIB:=true
GL_CFLAGS:=
GL_LDFLAGS:=-lGL
HAVE_GLEW_H:=true
HAVE_GLEW_LIB:=true
GLEW_CFLAGS:=
GLEW_LDFLAGS:=-lGLEW
HAVE_OGG_H:=true
HAVE_OGG_LIB:=true
OGG_CFLAGS:=
OGG_LDFLAGS:=-logg
HAVE_PNG_H:=true
HAVE_PNG_LIB:=true
PNG_CFLAGS:=-I/x86_64/host/include/libpng16
PNG_LDFLAGS:=-L/x86_64/host/lib -lpng16
HAVE_SDL2_H:=true
HAVE_SDL2_LIB:=true
SDL2_CFLAGS:=-I/x86_64/host/x86_64-buildroot-linux-gnu/sysroot/usr/bin/../../usr/include/SDL2 -I/x86_64/host/x86_64-buildroot-linux-gnu/sysroot/usr/bin/../../../../x86_64-buildroot-linux-gnu/sysroot/usr/include -D_REENTRANT
SDL2_LDFLAGS:=-L/x86_64/host/x86_64-buildroot-linux-gnu/sysroot/usr/bin/../../usr/lib -lSDL2
HAVE_SDL2_TTF_H:=true
HAVE_SDL2_TTF_LIB:=true
SDL2_TTF_CFLAGS:=-I/x86_64/host/x86_64-buildroot-linux-gnu/sysroot/usr/bin/../../usr/include/SDL2 -I/x86_64/host/x86_64-buildroot-linux-gnu/sysroot/usr/bin/../../../../x86_64-buildroot-linux-gnu/sysroot/usr/include -D_REENTRANT -I/x86_64/host/bin/../x86_64-buildroot-linux-gnu/sysroot/usr/include/freetype2 -I/x86_64/host/bin/../x86_64-buildroot-linux-gnu/sysroot/usr/include/libpng16
SDL2_TTF_LDFLAGS:=-lSDL2_ttf -L/x86_64/host/x86_64-buildroot-linux-gnu/sysroot/usr/bin/../../usr/lib -lSDL2
HAVE_TCL_H:=true
HAVE_TCL_LIB:=
TCL_CFLAGS:=
TCL_LDFLAGS:=
HAVE_THEORA_H:=true
HAVE_THEORA_LIB:=true
THEORA_CFLAGS:=
THEORA_LDFLAGS:=-ltheoradec
HAVE_VORBIS_H:=true
HAVE_VORBIS_LIB:=true
VORBIS_CFLAGS:=
VORBIS_LDFLAGS:=-lvorbis
HAVE_ZLIB_H:=true
HAVE_ZLIB_LIB:=true
ZLIB_CFLAGS:=
ZLIB_LDFLAGS:=-lz

**Comment by mthuurne** [comment]
OK, so the link flags are missing because the build, specifically the `build/libraries.py` script, failed to find TCL.

The underlying problem is that TCL installs a script that contains its configuration in a location that is not in `$PATH`, for example in `/usr/lib64/tclConfig.sh`. So the best we can do is look for this script in a few likely locations, but when you're building using a separate toolchain like Buildroot does, those locations are unpredictable.

As a way around this, the openMSX build allows you to set the `TCL_CONFIG` environment variable, which should point to the directory containing the `tclConfig.sh` script. If you do this, you should see TCL being found in the `tcl-search.log`.

**Comment by dmanlfc** [comment]
Ok better now, but I now have another error in probe.log

`derived/tcl-search.log`

Looking for Tcl...
Config script: /x86_64/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/tclConfig.sh
Found: version 8.6
Selected: /x86_64/host/x86_64-buildroot-linux-gnu/sysroot/usr/lib/tclConfig.sh
Getting Tcl compile flags...
Result: -I/usr/include
Getting Tcl library type (shared/static)...
Result: 1
Getting Tcl dynamic link flags...
Result: -L/usr/lib -ltcl8.6

`probe.log`

Probing system:
Compiler works: /x86_64/host/bin/x86_64-buildroot-linux-gnu-g++ -m64 (LC_ALL=C.UTF-8)
Found function: ftruncate
Found function: mmap
Found function: posix_memalign
Found function: nftw
ALSA: Found header
ALSA: Found lib
GL: Found header
GL: Found lib
GLEW: Found header
GLEW: Found lib
OGG: Found header
OGG: Found lib
PNG: Found header
PNG: Found lib
SDL2: Found header
SDL2: Found lib
SDL2_TTF: Found header
SDL2_TTF: Found lib
compiler command: /x86_64/host/bin/x86_64-buildroot-linux-gnu-g++ -c derived/x86_64-linux-opt/config/TCL.cc -o derived/x86_64-linux-opt/config/TCL.o -m64 -I/usr/include
x86_64-buildroot-linux-gnu-g++: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/include'
return code from compiler: 1
TCL: Missing header
TCL: Cannot test linking because compile failed
THEORA: Found header
THEORA: Found lib
VORBIS: Found header
VORBIS: Found lib
ZLIB: Found header
ZLIB: Found lib

**Comment by mthuurne** [comment]
What are the `TCL_CFLAGS` now in `probed_defs.mk`?

Possibly the compile flags that `tclConfig.sh` reports are incorrect: `/usr/include` is the host header directory; `tclConfig.sh` should be pointing to the Buildroot sysroot dir instead.

**Comment by dmanlfc** [comment]
TCL_CFLAGS:=-I/usr/include
TCL_LDFLAGS:=-L/usr/lib -ltcl8.6

**Comment by dmanlfc** [comment]
TCL_INCLUDE_SPEC='-I/usr/include'

**Comment by mthuurne** [comment]
Yeah, that path is incorrect.

The best solution would be to change something in Buildroot to either make TCL produce correct paths in its `tclConfig.sh` script or to patch up `tclConfig.sh` in a post-build step.

A quick and dirty solution would be to patch the `TCL.getCompileFlags()` and `TCL.getLinkFlags()` methods in the openMSX `build/libraries.py` file to return hardcoded flags.

---

By the way, why are you compiling openMSX for the host? Typically people want to compile it for the target system instead.

**Comment by dmanlfc** [comment]
Yeah I was coming to the same conclusion - let me try that

**Comment by dmanlfc** [comment]
Almost there - compiled but failed on - Linking openmsx...
/usr/bin/ld: cannot find /lib64/libm.so.6
/usr/bin/ld: cannot find /lib64/libmvec.so.1
collect2: error: ld returned 1 exit status

**Comment by dmanlfc** [comment]
Sorted :-) Now to test it!

**Comment by dmanlfc** [comment]
Thanks for your help @mthuurne - you can close this one!

**Comment by MBilderbeek** [comment]
Can you please summarize how you solved all issues, for when someone who
has the same issues and finds this thread?

Op za 27 nov. 2021 12:18 schreef Daniel Martin ***@***.***>:

**Comment by dmanlfc** [comment]
yeah - I will post a link to the source code

**Comment by dmanlfc** [comment]
https://github.com/dmanlfc/batocera.linux/commit/9059e2284caaa5bb3e68085755a52a1a06b4e3a5#diff-fb88d87304eea35f3b98ee47ce8f2b4935908eae7d4f83aebc63603a77ca4daf

**Comment by MBilderbeek** [comment]
Well, thanks, but can you just tell us which solutions you found for which
problems?

Also, why that settings.xml? And how did you come to its content?
These binds look strange, or at least superfluous.

Note that without that file, openMSX uses default settings, which should be
okay for almost all use cases. The file normally contains only a setting if
the value is different from the default.

Op za 27 nov. 2021 14:01 schreef Daniel Martin ***@***.***>:

**Comment by dmanlfc** [comment]
The solutions are in the .mk file

Essentially:

1. Ensuring the environment variables were set correctly via OPENMSX_CONF_ENV
- Especially important is setting the PATH to include $(STAGING_DIR)/usr/bin" so that SDL is detected
- TCL_CONFIG="$(STAGING_DIR)/usr/lib" is set to ensure tclConfig.sh can do it's work (after being patched, see point 2)
- LD_FOR_BUILD="$(TARGET_CROSS)ld" for compilation linking

2. Patch the tclConfig.sh file as suggested by mthuurne in OPENMSX_TCL_CONFIG_FIXUP
3. Then restore it after build & install, just to be sure in OPENMSX_POST_INSTALL_CLEANUP
4. USe OPENMSX_BUILD_CMDS to use the environment variable again that we set earlier - especially LD_FOR_BUILD

I had a look at the bindings from here - https://www.msxinfo.net//files/openmsxarcade.JPG
Initially I just wanted the emulator to start fullscreen
We're not finished, I will be handing this over to get more fine tuning soon.

**Comment by MBilderbeek** [comment]
Thanks, clear. Later readers of this thread will be grateful :)

These bindings are mostly binding controller inputs to keyboard input. But in the settings.xml you have keyboard events binding to keyboard input. That's strange :)

If you need help or advice, feel free to ask.

**Comment by dmanlfc** [comment]
Yeah it's for my testing on the picade controller. It won't be in upstream 😉
