### ISSUE TITLE
YJK calculation discrepancy between real MSX machine and emulator

### ISSUE THREAD

**Issue by Dalekamistoso** [openMSX/openMSX#1394]
An user called "MDPC" at twitter has found a bug in YJK calculations 

I already confirmed the bug with my own real machine (MSX TurboR FS1AST) and latest openMSX build, the bug shows a diffent color pattern and a different screen representation (bug confirmed with GT too).

The code he used to reproduce this bug is:

10 SCREEN 12:FOR A=0 TO 255 STEP2:VPOKEA,-(AMOD8=0)*2:VPOKEA+1,4:NEXT
20 COPY(0,0)-(255,210)TO(0,1)
30 A$=INPUT$(1)

It seems to be a mismatch in color calculation, the user thinks that calculation should be in this way:

R = Y + J
G = Y + K
B = (Y × 5-J × 2-K) ÷ 4 <- not correct
B = (Y × 5-J × 2-K + 2) ÷ 4

The original source of the report:
https://twitter.com/mdpc___/status/1480432007180341251?s=20

Real machine output:
![real-machine-output](https://user-images.githubusercontent.com/67012746/149386657-ec20652a-4265-4b5a-a011-7527800b957b.png)

Emulated machine output:
![emulated-machine-output](https://user-images.githubusercontent.com/67012746/149386652-f6d33a30-3350-426f-9dbc-4db893626756.png)

**Comment by m9710797** [comment]
Hi, thanks for your report.
I will investigate.

**Comment by MBilderbeek** [comment]
As @mthuurne put it: 
< mth > (... + 2) ÷ 4 means that it's effectively half a step off
< mth > the difference between arithmetical rounding vs always rounding down

[patch.diff.txt](https://github.com/openMSX/openMSX/files/7866133/patch.diff.txt)

**Comment by Dalekamistoso** [comment]
I would like to add this link to the document referring this issue (use google translate is a very interesting page with lots of technical information) 

http://ngs.no.coocan.jp/doc/wiki.cgi/datapack?page=9%BE%CF+YJK%CA%FD%BC%B0

**Comment by MBilderbeek** [comment]
But that link gives the same formula... right? So, without the extra +2 to change the rounding.

**Comment by Dalekamistoso** [comment]
Yes, that is the reason why I suppose that all emulators (webmsx and bluemsx at least) have this bug too, because probably this formula is not properly documented, i added this link as reference of this issue, also is an interesting source of information

**Comment by m9710797** [comment]
I've confirmed this in my real turbor machine.
I've fixed this in openMSX.

Thanks again for reporting this bug.

**Comment by Dalekamistoso** [comment]
Thank you very much for your effort!
