### ISSUE TITLE
Change userdir ?

### ISSUE THREAD

**Issue by liberodark** [openMSX/openMSX#1395]
Hi,

I need to change the user_dir : `/home/pc/.openMSX` to `/home/pc/configs/openmsx`
Have see two options in you code : `OPENMSX_USER_DATA` & `OPENMSX_HOME` but i don't know if you have better way.
You have any idea how to make that with configuration file or args `openmsx --dir ` ? Or i need to make a .patch for that ?

With a .patch i think is here : 

```
const string& getUserOpenMSXDir()
{
	static const string OPENMSX_DIR = []() -> string {
		if (const char* home = getenv("OPENMSX_HOME")) {
			return home;
		}
#ifdef _WIN32
		return expandTilde("~/openMSX");
#elif PLATFORM_ANDROID
		// TODO: do something to query whether the storage is available
		// via SDL_AndroidGetExternalStorageState
		return strCat(SDL_AndroidGetExternalStoragePath(), "/openMSX");
#else
		return expandTilde("~/.openMSX");
#endif
	}();
	return OPENMSX_DIR;
}
```

Best Regards

**Comment by liberodark** [comment]
Ok have make a .patch

**Comment by MBilderbeek** [comment]
Please check http://openmsx.org/manual/setup.html#settings in the last part
of that section.

Op za 15 jan. 2022 19:06 schreef liberodark ***@***.***>:
