### ISSUE TITLE
R800 block I/O instructions only affect Z and N

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1406]
Japanese Twitter user [MSX研鑚推進委員会](https://twitter.com/mdpc___) reported an issue with R800 emulation: https://twitter.com/mdpc___/status/1499659710349582336

On the Z80, contrary to the official documentation, block I/O instructions affect all flags rather than just Z and N. This is described in [The Undocumented Z80 Documented](http://www.myquest.nl/z80undocumented/z80-documented-v0.91.pdf), and emulated correctly.

The R800 however follows the official Z80 documentation, and block I/O instructions only affect Z and N, and it does so in the exact way the Z80 manual describes (Z is set if B is 0 after the instruction, and N is always set).

I made a test program to confirm (source included): [R800OutFlags.zip](https://github.com/openMSX/openMSX/files/8191718/R800OutFlags.zip)

It does two tests for each block I/O instruction, first with all flags set, second with all flags cleared before executing the instruction. The first two columns show the state of the flags register afterwards. The third column shows the bits that changed in either test, iow the flag bits that the instruction affects.

Real Panasonic FS-A1GT output:

![20220306_011759](https://user-images.githubusercontent.com/772052/156904096-e1027a2e-9112-4278-bd07-d60980ceb731.jpg)

OpenMSX Panasonic FS-A1GT output:

![quicksave](https://user-images.githubusercontent.com/772052/156904036-891d85a1-b7f3-4cea-aeb7-057584251916.png)

**Comment by grauw** [comment]
OpenMSX Panasonic FS-A1GT output after fix:

![afbeelding](https://user-images.githubusercontent.com/772052/156904622-d69ea212-f4aa-4d74-a3d7-1ea1fd82ad19.png)

**Comment by m9710797** [comment]
Thanks!
