### ISSUE TITLE
MacOS builds fail (due to switch to c++20?)

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1411]
Compiling CommandLineParser.cc...
In file included from src/CommandLineParser.cc:1:
In file included from src/CommandLineParser.hh:13:
In file included from src/commands/InfoTopic.hh:4:
In file included from src/commands/Completer.hh:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:2017:21: error: object of type 'view::detail::TransformIterator<const std::string_view *, (lambda at src/CommandLineParser.cc:88:3)>' cannot be assigned because its copy assignment operator is implicitly deleted
                __m = __first;
                    ^
src/utils/stl.hh:317:4: note: in instantiation of function template specialization 'std::vector<openmsx::CommandLineParser::FileTypeData>::insert<view::detail::TransformIterator<const std::string_view *, (lambda at src/CommandLineParser.cc:88:3)>>' requested here
        x.insert(std::end(x), std::begin(y), std::end(y));
          ^
src/utils/stl.hh:346:10: note: in instantiation of function template specialization 'detail::append<std::vector<openmsx::CommandLineParser::FileTypeData>, view::detail::Transform<std::initializer_list<std::string_view> &, (lambda at src/CommandLineParser.cc:88:3)>>' requested here
        detail::append(v, std::forward<Tail>(tail)...);
                ^
src/CommandLineParser.cc:87:2: note: in instantiation of function template specialization 'append<openmsx::CommandLineParser::FileTypeData, view::detail::Transform<std::initializer_list<std::string_view> &, (lambda at src/CommandLineParser.cc:88:3)>>' requested here
        append(fileTypes, view::transform(extensions,
        ^
src/utils/view.hh:237:32: note: copy assignment operator of 'TransformIterator<const std::string_view *, (lambda at src/CommandLineParser.cc:88:3)>' is implicitly deleted because field 'op' has a deleted copy assignment operator
        [[no_unique_address]] UnaryOp op;
                                      ^
src/CommandLineParser.cc:88:3: note: lambda expression begins here
                [&](auto& ext) { return FileTypeData{ext, &cliFileType}; }));
                ^
1 error generated.
make[1]: *** [derived/x86_64-darwin-opt-3rd/obj/CommandLineParser.cc.o] Error 1
make: *** [staticbindist] Error 2

**Comment by m9710797** [comment]
I can reproduce it when building with clang/libc++.
I think I introduced this regression in e2c059bdd29e when fixing a visual studio bug ... apparently the 'semiregular' stuff IS still needed (for libc++).
I'll try to fix it (hopefully tomorrow).

**Comment by m9710797** [comment]
Should be fixed now (libc++ compiles again for me on Linux).
Please re-open this ticket in case it isn't fixed for you.

**Comment by sdsnatcher73** [comment]
Confirmed, can build again
