### ISSUE TITLE
ProTracker music sounds bad on NukeYKT core

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1417]
As @TFHFony put it: 
> I was just trying Tyfoon Soft's Protracker on the new OpenMSX. MSX-Audio sounds fine, but MSX-Music  sounds borked.
> It  already starts with the intro music.
> But also stuff like the Fony Demodisk #2  sounds borked. 
> Doesn't matter if I use a European machine with FM-Pac  or for example a Turbo-R with MSX-Music built in
> Tried another game (Feedback) which seems to work fine.
> Example: https://download.file-hunter.com/X/borked.avi

To reproduce, load the attached savestate file and press F2 to play the music.
How it sounds normally: https://www.file-hunter.com/MSX/index.php?id=protracker (press F3 to load HAPPY and then F2 to play it).

To reproduce the save state:
1. start with turboR GT with the DMK image (see comment below with attachment)
2. press space in the title screen to get into the program
3. put the other disk image into the drive (PROTRACK.dsk)
4. press F3 to Load a song
5. select HAPPY
6. Press F2 to play the song

Then @grauw suggested to revert this hack: https://github.com/openMSX/openMSX/commit/44d29c951e04d8399ada7708a1f060879046b2ac I did that by commenting out the while-loop in src/sound/YM2413NukeYKT.cc:
```
diff --git a/src/sound/YM2413NukeYKT.cc b/src/sound/YM2413NukeYKT.cc
index 665b7f6b7..aaad99e8e 100644
--- a/src/sound/YM2413NukeYKT.cc
+++ b/src/sound/YM2413NukeYKT.cc
@@ -868,6 +868,7 @@ void YM2413::writePort(bool port, uint8_t value, int cycle_offset)
        //  faster this can result in artificial too-fast-access. We need to
        //  solve this properly, but for now this hack should suffice.
 
+/*
        while (unlikely(cycle_offset < allowed_offset)) {
                float d = 0.0f;
                float* dummy[9 + 5] = {
@@ -880,6 +881,7 @@ void YM2413::writePort(bool port, uint8_t value, int cycle_offset)
        // after data-port access. Divide by 4 to translate to our 18-step
        // timescale.
        allowed_offset = ((port ? 84 : 12) / 4) + cycle_offset;
+       */
 
        writes[cycle_offset] = {port, value};
        if (port && (write_address == 0xf)) {
```
That actually fixes the issue... (and breaks full throttle with NukeYKT) so the hack is not good enough, apparently.

He also wrote: 
> If that’s it, I think Bengalack might’ve run into it as well here https://www.msx.org/forum/msx-talk/openmsx/ym2413-wait-states-emulation-in-openmsx-17
[happy.oms.zip](https://github.com/openMSX/openMSX/files/8682069/happy.oms.zip)

**Comment by grauw** [comment]
See https://github.com/openMSX/openMSX/issues/935 for prior discussion on potential solutions.

Quick TLDR, the possible solutions were:

1. Disable the hack when running at 100% speed.
2. Remove the hack and let the audio buffer skip at non-100% speeds instead ("easy").
3. Apply pitch-preserving resampling (complex).

Option 3 is the ideal but complex, option 1 was favoured as a compromise for that reason (but not implemented yet).

**Comment by TFHFony** [comment]
Aha, good to find this issue here. I noticed it when making some recordings of some Pro Tracker songs I made in the past.
In old versions of OpenMSX it worked fine, but I tested this ages ago, so I can't give you version number.

**Comment by grauw** [comment]
Attaching the demonstrations;

1. Recording by TFHFony of it sounding bad: [borked.avi.zip](https://github.com/openMSX/openMSX/files/8682151/borked.avi.zip)
2. Recording by Quibus of it sounding good: [happy.avi.zip](https://github.com/openMSX/openMSX/files/8682150/happy.avi.zip)

The latter is after reverting the 44d29c9 hack.

**Comment by MBilderbeek** [comment]
Also adding 2 disk images of ProTracker, at least one of which is probably required by the savestate.
[PROTRACK.dsk.gz](https://github.com/openMSX/openMSX/files/8682730/PROTRACK.dsk.gz) (was originally not gzipped)
[Pro Tracker 1.0 (1992)(Tyfoon Software)(DMK).zip](https://github.com/openMSX/openMSX/files/8682731/Pro.Tracker.1.0.1992.Tyfoon.Software.DMK.zip)

**Comment by MBilderbeek** [comment]
Problem fixed by that commit, as confirmed by @TFHFony .
