### ISSUE TITLE
RAM in Popolon Sound Cartridge extensions not cleared on power cycle

### ISSUE THREAD

**Issue by sdsnatcher73** [openMSX/openMSX#1418]
I found that when using Popolon Sound Cartridge in openMSX the RAM of the sound cartridge is not cleared when issueing "set power off" followed by "set power on". This probably effects the Snatcher and SD Snatcher extensions as well but is possibly more widespread (I did not do any further testing) in e.g. MegaRAM, RAM carts etc.

**Comment by MBilderbeek** [comment]
Looks like we forgot to clear the RAM of this device. Would probably make sense to implement this. Thanks for the report :)

**Comment by MBilderbeek** [comment]
@sdsnatcher73 Can you help to provide a good testcase to test the fix?

**Comment by MBilderbeek** [comment]
Proposed patch:

```
diff --git a/src/sound/MSXSCCPlusCart.cc b/src/sound/MSXSCCPlusCart.cc
index de2012b7f..b07b5f84b 100644
--- a/src/sound/MSXSCCPlusCart.cc
+++ b/src/sound/MSXSCCPlusCart.cc
@@ -89,6 +89,7 @@ MSXSCCPlusCart::MSXSCCPlusCart(const DeviceConfig& config)
 void MSXSCCPlusCart::powerUp(EmuTime::param time)
 {
        scc.powerUp(time);
+       ram.clear();
        reset(time);
 }
```

**Comment by MBilderbeek** [comment]
@sdsnatcher73 As the fix is trivial, I already pushed it... but please help us test the fix.
