### ISSUE TITLE
Cross-compiled M1 build (on amd64 host) doesn't work on M1 Mac

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1430]
As @sndpl wrote: 
> this build doesn't work on my M1, it gives: “openMSX.app” is damaged and can’t be opened. You should eject the disk image."

I could find something similar here: https://developer.apple.com/forums/thread/692774

When building the same version on his M1, @sndpl found the dmg was working fine.

**Comment by mthuurne** [comment]
For some context: both the x86-64 and the aarch64 DMG were built with GitHub Actions, on a macos x86-64 VM.

The error message is weird: why does it talk about both the `.app` folder and the disk image? Those are in two separate layers of the OS.

Does the error message change or go away when `openMSX.app` is copied from the image to the hard drive?

Does `xattr -c` (removing quarantine) solve the issue?

Does it help if we add 64-bit ARM in `LSMinimumSystemVersionByArchitecture` in the `Info.plist`?

**Comment by MBilderbeek** [comment]
The same issue also occurred when @grauw built the 18.0 release on his x86 mac. The cross-compiled binary for M1 showed the same symptom on @sndpl 's M1 mac.

**Comment by MBilderbeek** [comment]
About the Info.plist thing: on the native build on M1 hardware as done by @sndpl , that Info.plist file is identical and still it suddenly starts working, compared to the cross-compiled build.

**Comment by mthuurne** [comment]
> About the Info.plist thing: on the native build on M1 hardware as done by @sndpl , that Info.plist file is identical and still it suddenly starts working, compared to the cross-compiled build.

That's interesting. Was openMSX started from an `.app` folder though, or was the built executable started directly?

If it was an `.app` folder, are there any differences between that and the one from the Actions build, apart from the binary?

**Comment by grauw** [comment]
https://wiki.lazarus.freepascal.org/macOS_Big_Sur_changes_for_developers#Code_signing_-_Intel_vs_M1

> Code signing - Intel vs M1
>
> On Intel systems running Big Sur very little is required to be signed except for kernel and system extensions and related code which require special approval from Apple.
>
> The situation is different on M1 Apple Silicon (aarch64) systems running Big Sur. There are a few situations to consider:
>
> * Intel code running under Rosetta 2 - this does not need to be signed for practical reasons (ie the code is translated into aarch64 code for the M1 and so any signature for the Intel code would of course be invalid when applied to the aarch64 code).
>
> * Native M1 aarch64 code will be blocked from execution unless a valid signature is attached. This signature can be as simple as an ad hoc code signature that doesn’t bear any actual identity from the secret half of an asymmetric key pair (it’s simply an unauthenticated measurement of the binary). The reason for this requirement is not to enable conventional code signature checks, but so that the executable code has a cdhash (code directory hash), which is used when macOS checks code before running it to verify that the contents of a binary have not changed since being code signed. If you don’t have an Apple developer signing certificate, an ad-hoc certificate generated on your Mac is quite sufficient. For those without developer accounts, Xcode now defaults to applying ad-hoc signing to its projects. As there is no requirement for an identity, and therefore any certificate to prove that identity, anyone can sign an application to run locally.
>
> * Universal binaries that include both Intel code and native M1 aarch64 code will be blocked from execution unless a valid signature is attached.

**Comment by MBilderbeek** [comment]
@grauw wrote on IRC:
> If you deploy: 1) an unsigned binary to your endusers, they will NOT be able to execute the binary on an M1 Apple Silicon computer. Note, however, that if the binary was linked on an M1 Apple Silicon computer, the macOS linker will have ad hoc signed the binary for you.

This explains what we saw, i.e. that the M1 built binary (by @sndpl) does work on the M1 silicon.

He also wrote:
> For manual ad hoc code signing of an application bundle (note that a dash is using for the signing identity after the -s argument): > codesign --force --deep -s - MyApp.app

Perhaps we can put this in the build-steps somehow?

**Comment by mthuurne** [comment]
It would have to be inserted after populating the `.app` folder and before creating the `.dmg` image.

So in `build/package-darwin/app.mk`, add a phony `signed-app` target which depends on `app` and then signs it. Finally make `bindist` depend on `signed-app` instead of `app`.

**Comment by grauw** [comment]
I am getting this complaint when I try it:

```
openMSX.app: unsealed contents present in the bundle root
```

So that needs to be investigated a bit further. I can’t get it to say which contents specifically even with the `--verbose` flag.

p.s. On the aarch64 cross-compile, it additionally says:

```
openMSX.app: replacing existing signature
```

So it seems even on a cross compile some kind of signature had been added.

**Comment by gilbertfrancois** [comment]
@grauw Please look at PR #1457. I think I have solved this issue.

**Comment by MBilderbeek** [comment]
@grauw can you confirm this has been fixed?

**Comment by grauw** [comment]
Yes should be, GitHub Actions builds are signed now, thanks to Joost I believe.
