### ISSUE TITLE
Will you port this good active msx emulator for RetroArch libretro?

### ISSUE THREAD

**Issue by AngelofMe** [openMSX/openMSX#1435]
I installed openMSX 1.15.0 android github stable version
i don't like that
it's inactive
https://github.com/openMSX/openMSX/issues/285
i think it's a good idea
why not?

**Comment by MBilderbeek** [comment]
What's the added value of this ticket compared to the #285 you mentioned?

Anyway, help to port to libretro is welcome.

Op za 2 jul. 2022 12:16 schreef AngelofMe ***@***.***>:

**Comment by MBilderbeek** [comment]
For now, I'm closing this as duplicate of #285 . Feel free to add more information to that issue there.
