### ISSUE TITLE
Does it support these ColecoVision & SG-1000 games?

### ISSUE THREAD

**Issue by AngelofMe** [openMSX/openMSX#1438]
ColecoVision
[drhelius/Gearcoleco#20](https://github.com/drhelius/Gearcoleco/issues/20)

some SG-1000 DahJee(大者) adapter games
Yie Ar Kung-Fu II (Taiwan) (Unl)
King's Valley (Taiwan) (Unl)

**Comment by MBilderbeek** [comment]
Why don't you just try them?

**Comment by AngelofMe** [comment]
i only have one Android device

**Comment by AngelofMe** [comment]
openMSX 18.0 doesn't support Android

**Comment by MBilderbeek** [comment]
So, try on a Windows, Mac or Linux PC?

Op zo 10 jul. 2022 03:47 schreef AngelofMe ***@***.***>:

**Comment by MBilderbeek** [comment]
We're interested in reports of not-working games that do work on real hardware. But we're not interested in requests to try certain games, so closing this issue.
