### ISSUE TITLE
Request: Automatic (or easier) IPS soft patching

### ISSUE THREAD

**Issue by ryz** [openMSX/openMSX#1440]
Hello, I've been tinkering a lot with openMSX in the last few days and it's very flexible. I was positively surprised to see that soft patching is a thing, kudos for that. 

I think the usability of soft patching could be improved though and I see a few options:
- Automatically apply soft patches if the IPS patch is in the same directory as the cartridge/disk, e.g. `game.dsk` and `game.ips`. I think this the best solution from a user perspective. (This approach is similar to software like RetroArch/LibRetro).
- Allow for selecting a IPS patch via the OSD menu. I use the OSD menu a lot because it's quick to select software in directories outside of openMSX's home directory, which brings me to my last point..
- Allow for properly setting a custom "file pool" in an arbitrary location (Maybe that is already possible, but the documentation is recommending against it), as this would make navigating to a path with the ROM/IPS file much faster. I personally don't use user directories at all, as I keep most of my files in the cloud synced on different drives (example: "D:\Cloud\games\emulation\roms\Microsoft_MSX2_Disks", specifying this per hand on the console for both the rom and the ips file is quite tedious).
   - (I'm inclined to open another issue for that, but I don't want to spam the issue tracker :) Let me know if I should.)

Thanks again!

**Comment by MBilderbeek** [comment]
Hi,

Thanks for the feedback.

As for your points:
* Automatically applying patches is a bit tricky. If you would want to not apply it, you'd have to move the file out of the way. Not very comfortable either, I'd say.
* This is something I'd like to think about. Perhaps add an IPS patch option in the menu that also shows '[eject]' for each media slot. Do you have some ideas on where it should be placed and how it would work?
* It's good to put separate issues into separate tickets in the tracker. This sounds like a different issue, as it has not much to do with IPS patches.

**Comment by MBilderbeek** [comment]
@ryz I implemented a basic IPS functionality for ROM images in the OSD menu. If it's good enough, perhaps we can also add it for disk images. I opted for the suggestion you made in the 2nd bullet.

**Comment by MBilderbeek** [comment]
@ryz Your reply, please. If I don't hear any response, I guess things are good enough for now and I'll close the ticket.
