### ISSUE TITLE
Linux - SDLGL-PP renderer not available in 18.0

### ISSUE THREAD

**Issue by pjagiello** [openMSX/openMSX#1442]
Hi,
I noticed that in 18.0 on Linux, the build seems to no longer include SDLGL-PP renderer. I built things effectively from source (an AUR package that basically calls "make") and the build process seems to show "GL renderer: yes" (and I do have OpenGL and GLEW installed), nevertheless, Catapult in 18.0 doesn't show the SDLGL-PP renderer anymore as one of the available options. I also tried to switch renderers with this command from the manual, didn't work (no such renderer):
https://openmsx.org/manual/commands.html#renderer

On the exact same machine, compiling 17.0 from sources results in the SDLGL-PP renderer being available and working correctly.
I'm pretty sure on 18.0 I'm getting the old SDL renderer as well because both in 17.0 and 18.0 it has a weird behaviour where scaling by 4x doesn't work (it has the same size as scaling 3x), and fullscreen doesn't center - this is what led me to notice that the renderer is missing in the first place.

So all of this leads me to believe SDLGL-PP renderer just didn't make it into my build of 18.0 (while in 17.0 it works), and I couldn't figure out from the documentation how to make it work.

Any suggestions for what I might be doing wrong, or maybe some bug in the build files?

**Comment by pjagiello** [comment]
... well seemingly randomly it worked after I built it the 3rd time but not sure what fixed it. I reinstalled GLEW in the meantime (to the exact same version) and tried deleting settings.xml but I'm not sure which would fix it and why... Can't reproduce it now.

EDIT: this is what --version shows now, sadly I didn't have the idea to run this when it didn't work:
```
$ openmsx --version
openMSX 18.0
flavour: opt
components: ALSAMIDI CORE GL LASERDISC
```

**Comment by MBilderbeek** [comment]
Is it possible the build was partial when it didn't work, a remainder of a
build without GL support?
Perhaps simply a full fresh build solved the issue?

At least settings.xml has nothing to do with the availability of renderers.

Op za 13 aug. 2022 22:03 schreef Piotr Jagiełło ***@***.***>:

**Comment by pjagiello** [comment]
I think it's possible I interrupted this build at some point and then tried again later, but at this point I don't think there is a way to tell. If you can't/don't want to reproduce it you can probably close the issue...

**Comment by pjagiello** [comment]
Okay, actually I can piece together what happened and you're right - since I used an AUR helper I have a log when I built what, and my first build of openmsx happened before I installed GLEW - I since retriggered the build but it probably used cached files from that first build.
