### ISSUE TITLE
more machines

### ISSUE THREAD

**Issue by soundsnow** [openMSX/openMSX#1447]
[machines](https://github.com/Rakashazi/emu-ex-plus-alpha/files/9603692/MSX-SVI-ColecoVision-SG1000.blueMSX.zip)

**Comment by MBilderbeek** [comment]
We are aware of the blueMSX configurations. But they're not openMSX configurations. But more specifically: many of these were not checked or dumped in such a way that we think it's accurate or complete for our standards. (They lack information needed for openMSX confinguration anyway). So, we cannot really use them directly.
