### ISSUE TITLE
Incorrect Ninja Tap emulation

### ISSUE THREAD

**Issue by aoineko-fr** [openMSX/openMSX#1451]
I added Ninja Tap driver from DM System 2 to MSXgl (my C game lib) and if [the sample program](https://github.com/aoineko-fr/MSXgl/raw/main/projects/samples/emul/rom/s_ntap.rom)  works just fine on real hardware, it don't work with the Ninja Tap device emulation in OpenMSX.
Is this a known issue? Is the emulation problem limited to detection? Is the reading of data supposed to work in OpenMSX?

**Comment by MBilderbeek** [comment]
It is supposed to work. Perhaps it broke down at some point...

**Comment by MBilderbeek** [comment]
@aoineko-fr Looks like @m9710797 got it fixed via commits 75aec52851de70000eaaf2c26e1277a63c26955c and f01ba7f437221ed438c11a0f18815a69dc109e91... latest development build should show that. Can you confirm?

**Comment by aoineko-fr** [comment]
Everything seems to work fine with the latest version (openmsx-18.0-96-ga075c3511c) but I can't test the case of two Ninja Tap connected because OpenMSX don't allow me to connect a Ninja Tap in each port.

**Comment by MBilderbeek** [comment]
@aoineko-fr OK, thanks. If you think we should add support for a 2nd ninjatap, please make new issue and perhaps you could then also add how you would think it must work from a user point of view.

**Comment by aoineko-fr** [comment]
I can confirm that everything seem to works fine with OpenMSX 18.0-97.
