### ISSUE TITLE
IDE and Nextor 2.1.1

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#1455]
I just tested and the openMSX IDE interface works just fine with the [Nextor-2.1.1.SunriseIDE.ROM](https://github.com/Konamiman/Nextor/releases/tag/v2.1.1) .

Please add this ROM checksum to the ide.xml file so the Nextor can be easily used by default without having to edit this file. Currently, the openMSX IDE is stuck in the past with DOS2 ROMs only, while most of the real hw IDE users already upgraded them to use Nextor.

**Comment by MBilderbeek** [comment]
Do we need the 'emulators' version? If yes, why? :)
Which ROM image did you test with?

**Comment by MBilderbeek** [comment]
@Konamiman Can you explain?

**Comment by MBilderbeek** [comment]
When I use openMSX with the latest non-emulator Sunrise IDE ROM file I get these warnings printed:
```
  unknown packet command 0x25
  unknown packet command 0x25
  unknown packet command 0x25
```
What is this packet command? Is it important?

EDIT: this is only printed for the IDE CD-ROM device. We can probably leave it out in a SunriseIDE_Nextor extension anyway. I guess the CD-ROM devices are less fully implemented than IDE devices.

**Comment by sdsnatcher** [comment]
0x25 is the ATAPI command RDCAPACITY. 

It’s used only to get the media size of ATAPI devices, so it’s not important for hard disk emulation.

It would be nice [openMSX implemented this for the CD-ROM and other types of removable discs](https://wiki.osdev.org/ATAPI#Detecting_a_Medium.27s_Capacity), though, since it’s a very simple command.

**Comment by MBilderbeek** [comment]
Your patch is most welcome!

**Comment by MBilderbeek** [comment]
I guess we can close this ticket. Enhancing the IDE CD-ROM support should be in another ticket.
