### ISSUE TITLE
Setting the "message_callback" setting to suppress OSD messages isn't persisting

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1462]
Same for the invalid PSG directions callback.

The code for these settings doesn't have a "DONT_SAVE" tag, so I guess it should be saved.
I set it to empty string to test, but also setting it to something else and doing `save_settings`, the original comes back.

**Comment by mthuurne** [comment]
I think there are two separate questions here:
1. Why aren't these settings that lack the `DONT_SAVE` flag saved currently?
2. Do we want them to be saved?

Question 1 might point to a bug or at least to hard to understand behavior in the code.

Regarding question 2, I'm not sure they should be saved. What reason is there to override them? If someone is making a customized UI for example, the override should only be present when the rest of that UI is active. If someone doesn't want to see a particular message, then what we need is a way to disable that message, not a way to suppress all messages, since the same user might be interested in other messages.

**Comment by MBilderbeek** [comment]
I discovered this issue in the use case that the user wanted to suppress
all messages on the OSD, as it interfered with his streaming activity.
Note that we should check whether all messages are sent with the message
proc and not some directly with osd::display_message to make this work. An
example the user mentioned is the screenshot message.

Op zo 20 nov. 2022 22:39 schreef Maarten ter Huurne <
***@***.***>:

**Comment by m9710797** [comment]
I did some research ...
* The settings ARE correctly saved and restored.
* But on startup the script callbackprocs.tcl will unconditionally overwrite the value of the setting.

In other words:
* The openMSX core works fine.
* But the scripting around it makes the settings basically useless (i mean saving/restoring the value of the setting).

**Comment by MBilderbeek** [comment]
So, what shall we do? Remove the 'hard' set command from callbackprocs.tcl and make the assigned proc there the default value? (And if necessary make the code able to handle an unset setting?)

**Comment by m9710797** [comment]
I'm not sure. But I kind of agree with @mthuurne's 2nd point that maybe these settings should not be saved:
* Regular users might change them accidentally and then there's no easy way (as in easily discoverable) to recover from this.
* Power users can add a startup script to change the setting (caveat: I haven't tested this).

Again, I'm not sure. But IF this is what we want, then today we kind of already have the effect of a non-saved setting (but the code could use some cleanup).

**Comment by MBilderbeek** [comment]
Consider the use case: an novice user wants to disable the message display
of these callbacks. What must he do to achieve this? What is reasonable? A
setting seems reasonable. Editing a script does not seem so. Any other ways?

Op za 3 dec. 2022 09:25 schreef Wouter Vermaelen ***@***.***>:

**Comment by m9710797** [comment]
I have no strong opinion. Feel free to change if you think that's better.

**Comment by MBilderbeek** [comment]
I am not sure what to change exactly. What are the implementation options?

Op za 3 dec. 2022 11:09 schreef Wouter Vermaelen ***@***.***>:

**Comment by MBilderbeek** [comment]
There are several callbacks each with their own default proc. Some are hardcodedly set in `callbackprocs.tcl`, some are just commented out there. So, apparently the ones that are set are the ones we would like to have enabled by default.

Proposal is to set the defaults of these individual settings to actual proc names (currently defaults are empty string) and let the settings system handle the rest.
But that's for each individual callback.

That would work, but is there also something we should do to let a user disable the full message display? Actually, in callbackprocs.tcl there is also one for this, called `message_callback`.  This one could also simply be handled as described above to globally shut up message display on the OSD. For this, we could make the default value of this setting `default_message_callback` and let that one point to `osd::display_message`.

But I feel not hardcodedly setting all these other callbacks is also a good idea. Use the same mechanism there as well?

**Comment by MBilderbeek** [comment]
Fixed with 8bf380938dd24c3be030afff0c0a6736736a4a6b.
