### ISSUE TITLE
Dooly mapper broken (it seems)

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1463]
When I tried to fix a crash when the ROM used with the Dooly mapper is < 32kB (e.g. 16kB), I noticed that the game wasn't running at all. Not even when I restored the code to the current state in master. Also in openMSX 18.0 the game isn't starting up when using its mapper... (e.g. via the ROM database).

Mapper broke along the way?

**Comment by m9710797** [comment]
This isn't a regression. It never worked on anything but turbor(?) machines. (Any machine that last wrote a 0 to the mapper).
I "fixed" it based on some educated *guesses*. See commit 2e54f5d7051900e759427d81a5b76406fed29fa8 for details.
