### ISSUE TITLE
Philips VY-0010 emulation not working correctly (mostly when formatting?)

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1468]
1. Start emulation of e.g. a Philips VG 8020 with the VY-0010 disk drive.
2. Create a 360kB disk image with diskmanipulator and insert it
3. Test:
    a) FILES: File not found -> OK
    b) Type a small basic program and saving it. Ok -> OK
    c) FILES: shows the just saved file -> OK
    d) Loading this program back: Ok -> OK
    e) CALL FORMAT: "Disk error" -> NOK

Discovered this when trying to emulate the JVC-HC-F303, which has an identical disk ROM.

Tested with the disk ROM that also has a `_GETVER` and `_VICTOR` command.

**Comment by MBilderbeek** [comment]
Here's some testing results by @m9710797 which are not 100% consistent with my findings (in Dutch):

> Het SAVE en FILES commando lijkt correct uit te voeren. Maar mij lukt het toch niet om daarna het BASIC programma terug te LOADen.
>
> Het BASIC FORMAT commando stopt uiteindelijk met een error. Maar als ik logging toevoeg dan lijken de WD2793 format commandos (voor 80 tracks) wel correct te zijn. Mogelijk gaat er iets fout achteraf bij het schrijven van boot/FAT/dir-sectors?
> 
> Bij het opstarten zie ik onverwacht gedrag:
> Voor drive A:
> 5x step-in commando, gevolgd door restore (=seek to track 0) command. Dit werkt volledig zoals verwacht.
> Daarna voor drive B (maar interface heeft maar 1 drive geconnecteerd):
> 5x step-in, gevolgd door restore, maar dat laatste commando triggert een timeout.
> Dit lijkt op een drive-A/B presence-test. Maar ik zie niet onmiddellijk wat precies de test nu doet slagen. Ik vermoed dat er daar ergens nog een detail fout geemuleerd wordt??

Disassembly of this disk ROM can be found here: https://sourceforge.net/p/msxsyssrc/git/ci/master/tree/diskdrvs/vy0010/driver.mac

**Comment by zeilemaker54** [comment]
Is the TYPE1 bit implemented in the hardware emulation ? This bit indicates single or double sided drive

**Comment by m9710797** [comment]
Probably not. Can you describe this in more detail? Or point me to some documentation? Thanks.

**Comment by zeilemaker54** [comment]
Suggested code change in PhilipsFDC.cc
```


case 0x3FFF: {
		// Drive control IRQ and DRQ lines are not connected to Z80
		// interrupt request
		// bit 7: !dtrq
		// bit 6: !intrq
		// bit 5: !type1 (vy0010/fc303)
		// bit 4: !type0 (vy0010/fc303)
		// TODO check other bits !!
		byte value = 0xF0;
```

**Comment by zeilemaker54** [comment]
the type1 bit was designed to indicated double sided drive (PIN 2 of the FDD interface), but was never used. So it reads always 1. But the DSKFMT routine of the ROM does use this bit to format single of double sided format,
there is also a type0 bit (PIN 1 of the FDD interface), but it has no reference in the disk driver code.
You can view the type0/type1 hardware implementation in the service manual of the VY0010.

**Comment by MBilderbeek** [comment]
Strange that that bit is used to decide single or double sided... the documentation of the generic pinout says Low/Hi density select... maybe Philips used it for something else? Or it was different before High Density drives were invented?

That type0 bit is even stranger. The documentation of the 34-pin FDD cable doesn't even specify it... but yeah, the bit is documented in the VY-0010 service manual. I couldn't find it properly documented though.

Do you know of other disk ROMs that care about that 'type1' bit? I.e. if we hardcode it to 1, would it possibly break something? E.g. the Sony drives are emulated with the same class... at least the Sony HBD-50 service manual says only the IRQ bits are used (bit 6-7), so hopefully it's only testing these...?

**Comment by MBilderbeek** [comment]
I've tested with a value of 0xF0 and a value of 0xE0, but with both I still cannot format disks with the VY-0010...

**Comment by zeilemaker54** [comment]
May be we first have to determine where the format routine is failing.
Does it reach breakpoint at 0x7A3D (switch to side 1) ? It should not, because it is a single sided drive
Does it reach breakpoint at 0x7A40 (physical format of tracks complete) ?

May be it is possible to trace the commands to the FDC ?

**Comment by zeilemaker54** [comment]
> Strange that that bit is used to decide single or double sided... the documentation of the generic pinout says Low/Hi density select... maybe Philips used it for something else? Or it was different before High Density drives were invented?
> 
> That type0 bit is even stranger. The documentation of the 34-pin FDD cable doesn't even specify it... but yeah, the bit is documented in the VY-0010 service manual. I couldn't find it properly documented though.
> 
> Do you know of other disk ROMs that care about that 'type1' bit? I.e. if we hardcode it to 1, would it possibly break something? E.g. the Sony drives are emulated with the same class... at least the Sony HBD-50 service manual says only the IRQ bits are used (bit 6-7), so hopefully it's only testing these...?

TYPE0 and TYPE1 (PIN1 and PIN2) are not part of any FDD interface standard as far as I know. Other MSX FDC interface implementations do not use b5 and b4 (or any other bits) of 0x7FFF. So hardcoding b5 and b4 to 1 will not break anything. Even further, b3-b0 should be a 1 as well because they are not connected to the databus, meaning they would be pulled up to a logical 1.

**Comment by zeilemaker54** [comment]
Did some test with the orginal OpenMSX 18.0, so with wrong TYPE1 readback, and it is indeed trying to format the disk as double sided disk (inserted with a 720KB image). The format routine first formats all 80 tracks on side 0, with no errors. But when the routine selects side 1 and tries to format track 0, the FDC write track returns 80H in the status register, meaning not ready. May be this helps. I used a breakpoint at 0x79F5

**Comment by MBilderbeek** [comment]
OK, I made a mistake in my test. Changing the 0xC0 in 0xFF does fix the formatting indeed. But I think I changed it in peekMem and not in readMem... oops.

**Comment by MBilderbeek** [comment]
@m9710797 please review.
