### ISSUE TITLE
FS-A1GT running MuPlay, broken graphics

### ISSUE THREAD

**Issue by denjhang** [openMSX/openMSX#1469]
Here is a sample disk, enter muplay after booting, you will get a broken software interface,
[muplay.zip](https://github.com/openMSX/openMSX/files/10297995/muplay.zip)

**Comment by Vampier** [comment]
check the integrity of your disk image, one easy way to check is to write the disk image to a real disk and try it on a real MSX - also it would be nice to have some extra information to make debugging easier - the music plays fine here only the interface looks corrupt.

![image](https://user-images.githubusercontent.com/12684428/209421859-89a9d909-9649-4581-a1da-7f2d1f6b0239.png)

**Comment by Vampier** [comment]
screenshot without noise and scanlines for clarity how it really looks: 
![image](https://user-images.githubusercontent.com/12684428/209421945-7657fab8-a0a8-48da-8ec1-82a574638583.png)

**Comment by MBilderbeek** [comment]
I can reproduce the issue with your disk. However, when I download the program from https://github.com/K-Sakanoshita/MuPlay I could run MuPlay 2.61 without the corruption. I haven't found out yet what the difference is exactly.

**Comment by MBilderbeek** [comment]
![muplay](https://user-images.githubusercontent.com/12675978/209588485-012e0e87-4de6-497d-92ef-e42c0a507efc.png)
This is your disk with the files overwritten from that github site... that one works for me. Still need to find out what is different (muplay.com seems identical).
[muplay_2.zip](https://github.com/openMSX/openMSX/files/10304994/muplay_2.zip)

**Comment by MBilderbeek** [comment]
OK, the missing part is MUPLAY.BIN. That file probably contains graphics data or so and there is no error if it's missing. But when I add that file, your disk starts working. I'm pretty sure the same will happen on a real MSXturboR. Can you verify, @denjhang ?

**Comment by denjhang** [comment]
I determined it was my low-level mistake, I missed MuPLAY.bin
