### ISSUE TITLE
Fix compiling with GCC 13

### ISSUE THREAD

**Issue by musuruan** [openMSX/openMSX#1487]
Hi. I had to include <cstdint> in src/utils/hash_set.hh to be able to compile openMSX v18.0 under GCC 13:
https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes

diff -durN openmsx-18.0.orig/src/utils/hash_set.hh openmsx-18.0/src/utils/hash_set.hh
--- openmsx-18.0.orig/src/utils/hash_set.hh	2022-06-12 15:53:09.000000000 +0200
+++ openmsx-18.0/src/utils/hash_set.hh	2023-02-04 13:36:45.464895318 +0100
@@ -11,6 +11,7 @@
 #include "xrange.hh"
 #include <cassert>
 #include <cstdlib>
+#include <cstdint>
 #include <functional>
 #include <initializer_list>
 #include <iterator>

**Comment by m9710797** [comment]
Thanks for reporting! I've pushed a fix.
(Your diff wasn't readable, but it wasn't too difficult to figure out).
