### ISSUE TITLE
realfun3 missing vocals

### ISSUE THREAD

**Issue by denjhang** [openMSX/openMSX#1490]
[realfun3_hunt.zip](https://github.com/openMSX/openMSX/files/10704978/realfun3_hunt.zip)
I use the extension to run:
v9990, 4mb ram, slotexp, scc+.Found that there is no sound when playing music.
There is also a webmsx version here, it works fine there.
https://www.file-hunter.com/Homebrew/index.php?id=realfun3

**Comment by denjhang** [comment]
Finally there is sound, I found out that I must use the following extensions:
MegaFlashROM SCC+SD,
Slotexplander,
SN76489,
4MB,
SCC,
SCC+
Video9990

**Comment by denjhang** [comment]
https://www.youtube.com/watch?v=JWkUhC7vnHw
When I play hunt, the vocal on scc channel 1 is completely gone.But it is normal in the youtube video.

**Comment by MBilderbeek** [comment]
I get sound using Boosted MSXturboR with IDE. I'm sure you don't need all these extensions though.

Anyway, I don't know what the point is of this bug report. Did you try it on a real MSX? What was required there? 
I'm pretty sure that the author also uses openMSX to record his songs, so there's probably no bug in openMSX here....

**Comment by denjhang** [comment]
I'm sure it's not an openmsx problem.
