### ISSUE TITLE
 BMXL VDP command in OpenMSX differs from real hardware

### ISSUE THREAD

**Issue by pvmm** [openMSX/openMSX#1493]
I wrote a code that uses BMXL to copy from linear memory to coordinates on P1 mode (v9990). This is what I get on my SMX with the Power Graph:
![image](https://user-images.githubusercontent.com/7815819/224901857-36da9714-aecb-453e-953a-cd376c25379e.png)
The letter A blocks are layer A blocks created by using BMXL on both PGT and PNT. While letter B blocks are created by BMXL on PNT only.

And this is how openMSX renders it (exactly the same code):
![image](https://user-images.githubusercontent.com/7815819/224902547-f34a67ab-00d3-426b-bb21-c4875ffd0748.png)

explanation:
- BMXL on P1 mode misinterprets NX in openMSX. Because of how memory works in P1 mode, BMXL should be halved by each memory region (VRAM0 and VRAM1);
- Layer A is created on the PGT from two distinct memory regions (VRAM0 and VRAM1, 0x40000 bytes apart), but since NX is misinterpreted as having the wrong size, the image gets truncated;
- Both Layer A and B has orange blocks that are not visible on the real hardware, they are created just to fill empty space so we can see that BMXL is not doing exactly the same on OpenMSX.

[You can check the problem using bmxl.com in this zip (it requires the V9990 extension obviously).](https://github.com/pvmm/msx-dev/raw/main/experiments/bmxl.zip)

**Comment by m9710797** [comment]
Hi,

Thanks for this report. Unfortunately I don't fully understand it :(

The V9990 BMXL command for P1 mode is implemented in src/video/v9990/V9990CmdEngine.cc on line 1302. It's a templatized method: for P1 the 'Mode' template parameter is 'V9990CmdEngine::V9990P1' (so the behavior can be customized per mode).

Note that on line 1313 we do a 'vram.readVRAMBx()'. This mean we use interleaved VRAM addressing, even in P1 mode. To be honest I don't remember why I implemented it like that. I guess it must be based on tests, but I don't remember the details.

You say that in P1 mode NX must be halved. (As a quick test/hack) I added this statement on lines 1269 and 1327:
    if (cmdMode == 0) ANX /= 2;  // halve NX in P1 mode
But it only made things worse.

Probably I misunderstood your proposed solution. Can you explain again? Possibly try experimenting yourself with implementing the fix. If needed I can help of course.

Thanks.

Wouter

**Comment by pvmm** [comment]
Nevermind, I found the bug: 
![image](https://user-images.githubusercontent.com/7815819/225117495-1d853645-907d-4b9c-bb96-f360bc226066.png)

I used some sample code from Fusion-C/g9klib and it used a wrong BPP mode. One that openMSX does not implement. Maybe we can issue an optional warning when setting wrong screen mode arguments.

**Comment by m9710797** [comment]
Sure. Such a patch would be welcome :-)
I'll close this issue for now.

**Comment by MBilderbeek** [comment]
So, the effect of the wrong BPP is a wrong number of bytes getting copied, right? So, the BPP "mode register" (I don't know how it's in the V9990) is used to calculate the amount of bytes for the V9990, even in P-modes? Would that be reasonably easy to implement?
In other words, looks like the pitch is internally calculated by the BPP mode flag, whatever the other mode bits say?
