### ISSUE TITLE
custom USR Disk issue

### ISSUE THREAD

**Issue by pokemonfan6498** [openMSX/openMSX#1497]
i was playing XAK for msx2 but i ran into problem SRAM was inaccessible as well as user disk option i looked everywhere and couldn't find any option for making user disks

**Comment by MBilderbeek** [comment]
You can use any blank disk image or create one with this: https://openmsx.org/manual/diskmanipulator.html#create and then insert it in the drive when the game requests it.

**Comment by MBilderbeek** [comment]
As this doesn't seem to be an openMSX issue, but more a 'how to use' question, I'm closing it for now. Feel free to ask questions here, or more preferably on the openMSX forum on msx.org or on our Discord or IRC channels.
