### ISSUE TITLE
Hat buttons not working on non-xinput controllers (DS4, dualsense, switch pro)

### ISSUE THREAD

**Issue by Tartifless** [openMSX/openMSX#1503]
Hello,
It seems that in version 18.0 (latest available on github), hat events are not recorded properly for non-xinput gamepads.

I have tested with both dualsense & Switch Pro controller.

Note that these gamepads do not use "hat" in the SDL library, the d-pad is actually recorded in SDL library as buttons 11, 12, 13 and 14, and not as hat.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/BENOIT/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/BENOIT/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Hat up |  11
Hat right | 14
Hat down |12
Hat left |  13

</body>

</html>

**Comment by MBilderbeek** [comment]
Can you check whether it improved in the latest development build, which
got a newer version of SDL2 included.

Op do 20 apr. 2023 00:46 schreef Benoit S. ***@***.***>:

**Comment by Tartifless** [comment]
Hello,
I have tested with latest dev build and same behavior.

Here is my analysis:

This is the default joystick_config that is set when plugging the controller:
![image](https://user-images.githubusercontent.com/13442986/233346494-c6ff62db-4e83-40ba-a042-bebc7c9697c6.png)

As you can see: 
- all even buttons are mapped to A
- all odd buttons are mapped to B
- axis and hats are mapped to directions

The non-xinput controllers, with SDL, do not have "hats" in the SDL wrapper, the 4 D-PAD buttons are identified as buttons 11, 12, 13 and 14:
![image](https://user-images.githubusercontent.com/13442986/233347095-21b2fedc-fd21-45b6-9850-1806e626b704.png)

I have tried using the "dict set joystick1_config" to come to the following situation:
![image](https://user-images.githubusercontent.com/13442986/233347932-124a6af9-92b5-450a-9238-eed25da6ae0d.png)

But to no availability.

Here is how the controller works (tested with dualshock 4, Dualsense and Switch pro):
- Left analog stick correctly controls the directions
- Left and up D-PAD act as A & B
- Up and Down act as A & B
- A and B act correctly (reversed on Switch pro but this is normal as it is the nintendo layout)

It seems like openMSX code is forcing the "hat" value even for controllers that are not xInput.

**Comment by cmitu** [comment]
> It seems like openMSX code is forcing the "hat" value even for controllers that are not xInput.

I've seen the same behavior on Linux with a wired PS3 (Sixaxis/Dualshock3) controller.

The built-in mapping (axis/hats for directions, even buttons for A + odd buttons for B) is retained despite the explicit configuration of `joystick1_config` (via `bind` or `bind_default`).

I've seen that the built-in mapping is set through [code](https://github.com/openMSX/openMSX/blob/d5d687a3e36c0727bf988710157c939ddf4acfc5/src/input/Joystick.cc#L127). In my case the I'm using `bind_default` from a `.tcl` script linked to the user's `scripts` folder to add my custom mappings.

**Comment by Tartifless** [comment]
Hi,
I did not find how to use "bind" for joystick directions, documentation only writes about "dict" "set" or "append" for the generic buttons (directions & A & B).
Is it possible to simply use a bind line for these ?

I am already binding loads of hotkeys, so it would be no problem to additionnally bind 4 buttons.

Regards

**Comment by Tartifless** [comment]
> > It seems like openMSX code is forcing the "hat" value even for controllers that are not xInput.
> 
> I've seen the same behavior on Linux with a wired PS3 (Sixaxis/Dualshock3) controller.
> 
> The built-in mapping (axis/hats for directions, even buttons for A + odd buttons for B) is retained despite the explicit configuration of `joystick1_config` (via `bind` or `bind_default`).
> 
> I've seen that the built-in mapping is set through [code](https://github.com/openMSX/openMSX/blob/d5d687a3e36c0727bf988710157c939ddf4acfc5/src/input/Joystick.cc#L127). In my case the I'm using `bind_default` from a `.tcl` script linked to the user's `scripts` folder to add my custom mappings.

Hi, 
I am already binding a lot of keys so indeed it would not be a problem to "bind" them, but i was under the impression that default keys (directions, A & B) could not be used in "bind" commands but only in dict set / append commands.

Do you have an exemple ?

bind "joy1 button11 down ...... ?

**Comment by cmitu** [comment]
> Do you have an exemple ?

You're right, I'm using `dict lappend` for `joystick1_config` after clearing it, but I'm also using `bind` to map some buttons to F2/F3 + Start button to open/close the OSD Menu. Initially I was using `bind_default`, but during debugging I've changed it to use a simple `bind`.

Here's my joystick configuration part of my script:
``` tcl
proc auto_config_joypad { } {
    # clear existing joypad configuration
    dict for {btn binding} $::joystick1_config { dict set ::joystick1_config $btn {} }

    bind "joy1 button2 down" "keymatrixdown 6 0x40"
    bind "joy1 button2 up" "keymatrixup 6 0x40"
    bind "joy1 button3 down" "keymatrixdown 6 0x20"
    bind "joy1 button3 up" "keymatrixup 6 0x20"
    bind "joy1 button4 down" "keymatrixdown 6 0x80"
    bind "joy1 button4 up" "keymatrixup 6 0x80"
    bind "joy1 button5 down" "keymatrixdown 7 0x01"
    bind "joy1 button5 up" "keymatrixup 7 0x01"
    bind "joy1 button8 down" "toggle_osd_keyboard"
    bind "joy1 button9 down" "main_menu_toggle"
    bind "joy1 button9 down" -layer osd_menu "main_menu_close"
    bind "joy1 button14 down" -layer osd_menu { osd_menu::menu_action DOWN }
    dict lappend ::joystick1_config A button1
    dict lappend ::joystick1_config B button0
    dict lappend ::joystick1_config DOWN +axis1
    dict lappend ::joystick1_config DOWN button14
    dict lappend ::joystick1_config LEFT -axis0
    dict lappend ::joystick1_config LEFT button15
    dict lappend ::joystick1_config RIGHT +axis0
    dict lappend ::joystick1_config RIGHT button16
    dict lappend ::joystick1_config UP -axis1
    dict lappend ::joystick1_config UP button13
}
```

For completeness, I'm using a post-18.0 source build and SDL2 `2.26.3`.

**Comment by Tartifless** [comment]
> > Do you have an exemple ?
> 
> You're right, I'm using `dict lappend` for `joystick1_config` after clearing it, but I'm also using `bind` to map some buttons to F2/F3 + Start button to open/close the OSD Menu. Initially I was using `bind_default`, but during debugging I've changed it to use a simple `bind`.
> 
> Here's my joystick configuration part of my script:
> 
> ```tcl
> proc auto_config_joypad { } {
>     # clear existing joypad configuration
>     dict for {btn binding} $::joystick1_config { dict set ::joystick1_config $btn {} }
> 
>     bind "joy1 button2 down" "keymatrixdown 6 0x40"
>     bind "joy1 button2 up" "keymatrixup 6 0x40"
>     bind "joy1 button3 down" "keymatrixdown 6 0x20"
>     bind "joy1 button3 up" "keymatrixup 6 0x20"
>     bind "joy1 button4 down" "keymatrixdown 6 0x80"
>     bind "joy1 button4 up" "keymatrixup 6 0x80"
>     bind "joy1 button5 down" "keymatrixdown 7 0x01"
>     bind "joy1 button5 up" "keymatrixup 7 0x01"
>     bind "joy1 button8 down" "toggle_osd_keyboard"
>     bind "joy1 button9 down" "main_menu_toggle"
>     bind "joy1 button9 down" -layer osd_menu "main_menu_close"
>     bind "joy1 button14 down" -layer osd_menu { osd_menu::menu_action DOWN }
>     dict lappend ::joystick1_config A button1
>     dict lappend ::joystick1_config B button0
>     dict lappend ::joystick1_config DOWN +axis1
>     dict lappend ::joystick1_config DOWN button14
>     dict lappend ::joystick1_config LEFT -axis0
>     dict lappend ::joystick1_config LEFT button15
>     dict lappend ::joystick1_config RIGHT +axis0
>     dict lappend ::joystick1_config RIGHT button16
>     dict lappend ::joystick1_config UP -axis1
>     dict lappend ::joystick1_config UP button13
> }
> ```
> 
> For completeness, I'm using a post-18.0 source build and SDL2 `2.26.3`.

Hi,

Just tested that but no chance, my hats are always acting as A & B buttons.

Even after cleansing, my D-PAD still acts as A & B:
![image](https://user-images.githubusercontent.com/13442986/233426899-bb7a367b-e93f-42ea-9ae8-da1b4bc2da83.png)

**Comment by MBilderbeek** [comment]
> > It seems like openMSX code is forcing the "hat" value even for controllers that are not xInput.
> 
> I've seen the same behavior on Linux with a wired PS3 (Sixaxis/Dualshock3) controller.
> 
> The built-in mapping (axis/hats for directions, even buttons for A + odd buttons for B) is retained despite the explicit configuration of `joystick1_config` (via `bind` or `bind_default`).
> 
> I've seen that the built-in mapping is set through [code](https://github.com/openMSX/openMSX/blob/d5d687a3e36c0727bf988710157c939ddf4acfc5/src/input/Joystick.cc#L127). In my case the I'm using `bind_default` from a `.tcl` script linked to the user's `scripts` folder to add my custom mappings.

This is only the default. You can adjust the mapping most comfortably in the OSD menu under Misc Settings -> Host to MSX controller mapping... Please let me know how that goes for you.

**Comment by cmitu** [comment]
> This is only the default. You can adjust the mapping most comfortably in the OSD menu under Misc Settings -> Host to MSX controller mapping... Please let me know how that goes for you.

The mapping dialog doesn't let me map the buttons for Left/Right/Up/Down, I can only map one of the joysticks (the Dualshock 3 has 2 analog joysticks). It's probably because it only accepts Axis or Hat type inputs, while the controller reports them as Button inputs.

For reference [here](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony-PlayStation3-DualShock3-Controller-USB.cfg) is how the DS3 controller's inputs are set when connected via USB vs the [Dualshock 4](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony-PlayStation4-DualShock4-Controller-Bluetooth.cfg)'s inputs. Notice how the left/right/up/down are reported as buttons for the DS3, while being reported as HAT inputs on the DS4.

* DS3 config 
``` cfg filename="Dualshock 3"
...
input_up_btn = "13"
input_down_btn = "14"
input_left_btn = "15"
input_right_btn = "16"
...
```

* DualShock 4 config
 ```
 ... 
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
 ...
```` 

One more thing is the behavior in the OSD menu. After I map the A/B to _button 1_/_button0_ respectively, I would expect that by pressing _button1_ it would invoke the _A_ action (i.e. open the menu or activate the menu entry) and _button0_ would invoke the _B_ action (i.e. cancel or exit out of the menu), however the action are still reversed. _Button0_ always invokes the _A_ action and _Button1_ invokes the _B_ action, just like in the default built-in configuration.

During these tests I disabled my mapping script and only did the mapping from the OSD Menu.

LATER EDIT
Now, if I run my config mapping script as usual, on the DS3 the Left/Right/Up/Down are correctly recognized in the emulated machine, but when opening up the OSD Menu, the A and B actions are triggered as described above, including by the D-Pad buttons. The D-Pad buttons should scroll down/up in the OSD menus, but instead they trigger the A/B actions.

For testing the mapping in the emulated machine, I've used the `HIDTEST.COM` utility by FSR (which reports itself as _MSX HID Tester v3.1_).

**Comment by MBilderbeek** [comment]
You're right, it only allows hat/axis events to be mapped to directions and button events to buttons. These mappings are how the host input is mapped to the MSX joystick. It's not about control of the OSD menu, these are not configurable, see InputEventGenerator.cc:200 (and around).

**Comment by Tartifless** [comment]
> You're right, it only allows hat/axis events to be mapped to directions and button events to buttons. These mappings are how the host input is mapped to the MSX joystick. It's not about control of the OSD menu, these are not configurable, see InputEventGenerator.cc:200 (and around).

OK, so this means that most recent controllers won't play well with dpad.
Is left joystick the only way or can this be updated ?

**Comment by Tartifless** [comment]
> 

Ps4 controller is not recognized similarly between udev (your link) and sdl2, with sdl2 directions are buttons, not hats. 

Udev is so easy, I wish MS would not give us all these countless drivers (winmm, dinput, xinput, ...) and sdl2 would not be so buggy lately.

**Comment by cmitu** [comment]
> You're right, it only allows hat/axis events to be mapped to directions and button events to buttons. These mappings are how the host input is mapped to the MSX joystick.

Right. In the emulated machine, looks like my joystick mapping is working fine.

> It's not about control of the OSD menu, these are not configurable, see InputEventGenerator.cc:200 (and around).

I see now, after looking in the source file you mentioned. I was thinking that using the `osd_menu` binding layer they can be customized, since I managed to make the Start working (i.e. was bound to closing the menu).
In this case my issue is only with the OSD Menu and I apologize for hijacking the issue - @Tartifless seems to experience a different problem.

@Tartifless the binding commands I posted earlier do work for me in the emulated machine and the D-Pad works (even if the inputs are not Hat/Axis). For reference, this is the config I get for my PS3:

``` tcl
> set joystick1_config
LEFT {-axis0 button15} RIGHT {+axis0 button16} UP {-axis1 button13} DOWN {+axis1 button14} A button1 B button0
```

**Comment by MBilderbeek** [comment]
Please consider to file bug reports against SDL2 for not properly working input devices. There isn't much we can do about it in openMSX.

**Comment by Tartifless** [comment]
Hello,

Well this is not really a sdl2 issue, most sdl2 emulators are correctly mapping these gamepads (duckstation , pcsx2, cemu, mame, supermodel, rpcs3, dolphin, ares, libretro, mupen64...).

I wish I could read c as well as c#, maybe in a few months I'll ramp up on that one.

**Comment by MBilderbeek** [comment]
@Tartifless can you check whether this is working now, after we updated the used SDL2 a few times?

**Comment by Tartifless** [comment]
In India for 5 days, will check next week

**Comment by MBilderbeek** [comment]
Any updates, @Tartifless ?

**Comment by Tartifless** [comment]
Hello, still need some days, came back with an indian flue...

**Comment by Tartifless** [comment]
Ok, it seems to work since 19.1.
However with latest build versions the menu has been revamped, i cannot seem to navigate with gamepad in the latest dev builds interface.

**Comment by MBilderbeek** [comment]
OK, thanks. Yes, the current (new) GUI only works with mouse.  I made https://github.com/openMSX/openMSX/issues/1666 for that, but this was already known.
Will close this issue as solved. Thanks for retesting! And please keep the feedback coming.
