### ISSUE TITLE
3rd party theora-1.1.1 doesn't support aarch64 in config.guess

### ISSUE THREAD

**Issue by meesokim** [openMSX/openMSX#1506]
**config.guess** has no aarch64 related identification of architecture.

the following bold lines can make the compiling possible.

    arm*:Linux:*:*)
	echo ${UNAME_MACHINE}-unknown-linux-gnu
	exit 0 ;;
    **aarch64:Linux:*:*)
	echo ${UNAME_MACHINE}-unknown-linux-gnu
	exit 0 ;;**

**Comment by MBilderbeek** [comment]
Can you make a patch for the 3rdparty lib? By putting it in build/3rdparty/ as .diff file, it will be automatically applied. So, please make a PR with the file and it can be merged easily. Actually, we already have a patch for it there build/3rdparty/libtheora-1.1.1.diff - this file will have to be extended then.

**Comment by meesokim** [comment]
Here you are!

<code>
diff -ur libtheora-1.1.1.org/config.guess libtheora-1.1.1/config.guess
--- libtheora-1.1.1.org/config.guess	2023-05-08 17:32:54
+++ libtheora-1.1.1/config.guess	2023-05-08 17:34:22
@@ -792,6 +792,9 @@
     arm*:Linux:*:*)
 	echo ${UNAME_MACHINE}-unknown-linux-gnu
 	exit 0 ;;
+    aarch64:Linux:*:*)
+        echo ${UNAME_MACHINE}-unknown-linux-gnu
+        exit 0 ;;
     ia64:Linux:*:*)
 	echo ${UNAME_MACHINE}-unknown-linux-gnu
 	exit 0 ;;
diff -ur libtheora-1.1.1.org/configure libtheora-1.1.1/configure
--- libtheora-1.1.1.org/configure	2023-05-08 17:32:54
+++ libtheora-1.1.1/configure	2023-05-08 17:36:03
@@ -11863,7 +11863,7 @@
         case $host in
         *)
                 DEBUG="-g -Wall -Wno-parentheses -DDEBUG -D__NO_MATH_INLINES"
-                CFLAGS="-Wall -Wno-parentheses -O3 -fforce-addr -fomit-frame-pointer -finline-functions -funroll-loops"
+                CFLAGS="-Wall -Wno-parentheses -O3 -fomit-frame-pointer -finline-functions -funroll-loops"
                 PROFILE="-Wall -Wno-parentheses -pg -g -O3 -fno-inline-functions -DDEBUG";;
         esac
 fi
</code>

**Comment by MBilderbeek** [comment]
Thanks, integrated! I hope it works.
