### ISSUE TITLE
CAS 2400 bauds saving corruption except in ASCII format

### ISSUE THREAD

**Issue by 86Jer** [openMSX/openMSX#1510]
Hi all,

I'm new here and open a issue on the advice SDSnatcher on MRC forum.

[https://www.msx.org/forum/msx-talk/openmsx/bug-at-2400-bauds-saving-speed-0](url)

I discovered (at least on my PC) that setting the cassette speed to 2400 bauds gives erratic results on openMSX 18.
The attached file contains a package of 6 wav files saved with OpenMSX 18 : a BASIC program (10 PRINT"HELLO") saved in Tokenized BASIC and in ASCII FORMAT (both at 1200 and 2400 bauds speed) and a binary file containing memory data (previously filled with &HFF) from &HD000 to &HD050 (at 1200 and 2400 bauds too).

All the files are loading without any I/O error in openMSX and the 1200 bauds ones show the expected content.

However at 2400 bauds, only the ASCII file is correct !

Tokenized BASIC leads to a line 10 filled with junk and binary file shows that the &HFF data are randomly replaced by &HFE !!!

If the same process is used for the binary but with &H00, it's OK !
If the 1200 bauds wav files are speed up to reach 2400 bauds, it's OK too !

Is there a "random" or sync problem for the last data bit (1 coded as 0) at 2400 bauds setting ?

[2400baud_Bug.zip](https://github.com/openMSX/openMSX/files/11471971/2400baud_Bug.zip)

**Comment by MBilderbeek** [comment]
I can reproduce it with openMSX 18.0, but not with the latest development versions...

**Comment by 86Jer** [comment]
You're right latest versions fix the bug !
