### ISSUE TITLE
Pasteing clipboard after changing DirAsDisk on running instance.

### ISSUE THREAD

**Issue by EMLommers** [openMSX/openMSX#1516]
When changing the DirAsDisk on a running instance (menu upper left side ), and having data on clipboard or memory (data copy with CTRL-C), it will paste the data on the running machine, like  Input Text.
OpenMSX 18.0, Linux

**Comment by MBilderbeek** [comment]
I can't reproduce this... can you investigate what other factors might be relevant?

What I tried:
1. start openMSX 18.0 with a Sony HB-F1XDJ
2. put something (a text) on the clipboard
3. click the menu button
4. select the disk drive A item
5. browse to a dir on my /tmp/ for this test and insert it as disk
6. (nothing happens)
7. Repeat steps 3-5, but still nothing happens.

What am I doing wrong?

**Comment by EMLommers** [comment]
I think it is my doing, I tested and noticed I am clicking too much close to the middle of the touchpad.
And middle click is paste.

Close! Sorry!
