### ISSUE TITLE
[Feature] Detect presence of DirectX headers, component in buildsystem [sf#128]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#152]
**Reported by manuelbi on 2005-06-18 12:03 UTC**
Enhance the build files to check if DirectX headers are
available. If not, don't build with DirectX Sound
driver. In other words: make it a component like openGL
support.

**Comment by MBilderbeek** [comment]
The DirectX sound driver was removed in 831ff6c5712714a9b3f92000a0a529cfeb31b841 (2016), so this is obsolete.
