### ISSUE TITLE
First line not visible on MacOS (v 18.0.0)

### ISSUE THREAD

**Issue by rolandvans** [openMSX/openMSX#1523]
In the MacOS version, the first line of the vdp is not displayed.
The following test code should display a white line on y=0 and a red line on y=1, but only the red one is visible.
The top line is also missing in screen 0.
Screenshots from MacBook Air M1, OS version 13.4.1
[missing line in screen 5](https://i.imgur.com/gC53AVe.png)

the code:
[code to generate the image](https://i.imgur.com/1RcA5ac.png)

**Comment by MBilderbeek** [comment]
Are you using the TV-scaler? If yes, then it's a known issue of that scaler, see #1361 .

**Comment by rolandvans** [comment]
You are correct! It is the TV-scaler. This appears to be the default setting? Maybe use a different default to avoid this upon first use.

**Comment by MBilderbeek** [comment]
No, it's not the default. Default is `simple` scaler. Now we should find out how it got on `TV` on your system...
