### ISSUE TITLE
openmsx 19.0 build failures with macOS big_sur

### ISSUE THREAD

**Issue by chenrui333** [openMSX/openMSX#1530]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
In file included from src/CLIOption.cc:2:
In file included from src/MSXException.hh:4:
In file included from src/utils/strCat.hh:4:
In file included from src/utils/TemporaryString.hh:4:
In file included from src/utils/StringStorage.hh:4:
src/utils/ranges.hh:39:86: error: no type named 'identity' in namespace 'std'
template<typename ForwardRange, typename Compare = std::less<>, typename Proj = std::identity>
                                                                                ~~~~~^
src/utils/ranges.hh:114:98: error: no type named 'identity' in namespace 'std'
template<typename ForwardRange, typename T, typename Compare = std::less<>, typename Proj = std::identity>
                                                                                            ~~~~~^
src/utils/ranges.hh:123:98: error: no type named 'identity' in namespace 'std'
template<typename ForwardRange, typename T, typename Compare = std::less<>, typename Proj = std::identity>
                                                                                            ~~~~~^
src/utils/ranges.hh:137:98: error: no type named 'identity' in namespace 'std'
template<typename ForwardRange, typename T, typename Compare = std::less<>, typename Proj = std::identity>
                                                                                            ~~~~~^
src/utils/ranges.hh:342:32: error: no type named 'identity' in namespace 'std'
         typename Proj1 = std::identity, typename Proj2 = std::identity>
                          ~~~~~^
src/utils/ranges.hh:342:64: error: no type named 'identity' in namespace 'std'
         typename Proj1 = std::identity, typename Proj2 = std::identity>
                                                          ~~~~~^
src/utils/ranges.hh:360:32: error: no type named 'identity' in namespace 'std'
         typename Proj1 = std::identity, typename Proj2 = std::identity>
                          ~~~~~^
src/utils/ranges.hh:360:64: error: no type named 'identity' in namespace 'std'
         typename Proj1 = std::identity, typename Proj2 = std::identity>
                                                          ~~~~~^
src/utils/ranges.hh:379:52: error: no type named 'identity' in namespace 'std'
template<typename InputRange, typename Proj = std::identity>
                                              ~~~~~^
src/utils/ranges.hh:412:98: error: no type named 'identity' in namespace 'std'
template<typename ForwardRange, typename T, typename Compare = std::less<>, typename Proj = std::identity>
                                                                                            ~~~~~^
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5703614683/job/15456526027?pr=137602
relates to Homebrew/homebrew-core#137602

**Comment by m9710797** [comment]
Hi chenrui333,

It seems like your compiler doesn't recognize 'std::identity' yet. Which compiler are you using? And then in particular which version of the compiler?

Since you're using macOS, I'm assuming you're using clang? What does the command `clang --version` return?

To build openMSX you'll need at least clang version 14 (but higher is recommended). That is the 'official' clang version 14. On macOS the situation is a bit complicated because there's also an "Apple clang" which uses a different version numbering. Apple clang also lacks behind in functionality. If possible try to avoid Apple clang.

I'm not familiar with macOS. So I don't know how you should upgrade your clang compiler to the newest version. (Or how you should switch from Apple clang to the 'real' clang).

I hope this helps.

Wouter

**Comment by MBilderbeek** [comment]
We do know that it builds on GitHub on macOS on a system with these specs:
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
So, that's macOS 12 and I believe Big Sur is macOS 11.

From our git logs I see we upgraded to a  macOS 12 runner on June 14th 2022, to get a newer clang. That's shortly after our previous release.

Does the binary we provided work on your system? If yes, you can use that. If you really need to build openMSX on your system, you need a newer clang as Wouter already indicated. I also don't know what the best way to do that is. (Perhaps upgrade to macOS 12?)

Maybe @gilbertfrancois or @grauw can shed a light on this.

**Comment by gilbertfrancois** [comment]
Unfortunately, I cannot test on Big Sur myself. I have no computer with the old macOS version running. However. if the clang version is the only issue, you can easily install a higher version with brew. At the time of writing, the most recent llvm version on brew is 16, which can be installed with:

```sh
brew install llvm
```

Then, before compiling openMSX, set the compiler with:

```sh
export BREW_PREFIX=`brew --prefix`

export LDFLAGS="-L${BREW_PREFIX}/opt/llvm/lib"
export CPPFLAGS="-I${BREW_PREFIX}/opt/llvm/include"
export LDFLAGS="-L${BREW_PREFIX}/opt/llvm/lib/c++ -Wl,-rpath,${BREW_PREFIX}/opt/llvm/lib/c++"
export PATH="${BREW_PREFIX}/opt/llvm/bin:$PATH"
export CC="${BREW_PREFIX}/opt/llvm/bin/clang"
export CXX="${BREW_PREFIX}/opt/llvm/bin/clang++"
```

**Comment by MBilderbeek** [comment]
I'm assuming this issue is fixed with the suggestions of @gilbertfrancois . So closing.
