### ISSUE TITLE
Unknown mappertype: MegaFlashRomSccPlusSD

### ISSUE THREAD

**Issue by retrodeluxe** [openMSX/openMSX#1535]
Trying to use the MegaFlashROM_SCC+_SD extension in MacOS I get the error in the header

**Comment by MBilderbeek** [comment]
That is strange. Which openMSX version are you using? Output of `openmsx -v` is enough.

**Comment by MBilderbeek** [comment]
More importantly: it looks like your `MegaFlashROM_SCC+_SD.xml` doesn't match with the openmsx binary. As you can see in b8b2e9bca71609702fc4e19ae5b3402cda1db622 the mappertype was removed in 2017.

**Comment by retrodeluxe** [comment]
I updated from an older version indeed. But I used the installer for 19.0

I will remove the app folder entirely and reinstall to confirm that solves the problem.

**Comment by retrodeluxe** [comment]
ok, I removed the folder /Applications/openMSX.app entirely and reinstalled again, and I confirm I am getting the same problem. hmm maybe this is related to the .openMSX folder in the home directory?  do I have to clear it as well?

I am using the installer for macOS Apple 64bit

**Comment by retrodeluxe** [comment]
Yeah, I confirm that solves the problem.

I had to clear the extensions folder in the ~/.openMSX folder after updating.
