### ISSUE TITLE
[V19] Laserdisc support broken

### ISSUE THREAD

**Issue by jimten69** [openMSX/openMSX#1536]
Hello, since V19, Laserdisc ( Pioneer PX7 driver) does not work anymore. There is an error message "unknown stream in the ogv file" when trying to launch a laserdisc game :-(
Is it normal? If not can you fix it ?
Thanks for your help
Regards

**Comment by MBilderbeek** [comment]
You are correct, we will release an update soon to fix it. See 283b8814f2bf74668c0368e75161bb0e6cbe94e8
