### ISSUE TITLE
Sex Bomb Bunny flickering graphic

### ISSUE THREAD

**Issue by Anths2016** [openMSX/openMSX#1545]
Sex Bomb Bunny flickering graphic. I did not expect Openmsx to lose points to Bluemsx, which instead works correctly.

**Comment by Colpocorto** [comment]
That's essentially because the original programmer of Sex Bomb Bunny (someone who has a deep, I mean extremely deep knowledge of the VDP) was involved in the BlueMSX development.

**Comment by MBilderbeek** [comment]
This is a duplicate of #471 , so closing. Please continue discussion in that issue.
