### ISSUE TITLE
Detecting controller connection while openMSX is running

### ISSUE THREAD

**Issue by MuntKaicho** [openMSX/openMSX#1546]
Hot plugging a controller would be nice to have as a fallback in case the battery runs out or the user starts the emulator but forgets to start the controller first.

As it is now the only way for the emulator to see the controller is if it's on before launch, and if it gets disconnected at any point the only solution is to shut down and re-launch.

**Comment by m9710797** [comment]
This should work now. (As of Feb 10 already, but I forgot to react to this ticket.)
