### ISSUE TITLE
OSD glitch

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/openMSX#1551]
Hello, 

I see this glitch when showing OSD elements on OpenMSX 19.1-423-ge225918c1:

![image](https://github.com/openMSX/openMSX/assets/24856281/96ba77d1-7b9c-40a4-a431-0e88cad219d4)

It happens at least on two different Windows 10-based computers.

**Comment by MBilderbeek** [comment]
That's because you still have the now obsolete OSD scripts installed. Please remove openMSX completely and then install the ImGUI development build.

**Comment by m9710797** [comment]
Most likely this means you're using a mixed installation: the scripts from openMSX version 19.1 and the executable from the development snapshot.

Before the OSD icons where implemented as a Tcl script, and they could only be placed on a few fixed positions on screen. Now they are rendererd as ImGui elements (and e.g. they can be placed anywhere, including off-screen, or docked in another window).

Ah. I (only now) see that MBilderbeek already gave the same reply.

**Comment by Colpocorto** [comment]
Yes, you're both right, guys.

I've always merged every new release into my current installation and never had this issue, so I mistakenly assumed this time would work fine as well.

Thank you for your help.
