### ISSUE TITLE
UI: incorrect disassembling

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/openMSX#1552]
When trying to debug an MSX program, incorrect disassembling happens after stepping into a function. The following steps are an actual example of the issue: 

- Set a breakpoint to an address that calls function at #2740. Run the program and wait for it to stop at the BP:

![image](https://github.com/openMSX/openMSX/assets/24856281/15181956-7cdd-4bc7-8601-ff501d7938eb)

- Use the "step-in" button. Function #2740 is not shown properly (the instruction starting at #2740 is wrongly taken as part of an op-code formed with the previous bytes):

![image](https://github.com/openMSX/openMSX/assets/24856281/e8df4a4b-e28e-497e-a65d-e650c5f03252)

The existing instruction starting at #2740 is LD IY,(#FCC0) formed by op-code FD 2A C0 FC. However, the disassembler shows a wrong instruction starting at #273F instead.

**Comment by m9710797** [comment]
That's a well known problem with variable length instruction set (like Z80). In general there's no algorithm that always generates the correct disassembly view. All (approximate) solutions will use heuristics, meaning there will always be cases where it can go wrong.

The heuristic that's currently implemented in the openMSX debugger view is:
* Show instructions as-if you started disassembling from address 0.
* Internally it's possible to optimize this, so we don't really start from address 0, we only guarantee that the output will look the same as if you would.

A nice property of this heuristic is that is you start scrolling through the disassembly view, the output remains stable. Another thing is that it's not super complex to implement (though also not trivial to make efficient).

An few alternative heuristics could be:
* Just start disassembling from the address at the top of the view (and scroll byte-per-byte). But that looks _very_ ugly and often the first few instructions in the view will be wrong. (_Way_ more often than is currently the case)
* Always make sure that the address pointed to by the program counter (PC) is the start of an instruction. That's more complex to implement, and you need a special way to display the possibly incomplete instruction before the PC.

You just did show an example where the current heuristic goes wrong. So I'm certainly not saying it's a perfect heuristic. But I would like to say that often (not always) code and data are reasonably well separated in the 64kB address space. And you only run into problems like this when data (non-instructions) is followed by instructions, so typically not too often.

When implementing this I was aware of these corner cases. Nevertheless I considered it a reasonable compromise between simplicity, easy of use, looks, ....

So for now I'm closing this issue. But feel free to make suggestions for a better heuristic and reopen this issue (but do keep all the above tradeoffs in mind).

**Comment by m9710797** [comment]
And of course thanks a lot for reporting this issue. Keep the feedback coming!

**Comment by Colpocorto** [comment]
But the classic UI does it correctly:

![image](https://github.com/openMSX/openMSX/assets/24856281/55f7d4ed-1687-42f7-b1d4-06a42bc45736)

If the program jumps to a specific address, unless it is a caused by a bug, it should be guaranteed that a new op-code starts at that position, therefore the disassembler should know what to do.

**Comment by MBilderbeek** [comment]
Checked this with @m9710797 and he wrote:

>  it breaks disassmbling one instruction (instead it outputs a partial instruction line "db 0xcd" and then restarts
> it's a different heuristic. Depending on the situation either one or the other is correct

@m9710797 would it be useful to be able to switch heuristics?

**Comment by Colpocorto** [comment]
> Checked this with @m9710797 and he wrote:
> 
> > it breaks disassmbling one instruction (instead it outputs a partial instruction line "db 0xcd" and then restarts
> > it's a different heuristic. Depending on the situation either one or the other is correct
> 
> @m9710797 would it be useful to be able to switch heuristics?

In its current form, I find the disassembler useless. No matter what heuristics you use: if you track a portion of code after a JP or CALL, it is 99.9% sure that a new op-code must start exactly at that point. The current behaviour is even worse than the old UI updating issues.

**Comment by m9710797** [comment]
Hi Colpocorto,

I'll try to merge both heuristics: the current algorithm, but in addition make sure that the position of the PC is always the start of an instruction (with then possibly an incomplete instruction in front).

But note that this will _only_ work for the exact instruction the PC is pointing to. So as soon as you take a single step, the previous instruction will be displayed "wrong" again. In other words: the disassembly view will (remain) stateless: we don't keep track of the history of the PC.

I've put it on my TODO list, but with low priority. I know you've hit it, but in general this is a relatively rare situation. And we have more important items to work on ATM. (Help with implementing this would be appreciated of course).

Wouter

**Comment by Colpocorto** [comment]
> But note that this will _only_ work for the exact instruction the PC is pointing to. So as soon as you take a single step, the previous instruction will be displayed "wrong" again.

Sure, that's something one can expect (and in fact it already happened sometimes with the old UI). But starting an instruction at PC right after a jump/call will undoubtedly make things smoother.

Thank you guys for your good work.

**Comment by m9710797** [comment]
Implemented as discussed.
Feel free to reopen this ticket if something still isn't right.
