### ISSUE TITLE
"Configure messages" window design issues

### ISSUE THREAD

**Issue by theNestruo** [openMSX/openMSX#1555]
> - Windows version: 10.0.19045.3754
> - OpenMSX version: 19.1-467-g993c367c0 [Release]

The current "Configure messages" window:
![image](https://github.com/openMSX/openMSX/assets/12213477/058ed81e-841f-47f6-b005-c5489a6d9066)

It looks like there are three radiobutton groups with four radiobuttons, but, actually, there are six radiobutton groups with two "fake radiobuttons" that act as either radiobuttons or checkboxes.

Please redesign this window so any radiobutton acts as a radiobutton, and radiobutton groups are clear.
Mock-up/proposal:
![image](https://github.com/openMSX/openMSX/assets/12213477/4a9360da-2d7e-49ef-a588-720baeb4e69a)

**Comment by m9710797** [comment]
I'm back from a small break.

@theNestruo thanks a lot for reporting this and several other issues! This one should be fixed. I'll continue (slowly) with the others.

I read on MRC that you think many of these issues are "obvious", and that might be true. Though after working on this for several months it becomes too easy to overlook issues that might be obvious for other people.
Or sometimes I just never thought about testing a specific case. For example I never had my file manager overlapping with my openMSX window, so I never noticed issues like https://github.com/openMSX/openMSX/issues/1554.

So thanks again for reporting!

**Comment by MBilderbeek** [comment]
For clarity: @theNestruo please confirm that it's fixed, so we can close the issue.

**Comment by theNestruo** [comment]
Verified.
A nitpicking detail: it says "Don't show any popup" and "Do not open log window". For consistency it would be better that both sentences start with "Do not..." (instead of "Don't...").
