### ISSUE TITLE
Dialogs not properly brought to front

### ISSUE THREAD

**Issue by theNestruo** [openMSX/openMSX#1557]
> - Windows version: 10.0.19045.3754
> - OpenMSX version: 19.1-467-g993c367c0 [Release]

Steps to reproduce:
1. Open the "Configure messages" window
2. Move that window outside the main OpenMSX window
3. Cover that window with another window (browser, file explorer, command prompt... any other window)
4. Cause an error (e.g.: Connectors > MSX Printer port > logger)
    ![image](https://github.com/openMSX/openMSX/assets/12213477/6cb5eb70-4ae4-4542-9dbe-9195fd80e04e)
5. Click the "Configure..." button of the error window

Current behaviour:

6. The "Configure messages" window is not brought to the front nor it gets the focus.

Expected behaviour:

6. The "Configure messages" window is brought to the front and gets the focus.

**Comment by m9710797** [comment]
Should be fixed now. For this example and a few others (i did an audit of our code for places were we open a window via a push-button, not toggle open/close via a check-mark).

Please verify and reopen this ticket if something still isn't right.
