### ISSUE TITLE
Focus should not unpause emulation if it was manually paused

### ISSUE THREAD

**Issue by theNestruo** [openMSX/openMSX#1558]
> - Windows version: 10.0.19045.3754
> - OpenMSX version: 19.1-467-g993c367c0 [Release]

Steps to reproduce:
1. Manually pause the emulation ("Pause/Break" key)
2. Click outside the OpenMSX window (OpenMSX window loses the focus)
3. Click inside the OpenMSX window (OpenMSX window gains the focus)

Current behaviour:

4. Emulation unpauses

Expected behaviour:

4. Emulation is still paused until the user manually unpauses

This is particularly annoying in the probable scenario of pausing the game, then wanting to inspect the bitmap/tile/sprite viewer. When clicking on the menu to open another viewer, the emulation is unpaused thus you no longer can inspect that particular frame.

**Comment by MBilderbeek** [comment]
Hmm, I cannot reproduce this myself. Do you have any 'after focus' bindings active? Can you attach your settings.xml file?

**Comment by theNestruo** [comment]
&lt;installation path&gt;/share: [installation path settings.zip](https://github.com/openMSX/openMSX/files/13404460/installation.path.settings.zip)
&lt;user home&gt;/Documents/openMSX/share: [user documents settings.zip](https://github.com/openMSX/openMSX/files/13404464/user.documents.settings.zip)

**Comment by MBilderbeek** [comment]
Aha, you have this setting enabled:
`<setting id="pause_on_lost_focus">true</setting>`
This setting causes the emulation to pause on losing focus and to unpause on gaining focus. The latter is what you're looking at. This behaviour is not new in this version, and should have been like that for ages. Can you confirm that?

**Comment by MBilderbeek** [comment]
Perhaps `pause_on_lost_focus` should only unpause when regaining focus if the pause was caused by losing focus? :-)

**Comment by theNestruo** [comment]
> Perhaps `pause_on_lost_focus` should only unpause when regaining focus if the pause was caused by losing focus? :-)

That is the issue.

It may have been like that for ages, but it is more noticeable due the additional OpenMSX windows (such as bitmap/tile/sprite viewers), as I stated in the first post

**Comment by MBilderbeek** [comment]
@m9710797 what about this first try for a patch?

```
diff --git a/share/scripts/pause_on_lost_focus.tcl b/share/scripts/pause_on_lost_focus.tcl
index 649ed59ef..40495cd86 100644
--- a/share/scripts/pause_on_lost_focus.tcl
+++ b/share/scripts/pause_on_lost_focus.tcl
@@ -1,17 +1,60 @@
 namespace eval pause_on_lost_focus {
 
+variable paused_due_to_lost_focus false
+variable changing_pause_from_here false
+
+proc paused_due_to_lost_focus {} {
+       variable paused_due_to_lost_focus
+       variable changing_pause_from_here
+       if {!$::pause} {
+               # puts "Lost focus, going to enable pause"
+               set changing_pause_from_here true
+               set ::pause on
+               set changing_pause_from_here false
+               set paused_due_to_lost_focus true
+       } else {
+               set paused_due_to_lost_focus false
+       }
+}
+
+proc unpaused_due_to_gain_focus {} {
+       # puts "Gained focus, possibly going to disable pause"
+       variable paused_due_to_lost_focus
+       variable changing_pause_from_here
+       if {$paused_due_to_lost_focus} {
+               set changing_pause_from_here true
+               set ::pause off
+               set changing_pause_from_here false
+               set paused_due_to_lost_focus false
+       }
+}
+
 proc setting_changed {name1 name2 op} {
+       variable paused_due_to_lost_focus false
        if {$::pause_on_lost_focus} {
-               bind_default "focus 0" "set pause 1"
-               bind_default "focus 1" "set pause 0"
+               bind_default "focus 0" "pause_on_lost_focus::paused_due_to_lost_focus"
+               bind_default "focus 1" "pause_on_lost_focus::unpaused_due_to_gain_focus"
        } else {
+               set paused_due_to_lost_focus false
                unbind_default "focus 0"
                unbind_default "focus 1"
        }
 }
 
+proc pause_setting_changed {name1 name2 op} {
+       variable paused_due_to_lost_focus
+       variable changing_pause_from_here
+       if {$changing_pause_from_here} {
+               # puts "Puase setting changed from this script itself to $::pause"
+       } else {
+               # puts "Pause setting changed by user to $::pause"
+               set paused_due_to_lost_focus false
+       }
+}
+
 user_setting create boolean pause_on_lost_focus "pause emulation when the openMSX window loses focus" false
 trace add variable ::pause_on_lost_focus write [namespace code setting_changed]
+trace add variable ::pause write [namespace code pause_setting_changed]
 
 # initial setup (bind or unbind)
 setting_changed pause_on_lost_focus "" write
```

**Comment by MBilderbeek** [comment]
Should be fixed now, please confirm @theNestruo .

**Comment by theNestruo** [comment]
Verified. Thanks!
