### ISSUE TITLE
Key binding should be contextual

### ISSUE THREAD

**Issue by theNestruo** [openMSX/openMSX#1559]
> - Windows version: 10.0.19045.3754
> - OpenMSX version: 19.1-467-g993c367c0 [Release]

Steps to reproduce:
1. Open OpenMSX and load any game
2. Open the disassembly window
3. Click on the disassembly window
4. Navigate through the code using keys up, down, Home, End, PgUp, PgDown

Current behaviour:

5. Keys trigger navigation actions (right), but also emulator actions (wrong). E.g.: PgUp and PgDown are also trigger the reverse/replay feature

Expected behaviour:

5. Any key event that is handle by a window should be consumed and not passed to the main window

**Comment by ocornut** [comment]
Hello, dear imgui author here.

Technically openMSX could query the focus state of e.g. game window to decide to pipe inputs solely to it. But I believe there are many situation where it would be desirable to manipulate controls while toying with tools, and no simple single-change will full-fill all need.

The input-aware/key ownership system, and input routing system (via e.g. high-level functions like `Shortcut()`) can accommodate for many things but it's not a trivial system and poorly documented. If an openMSX author wants to have a video-call/conversation about those someday I'm open to it.

**Comment by MBilderbeek** [comment]
@theNestruo can you please confirm that this is fixed in the latest development build? (We indeed improved input routing, thanks to @pvmm .)

**Comment by MBilderbeek** [comment]
@theNestruo I'm closing it, please reopen with comment if you don't agree.
