### ISSUE TITLE
Selecting "dir as disk" is broken

### ISSUE THREAD

**Issue by gilbertfrancois** [openMSX/openMSX#1566]
I cannot select a folder as floppy disk (anymore) with the current UI.

Media -> Disk drive A -> select "dir as disk" -> click on folder icon -> file chooser opens -> select a folder, click on "Ok" -> file chooser closes. Now the path in the dropdown from "dir as disk" is still empty and the buttons "Apply" and "Ok" are disabled.

Tested with openMSX 60163a208b9162e15ffd24c2bcfd1b2e861d651d using Canon V-20 and Philips VY-0010 floppy drive.

**Comment by m9710797** [comment]
Was broken after last upgrade of the (3rd party) library ImGuiFileDialog (see commit message for more details).
Should be fixed now.

Thanks a lot for reporting!

**Comment by gilbertfrancois** [comment]
I can confirm that it works again. Thank you for fixing it so swift.
