### ISSUE TITLE
Debugging should unpause the emulation

### ISSUE THREAD

**Issue by theNestruo** [openMSX/openMSX#1570]
Right now, it is unpractical to use the debugger if "pause_on_lost_focus" is active.
When you hit a breakpoint and then click on any of the debugger windows, the focus is lost and the emulation is paused. When you click on any debugger button (run, step-in, step-over, step-out, or step-back), the emulation is still paused, so you need to click on the main window to unpause.
In my opinion, any of the debugger buttons should also unpause the emulation.

**Comment by theNestruo** [comment]
Side note: do run, step-in, step-over, step-out, or step-back have equivalent command(s) in the console? can they be binded to a keystroke?

**Comment by m9710797** [comment]
Thanks for reporting! Personally I never use 'pause_on_lost_focus'. So I never noticed this usability issue.

I'll put this on the TODO list. Though I'm still thinking about how to best solve this. One possibility is what you suggest (auto unpause on all debugger-resume commands). Another possibility is to merge the "pause" and the "debug break" concepts into one (this would simplify the implementation and maybe also the usage, but then what about backwards compatibility (also with existing scripts)). I'm not sure yet.

Everything is also available as console commands, and can thus be bound to input events (e.g. keyboard). The command names are `step_in`, `step_over`, `step_out`, `step_back`, ... You can find more info in the [manual](https://openmsx.org/manual/commands.html#other), or via a console command like `about step`.

To make a binding execute a command like `bind F8 step_in`. Again more info in the manual.

**Comment by m9710797** [comment]
I've implemented this. Please verify and give feedback (and then possibly re-open this issue).
