### ISSUE TITLE
Problem with loading on MSX tR disk drive (TC8566AF)

### ISSUE THREAD

**Issue by NYYR1KK1** [openMSX/openMSX#1580]
How to reproduce the problem:
- Use Panasonic A1GT machine
- Mount the SymbOS 4.0 beta setup disk 1
- Use SymShell or SymCommander to browse the disk
- Go to "Extra"-folder

It seems that the real content of directory is not loaded but the directory is displayed using what ever data happens to be in memory. Loading the directory sector with DiMon seems to work fine. This same happens also, if "dir as disk"-feature is used. At first I naturally thought this is SymbOS bug, but for some reason I was unable to reproduce this same problem on real hardware although same disk was used. CPU mode does not seem to affect the issue... Also location of disk driver or SymbOS version does not seem to change things. I've seen this happening also with other disks that have directories.

The problem has been tested with openMSX 18 and 19 & SymbOS 3.0 and 4.0 beta.

[SymSetup_disk1.zip](https://github.com/openMSX/openMSX/files/14161701/SymSetup_disk1.zip)

**Comment by NYYR1KK1** [comment]
Oh, forgot to mention that both on real and emulated environment the SymbOS was installed to MFR+SD... I did try on emulator using also Sunrise IDE, but the 2nd storage driver did not affect the end result.

**Comment by mthuurne** [comment]
Does this only happen with turbo R machines or also with other MSX models?

The turbo R has a disk change sensor, which allows the OS to cache previously read sectors for a long time, because it can check whether the same disk is still in the drive. Perhaps something is wrong in the emulation of that sensor.

**Comment by NYYR1KK1** [comment]
I've seen this happening only on MSX tR. Other disk controllers don't seem to suffer from this problem, but please note that SymbOS uses custom drivers for all different disk drive interfaces. This anyway sounds like a plausible explanation.

**Comment by NYYR1KK1** [comment]
Hmm... not so sure about the theory anymore... 

Here are sources of the floppy routines:
[Drv-FDCPanasonic.zip](https://github.com/openMSX/openMSX/files/14165967/Drv-FDCPanasonic.zip)

**Comment by m9710797** [comment]
Hi,

Thanks a lot for reporting this issue. I'll look into it, though probably only next week (I'm a bit ill and I also first want to finish some other small tasks).

mthuurne's hypothesis is plausible. Though my best *guess* would be that for some reason the read-sector routine stops too early (without reporting an error? or symbos ignoring the error?). So leaving the buffer where the sector data should end up unchanged.

Thanks a lot for including the source code of the symbos driver. It's not too much code. (Later) I'll try to study that code and compare it with how openMSX expects the TC8566AF to behave.

Another wild guess: maybe reading more than one sector using a single FDC command is not working correctly in openMSX. (Does symbos issue such commands?) There _is_ emulation code for that case, but I guess the standard turboR BDOS, nor XelaSoft's fastcopy use such commands. So it's possible that emulation code was never tested?

Wouter

**Comment by NYYR1KK1** [comment]
AFAIK SymbOS does not try to do multisector reads and the disk routines have been forked from XelaSoft's routines.

This whole stuff kind of kept bothering me, so I had to take a bit closer look although I must say I'm pretty far from my comfort zone with these kinds of things, but here is what I found while trying to decipher the problem:

To me it seems that things start to go haywire when OS tries to load the directory sector. When request is sent #7FF5 bit 5 goes to 1 (Non-DMA mode ???)

This will cause "result phase" to be read (HEX): 40 04 00 24 01 02 02 
If I deciphered this message correctly, it means: Abnormal Termination of Command. Command execution was started, but was not successfully completed. Sector was not found: Cylinder 36, Head 1, Sector 2

As there is SCF missing from end of the fdcres2-routine the fault goes under the radar in OS level and we end up to what I described.

**Comment by NYYR1KK1** [comment]
BTW if you fix the error in driver, this hides the problem completely as then SymbOS just tries again and then all goes well... (I think this is what happens in MSX-DOS as well) How ever it does not explain why the problem happens in the first place.

Here is source & binary of fixed driver:
[Panasonic_SMD3.zip](https://github.com/openMSX/openMSX/files/14189893/Panasonic_SMD3.zip)

**Comment by m9710797** [comment]
Hi NYYR1KK1,

Thanks for investigating and sharing your findings, it's very useful. I haven't been able to do much work on this myself yet. The only thing I did was verify that the SymbOS driver indeed does NOT do multi-sector reads (the function does take a number-of-sectors parameter, but internally the function then issues so many single-sector read-commands).

Your interpretation of the "result phase" is correct: we tried to read "track 36, head 1, sector 2", and that indeed resulted in the error "sector not found". Did you verify that "track 36 head 1 sector 2" is indeed the requested sector (i mean at the start of the command)? In the rest of this message I'm assuming it is the same. 

What is strange (to me) is that when this command gets retried it does succeed. Emulation in openMSX is (or should be) deterministic, so reading the same sector multiple times should not fail sporadically. The only explanation I can think of right now is that the drive head is not yet positioned above the correct track (and it is when the command gets retried). This is a wild guess: could it be that shortly before the first read-sector command we issued a seek command, and then there's a bug in waiting for this seek to complete? (And the bug could either be on the SymbOS or the openMSX side). 

One peculiar thing about the TC8566AF controller (or at least different from the WD2793 family) is that it can issue 4 simultaneous seek commands to (up-to) 4 connected drives. While one drive is still seeking it's possible to issue another command on another drive. A consequence is that the seek command itself finishes quickly, but meanwhile the drive is still performing the seek in the background. And then there is a different mechanism to query whether (each of the 4) drives(s) is still seeking. In the driver code I do see some code to wait for the actual seek to finish, but I haven't yet studied this code in detail.

Emulating these independent seeks was "relatively recently" added to openMSX (Jun 2021). And there's not so much MSX software that exercises the TC8566AF in different ways. So I wouldn't be surprised if some detail of this emulation behavior isn't fully correct yet.

Thanks again for investigating.

Wouter

**Comment by NYYR1KK1** [comment]
It tries to read logical sector 658 that matches with the "Extra" folder directory, so "track 36 head 1 sector 2" sounds right to me. Even if it would be wrong, it should not lead to this kind of error.

I would not put much effort in to thinking if SymbOS is doing everything right either (as we saw already, it was not) but that is not the reason I opened the case. The important point is that what ever it is doing seems to work fine on real HW and it causes this failure only on openMSX. 

This can indeed be just some timing error that the seek takes too long or the FDC does not wait long enough. Previous logical sector that is read by FDC is 1, so this would make sense as the track 36 is already almost "half disk surface" away.

**Comment by NYYR1KK1** [comment]
I did check the SymbOS driver seek wait routine and it seems to run other OS tasks until none of the 4 drives are in seek mode or if ST0 bit 5 indicates that the seek command has been completed... This sounds ok approach to me.

**Comment by m9710797** [comment]
I agree. It does seem like the SymbOS driver (correctly?) checks for the seek to finish. Though at the moment, without having done much investigation, failing to wait for seek remains my current best hypothesis. So possibly the bug is located on the openMSX side? E.g. openMSX already signaling the seek is finished, while in fact it is not??

I tried to investigate, but I didn't get very far. Mostly because I have zero experience with SymbOS. I have no clue how to reproduce the problem. I tried booting the SymSetup_disk1.dsk disk image in a turboR-gt, but that resulted in a hang (DI+HALT detected without any other error messages). I also have no experience with MFR+SD (even though I probably (helped to?) implement emulation of that device). Can someone give me more detailed instructions for how to reproduce this problem? Thanks.

**Comment by NYYR1KK1** [comment]
Yeah... SymbOS is not difficult, but the hard part is that you need to get MSX-DOS2 running first... I try to give quick instructions, ask if you need more help with some particular subject and I try to see what I can do:

Personally I've backed up some RAW copies of memory cards that I've earlier used on my real MSX and just used them as starting point when ever I've tried HDD emulation on openMSX, but if you don't have such, it is a bit more complex problem.
I think that you can just create a big empty file (how to do such depends of OS) and mount it as HDD using ie. Catapult. There is also some command called diskmanipulator in openMSX. I don't know if it can be used, but at least personally I've newer managed to do anything useful with it, so I can't really recommend trying to use that. It is very complex way to approach the issue. The actual interface can be also other than MFR+SD, but I've used that lately as it has Nextor kernel by default. The machine setup may not want to start and then you need to go and delete megaflashromsccplussd.sram file from your pesistent folder first. Catapult status Info tab will show the exact folder in the error message. Once you get it to start you will likely drop to MultiMente. You need to exit by using ESC and go to BASIC by using BASIC-command. You can now use CALL FDISK command to create you partitions. Once done & saved, boot again to get back to MultiMente. Now you should have drive that you created with FDISK... It is likely B: or so... Now you need to copy COMMAND2.COM and MSX-DOS2.SYS or NEXTOR.SYS to the root of that drive from drive A: 

Now to get rid of MultiMente, the read only A: and such stupid stuff, you need to reboot while holding "UP"-key down, this should bring you to menu where you can select "Delete ROM drive" or something like that. Once you have done that and booted, you should finally sit on MSX-DOS2 prompt and you should have A: as your memory card and B: as your floppy drive. I suggest to take a backup of your created HDD image, as You may like to have a fresh HDD image to start with later for other experiments that need MSX-DOS2 / Nextor

Now you can install SymbOS -> Plug in mouse and put the setup disk to the floppy drive. Go to drive B: and execute SYMSETUP.COM This will get you to Wizard that will ask you series of questions about installation folder, HW etc. You can just follow this manual from page 10 to get trough this part: https://symbos.org/download/20211230-V31/symbos-manual.zip

Once the SymbOS is up you need to click Start/Settings/Control Panel. From the opening window you need to select "Mass Storage".  Click "Add" and fill: Name: Floppy, check "Removable media", Drive Letter "B:", Floppy disk, Drive A, Head 0 and click Ok. Then click File/Save settings (or Start/Settings/Save).

Now you should be able to perform the test described on the first message.

**Comment by MBilderbeek** [comment]
@NYYR1KK1 can you prepare a file (disk or hd image) to easily investigate this?

**Comment by NYYR1KK1** [comment]
Are you guys serious? It is likely the fact that MFR attaches two SD-cards that confused you... This is why the disk drive can not be found from drive B: in DOS.

Oh, well... I made a fresh install... Put MFR+SCC+SD to slot 1 and place the megaflashromsccplussd.sram to "openMSX\persistent\MegaFlashROM_SCC+_SD\untitled1"-folder. Then mount the attached DSK-file as Hard disk using Catapult and press start. (Plugging mouse highly recommended)

[SYM.zip](https://github.com/openMSX/openMSX/files/14418811/SYM.zip)

**Comment by NYYR1KK1** [comment]
Just in case the rest of the manual setup steps that I did not explain yet (In DOS2):

Type C: {enter} (to go from SD-card to floppy drive)
Type: SYMSETUP {enter} (to start the installation program)
Type: "1" (to select new SymbOS installation)
Type: {enter} (to accept A:\SYMBOS as installation directory. NOTE: Might point to ROMdisk if you didn't delete it as I suggested)
Type: {enter} (to begin copying of system files)
Type: {enter}  (to start device configuration)
Tppe: "S" to save the automatically detected devices
Type: {enter}  (to skip instructions)
Type: "1" (to tell that my A:\SYMBOS directory is on "MegaSD SD card reader")
Type: "1" (to tell that the SD-card is on SD slot 1)
Type: "0" (to tell that I have not partitioned the SD-card. NOTE: Might be also 1 if you created a partition on FDISK step)
Type: "Y" (to confirm that I've made correct selections)
Type: {enter}  (to accept saving of the data)
Type: {enter}  (to skip instructions)
Type: {enter}  (to start SymbOS)

(all rest of the steps I explained already, I think.)

**Comment by MBilderbeek** [comment]
Yes, we're very serious. We'd like to spend time working on the actual problem, instead of trying to create a SymbOS install that we have never done before (or maybe once years ago...) So, it helps a lot if the reporter, who can reproduce the problem, shares the means he has to reproduce it :) Thanks for submitting these files.

Now, with these files, how to reproduce the problem after starting openMSX as you explained... here's what I did (@m9710797 I hope it's useful):
* download and unzip the [SYM.zip](https://github.com/openMSX/openMSX/files/14418811/SYM.zip) in `/tmp`. Also download [SymSetup_disk1.zip](https://github.com/openMSX/openMSX/files/14161701/SymSetup_disk1.zip) to `/tmp`
* Go to the openMSX extension folder and `cp MegaFlashROM_SCC+_SD.xml SymbOS_MFR.xml`
* `openmsx -machine Panasonic_FS-A1GT SymbOS_MFR` (to create the persistent folder) and exit openMSX again.
* `cp /tmp/megaflashromsccplussd.sram ~/.openMSX/persistent/SymbOS_MFR/untitled1/megaflashromsccplussd.sram`
* `cp /tmp/SYM.dsk ~/.openMSX/persistent/SymbOS_MFR/untitled1/SDcard1.sdc`
* `openmsx -machine Panasonic_FS-A1GT -ext SymbOS_MFR -diska /tmp/SymSetup_disk1.zip`
* `plug joyporta mouse` and `reset` (to get mouse working)
* double click SymCommander on the top left
* click A top left and change to B
* double click on the `[EXTRA]` folder
* observe corruption

**Comment by m9710797** [comment]
@MBilderbeek Thanks for the detailed instructions. That motivated me to pick this up again.

Once I was able to reproduce the issue, I could relatively easy (within a few hours) diagnose and fix the problem. Though it was still a bit tricky. See the commit message of 0bdacbdd32e16 for details.

In summary: it was indeed the case that SymbOS already started the read-sector command before the seek was finished. But that was because openMSX incorrectly signaled seek was finished (because this bit was still set from a previous seek command).
