### ISSUE TITLE
Problem d-pad of Dualshock 4

### ISSUE THREAD

**Issue by Anths2016** [openMSX/openMSX#1581]
The dpad on the Dualshock 4 does not work, only the analogue works.

**Comment by MBilderbeek** [comment]
Which openMSX version are you using?

**Comment by Anths2016** [comment]
19.1

**Comment by m9710797** [comment]
Hi Anths2016,

I don't know any specifics about the "Dualshock 4", so I'll keep my answer general.
For many joysticks SDL reports the D-pad as 4 regular buttons. And then openMSX has no idea which group(s) of 4 buttons form a D-pad and which are regular buttons. That's why, by default, the D-pad is not always mapped.

The solution is to define your own mapping (from buttons/axis on the host joystick to buttons/axis on the emulated MSX joystick). How to do this exactly differs between openMSX versions.

For version 19.1 you have to manually set the "joystick<1>_config" setting. I'll refer to the manual for more details.

In the latest development versions there's a GUI that shows a graphical representation of the MSX joystick. you click on one of the MSX joystick buttons, and then press the corresponding host joystick button/axis/dpad.

Wouter

**Comment by MBilderbeek** [comment]
Actually, in 19.1 this can be set up in the OSD menu. Menu -> Settings -> Misc -> Host to MSX joystick mapping.

**Comment by Anths2016** [comment]
> n the latest development versions

Don't recognize GFX9000

**Comment by MBilderbeek** [comment]
Can you be more specific on what you tried and what the exact result was?

**Comment by Anths2016** [comment]
I use openMSX Launcher to activate GFX9000, but Openmsx in development does not recognise it.

**Comment by MBilderbeek** [comment]
> I use openMSX Launcher to activate GFX9000, but Openmsx in development does not recognise it.

I am not familiar with that program, it is not made by us. Can you try without it? 
What is the reason you use that program? Let us know if there is anything missing in the new user interface of the development build.

**Comment by Anths2016** [comment]
How can I do without it? How do I activate it in the menu?

**Comment by MBilderbeek** [comment]
> How can I do without it? How do I activate it in the menu?

Just select it under media -> extensions...

**Comment by MBilderbeek** [comment]
All clear? Did you get your Dualshock 4 working now?

**Comment by Anths2016** [comment]
No. The latest version does not work with openMSX Launcher. I have to remain at 1.9.1

**Comment by MBilderbeek** [comment]
But you don't really need openMSX Launcher, do you?

**Comment by MBilderbeek** [comment]
Anyway, perhaps @oksoelsha can take a look, I believe he wrote openMSX Launcher.

**Comment by oksoelsha** [comment]
Hi Anths2016,

I am the developer of openMSX Launcher. I tried the latest development build 474 from Dec 2nd with openMSX Launcher, and switching to GFX9000 worked. The command line arguments that openMSX Launcher uses to start openMSX in GFX9000 mode are:

-carta <path>\game.rom -machine machine-name -script script.tcl

(specify the path to the rom (or use a disk) and the machine of choice)

where the content of the script.tcl file is:

ext gfx9000
ext slotexpander
after time 10 "set videosource GFX9000"

You can always try the command line like this to start openMSX to see if there's a problem on your end.

**Comment by m9710797** [comment]
Hi oksoelsha,

That's indeed what I would expect. But thanks a lot for verifying!

Just one detail:
"The latest development build 474": that's only about 100 revisions behind the actual latest revision "19.1-570  (Feb 17)" ;-)

You can find the latest versions here:
* Windows builds:
    https://openmsx.vampier.net/zips/
* All platforms (but maybe you need a github account?):
    List of all revisions: https://github.com/openMSX/openMSX/actions/workflows/build_snapshots.yml
   Direct link to revision 570, at the bottom of the page you can find the download links: https://github.com/openMSX/openMSX/actions/runs/7944137761

**Comment by MBilderbeek** [comment]
@Anths2016 please give us more information on what exactly you are doing and what the results are. We can't help you without.

**Comment by Anths2016** [comment]
Works with script.

**Comment by MBilderbeek** [comment]
Please give more details on what you mean. Do you see an error? Do you see nothing? In the latter case, did you switch the videosource to display the gfx9000?

Here's the setting in the latest development build:
![image](https://github.com/openMSX/openMSX/assets/12675978/1eee5edf-aa31-41be-a28a-a89bc283252c)

openMSX Launcher sets it after 10 seconds, as we can see from the post of @oksoelsha .

**Comment by Anths2016** [comment]
I used script.tlc : 
ext gfx9000
ext slotexpander
after time 10 "set videosource GFX9000"
Finally also dpad works.

**Comment by MBilderbeek** [comment]
OK, so all works as expected, you just needed to select the video output....
