### ISSUE TITLE
Machine selector generates many SRAM file not found messages

### ISSUE THREAD

**Issue by grauw** [openMSX/openMSX#1584]
When using the machine selector UI I get a ton of "SRAM file not found" complaints in the message log, which pops up again and again after I close it as I continue browsing the machines. Seems these are generated as a result of the query for the machine information tooltip.

May want to clear out the SRAM files from your ~/.openMSX directory to reproduce that, since it seems to only occur once for every machine and then creates the SRAM file in my user dir.

Using Github actions build openmsx-19.1-571-ge11842aaa-mac-aarch64-bin.dmg.zip

**Comment by MBilderbeek** [comment]
Yes, this happens because the machines are actually instantiated. A similar thing is that for the extensions in some cases large files are created (e.g. empty HD images). But that doesn't give a pop-up I guess.

@m9710797 wouldn't it be better to make something to avoid this when we only want to instantiate for some queries?

**Comment by m9710797** [comment]
I agree. I'll put this on my TODO list.

**Comment by m9710797** [comment]
With a one-line change I could suppress the messages (revision 92a8dcad630).
However the SRAM files (typically for the RTC) and HD images are still being created.
* On the one hand that's fine. That also tests that those files really can be created (e.g. the directory is writable). And SRAM files don't take much space.
*  On the other hand, empty HD images are also created. These are 100MB. Nowadays that's not a whole lot, but also not negligible.

**Comment by grauw** [comment]
Messages were previously silenced in 92a8dca, and now the “SRAM file not found, assuming blank content” message has also been removed altogether in f1bbc93.
