### ISSUE TITLE
Cannot load settings

### ISSUE THREAD

**Issue by breadncup** [openMSX/openMSX#1587]
I've installed the development version ([openmsx-19.1-623-g2a4070ae1-mac-aarch64-bin.dmg](https://github.com/openMSX/openMSX/actions/runs/8132036942/artifacts/1293067912)) in https://github.com/openMSX/openMSX/actions/runs/8132036942

When I run this command, I get an error:

```
load_settings ~/.openMSX/share/mysettings.xml
```
in the console, it get this error:

```
can't set "enable_session_management": can't read "after_quit_id": no such variable
```

[mysettings.xml.zip](https://github.com/openMSX/openMSX/files/14475681/mysettings.xml.zip)

**Comment by m9710797** [comment]
This evening, when I'm back at home, I'll check in more detail. But could you verify whether your openMSX installation is correct?

In particular, when you upgraded to the new version, did you update _both_ the openMSX executable _and_ the openMSX scripts. Did you also remove the old scripts.

These type of errors sometimes occur when you're running a mix of an old and new openMSX installation. E.g. there's still an old script in your openMSX installation that has been removed in the new version, or something like that.

**Comment by m9710797** [comment]
Never mind my remark from this morning. It's not related to the openMSX installation.

I could easily reproduce the problem with the given 'mysettings.xml' file.
After that fixing was relatively easy.

**Comment by breadncup** [comment]
Thanks for the fix, @m9710797 .

I tested, but I found another issue: https://github.com/openMSX/openMSX/issues/1590

Would you take a look if you have a chance, please?
