### ISSUE TITLE
load_settings <file> working weird

### ISSUE THREAD

**Issue by breadncup** [openMSX/openMSX#1590]
I filed the issue yesterday about `load_settings`, and it seems that it has been fixed by https://github.com/openMSX/openMSX/commit/fa5be6914520e91d776f17fac0441abaa50705b8

I tested it with https://github.com/openMSX/openMSX/actions/runs/8145809781, which seems to include the fix but does not work as expected. 

The error message was gone, and it loads the settings, but it does not read whole at the beginning, and when I run twice, it reads it.

[testsettings.xml.zip](https://github.com/openMSX/openMSX/files/14488645/testsettings.xml.zip)

Please test it with this testsettings.xml

The xml contains `<setting id="scale_factor">4</setting>`, which scales the openMSX windows four times.

Steps to Reproduce :

1. copy testsettings.xml into ~/.openMSX/share/settings.xml
2. copy testsettings.xml to ~/.openMSX/share/testsettings.xml
3. launch openMSX.app
4. It scales openMSX four times as settings.xml has `<setting id="scale_factor">4</setting>`
5. run `load_settings ~/.openMSX/share/testsettings.xml`
6. It shrinks the window as scale=1
7. run `load_settings ~/.openMSX/share/testsettings.xml` again
8. It scales the window as scale=4 as in the testsettings.xml

**Comment by m9710797** [comment]
Thanks for reporting. I can reproduce this issue. I'll investigate ...

**Comment by m9710797** [comment]
Should be fixed now. Please verify.
