### ISSUE TITLE
save_settings <file> is removing some existing settings!

### ISSUE THREAD

**Issue by breadncup** [openMSX/openMSX#1592]
Hi,

I filed the issue (https://github.com/openMSX/openMSX/issues/1590), and when I tested it with https://github.com/openMSX/openMSX/actions/runs/8161196915, It seems that it is fixed.

However, there is another issue: it removes some existing settings when I run save_settings to the same file.

[testsettings.xml.zip](https://github.com/openMSX/openMSX/files/14503535/testsettings.xml.zip)
[after-save-testsettings.xml.zip](https://github.com/openMSX/openMSX/files/14503536/after-save-testsettings.xml.zip)

Steps to reproduce:

1. load_settings ~/.openMSX/share/testsettings.xml
2. save_settings ~/.openMSX/share/testsettings.xml

The diff shows like this:
```diff
--- testsettings.xml	2024-03-05 17:52:50
+++ after-save-testsettings.xml	2024-03-05 17:53:34
@@ -4,17 +4,15 @@
     <setting id="scale_factor">4</setting>
     <setting id="osd_rom_path">/Users/ysong/.openMSX/share/software/ROM</setting>
     <setting id="fullspeedwhenloading">true</setting>
-    <setting id="msxjoystick1_config">UP {{joy1 -axis1}} DOWN {{joy1 +axis1}} LEFT {{joy1 -axis0}} RIGHT {{joy1 +axis0}} A {{joy1 button0}} B {{joy1 button1}}</setting>
-    <setting id="save_settings_on_exit">false</setting>
-    <setting id="resampler">hq</setting>
-    <setting id="default_machine">Panasonic_FS-A1GT</setting>
     <setting id="osd_leds_set">none</setting>
+    <setting id="default_machine">Panasonic_FS-A1GT</setting>
+    <setting id="resampler">hq</setting>
+    <setting id="save_settings_on_exit">false</setting>
     <setting id="invalid_psg_directions_callback">psgdirectioncallback</setting>
-    <setting id="renshaturbo">1</setting>
     <setting id="blur">0</setting>
-    <setting id="joymega1_config"/>
     <setting id="invalid_ppi_mode_callback">ppimodecallback</setting>
-    <setting id="di_halt_callback">dihaltcallback</setting>
+    <setting id="joymega1_config"/>
     <setting id="joystick1_config">LEFT {-axis0 L_hat0} RIGHT {+axis0 R_hat0} UP {-axis1 U_hat0} DOWN {+axis1 D_hat0} A {button0} B {button1}</setting>
   </settings>
+  <bindings/>
 </settings>
```

Why does it remove that? Why not store the existing one properly? @m9710797 FYI

**Comment by m9710797** [comment]
Hi. Thanks again for reporting this issue. Already the 3rd issue, seems like loading/saving settings was quite buggy :(

I'll investigate this evening when I'm back at home. But here's already a quick analysis to make sure I correctly understand your bug report.

The `<setting>` tags in the settings file have the following two properties:
* The order in which they occur in the file is arbitrary.
* Settings which have their default value are not stored.

If I take your diff, only look at the changed lines, and reorder, then I get something like this:
```
-    <setting id="default_machine">Panasonic_FS-A1GT</setting>
+    <setting id="default_machine">Panasonic_FS-A1GT</setting>
-    <setting id="joymega1_config"/>
+    <setting id="joymega1_config"/>
-    <setting id="resampler">hq</setting>
+    <setting id="resampler">hq</setting>
-    <setting id="save_settings_on_exit">false</setting>
+    <setting id="save_settings_on_exit">false</setting>
-    <setting id="msxjoystick1_config">UP {{joy1 -axis1}} DOWN {{joy1 +axis1}} LEFT {{joy1 -axis0}} RIGHT {{joy1 +axis0}} A {{joy1 button0}} B {{joy1 button1}}</setting>
-    <setting id="renshaturbo">1</setting>
-    <setting id="di_halt_callback">dihaltcallback</setting>
```

So the first 4 (`default_machine`, `joymega1_config`, `resampler` and `save_settings_on_exit`) are fine, these are only reorderings.

Setting `msxjoystick1_config` might be fine if this corresponds to the default value for this setting (and that depends on the type of your host joystick)

But clearly the last 2 (`renshaturbo` and `di_halt_callback`) are wrong. I agree these should have been kept in the settings file. This is a bug. I'll investigate.

**Comment by breadncup** [comment]
`msxjoystick1_config ` is more important to me.

It is set by settings.xml, actually. and when there is an additional setting like renshaturbo, and if `save_settings` removes `msxjoystick1_config`, it is not what i want.

Maybe when I store new settings, the joystick might not be connected. 

Would it be possible to keep the original settings whatever? and if a new one is added, just add it in the setting file?

**Comment by m9710797** [comment]
Hi again.

I made another one-line-fix. Hopefully it fully works now.
I verified that, for me, loading and saving settings results in the same file (though possibly settings are in a different order, but that shouldn't matter).
I also checked that saving settings when no host joystick is plugged keeps the previously defined joystick settings.

Please test, and let me know if there's anything still wrong.

**Comment by breadncup** [comment]
Thanks, @m9710797 ,

Now, it is working as expected. As you said, the order has been changed, but all settings were remained as before.

Thank you, now, I'm closing this ticket.
