### ISSUE TITLE
Pasting text into a debugger window results in emulator keystrokes

### ISSUE THREAD

**Issue by santiontanon** [openMSX/openMSX#1594]
- Tested on Mac on version openmsx-19.1-630-g9223ec4d7-mac-aarch64-bin
- Start OpenMSX, boot an MSX and let it go to the BASIC (where it's easy to see this effect)
- Open a debugger window, e.g. "breakpoints", create a new breakpoint and paste some name with COMMAND+V
- As a result, the text is both pasted into the debugger window AND on MSX. I would expect the MSX not to see those keystrokes

**Comment by santiontanon** [comment]
I just noticed there is a PR already targeting this (sorry, didn't notice it when I created the issue): https://github.com/openMSX/openMSX/pull/1593

**Comment by m9710797** [comment]
Hi santiontanon,

This is indeed a known issue. And unfortunately not easy to fix. But it is high on our priority list (it's something that must be fixed before we can 'officially' release the new openMSX GUI stuff).
Thanks anyway for reporting.
