### ISSUE TITLE
Zombie Hunter won't run properly

### ISSUE THREAD

**Issue by pokemonfan6498** [openMSX/openMSX#1597]
i was trying to play zombie hunter but no matter which configuration option i pick it always has green screen and nothing else

**Comment by MBilderbeek** [comment]
Why are you closing the issue just after opening?

**Comment by pokemonfan6498** [comment]
I had issue with translation of a game and not original rom

**Comment by MBilderbeek** [comment]
Okay, I guess wrong mapper type as the translation is not in the rom database?

**Comment by pokemonfan6498** [comment]
I guess translated aren't
