### ISSUE TITLE
Ability to disable all onscreen messages including the OSD from config file

### ISSUE THREAD

**Issue by DamienHillBoy** [openMSX/openMSX#1609]
I use OpenMSX in Batocera. Unfortunately, on startup, the osd and various messages are displayed on screen. It would be really conveniant if this could be disabled in the config file.

**Comment by MBilderbeek** [comment]
Try this:

1)  turn "menu" button off.
Open console (F10):
set osd_menu_button off
save_settings

2) remove LED icons at the bottom of the screen.
Open console (F10):
load_icons none
save_settings

3) hide reverse bar at he top of the screen.
Open console (F10):
set auto_enable_reverse off
save_settings

What's still left with these settings applied?

**Comment by DamienHillBoy** [comment]
There is an automated screenshot message at the start and a psg message when the game starts. Unfortunately, Settings are not saved in Batocera. Ik was able to do the things you mentioned by editing the openmsx script files. Only the two messages below remain. It would be really convenient if all on screen messages could be disabled within the settings  file
![PSG port Message](https://github.com/openMSX/openMSX/assets/166705058/1814dd18-f37a-446a-93e5-267ba116c446)
![Screenshot taken Message](https://github.com/openMSX/openMSX/assets/166705058/bb67c4f6-3c00-4b7c-a7b8-e59e6a8cbec6)

**Comment by MBilderbeek** [comment]
> There is an automated screenshot message at the start and a psg message when the game starts. Unfortunately, Settings are not saved in Batocera. Ik was able to do the things you mentioned by editing the openmsx script files. Only the two messages below remain. It would be really convenient if all on screen messages could be disabled within the settings  file
> ![PSG port Message](https://github.com/openMSX/openMSX/assets/166705058/1814dd18-f37a-446a-93e5-267ba116c446)
> ![Screenshot taken Message](https://github.com/openMSX/openMSX/assets/166705058/bb67c4f6-3c00-4b7c-a7b8-e59e6a8cbec6)
> 
> 

Why are settings not saved? What about specifying a settings.xml?

Why is it making a screenshot orsaving a state at start? That's not default behaviour.

The PSG message can also be overridden with a setting, but I am at this moment not sure what the value should be to disable it. See the invalid_psg_directions_callback setting.

There is also a way to redefine the message handler, which currently puts all these messages in a pop up.

**Comment by MBilderbeek** [comment]
> There is an automated screenshot message at the start and a psg message when the game starts. Unfortunately, Settings are not saved in Batocera. Ik was able to do the things you mentioned by editing the openmsx script files. Only the two messages below remain. It would be really convenient if all on screen messages could be disabled within the settings  file
> ![PSG port Message](https://github.com/openMSX/openMSX/assets/166705058/1814dd18-f37a-446a-93e5-267ba116c446)
> ![Screenshot taken Message](https://github.com/openMSX/openMSX/assets/166705058/bb67c4f6-3c00-4b7c-a7b8-e59e6a8cbec6)
> 
> 

Why are settings not saved? What about specifying a settings.xml?

Why is it making a screenshot orsaving a state at start? That's not default behaviour.

The PSG message can also be overridden with a setting, but I am at this moment not sure what the value should be to disable it. See the invalid_psg_directions_callback setting.

There is also a way to redefine the message handler, which currently puts all these messages in a pop up.

**Comment by m9710797** [comment]
Hi. I confirm what MBilderbeek said. Just some small additions.

In the current in-development openMSX version we're totally reworking the OSD stuff. It will be replaced with an integrated GUI.
This may fix some of the items you mentioned, but it may also introduce new issues for you. I'm not familiar with 'Batocera' nor your specific use case, so I cannot predict what those issue might be (if any).

I think in the new openMSX version all the OSD elements that were mentioned here (LEDs, reversebar, messages) can be re-configured to be hidden. But it's not the default, so it does rely on saving settings.

**Comment by DamienHillBoy** [comment]
I wait for the new version then. batocera is a retrogaming distro --> batocera.org

**Comment by DamienHillBoy** [comment]
By the way
I tried this on my a standalone openmsx. But the setting was not saved. The settings file however WAS saved

remove LED icons at the bottom of the screen.
Open console (F10):
load_icons none
save_settings

**Comment by MBilderbeek** [comment]
The settings file should contain (after saving) settings names `osd_leds_set` and possibly `osd_leds_pos`. Via these internal settings, the selected OSD icon set is saved.

It might be good to try and figure out why you can't save settings on your distro. As mentioned earlier, you could prepare a settings file on your standalone installation and pass it to the openMSX on batocera on the command line.

**Comment by DamienHillBoy** [comment]
No, i did this on a normal openmsx install and it did not work

**Comment by MBilderbeek** [comment]
Can you tell me step by step what you did and how you checked whether it worked? Perhaps sounds silly, but this is very common stuff that should simply work everywhere.

**Comment by DamienHillBoy** [comment]
strange, tried it again and now it does work. Sorry for the commotion

**Comment by MBilderbeek** [comment]
Good, anything else regarding this issue? If not, then please close the issue.

**Comment by DamienHillBoy** [comment]
I'll close it then

**Comment by MBilderbeek** [comment]
OK thanks. Please let us know again if you find issues with openMSX. Also, please feel free to try out a recent development build and give us feedback on that.
