### ISSUE TITLE
Compilation on macOS version 13 or lower (apple clang 14.0.3 and lower) fails

### ISSUE THREAD

**Issue by gilbertfrancois** [openMSX/openMSX#1618]
I tried to compile the latest master version [4e5fa9d](https://github.com/openMSX/openMSX/commit/4e5fa9db0a12d5795e1b90d4a27e6645f61d4726) on two of my (x86_64) macOS machine, but it breaks at the same point. However, on an M2 machine, it works. I don't know what commit changed it from working to not working. I had a version with the new GUI successfully compiled on these machines in the recent past.

I tried compiling with clang++ 18 (llvm 18 from homebrew) instead of the clang++ 14 shipped with Xcode, but that did not solve the problem.

iMac running macOS 12 (x86_64): compilation error
Macbook Pro running macOS 13 (x86_64): compilation error
Macbook Air running macOS 14 (arm64): works

```
$ clang++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
Creating derived/x86_64-darwin-opt-3rd/config/components_defs.mk...
Using Python: python3
Build configuration:
  Platform: x86_64-darwin
  Flavour:  opt
  Compiler: clang++
  Subset:   full build
Creating derived/x86_64-darwin-opt-3rd/config/Version.ii...
Creating derived/x86_64-darwin-opt-3rd/config/build-info.hh...
Creating derived/x86_64-darwin-opt-3rd/config/components.hh...
Compiling Autofire.cc...
In file included from src/Autofire.cc:1:
In file included from src/Autofire.hh:4:
In file included from src/DynamicClock.hh:4:
In file included from src/EmuTime.hh:4:
In file included from src/EmuDuration.hh:5:
In file included from src/serialize.hh:4:
In file included from src/serialize_core.hh:5:
In file included from src/serialize_meta.hh:5:
src/utils/xxhash.hh:65:16: error: no member named 'bit_cast' in namespace 'std'
                return *std::bit_cast<const uint32_t*>(ptr);
                        ~~~~~^
src/utils/xxhash.hh:65:25: error: expected expression
                return *std::bit_cast<const uint32_t*>(ptr);
                                      ^
src/utils/xxhash.hh:129:26: error: no member named 'bit_cast' in namespace 'std'
        const auto* data = std::bit_cast<const uint8_t*>(key.data());
                           ~~~~~^
src/utils/xxhash.hh:129:35: error: expected expression
        const auto* data = std::bit_cast<const uint8_t*>(key.data());
                                         ^
src/utils/xxhash.hh:131:11: error: no member named 'bit_cast' in namespace 'std'
        if (std::bit_cast<intptr_t>(data) & 3) {
            ~~~~~^
src/utils/xxhash.hh:131:20: error: unexpected type name 'intptr_t': expected expression
        if (std::bit_cast<intptr_t>(data) & 3) {
                          ^
In file included from src/Autofire.cc:1:
In file included from src/Autofire.hh:4:
In file included from src/DynamicClock.hh:4:
In file included from src/EmuTime.hh:4:
In file included from src/EmuDuration.hh:5:
In file included from src/serialize.hh:6:
In file included from src/utils/StringOp.hh:4:
In file included from src/utils/IterableBitSet.hh:4:
src/utils/ranges.hh:487:24: error: no member named 'bit_cast' in namespace 'std'
        return std::span{std::bit_cast<const uint8_t*>(s.data()), s.size_bytes()};
                         ~~~~~^
src/utils/ranges.hh:487:33: error: expected expression
        return std::span{std::bit_cast<const uint8_t*>(s.data()), s.size_bytes()};
                                       ^
src/utils/ranges.hh:485:59: warning: unused parameter 's' [-Wunused-parameter]
[[nodiscard]] inline auto as_byte_span(std::span<T, Size> s)
                                                          ^
In file included from src/Autofire.cc:1:
In file included from src/Autofire.hh:4:
In file included from src/DynamicClock.hh:4:
In file included from src/EmuTime.hh:4:
In file included from src/EmuDuration.hh:5:
In file included from src/serialize.hh:7:
src/config/XMLElement.hh:116:35: error: 'ChildRange' does not refer to a value
        static_assert(std::ranges::range<ChildRange>);
                                         ^
src/config/XMLElement.hh:111:9: note: declared here
        struct ChildRange {
               ^
src/config/XMLElement.hh:116:16: error: no member named 'range' in namespace 'std::ranges'; did you mean 'rand'?
        static_assert(std::ranges::range<ChildRange>);
                      ^~~~~~~~~~~~~~~~~~
                      rand
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:162:6: note: 'rand' declared here
int      rand(void) __swift_unavailable("Use arc4random instead.");
         ^
In file included from src/Autofire.cc:1:
In file included from src/Autofire.hh:4:
In file included from src/DynamicClock.hh:4:
In file included from src/EmuTime.hh:4:
In file included from src/EmuDuration.hh:5:
In file included from src/serialize.hh:7:
src/config/XMLElement.hh:116:46: error: expected expression
        static_assert(std::ranges::range<ChildRange>);
                                                    ^
src/config/XMLElement.hh:154:35: error: 'NamedChildRange' does not refer to a value
        static_assert(std::ranges::range<NamedChildRange>);
                                         ^
src/config/XMLElement.hh:148:9: note: declared here
        struct NamedChildRange {
               ^
src/config/XMLElement.hh:154:16: error: no member named 'range' in namespace 'std::ranges'; did you mean 'rand'?
        static_assert(std::ranges::range<NamedChildRange>);
                      ^~~~~~~~~~~~~~~~~~
                      rand
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:162:6: note: 'rand' declared here
int      rand(void) __swift_unavailable("Use arc4random instead.");
         ^
In file included from src/Autofire.cc:1:
In file included from src/Autofire.hh:4:
In file included from src/DynamicClock.hh:4:
In file included from src/EmuTime.hh:4:
In file included from src/EmuDuration.hh:5:
In file included from src/serialize.hh:7:
src/config/XMLElement.hh:154:51: error: expected expression
        static_assert(std::ranges::range<NamedChildRange>);
                                                         ^
src/config/XMLElement.hh:176:35: error: 'AttributeRange' does not refer to a value
        static_assert(std::ranges::range<AttributeRange>);
                                         ^
src/config/XMLElement.hh:171:9: note: declared here
        struct AttributeRange {
               ^
src/config/XMLElement.hh:176:16: error: no member named 'range' in namespace 'std::ranges'; did you mean 'rand'?
        static_assert(std::ranges::range<AttributeRange>);
                      ^~~~~~~~~~~~~~~~~~
                      rand
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:162:6: note: 'rand' declared here
int      rand(void) __swift_unavailable("Use arc4random instead.");
         ^
In file included from src/Autofire.cc:1:
In file included from src/Autofire.hh:4:
In file included from src/DynamicClock.hh:4:
In file included from src/EmuTime.hh:4:
In file included from src/EmuDuration.hh:5:
In file included from src/serialize.hh:7:
src/config/XMLElement.hh:176:50: error: expected expression
        static_assert(std::ranges::range<AttributeRange>);
                                                        ^
In file included from src/Autofire.cc:1:
In file included from src/Autofire.hh:4:
In file included from src/DynamicClock.hh:4:
In file included from src/EmuTime.hh:4:
In file included from src/EmuDuration.hh:5:
In file included from src/serialize.hh:8:
In file included from src/config/XMLOutputStream.hh:4:
src/config/XMLEscape.hh:30:11: error: no matching constructor for initialization of 'std::string_view' (aka 'basic_string_view<char>')
                        output(std::string_view(chunk, it));
                               ^                ~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/string_view:267:5: note: candidate constructor not viable: no known conversion from 'const char *' to 'std::basic_string_view::size_type' (aka 'unsigned long') for 2nd argument; dereference the argument with *
    basic_string_view(const _CharT* __s, size_type __len) _NOEXCEPT
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/string_view:261:5: note: candidate constructor not viable: requires 1 argument, but 2 were provided
    basic_string_view(const basic_string_view&) _NOEXCEPT = default;
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/string_view:276:5: note: candidate constructor not viable: requires single argument '__s', but 2 arguments were provided
    basic_string_view(const _CharT* __s)
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/string_view:258:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    basic_string_view() _NOEXCEPT : __data (nullptr), __size(0) {}
    ^
In file included from src/Autofire.cc:1:
In file included from src/Autofire.hh:4:
In file included from src/DynamicClock.hh:4:
In file included from src/EmuTime.hh:4:
In file included from src/EmuDuration.hh:5:
In file included from src/serialize.hh:8:
In file included from src/config/XMLOutputStream.hh:4:
src/config/XMLEscape.hh:38:11: error: no matching constructor for initialization of 'std::string_view' (aka 'basic_string_view<char>')
                        output(std::string_view(chunk, it));
                               ^                ~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/string_view:267:5: note: candidate constructor not viable: no known conversion from 'const char *' to 'std::basic_string_view::size_type' (aka 'unsigned long') for 2nd argument; dereference the argument with *
    basic_string_view(const _CharT* __s, size_type __len) _NOEXCEPT
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/string_view:261:5: note: candidate constructor not viable: requires 1 argument, but 2 were provided
    basic_string_view(const basic_string_view&) _NOEXCEPT = default;
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/string_view:276:5: note: candidate constructor not viable: requires single argument '__s', but 2 arguments were provided
    basic_string_view(const _CharT* __s)
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/string_view:258:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
    basic_string_view() _NOEXCEPT : __data (nullptr), __size(0) {}
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make[1]: *** [derived/x86_64-darwin-opt-3rd/obj/Autofire.cc.o] Error 1
make: *** [staticbindist] Error 2
```

**Comment by MBilderbeek** [comment]
Strange, perhaps clang is totally missing std::bit_cast for some architectures? 
According to https://en.cppreference.com/w/cpp/numeric/bit_cast we do include the proper header file.

**Comment by m9710797** [comment]
Hi Gilbert,

You're using a too old version of clang. We recently started requiring at
least version 15.
Note that version is the "real" clang version number. For some reason the
"apple clang" version numbers are still completely different, very
confusing (see https://en.cppreference.com/w/cpp/compiler_support/20,
compare the 'clang' and 'apple clang' columns).

Wouter

**Comment by gilbertfrancois** [comment]
I'm investigating it at the moment. It will take a bit of time.

**Comment by gilbertfrancois** [comment]
The recent adoption of modern C++ makes it very hard to compile openMSX. I fear that if this trend is continuing, we are not able to compile for macOS at all. Until not so long ago, compiling with different compilers worked like a breeze. I hope we can go back to supporting at least the latest apple clang version, so that installing additional clang versions is not needed. I don't think it is a macOS specific problem, since I used vanilla clang versions from [llvm.org](https://llvm.org) (via homebrew).

All compilation logs are attached at the end of this comment.

Note that **apple clang 14.0.3** and **clang 16** seem to behave similar.

| compiler | status |  requirements |
|-- |-- |-- |
| apple clang 15.0.0 | success | macOS 14, Xcode 15 |
| apple clang 14.0.3  | error | macOS 13, Xcode 14 |
| clang 15.0.7  | error | homebrew |
| clang 16.0.6  | error | homebrew |
| clang 17.0.6  | success | homebrew |
| clang 18.1.5  | error | homebrew |


[log_apple_clang_14.0.3.txt](https://github.com/openMSX/openMSX/files/15214575/log_apple_clang_14.0.3.txt)
[log_clang_15.0.7.txt](https://github.com/openMSX/openMSX/files/15214576/log_clang_15.0.7.txt)
[log_clang_16.0.6.txt](https://github.com/openMSX/openMSX/files/15214577/log_clang_16.0.6.txt)
[log_clang_17.0.6.txt](https://github.com/openMSX/openMSX/files/15214578/log_clang_17.0.6.txt)
[log_clang_18.1.5.txt](https://github.com/openMSX/openMSX/files/15214579/log_clang_18.1.5.txt)

**Comment by MBilderbeek** [comment]
Can you explain that it compiles fine on the GitHub Runners under macOS? 
See the images here: https://github.com/actions/runner-images/tree/main look at Included Software for the compilers installed. It seems XCode 15.x should be able to compile openMSX fine.
We are using the macos-latest image for both x86_64 and aarch64 builds. But perhaps we're doing something wrong? (E.g. should we have used macos-latest-large for x86_64?)

**Comment by gilbertfrancois** [comment]
It compiles on apple clang > 15.0.0, which is Xcode 15.x. Xcode 15.3 requires a Mac running macOS Sonoma 14 or later.  That explains why it worked on the machine with M2, but not on the older Intel machines. Only my computer with Apple Silicon can run the latest OS, but my older Intel machines are only able to run macOS 12 (iMac) and macOS 13 (Macbook Pro).

**Comment by MBilderbeek** [comment]
What if you use the clang-15 from brew?

**Comment by gilbertfrancois** [comment]
As you can see [here](https://github.com/openMSX/openMSX/issues/1618#issuecomment-2094957062), I tried with homebrew clang 15, 16, 17 and 18. The logs are included.

**Comment by MBilderbeek** [comment]
Before GitHub upgraded XCode on their runner, we also got it to compile with the brew clang-15... as per the instructions on the installed software list. 
Maybe @grauw has an idea what could be done?

**Comment by gilbertfrancois** [comment]
Maybe we should be less eager to adopt the very latest language features. OpenMSX was usually compatible with many compilers. At the moment it might be a bit too picky, by being incompatible with older _and_ newer compilers.

**Comment by grauw** [comment]
> It compiles on apple clang > 15.0.0, which is Xcode 15.x. Xcode 15.3 requires a Mac running macOS Sonoma 14 or later. That explains why it worked on the machine with M2, but not on the older Intel machines.

Just to be clear, Sonoma runs on Intel machines, but not those from before 2018. (Though theoretically possible by using OpenCore Legacy Patcher.) The runner was indeed previously compiling on macOS 12 using Homebrew llvm 15.0.7, I believe by passing `CXX=$(brew --prefix llvm@15)/bin/clang++` on the command line to the build script. I recently had to [revert](https://github.com/openMSX/openMSX/commit/781e463fc858e1d71b7d1d7748ef8e6fa64c3cf9) that once the build machines updated to macOS 14 since Apple Clang 15 conflicted with LLVM Clang 15.

Not sure what further to add here. I wasn’t involved in the decision to upgrade to Clang 15, but openMSX has always been on the cutting edge of C++ (with its extensive use of modern language features) so I can understand the desire to upgrade the development environment. Of course the minimum requirement for running openMSX builds is not upgraded so easily.

As for `std::bit_cast` specifically, perhaps a shim can be implemented? But I also understood the devs are eagerly awaiting the release of XCode 16 with Apple Clang 16, so there’ll be the same situation a couple months after that releases later this year.

In the end it is a project policy decision I think.

**Comment by grauw** [comment]
> But I also understood the devs are eagerly awaiting the release of clang 16, so there’ll be the same situation a couple months after that releases later this year.

Though since you mentioned that Apple Clang version numbering is not the same as LLVM Clang (confusing…), I just read that Apple Clang 15 is based on LLVM 16 so perhaps that upgrade isn’t necessary.

**Comment by grauw** [comment]
And [here](https://en.cppreference.com/w/cpp/compiler_support) I read that supposedly `std::bit_cast` is supported in Apple Clang 14.0.3 (XCode 14.3), so that’s even more confusing.

**Comment by gilbertfrancois** [comment]
> Just to be clear, Sonoma runs on Intel machines, but not those from before 2018. (Though theoretically possible by using OpenCore Legacy Patcher.) The runner was indeed previously compiling on macOS 12 using Homebrew llvm 15.0.7, I believe by passing `CXX=$(brew --prefix llvm@15)/bin/clang++` on the command line to the build script. I recently had to [revert](https://github.com/openMSX/openMSX/commit/781e463fc858e1d71b7d1d7748ef8e6fa64c3cf9) that once the build machines updated to macOS 14 since Apple Clang 15 conflicted with LLVM Clang 15.

The apple clang follows the version counting of Xcode (apple clang 15 in xcode 15, apple clang 14 in xcode 14, etc). The upstream version of apple clang 15 is llvm 16. Apple adds extra to the llvm toolkit, like Vision Pro support, optimizations for Apple Silicon and Apple Neural Engine, etc.

As stated before, the minimum version of openMSX is not clang-15. As one can see in the table above, brew llvm 15 is in the current situation not sufficient anymore. I suspect that [m9710797](https://github.com/m9710797) uses llvm 17, since that is the only clang version that compiles at the moment. And to repeat myself: apple clang 15 (!= clang 15) works too.

> And [here](https://en.cppreference.com/w/cpp/compiler_support) I read that supposedly `std::bit_cast` is supported in Apple Clang 14.0.3 (XCode 14.3), so that’s even more confusing.

That was indeed solved as soon as I upgraded the apple clang from version 14.0.0 to 14.0.3. But new issues emerged, like missing `std::less`.

**Comment by m9710797** [comment]
Hi,

I'm 100% sure I'm using clang-15 for my tests, But the non-apple-version!

Apple clang is a mess, If you google a bit, you'll find many complaints. E.g. even if apple-clang-15 is based on llvm-16, that doesn't mean all clang-16 features are included in apple-clang-15 .. really a mess. If possible at all, don't use apple-clang.

In openMSX we're using c+++20 (already reasonably well supported in gcc/msvc at the end of 2019). But compared to gcc/msvc, clang is lagging behind. For that reason we're using the latest clang that's available on the github runners, at the moment that's clang-15, but that one doesn't have complete c++20 support yet :(    So once clang-16 is available we'll likely switch to that.

I don't think using c++20 in 2024 is unreasonable. But most important: it's my way of staying interested in openMSX development.

**Comment by MBilderbeek** [comment]
So, how can we explain that it doesn't work with brew vanilla clang-15 on macOS? Although that worked fine on the GitHub Runners...

**Comment by gilbertfrancois** [comment]
> I'm 100% sure I'm using clang-15 for my tests, But the non-apple-version!

**Apple clang 15.0.0** is the one that works, if you look at the table above. **llvm clang-15** does not work and **apple clang 14.0.3** (based on **llvm 15**) does not work either, which is the one that I can use on my older intel machines from 2015 and 2017.  

I initiated this issue with the intention of exploring possibilities for utilizing my older Intel machines to emulate a computer from 1983. Given openmsx's wide user base, I believe it's valuable to maintain its accessibility to the largest possible audience. However, I've discovered that openmsx currently supports C++ versions that necessitate newer machines, operating systems, and compilers. 

While I appreciate the rationale behind adopting C++20 or C++23 in the near future, I must admit feeling a bit conflicted. On one hand, I understand the benefits, yet simultaneously, it saddens me to see these older machines and operating systems excluded from the capability to self-compile openmsx.

I accept the [answer](https://github.com/openMSX/openMSX/issues/1618#issuecomment-2095312702) as resolved and suggest to close the topic.

**Comment by grauw** [comment]
> I initiated this issue with the intention of exploring possibilities for utilizing my older Intel machines to emulate a computer from 1983. Given openmsx's wide user base, I believe it's valuable to maintain its accessibility to the largest possible audience.

The current minimum requirement for running openMSX is macOS Catalina, which supports Mid-2012 Macbook Pro’s. I believe that makes openMSX accessible to the wide general audience on Apple computers.

**Comment by gilbertfrancois** [comment]
No, I'm not. I refer to self compiling and running. Not running only. Especially now, with the transition to this amazing new UI, frequently pulling and working with the latest version brings lots of joy.

**Comment by grauw** [comment]
I get it, just saying (edited to clarify) that I think the need for supporting a wide user base is met. You _can_ run openMSX with the new UI on your Intel Macs (development binaries are built by [GitHub Actions](https://github.com/openMSX/openMSX/actions)). It is not unusual to me that the development environment has a higher requirement, within reason. In that sense, self-compiling is a niche, just like running openMSX on Macs older than 2012. The back-up solution for both of those cases is to use an older openMSX version.

It is unfortunate that Apple links the version of XCode to the macOS version, and thus the Macs it can run on, but at the same time how long is a project expected to let it hold themselves back from adopting newer language features that do bring meaningful value to the developers…

Since you have access to an M2 Mac, you can still cross-compile the current openMSX version for Intel on your M2 Mac, although since the introduction of Apple Silicon that does require signing with an Apple Developer account.

**Comment by grauw** [comment]
Closing per https://github.com/openMSX/openMSX/issues/1618#issuecomment-2099083213.
