### ISSUE TITLE
Breakpoints set at the new GUI not cleared correctly by commands

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/openMSX#1627]
Steps to reproduce it:

-Start OpenMSX
-Open Debugger > Breakpoints
-Add a breakpoint at #0038 (or any other address that is frequently hit) for any slot (X/X)
-Close Breakpoints window
-Close OpenMSX
-Start OpenMSX again. The execution will stop at #0038 (the breakpoint is still there).
-Open Console, type `debug list_bp` and `debug remove_bp bp#1` (or the one returned by list_bp).
-Continue the execution
-Close OpenMSX
-Start OpenMSX. The breakpoint has respawned.

It only happens if the Breakpoint is closed when the `debug remove_bp` command is executed. If the Breakpoint window is open, the breakpoint is correctly cleared with `debug remove_bp`.

Version: OpenMSX 19.1-909
OS: Windows 10 64bit (Intel)

**Comment by m9710797** [comment]
Thanks for reporting!
The hint about "... it only happens when the Breakpoint window is closed ..." was very useful, I think I know what the problem might be. I'll try to verify and fix it this evening.

**Comment by m9710797** [comment]
Fixed. It works for me now. But please also verify.
