### ISSUE TITLE
LED icons and reverse bar move when changing scale factor, but not saving settings

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1633]
Scenario:
- disable auto save on exit (that's what I use all the time, to not mess up my settings unless I explicitly save them)
- use scale factor 4 and have LED/icon bar on the bottom left and reverse bar on the bottom right (hide title)
- set scale factor to 2
- exit openMSX
- start openMSX: scale factor is back to 4, but LED/icons and reverse bar are still on the scale factor 2 position.

**Comment by MBilderbeek** [comment]
This is really pretty annoying, I run into this always when I try different scale factors (temporarily). But I guess most people won't have this situation (disabled auto_save_settings....) @m9710797 is this hard to fix?

**Comment by m9710797** [comment]
Should be fixed now (it works for me). But please verify.

**Comment by MBilderbeek** [comment]
Yes, works fine now, thanks!
