### ISSUE TITLE
ImGUI pop-ups steals focus so MSX doesn't receive key release

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1635]
If you use the default hotkey to save a state (ALT-F8), and the default pop-up is coming over the openMSX window ("screen saved to xxx.png"), the release of the ALT (MSX: Code) key isn't received in the emulated MSX and this causes the MSX Code key to be stuck pressed (until you press it again). Looks like the keyboard is totally going haywire... See a.o. https://www.msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=81 (and the preceding pages, reported by ro)

**Comment by MBilderbeek** [comment]
Some idea, which could be investigated: can we do a key release of all keys if the focus from the main MSX window gets lost?

**Comment by m9710797** [comment]
Should be fixed now. But this could use more testing. I'm reopening this ticket (only) to allow for more test-feedback.

**Comment by MBilderbeek** [comment]
I got confirmation from ro (the original reporter) that it's fixed. I tried to get more people into test. Let's see what happens, but I think this thing can be closed.
