### ISSUE TITLE
PgUp/PgDn to scroll in the history of the console doesn't work anymore

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1636]
In openMSX 19.1 (with the non-ImGUI console), one could use PgUp/PgDn to scroll through the console history, e.g. to look back at earlier output.
This doesn't work anymore since the ImGUI console got introduced.  (At that point, it would also trigger reverse actions in openMSX, even though only the console had focus. That got fixed, but the functionality to scroll back with a keyboard key isn't working anymore.)

**Comment by m9710797** [comment]
Fixed in ffc05953cd4d7bff0556fe105271f633830d5ba0.
