### ISSUE TITLE
Combobox/ListBox: start view at currently active item

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1641]
Cases which I could find where this behaviour is not yet in place:
- Connectors -> <any connector, e.g. MSX joystick port A>
- Machine -> Select MSX Machine -> the list box wint all the machines starts at the top, not at the current item

Requires call to `ImGui::SetItemDefaultFocus()`

**Comment by MBilderbeek** [comment]
@m9710797 I implemented it for the connector selector,but for the machine selector, I couldn't get it to work. There's probably something with the list clipper that interferes. Can you give some hints?

**Comment by m9710797** [comment]
Yes probably. `ListClipper` is a mechanism to only process the items that are actually visible.
But if the item for which you'd want to call `setItemDefaultFocus()` is not visible, then that doesn't work of course.
A possible workaround is to use the `ListClipper` overload on `ImGuiCpp.hh:553`, there you can pass the index of the item that always needs to be processed, even if it is invisible. Though that requires you can easily calculate that index. Or else you can stop using `ListClipper` (but there can be hundreds of machines in the list, so I'd prefer to keep using it).

**Comment by MBilderbeek** [comment]
And with 6593740375d14da37bab0c96978ac8428e5f50a5 this issue can be closed as completed.
