### ISSUE TITLE
The media recent items (in the window) don't contain items that were inserted via drag and drop and console

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1642]
The recent items function would become a lot more useful if all recent items inserted in any way would be listed there.

**Comment by MBilderbeek** [comment]
@m9710797 any idea how we can improve this? 
For dropped items, we could integrate the drop code from Manager into Media and then call `addRecent` with the proper group object. 
But then we don't have the media inserted via console or other places yet. Perhaps we can use some kind of callback from openMSX that a media was inserted and then put that in the recent list instead? (So get the info from the source, instead of the input location.) Then it should work from whatever location the media item is selected.

**Comment by m9710797** [comment]
Implemented in 7003e3f988b4718641ca1d78d269af7a6000075d.

Note that this intentionally only handles drag-and-drop. _Not_ console commands.
In some offline discussion we agreed the console commands should not influence the recently used list (e.g. commands executed via scripts). Also media-inserts done via reverse, or loading savestates, or replay files are excluded.
