### ISSUE TITLE
Hard to find/select machines in machine list

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1643]
Using the scroll wheel in the machine list scrolls 5 lines (which happens to be half a page), instead of entry by entry. That makes it harder to fine select with the scroll wheel.

(This part worked easier in the OSD menu.)

**Comment by m9710797** [comment]
I don't understand this issue ... isn't this how the scroll wheel works in most (almost all) other applications as well? 
You use the scroll wheel to (quickly) approximately go to the desired position (and the list is alphabetically sorted, so this isn't too difficult). Then (fine select) move the cursor to the correct entry and click it.

**Comment by MBilderbeek** [comment]
In the GNOME file browser, scrolling items also scrolls one at a time in a list of files/directories. But let's see what other people think.

**Comment by basalicante** [comment]
I think it's mostly because the scrolling is very chunky and it's easy to lose track of where you are. So basically I don't care if it scrolls 1 or 15 lines, but it'd be nice if there would be some smoothing/interpolation so your eyes can follow where the scroll is going.

Also wouldn't mind if the popup info-window would take a bit more than 0.1 seconds to appear. While scrolling around, it's not really needed and adds to the "disorientation". It's only useful when nearing the "destination" machine. Probably about 1 second of delay would look much better?

**Comment by MBilderbeek** [comment]
@m9710797 I tried to look into this, but I didn't see a way to pass some (experimental, alternative) `ImGuiHoveredFlags` to the tooltip, as it is created with `BeginToolTip`... what's the best approach there?

**Comment by m9710797** [comment]
Do we really need/want custom hover flags per item? My preference would be that tooltips behave the same everywhere, So I'd suggest to just experiment with `ImGuiHoveredFlags_xxx` inside our `im::Tooltip()` helper.

**Comment by MBilderbeek** [comment]
Well, these are 2 things.
1. Whether or not to customize it. In case of this particular list (the machine selector), I can imagine we'd want a slower tooltip. But not on other places, so far. So, yeah, I think this is an exception and it would be interesting to try whether it helps to make the list more usable by choosing the longer delay. But...
2. I have no idea how to manage the flags in this specific case. As I said, how to pass them inside our `im::Tooltip()` helper?

**Comment by m9710797** [comment]
You're not required to use our helper `im::Tooltip()` function. For an experiment you can manually call the underlying `ImGui::xxx` functions (so copy/paste the body of the helper and then modify it). That way you can easily experiment with differnt flags.

IF you do find a set of flags that you like, THEN we can think about generalizing the helper (we've already done this for other helpers).

**Comment by MBilderbeek** [comment]
@basalicante I tried to tweak the delay in the tooltip, can you test? See commit 65c62227dcb79c25c3b3e13f19b2d060a63c1ae4

**Comment by MBilderbeek** [comment]
Although @basalicante still says he'd rather see more smooth scrolling in the lists (so with in-between animation, instead of in steps), he is fine with the current implementation. Therefore, closing this issue.
