### ISSUE TITLE
When doing a step in the console (e.g. `step_back`), the Disassembly view doesn't scroll to the current PC

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1647]
When using the console 'step_back', the 'current instruction bar' in the disassembly view is updated properly, but the view isn't scrolling to keep that bar into view, unlike the toolbar step-back button.

**Comment by m9710797** [comment]
Fixed via d4fac32dcc3fc41f81ba1a7bb76285952e840926.
