### ISSUE TITLE
Extend Symbol Manager to immediately jump to a label or put a break point on that label

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1648]
See title, should be clear. 
This is just about cross linking some functionality.

**Comment by pvmm** [comment]
related to #1632

**Comment by m9710797** [comment]
Setting a breakpoint is already implemented.

TODO: scroll to that position in the disassembly view (ignoring slot).

**Comment by pvmm** [comment]
This can be closed now.

**Comment by m9710797** [comment]
Thanks!
