### ISSUE TITLE
Missing short cut in debugger to toggle break point at current address: CTRL-B

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1656]
As reported, we are missing:
- Toggle break point at current address (CTRL-B in old debugger?)

**Comment by MBilderbeek** [comment]
As this is a regression compared to the old debugger, let's fix this before release.

**Comment by m9710797** [comment]
Implemented via c2baf9d0bb2ffa1fc1f948f3cdc835de32b35233.
