### ISSUE TITLE
Headless control option

### ISSUE THREAD

**Issue by immetoo2** [openMSX/openMSX#1670]
Currently to startup openMSX in headless mode, this needs to be done with xml stdio;
```
<openmsx-control>
	<command>set power on</command>
</openmsx-control>
```
But because of ```-control stdio``` all output is also XML, for example;
```
<openmsx-output>
<reply result="ok">true</reply>
</openmsx-output>
```

Would it be possible to add ```-control headless``` which does an power on and
without renderer and let the rest of the control be handled by TCL scripts.
This would also keep openMSX in normal text output mode.

**Comment by immetoo2** [comment]
For example, running openMSX in xml stdio headless mode on per git push build CI server, gives output like;
```
FAIL_AFTER_BOOT=25 FAIL_AFTER_PATH=bin BOOT_HDD_PATH="bin/test/ahello-sdcc" BOOT_HDD_IMAGE="bin/test/ahello-sdcc/../dsk.img" JOYPORTA= JOYPORTB= SCALE_FACTOR=3 SPEED=333 SAVE_SETTINGS_ON_EXIT=off THROTTLE=off /usr/bin/openmsx -machine Philips_NMS_8250 -ext slotexpander -ext ide -ext ram4mb  -script /srv/gitci/.cache/act/41ac294fe232cd56/hostexecutor/lib/openmsx/boot_env.tcl -script /srv/gitci/.cache/act/41ac294fe232cd56/hostexecutor/lib/openmsx/boot_hdd.tcl -script /srv/gitci/.cache/act/41ac294fe232cd56/hostexecutor/lib/openmsx/fail_after.tcl -script /srv/gitci/.cache/act/41ac294fe232cd56/hostexecutor/lib/openmsx/omsxctl.tcl -control stdio < /srv/gitci/.cache/act/41ac294fe232cd56/hostexecutor/lib/openmsx/boot_stdio.xml
<openmsx-output>
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
<log level="warning">Unable to open SDL audio: ALSA: Couldn&apos;t open audio device: No such file or directory</log>
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: Permission denied
<log level="error">Could not open sequencer: Permission denied</log>
<reply result="ok">true</reply>
</openmsx-output>
grep "SDCC: Hello world..." bin/test/ahello-sdcc/test.out
SDCC: Hello world...from asm.
All assertions completed.
```
This XML gives extra noise to read over, and is the result of just one '''set power on''' command via XML.

**Comment by MBilderbeek** [comment]
I was going to suggest `openmsx -command "set renderer none"`, but that gives an assertion failure and still opens up a window. @m9710797 is there a better way to start up with `none` renderer?

**Comment by immetoo2** [comment]
Note, besides the renderer, it should also do the power on without printing that result command.

As it would be nice remove this 'true' noise; ```time make -s -j5 assert-all```  (note 2th run without compile)
```
=== Writing autoexec.bat for ahello-m80
=== Writing autoexec.bat for ahello-sdcc
=== Writing autoexec.bat for dist-qa-dos1
=== Writing autoexec.bat for dist-qa-dos2
=== Writing autoexec.bat for dist-qa-msx1
=== openMSX Start for ahello-m80
=== openMSX Start for ahello-sdcc
=== openMSX Start for dist-qa-dos1
=== openMSX Start for dist-qa-dos2
=== openMSX Start for dist-qa-msx1
<openmsx-output>
<openmsx-output>
<openmsx-output>
<openmsx-output>
<openmsx-output>
<reply result="ok">true</reply>
<reply result="ok">true</reply>
<reply result="ok">true</reply>
<reply result="ok">true</reply>
<reply result="ok">true</reply>
</openmsx-output>
</openmsx-output>
=== openMSX Done for ahello-sdcc
=== openMSX Done for ahello-m80
SDCC: Hello world...from asm.
M80: Hello world...
</openmsx-output>
=== openMSX Done for dist-qa-msx1
M80: Hello world...
</openmsx-output>
SDCC: Hello world...from asm.
=== openMSX Done for dist-qa-dos2
M80: Hello world...
SDCC: Hello world...from asm.
</openmsx-output>
=== openMSX Done for dist-qa-dos1
All assertions completed.

real    0m0.384s
user    0m1.414s
sys     0m0.908s
```

**Comment by m9710797** [comment]
IMHO something like `-control headless` doesn't make sense: you want to change the default renderer, not the mechanism for how to control openMSX.

So I like MBilderbeek's suggestion to use `-command "set renderer none"`. I did fix the assert that this used to trigger.
HOWEVER this still briefly shows a window. I'll see how easy it is to change that. So I'll keep this ticket open for now.

**Comment by m9710797** [comment]
OK, starting with `set renderer none`, either as a startup command (the `-command` option) or as part of a startup command (the `-script` option) should now result in a "headless" mode.

This required making some changes in the startup order of some stuff (e.g. run startup commands before initializing the renderer). I think this should be fine, but such stuff is always tricky. Let's see how it goes ...

For now I'm closing this ticket.

**Comment by immetoo2** [comment]
@m9710797 Sorry by bad, it was a path, issue now it is working.
