### ISSUE TITLE
Extension xml file from command line

### ISSUE THREAD

**Issue by immetoo2** [openMSX/openMSX#1672]
When running openMSX from managed script, sometimes it is needed to have a custom extension device for own or newer ROM file to run with.

Currently this is the only thing in openMSX which needs to be copyed to an openMSX install managed location to use.
But this pollution of non-version managed files in the end-user folder may conflicted with user or other script managed extensions in the common shared extension folders.

For example currently after coping extensions, you run with ```-ext mydev1 -ext mydev2```.
I would be great to also have an option to run with ```-extxml path/to/mydev1.xml -extxl path/to/mydev2.xml```

And thinking of it adding a ```-romdir path/to/myrom/folders``` would complete this fully.

**Comment by MBilderbeek** [comment]
The concept is that you have the extensions that come with the openMSX distributation in another location than your own extensions. The former are put there by the installer/packagemanager on a system wide basis. But in your home folder, you can put your own extensions, as well as ROM files, machine configuration, etc.

So, put your own stuff in your home folder's share folder, see http://openmsx.org/manual/setup.html#romlocation for the locations on different platforms. Never a need to change your installation!

**Comment by immetoo2** [comment]
Same is also true for custom machines, so may a shortcut is adding a override like ```-sharedir ~/.openMSX/share``` results in running openMSX without putting stuff into the home folder. (of the user of the user or a your home folder)

**Comment by MBilderbeek** [comment]
You can override the location of the folders as described here: http://openmsx.org/manual/setup.html#settings in the last part of that section.

**Comment by immetoo2** [comment]
RTFM for me, sorry for that.
This removes last possible problems with running parallel system roms tests.
