### ISSUE TITLE
Doc update optional exit code

### ISSUE THREAD

**Issue by immetoo2** [openMSX/openMSX#1674]
The [exit](https://openmsx.org/manual/commands.html#exit) usage is missing the exit code;
```
exit 	Exits the emulator
```
Suggested doc text;
```
exit [exit-code] 	Exits the emulator with optional exit code
```

**Comment by m9710797** [comment]
Thanks! I've changed it.
(Though the sentence above already talked about the exit code, I didn't repeat that part.)
