### ISSUE TITLE
Debugger; auto reload symbol files when their content changes (a new compilation was done)

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1693]
There's now a way to manually reload them, but the old Debugger loaded it automatically. 
The nicest way requires some platform specific code, but perhaps we can make a simpler mechanism that polls the modification time of all opened symbol files on a low frequency?

**Comment by m9710797** [comment]
This seems to be a duplicate of https://github.com/openMSX/openMSX/issues/1668
I'm closing this one.
