### ISSUE TITLE
[Feature] Initialize existing harddisk image / create it initialized [sf#146]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#170]
**Reported by manuelbi on 2007-03-27 19:31 UTC**
&lt;Quibus&gt; turbor: is there a way to format an existing hard disk iamge with diskmanipulator?
&lt;turbor&gt; you should be able to format the partitions yes, repartitioning.. no.
&lt;Quibus&gt; I mean, when you start openMSX you get an empty 100MB disk image
&lt;Quibus&gt; can you partition and initialize this existing image?
&lt;turbor&gt; ah, I don't think so, since that would require creating partitions
&lt;turbor&gt; I wonder if you can format hda itself, so no partitions
&lt;turbor&gt; but then you end up with at max 32M usable of those 100M
&lt;turbor&gt; but I guess you can 'set power off' and then 'create' a new file over the old 100 MB one...
&lt;Quibus&gt; it's a bit weird that you need the MSX FDISK.COm to initialize an existing harddisk image, while you can create new ones which are already partitioned/iniitialzed directly with dm
&lt;turbor&gt; So we need to alter openMSX, so that if it detects that no HD image exists it uses dm to create one instead of simply creating a 100MB file...

Or, make it possible to format/partition/initialize an existing harddisk image.

**Comment by grauw** [comment]
Resolved by https://github.com/openMSX/openMSX/commit/eca8328384ce43277c0e3675f8be40ec502beb37.
