### ISSUE TITLE
Unable to move the main window after unplugging a monitor

### ISSUE THREAD

**Issue by aoineko-fr** [openMSX/openMSX#1706]
Reproduction :
- Connect a 2nd screen,
- Move openMSX to the 2nd screen,
- Disconnect 2nd screen,
- OpenMSX can no longer be returned to the 1st screen.

The only solution at present is to delete the share/imgui.ini file.

Version: openMSX 19.1-575-g9a8dcad6 (mingw32, x86_64)
System: Windows 11 (64-bit)

**Comment by MBilderbeek** [comment]
@aoineko-fr can you please check with the latest development build? You seem to have a quite old one.... but even worse: I can't even find back that revision at all.

**Comment by MBilderbeek** [comment]
@aoineko-fr any news?

**Comment by aoineko-fr** [comment]
What Windows version would like me to test?

The last version available on https://archive.org/download/openMSX_Windows_Bin is "openmsx-19.1-1033-g7c0909fe5-windows-vc-x64-bin.zip" (25-Jul-2024 19:45). Is this one OK?

**Comment by MBilderbeek** [comment]
Sure, that one is 500 commits newer :)

**Comment by aoineko-fr** [comment]
I can reproduce the bug with version 19.1-1033-g7c0909fe5 with exactly the same reproduction steps.

**Comment by MBilderbeek** [comment]
@ocornut anything we can do about this? Should it be checked whether coordinates of windows are still valid before restoring them?

**Comment by ocornut** [comment]
What are the monitor and windows coordinates when the bug happens? Normally when a monitor gets removed the window gets moved back to primary monitor, i believe there’s code for that so i would need more details and/or a repro or a video of it happening with relevant metrics infos being visite (monitors bounds, window pos)

**Comment by aoineko-fr** [comment]
I had negative value in the `windowPos` parameter in share/imgui.ini when bug happened.
Setting manually positive value fix the bug.
```ini
[openmsx][manager]
windowPos=[ 100 100 ]
```

**Comment by ocornut** [comment]
Negative coordinates are not invalid.
Please confirm the monitor data submitted to dear imgui before/after unplugging.

**Comment by aoineko-fr** [comment]
>Please confirm the monitor data submitted to dear imgui before/after unplugging.

Don't know what you are talking about.
When the second monitor is plugged and if I move openMSX to that monitor, `windowPos` become negative.
If a close & reopen openMSX, it appear at the right position on the 2nd monitor.
If the second monitor is unpluged, the value still negative but there is now no way to bring openMSX back to the main monitor.

Note that if I set the second monitor to be right to main one, the value is positive but beyond the 1920 width of my main monitor.
This generate the exact same bug.

So the fix should be:
- Check if `windowPos` is inside valid screen space (depending of connected monitors, their position and their resolution)
- If not, reset `windowPos` to valid coordinate (`[ 0 0 ]` for example)

**Comment by ocornut** [comment]
Dear ImGui (which Openmsx uses) already does a check like that, this is why I am asking what Dear ImGui knowledge of monitor data is. I don’t work on openmsx and i don’t know how to access that data from openmsx. would prefer a bug report be submitted with appropriate data points so i can investigate it.

**Comment by MBilderbeek** [comment]
I'm sure @m9710797 can help out here.

**Comment by ocornut** [comment]
If openMSX team wants to investigate, fyi

```cpp
// When not moving ensure visible in its monitor
// Lost windows (e.g. a monitor disconnected) will naturally moved to the fallback/dummy monitor aka the main viewport.
const ImGuiPlatformMonitor* monitor = GetViewportPlatformMonitor(window->Viewport);
visibility_rect = ImRect(monitor->WorkPos, monitor->WorkPos + monitor->WorkSize);
```
```cpp
const ImGuiPlatformMonitor* ImGui::GetViewportPlatformMonitor(ImGuiViewport* viewport_p)
{
    ImGuiContext& g = *GImGui;
    ImGuiViewportP* viewport = (ImGuiViewportP*)(void*)viewport_p;
    int monitor_idx = viewport->PlatformMonitor;
    if (monitor_idx >= 0 && monitor_idx < g.PlatformIO.Monitors.Size)
        return &g.PlatformIO.Monitors[monitor_idx];
    return &g.FallbackMonitor;
}
```
**Interestingly I noticed that FallbackMonitor is not actually setup if the backend filled monitors data.** So there is likely a bug:
https://github.com/ocornut/imgui/commit/4b9bc4902084a4a7171d6d4339717c9ecb121ccf
But I'm not sure how this specific bug would affect you as the fallback monitor would be close to matching primary monitor anyhow. In this instance `FindPlatformMonitorForRect()` will likely always return monitor 0 anyhow.

**Comment by m9710797** [comment]
Hi,

I was on vacation. I'm only reading this issue now.
The issue is about the main openMSX window. That one is managed by openMSX itself, not by Dear ImGui. Nevertheless ocornut's comments were useful for pointing me in the right direction. Thanks!

@aoineko-fr Can you retest with the latest version? Could you also try with some non-main window? (E.g. the console-window (F10), or some of the debug-windows). From what I understood from the discussion above non-main windows (windows under control of Dear ImGui) should already be restored correctly. But it's good to test anyway. Unfortunately I can't easily test myself with multiple monitors.

Thanks.
