### ISSUE TITLE
Throttle off does not work when pumping data to the OPL4 wave port

### ISSUE THREAD

**Issue by bengalack** [openMSX/openMSX#1708]
On my windows version of openmsx 19.1 and the new version in the 19.x series (latest: 19.1-1008-ga3e708169-windows-vc-x64) I get slowdowns during operation when I attempt to use "throttle off", during special circumstances. Typically I want to speed up the initialization code to get right into the action with no wait, when kicking off a debug-session. This does not work with my latest OPL4/Moonsound development.

I've removed anything in my program to isolate things. What seems to be needed is to initialize the (opl4-part of the) chip, and then the issue occurs when data is pumped to the wave data port: 0x7F. Code is:

```
int main()
{
    opl4_init();
    opl4_uploadWaveKit();

spin: goto spin;

    return 0;
}
```

I'm adding a rom-file which tries to pump up 640 kB of data to this port. It is supposedly an ASCII16 cart and it will try to access certain data segments to read from . These segments are not included in this example, as the data-source did not seem to matter.

Start rom by using this command (machine can be whatever): `openmsx.exe -ext moonsound -machine Sanyo_phc-70FD2 -cart startup.rom -romtype ASCII16`

Then, get the reversebar up and running, and turn on the "FF / Fast forward" or throttle off functionality. See that everything runs super fast, until the opl4_uploadWaveKit is hit, and that super speed kicks in again when code gets to "spin".

I can add the source code too if needed, but the rom-file attached is probably sufficient?

Note that this works fine in openmsx18.

[startup.zip](https://github.com/user-attachments/files/16246337/startup.zip)

**Comment by m9710797** [comment]
Thanks for reporting! The test-rom was very useful to investigate this.
Should be fixed now. See commit message of 01c42ba4145a612645213599185df59acced9e04 for lots more details.

**Comment by bengalack** [comment]
Thanks a lot!! That was fast :)
