### ISSUE TITLE
OpenMSX instance inherits breakpoints from another running instance

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/openMSX#1714]
Steps to reproduce:

- Open an OpenMSX instance.
- Start debugging a program.
- Add a number of breakpoints, watchpoints or conditions. Among others, add a breakpoint at #4010 X/X.
- Open another OpenMSX instance with a different game/program (especially one that executes at #4010).
- The new instance will stop at #4010 even if no BP has been added to it. It seems to inherit debugging settings from the other instance, what is very annoying if you need to have two different instances for different (or temporary) purposes at once.
- It seems that the issue only happens on start up, but after that, debugging settings are not synced between instances. In other words, if now I do `debug remove_bp bp#13` on instance B, said breakpoint does not dissappear from instance A.

**Comment by MBilderbeek** [comment]
Stuff like watchpoints and breakpoints were saved before fixing #1665 - can you please check with the latest openMSX code?
There is no syncing at all. There's (or was) just saving in a single file and the 2nd instance loads from the same file.

**Comment by MBilderbeek** [comment]
@Colpocorto any feedback with the latest version?

**Comment by Colpocorto** [comment]
> @Colpocorto any feedback with the latest version?

Sorry, I've been very busy lately. I'll try to check it out by today or tomorrow.

Thank yor for your patience.

**Comment by MBilderbeek** [comment]
@Colpocorto can you please check whether this issue is still relevant and if not, close the issue? Thanks.

**Comment by Colpocorto** [comment]
I've just checked this issue isn't reproducing anymore with the latest version. I'm closing the ticket.
Thank you.
