### ISSUE TITLE
Build issue on MacOS

### ISSUE THREAD

**Issue by S0urceror** [openMSX/openMSX#1716]
I probably run the latest Python and use HomeBrew as my open source package manager. For this I had to make two tweaks:

In makeutils.py:
<img width="332" alt="image" src="https://github.com/user-attachments/assets/7a68ad1b-a7c0-4b55-a577-b4ed17b61a4b">

In probe.py:
<img width="597" alt="image" src="https://github.com/user-attachments/assets/17131401-bed0-449c-b99a-451511a33899">

I'll try to make a proper PR when I have sorted out my GitHub stuff.

**Comment by MBilderbeek** [comment]
@mthuurne can you check whether these changes make sense to you?

**Comment by mthuurne** [comment]
Making the regular expression (`_reEval`) a raw string is definitely a good practice.

I can't verify that the patch works, as I no longer have a working Mac, but it makes sense to me.

I'd like some cosmetic changes though:
- the [project website](https://brew.sh/) spells the name as "Homebrew" rather than "HomeBrew"
- "user local libraries" -> "local libraries", as `/usr/local` is a location for system-wide libraries

**Comment by MBilderbeek** [comment]
So, technically, that first change isn't really needed, is it, @S0urceror ?

**Comment by S0urceror** [comment]
@MBilderbeek, I think it depends on the Python version. 

I run:
```Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin```

And if I remove the suggested change for the first issue I get:
```
/build/makeutils.py:43: SyntaxWarning: invalid escape sequence '\$'
  _reEval = re.compile('(\$\(|\))')
Cleaning up...
```

When I encountered this I read [this](https://stackoverflow.com/questions/50504500/deprecationwarning-invalid-escape-sequence-what-to-use-instead-of-d) article and implemented the fix as suggested.

So I guess this is technically needed...

**Comment by S0urceror** [comment]
@mthuurne, understand the reasoning about /usr/local libraries as system wide. I added the printf to assist in debugging and for clarity. Feel free to use other wording to inform the user which libraries are being chosen to compile against.

**Comment by MBilderbeek** [comment]
> @MBilderbeek, I think it depends on the Python version.
> 
> I run: `Python 3.12.4 (main, Jun 6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin`
> 
> And if I remove the suggested change for the first issue I get:
> 
> ```
> /build/makeutils.py:43: SyntaxWarning: invalid escape sequence '\$'
>   _reEval = re.compile('(\$\(|\))')
> Cleaning up...
> ```
> 
> When I encountered this I read [this](https://stackoverflow.com/questions/50504500/deprecationwarning-invalid-escape-sequence-what-to-use-instead-of-d) article and implemented the fix as suggested.
> 
> So I guess this is technically needed...

I guess so. But I run the same Python version, but I guess the code doesn't trigger on Linux. Anyway, I already fixed this part now in git. So, the rest of your patch is about adding support for brew?

**Comment by S0urceror** [comment]
@MBilderbeek , yes that is for homebrew support on the Mac M1/M2 series of processors. On Intel it was still using /usr/local. More info [here](https://docs.brew.sh/Installation)

**Comment by MBilderbeek** [comment]
OK, best thing would be to create a PR for this, so it can be run on GitHub Actions before we merge. Can you do that and link to this issue?

**Comment by mthuurne** [comment]
Ah, it seems Python 3.12 has become more strict about escapes. In Python 3.11 it also works without a raw string and it produced the same regex there. So this is a bug fix every platform needs once they upgrade to Python 3.12.

**Comment by MBilderbeek** [comment]
@S0urceror as we want to release really soon, please submit your patch a.s.a.p....

**Comment by S0urceror** [comment]
@MBilderbeek, I'm sorry, initially I hoped you could work with the code snippets provided. But understand a proper PR is better. I'll get this sorted tonight and update here.

**Comment by S0urceror** [comment]
@MBilderbeek, PR is created. Saw that the change for makeutils.py was already applied by the openmsx team. Good luck merging and releasing a new and wonderful version of openmsx.
