### ISSUE TITLE
Move disasmCommand() and disasmBlobCommand() out of CPUCore

### ISSUE THREAD

**Issue by pvmm** [openMSX/openMSX#1718]
I fully understand you copied the existing pattern. So this is a remark against the code I've written.

I don't like that `disasmCommand()` and now also `disasmBinCommand()` is implemented in CPUCore: to disassemble something you don't need access to the active CPU state. There are two exceptions:
* The `PC` (for the `disasm` command, I already proposed to not use `PC` for `disasm_bin`). But we can instead query the PC from the active CPU instead of implementing disassembling in the CPU emulation code.
* The active time, because that's needed in peekMem(). This only applies to `disasm`, not `disasm_bin`. But again we can query this time and keep the actual disassembly code outside the CPUCore class.

I'm adding this as a review comment, but I don't expect you to 'fix' this very old design decision. You can of course, but I think it should be done in a separate commit (within this PR or as a separate PR). Or I can do it afterwards.

_Originally posted by @m9710797 in https://github.com/openMSX/openMSX/pull/1717#discussion_r1705831598_

**Comment by m9710797** [comment]
Implemented in d8f2b478bf0e33066fd9872155c067e93b24e39b.
