### ISSUE TITLE
Be able to fast-forward or rewind to a specific tape position

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1725]
Like on a real tapedeck you should be able to fast forward to a certain index in the tape, so you can load a later program on that same tape, without having to skip through earlier programs.

The use case is running not the first but a later program on multi-game tape. Rare, sure. But they exist.

**Comment by m9710797** [comment]
Is the implementation in 9791f0245b0d8ac22fe481cb243c856743f3ad3a and 95d6b54c8e7e9265cab2b10193663eee9e442691 sufficient to close this issue?
