### ISSUE TITLE
Assertion failure or crash when setting CPU speed too high

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1728]
This happens at least in openMSX 19.1 and the current development version. If you play around with the Z80 speed whilst running a game like Goonies, you can get an assertion failure like this:
`openmsx: src/video/VDP.cc:656: virtual void openmsx::VDP::writeIO(openmsx::word, openmsx::byte, openmsx::EmuTime::param): Assertion `isInsideFrame(time)' failed.`

I couldn't reproduce a crash in an optimized build, but on Windows doing this can cause a crash apparently: 

https://github.com/user-attachments/assets/65ccc72e-466f-4200-9b15-a4e718923ebb

**Comment by m9710797** [comment]
Possibly (likely?) fixed in e06ec4e06eba613331f35f2784fc70bc452a586f.

Before this patch I could reproduce the crash (though not 100% reliable).
After this patch I cannot reproduce it anymore.

But more testing won't hurt. I'll keep this ticket open for now.

**Comment by MBilderbeek** [comment]
Confirmed fixed by inchl, who submitted the issue.
