### ISSUE TITLE
CPU unlock/frequency edit is saved, but "ignore VDP access timing" is not

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1729]
Users who play around with higher speeds are confronted with this (seeming) inconsistency:

> I noticed that the cpu speed is remembered on restart of openmsx, however the setting 'way to handle too fast VDP access' is not. This causes an 'error/warning' when restarting openmsx because the msxboot logo triggers this problem when the cpu speed was set at a high value. 
(see https://www.msx.org/forum/msx-talk/openmsx/please-help-testing-upcoming-openmsx-release?page=113)

Perhaps we shouldn't persist the `z80_freq_locked` setting?

**Comment by MBilderbeek** [comment]
@m9710797 what's your opinion/idea about this?

**Comment by m9710797** [comment]
I indeed think we shouldn't persist `{z80,r800}_freq_locked`.
I think it's mostly meant as a debug-tool. You normally shouldn't use this to speed-up emulation: it causes too much unwanted side effect, and those will only become worse when we implement more accurate emulation of other chips.

**Comment by MBilderbeek** [comment]
If you want to emulate an MSX with a 7MHz extension/switch, this setting is therefore not suitable (as it's a global setting).  So, yeah, I think I agree. And perhaps we should think about how to model a 7MHz extension. See also #136 .
