### ISSUE TITLE
Setting video source from command line don't works any more

### ISSUE THREAD

**Issue by aoineko-fr** [openMSX/openMSX#1730]
With last available development build (openmsx-19.1-1045-gd8f2b478b-windows-vc-x64-bin.zip | 12-Aug-2024 16:20), setting video source from command line leads to an error.

Was working with my previous version 19.1-575-g9a8dcad6 and with official 19.1 release.

Setting video source through TCL command prompt works.

```
Fatal error: Couldn't execute command: set videosource GFX9000
can't set "videosource": can't set "::machine1::videosource": video source not available
Command failed: "D:\Dev\Private\MSX\MSXgl\tools/openMSX/openmsx"  -cart D:\Dev\Private\MSX\MSXgl\projects\samples/emul/rom/s_v9990.rom -ext gfx9000 -command "set videosource GFX9000" -ext debugdevice
```

Version: openmsx-19.1-1045-gd8f2b478b-windows-vc-x64-bin
System: Windows 11 (64-bit)

**Comment by MBilderbeek** [comment]
Thanks for reporting this, this got broken in commit 8c1061f01d0313b3de85bbbffc9f12f814788ba1
@m9710797 can you take a look?

**Comment by m9710797** [comment]
@aoineko-fr thanks for reporting.
@MBilderbeek  thanks for pinpointing the exact commit that broke it.

I did some investiagtion:
* With commit 8c1061f01d0313b3de85bbbffc9f12f814788ba1 we want to make `-command "set renderer none"` possible. I mean without having a window briefly popup and disappear again.
* In this issue we want to make `-command "set videosource gfx9000"` possible.

I'm afraid that having both working at the same time is not possible :(
* The `renderer none` thing requires that we process the `-command` command line option _before_ creating the renderer.
* But the `videosource` thing requires the opposite order.

But there is a workaround:
* Not for the `renderer none thing (there the only(?) possibility was to swap the order).
* But we can replace `-command "set videosource gfx9000"` with `-command "after time 0 {set videosource gfx9000}"`. In other words: we postpone this `set` command till right after everything is fully initialized.

@aoineko-fr Is this an acceptable workaround for you? We always try to be backwards compatible, but I'm afraid this is a case where we cannot easily achieve 100% backwards compatibility :(

**Comment by aoineko-fr** [comment]
As the alternative command works with older versions, there is no backward compatibility problem for me.
I've updated the MSXgl build tool.

Note that although I fully understand the interest of being able to start openMSX without an interface, I find it rather strange to have used the 'set videosource' command for this. A separate option (like “-nogui”) would have seemed more appropriate.
But it's up to you.

In any case, no more problems for me.
Thanks for your help.

**Comment by MBilderbeek** [comment]
OK, then let's close the issue. Sorry for breaking something that worked at first :(
