### ISSUE TITLE
Add support for the no$gmb symbols file output by some linkers (e.g. wlalink)

### ISSUE THREAD

**Issue by mdagois** [openMSX/openMSX#1750]
Some linker, like wlalink from `WLA-DX`, has the option to export a `no$gmb` symbols file.
`openMSX` cannot currently load such symbols file.
Attached is a ROM and its corresponding `no$gmb` symbols file.
[xenophon.zip](https://github.com/user-attachments/files/17044053/xenophon.zip)

**Comment by mdagois** [comment]
A PR adding support for those symbol files is here: https://github.com/openMSX/openMSX/pull/1751

**Comment by m9710797** [comment]
Implemented via PR#1751.
