### ISSUE TITLE
State autoload issue when run through command line

### ISSUE THREAD

**Issue by Tartifless** [openMSX/openMSX#1757]
Hello,
OpenMsx 20 on windows 11.

I create a savestate of metal gear game called Metal Gear.0.oms

Then i launch the emulator with the command line:
Openmsx -machine <mymachine> -cart c:\games\msx2\gradius.rom

Openmsx does not insert gradius, instead it is loading automatically the Metal Gear savestate.

If i delete first the savestate file, then gradius loads ok.

Is there something i am missing ?

**Comment by MBilderbeek** [comment]
Are you sure about that command line? There is no argument for `-machine`...
You do not mention the savestate on the command line?

**Comment by Tartifless** [comment]
It does this whatever the machine i use.
I usually one of the panasonic or national msx2 models.

And yes: it loads the state with this simple command line, this is the issue, it should not load a state.

**Comment by MBilderbeek** [comment]
Did you enable session management in the long list of all settings, under Settings -> Advanced?

**Comment by Tartifless** [comment]
Let me check, i'll give you further details with logs and settings files when going home

**Comment by Tartifless** [comment]
Some details.

This is the content of the savestates folder:
![image](https://github.com/user-attachments/assets/06e86fea-7788-4bd9-8f86-5e4e4b8b9996)

This is my command line:
`openmsx.exe -machine Philips_NMS_8245 "C:\RetroBat\roms\msx2\Gradius.rom"`

And this is my settings file content:
[settings.txt](https://github.com/user-attachments/files/17144076/settings.txt)

Looking for the session management setting right now.
Even when just double-clicking the openmsx executable it will load the state.

Enable session management is unticked:
![image](https://github.com/user-attachments/assets/69e74739-4996-4924-bc44-10324ddf1d26)

**Comment by Tartifless** [comment]
Ok it seems it has something to do with the state being named with a .0.oms...
If i rename it by removing the 0, it will work.

Edit : i renamed my states to _0 and now all is fine, so it seems the ".x.oms" is what triggers this behaviour, if there is a number it will automatically load the state.

**Comment by MBilderbeek** [comment]
How do you save the state? with that keybinding?
I see:

>    `<bind key="keyb F8+ALT">savestate [guess_title].0</bind>`
>     `<bind key="keyb F7+ALT">loadstate [guess_title].0</bind>`

(note that this will only work if you want to load a state of the currently loaded game)

Anyway, I have no idea. There is no code implemented to do what you describe, as far as I know (right @m9710797 ??).... Also, I can't reproduce the issue.

is this with a clean openMSX installation? Maybe you have a script in your `share/scripts` folder that does something like that?

**Comment by Tartifless** [comment]
Clean install and easily reproductible, you can even do it manually, just do a savestate, e.g "Metal Gear.oms", then rename it to "Metal Gear.0.oms", than run openmsx.exe.

Works every time from a fresh install and redownload.

**Comment by MBilderbeek** [comment]
Well, your savestate/loadstate bindings were not the defaults and they add that `.0` Did you make that custom binding?

**Comment by Tartifless** [comment]
Yes i do, i increment the number with every run so that i have multiple slots management.

But with _0 instead of .0 all works fine, it really is just that when you have an integer between 2 dots before the extension openmsx will autoload the state whatever the way it is launched and whatever cart or disk is specified as argument.

**Comment by MBilderbeek** [comment]
There are no other customizations done on the default openMSX installation, installed from the installer from our website?

Because, as I said, I am not aware of any autoload feature of savestates in our code.

**Comment by Tartifless** [comment]
Hello,

No only the bindings, but as said : easy to reproduce, did it on 2 computers and with another person to check.
Even without the bindings it happens, bindings are just there to have a shortcut to save.

It can be tested with vanilla openmsx first run (provided you have the systemroms of the machine the savestate with done with).

**Comment by MBilderbeek** [comment]
Where exactly did you download openMSX? Can you give me the full URL of the file you downloaded?

**Comment by Tartifless** [comment]
Here:
https://github.com/openMSX/openMSX/releases/download/RELEASE_20_0/openmsx-20.0-windows-vc-x64-bin.zip

**Comment by MBilderbeek** [comment]
OK, I did this on a Windows 11 laptop:
1. download that zip
2. unzip it
3. double-click openmsx.exe there, it boots with C-BIOS
4. open console with F10 and type: `savestate test.0` (when C-BIOS shows its text about no roms being found)
5. the savestate `test.0.oms` is saved with a screenshot
6. close openMSX
7. double-click openmsx.exe again
8. I see a normal boot showing the C-BIOS logo, i.e. it doesn't continue with the C-BIOS screen directly. But if I understand you correctly, you would expect to see the savestate getting loaded and C-BIOS would not show its logo as the saved state is from beyond that.

What am I doing wrong here?

**Comment by MBilderbeek** [comment]
Okay @Tartifless , we have a new idea on the cause of this. Please execute the following steps:
1. start openMSX
2. In the main menu, select Machine -> Test MSX hardware
3. In the dialog that pops up, click on the button "Open user system ROMs folder" (make sure to NOT click the "Open system wide system ROMs folder...")
4. That should open an Explorer window.
5. In the Explorer window, go one directory/folder up. That should be called `share`
6. That directory probably contains a `scripts` directory. Can you zip up that directory and attach it to this issue?

You also wrote:
> as said : easy to reproduce, did it on 2 computers and with another person to check.

What (folder) did you copy to the other computer exactly to get the system roms in place?

**Comment by MBilderbeek** [comment]
@Tartifless any updates?

**Comment by Tartifless** [comment]
Hi,
Sorry been on a professional trip, will get back to you soon.

**Comment by Tartifless** [comment]
Hello, 
I could quickly perform some tests yesterday and finally narrowed it down to the scripts folder, indeed i had scripts from a previous version in my share folder, when replacing them by the provided scripts of last version it does not cause this behavior.

So i guess one of the scripts from older version (19.0)was causing this behaviour.

I'll try to go script by script later this week or next week to find the culprit !

**Comment by MBilderbeek** [comment]
If you just attach a zip with your scripts folder, I can take a look. I'm sure I can easily find it.

**Comment by MBilderbeek** [comment]
Looking forward to the zip with scripts, but in the meantime, I'm closing this issue, as it is not an issue of openMSX. However, I did create #1772 earlier.
