### ISSUE TITLE
Proposal for creating presets

### ISSUE THREAD

**Issue by balyuf** [openMSX/openMSX#1768]
It would be nice to have presets in openMSX.  A way to setup frequently used configuration with one click.  The easiest way I can imagine is to save current configuration to a named preset.  Then after starting openMSX, one can then simply select a preset from a list. I feel that this can all be done in the first menu item (Machine), with (say) "Select preset ..." and "Save preset ..." or something alike.  Catapult would simply remember its last setup.  But there it was very easy to select all the necessary items in the panel.  In the new menu structure it is a lot of clicking around.  But this can be compensated by the preset feature, which would in fact do better than Catapult in that respect ...

**Comment by MBilderbeek** [comment]
is this the same as #1583?

**Comment by balyuf** [comment]
The idea is the same, yes.  I would stress however to certainly have the disk configs saved too.  E.g. have MSX DOS 2, ide and HD image selected.  As to where to store it: it could be in the main settings file, not necessarily in separate files.  In that way, it could be selected on the command line, or from the menu ...

**Comment by MBilderbeek** [comment]
Let's continue at #1583 and call this a duplicate. I think we want the same here.
