### ISSUE TITLE
Colecovision Emulation

### ISSUE THREAD

**Issue by artrag** [openMSX/openMSX#1774]
Openmsx keeps testing for DI/HALT also while emulating the colecovision and adds an automatic breakpoint.
The Colecovision is based on NMI, so DI/HALT does not cause a deadlock.
You should remove the test on DI/HALT while emulating Colecovision and Colecovision+SGM

**Comment by artrag** [comment]
Investigating a bit more the issue appears only then the profiling scripts in attach are included in share\scripts\
[profile.rar.txt](https://github.com/user-attachments/files/17281918/profile.rar.txt)
Rename as RAR

**Comment by m9710797** [comment]
The 'official' openMSX `dihaltcallback` callback is defined in `share/scripts/callbackprocs.tcl` line 67. That proc checks the machine type and only prints the message for MSX and SVI.

The `openmsx.tcl` script in your .rar file on line 24 installs a different callback. That proc (unconditionally) prints the message.

That fully explains the problem you're seeing I think:  openMSX does it correctly, but your local scripts overrule the callback in a way that's not compatible with Colecovision.

I'm closing this issue. But feel free to reopen if you think it's not fully addressed yet. And thanks for reporting.
