### ISSUE TITLE
Region/type filters in Machine selector don't work anymore when clicking with the mouse

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1776]
See video:
[test-2024-10-07_22.20.56.webm](https://github.com/user-attachments/assets/725d3654-0ca8-4531-9753-a22660cbc23b)

At the end, when it seems to work, I am using space/enter to open the list. And that does seem to work.

**Comment by m9710797** [comment]
Sorry, I don't understand. And the video is unclear, e.g. the mouse cursor is not visible, I can't see where you're clicking.
Anyway, if I test locally it all works as expected.

**Comment by MBilderbeek** [comment]
The original video didn't have the cursor, so I replaced it quickly afterwards (if you read this from the mail, you won't see it).
Simplest way to reproduce it for me is:
1. clean imgui.ini
2. start openMSX and open Select MSX Machine menu
3. move it outside of the main window
4. click the triangle at the Type filteror Region filter
You also see the main window flash a bit (not all the time)

Resizing the window to very large or smaller doesn't have any influence.

**Comment by MBilderbeek** [comment]
I think this is the same issue as https://github.com/openMSX/openMSX/issues/1792#issuecomment-2448632079 so, let's close this. When disabling the setting, it's working again for me.
