### ISSUE TITLE
Request change to allow when selecting MSX1, an actual MSX1 computer with NO floppy drive is used in openmsx

### ISSUE THREAD

**Issue by DamienHillBoy** [openMSX/openMSX#1779]
Request change to allow when selecting MSX1 games, an actual MSX1 computer with NO floppy drive is used in openmsx. This will remedy some .CAS games not loading when a diskdrive present.

**Comment by MBilderbeek** [comment]
Can you be specific on what you mean with "when selecting MSX1". So where are you selecting that? Command line? Or from the GUI? Or something else?

**Comment by DamienHillBoy** [comment]
Classification: Public

Sorry Manual, wrong github repo.

**Comment by MBilderbeek** [comment]
OK, which one was it meant for, I wonder now? :)

**Comment by DamienHillBoy** [comment]
Classification: Public

Batocera, a retrogaming distro
