### ISSUE TITLE
Toolbar buttons have inconsistent sizes and shapes

### ISSUE THREAD

**Issue by gilbertfrancois** [openMSX/openMSX#1780]
A minor (cosmetic) UI issue. The toolbar buttons have all different shapes and sizes, depending on the size of the icon. It would be nice(r) if all buttons have the same shape and size, when they only show an icon and no text label.

openMSX release version 20.0, running on macOS 14.6

<img width="334" alt="Screenshot 2024-10-10 at 23 00 09" src="https://github.com/user-attachments/assets/061220f4-4322-4010-b62a-18c86e7ba153">

**Comment by m9710797** [comment]
"Fixed" in commit 459f221f56328ba0bbd97bd988edef6d825dffd5. Maybe not yet ideal, but good enough?
@gilbertfrancois good enough to close this ticket? Feel free to re-open (but then I need help to properly fix it).

**Comment by gilbertfrancois** [comment]
You gave me the idea to make an adjustment, based on your commit 459f221f56328ba0bbd97bd988edef6d825dffd5. I just made another PR with commit cdc4b8daef1e5d5f145264f0b510ec9a991d4f23. It boils down to change the button type from image button to a regular button and print the glyph as a text label. This is easier to align and justify in the center of the button without scaling the glyph itself.
