### ISSUE TITLE
Hudson Soft BP-0001 BeePack

### ISSUE THREAD

**Issue by ReNardier** [openMSX/openMSX#1786]
https://www.msx.org/wiki/Hudson_BP-0001
https://en.wikipedia.org/wiki/Bee_Card_(game_cartridge)
no mention on https://openmsx.org/features.html so i assume that it ain't a feature yet, also it is very curious that catalog number BC-M6 ain't known to be a thing, perhaps a very limited run?

**Comment by ReNardier** [comment]
oh, BC-M6 is actually a thing, https://www.generation-msx.nl/software/hudson-soft/buggy-jump/release/6073/

**Comment by MBilderbeek** [comment]
How do you propose this would be emulated?

**Comment by ReNardier** [comment]
well... that's extremely out of my depth here, but i might as well take a shot in the dark: can a cartridge-based extension be set to be on a specific cart slot?, if so then maybe by simply setting the beepack at say slot A(or B), we could then select in slot A(or B) the bee card date we wish to run(while preventing regular cartridge data from running on that slot, since a regular msx cart obviously doesn't slot on the beepack), mh, perhaps in catapult the cart slot the beepack is set at could be marked in some way to denote this altered behaviour?, again im sorry if i wasn't useful, although at least from you posing to me this problem i found a device with a similar "it goes on the cart slot and then something else slots in it" behaviour, i will make another issue for it, thank you for inquiring me even though(again) my input quite possibly ain't that helpful, have a good day(even i post again it is best if i leave it as said)

**Comment by MBilderbeek** [comment]
What does a bee card image look like?

**Comment by ReNardier** [comment]
i do not own any nor have any images, sorry, although you posing this to me led me to find that MAME seemingly has support for the beepack as well as another similar device for which i will open another issue, i also found out that apparently someone already sent you some bee card images(that is, if you are Manuel, with the sender being romanoaj)
https://www.msx.org/forum/msx-talk/general-discussion/msx-bee-card-development-cards?page=1

**Comment by MBilderbeek** [comment]
The thing is, these are just ROM chips inside. And the ROM chips can be dumped. Which works exactly the same as a normal cartridge. So a Bee Card image is just a ROM image and it's not different from a normal cartridge ROM image...

So, I think there is no point in specifically emulating a BeeCard interface, as the difference with a normal ROM cartridge is not even noticeable by the user.

**Comment by ReNardier** [comment]
oh, i see... is that then enough to say on the features page that the beepack is supported?

**Comment by MBilderbeek** [comment]
Not sure, I don't think it matters really. I guess no one will ask whether it's supported or not, because their Bee Card dump just works as a ROM cartridge.

**Comment by m9710797** [comment]
I agree, this is just an adapter. We don't need to do anything extra to emulate this. More in detail: once the ROM is dumped there's no difference compared to a dumped ROM from a regular MSX cartridge.
Let's close this issue.
