### ISSUE TITLE
Astron SoftCard Adaptor

### ISSUE THREAD

**Issue by ReNardier** [openMSX/openMSX#1788]
https://www.msx.org/wiki/Electric_Software_Astron_SoftCard_Adaptor
implementation should be similar to the one done for the beepack, if the internet archive wasn't currently down i think this link might be of use in this case
https://archive.org/details/msx-softcard-adator

**Comment by MBilderbeek** [comment]
Simlar to #1786 , I don't see the point in explicitly emulating this, as the hardware only adapts the pins of a ROM chip to the MSX cartridge slot.

**Comment by ReNardier** [comment]
same as my other comment on #1788, is that enough to declare support on the features page?

**Comment by m9710797** [comment]
Same reasoning here as in #1786. Let's close this.
