### ISSUE TITLE
[Feature] Set balance per channel [sf#155]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#179]
**Reported by manuelbi on 2007-10-20 10:24 UTC**
This is necessary to properly support the FM Stereo PAK, which has YM2413 channels 1-6 on one stereo channel and 7-9 on the other stereo channel.

This can be set via settings, but not in the hardware config XML. Maybe it could be supported in the form of multiple balance elements with a channel attribute?

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2007-10-20 11:46 UTC**
Logged In: YES 
user_id=78178
Originator: YES

After more thoroughly checking: it is not yet possible to have balance per channel. So, this would have to be implemented as well, to properly support FM Stereo PAK. (This requires adjusting e.g. SoundDevice::mixChannels.)

Suggestion for the XML spec:
You either have the old spec (global balance) or:
&lt;balance&gt;
&lt;channels start="1" end="6"&gt;-100&lt;/channels&gt;
&lt;channels start="7" end="9"&gt;100&lt;/channels&gt;
&lt;/balance&gt;

Wouter prefers more something like this:
&lt;balance start="1" end="6"&gt;-100&lt;/balance&gt;
&lt;balance start="7" end="9"&gt;100&lt;/balance&gt;

But we agreed that the one who implements it can choose :P

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2007-10-20 11:46 UTC**
- **summary**: Set balance per channel in hardware config XML --> Set balance per channel

**Comment by MBilderbeek** [comment]
We already support this and is used in FM Stereo Pak...  was fixed in 2009 via 1a47e3acb668a69c10e703bb3db13bc0c7a67567
