### ISSUE TITLE
Show clear error message when cassette player isn't available

### ISSUE THREAD

**Issue by aoineko-fr** [openMSX/openMSX#1793]
Hello,
The MSXgl script that loaded tape application directly from command line when launching openMSX don't works anymore with openMSX 20: 
```
Fatal error: Couldn't execute command: cassetteplayer insert D:/Dev/Private/MSX/MSXgl/projects/samples/emul/cas/s_game.cas
invalid command name "cassetteplayer"
Command failed: "D:\Dev\Private\MSX\MSXgl\tools/openMSX/openmsx"  -command "cassetteplayer insert D:\Dev\Private\MSX\MSXgl\projects\samples/emul/cas/s_game.cas" -ext debugdevice
```

According to openMSX documentation, this command is suppose to still working.
Cf. chapter 5.3 (https://openmsx.org/manual/user.html)

Version : openMSX 20.0 (Windows 11)

**Comment by MBilderbeek** [comment]
Several things:
1. does your default machine have a cassette port? If not, the command won't work, as there is no cassette player device.
2. does the command still work for you in the openMSX console? If yes, that means the manual is not wrong :)
3. why not use the `-cassetteplayer` command line option? Does that work better?

I tried it myself, but it works fine here.

**Comment by aoineko-fr** [comment]
The error happened on a MSX turbo R machine, so without cassette support.
It works fine on a Canon V20.

The current error message is misleading because it says the "cassetteplayer" command is invalid instead of telling the current machine is not compatible with this valid command.

**Comment by MBilderbeek** [comment]
Yes, unfortunately the implementation is such that the whole command isn't created when there is no cassetteport.

**Comment by MBilderbeek** [comment]
@m9710797 what if we implement the command in the DummyCassetteDevice and let it respond to all commands with an error explaining that there is no cassette player present in the current configuration?

**Comment by m9710797** [comment]
Yes, good idea.

A slight variation is to move the command out of `CassettePlayer` (to be able to reuse the code). And instantiate it both in `CassettePort` and in `DummyCassettePort` (not in DummyCassetteDevice because that also exists in MSX machines with a cassette-port). And then obviously make the command check for the presence of a `CassettePlayer` (e.g. pass this as a constructor parameter). And then make it return this error.

The main difference is that this retains the help-text (and tab-completion).

**Comment by MBilderbeek** [comment]
I think I need some help with the OUTER construct that is used in the TapeCommand class.... when taking the command outside of `CassettePlayer`...

**Comment by m9710797** [comment]
`OUTER` is a trick to avoid having to store a `CassettePlayer*` inside `TapeCommand`. After the proposed refactoring that trick no longer applies, so then you do have to store that pointer.

More in detail:
In the current code the `TapeCommand` object is a member variable of `CassettePlayer`. So if you have a pointer to (the start of) the `CassettePlayer` object, you can calculate where the `TapeCommand` is located (it's at some fixed offset). Similarly when you have a pointer to (the start of) the `TapeCommand` object, you can calculate where the (start of) the `CassettePlayer` object must be located in memory.
And the latter is what `OUTER` does: we're executing in a `TapeCommand` method, so the `this` pointer points to the (start of) the `TapeCommand` object. And thus without storing any extra run-time information we can calculate a pointer to `CassettePlayer`.

Note that this is only possible when we have an inner object nested in an outer object (the `OUTER` macro calculates the outer-pointer from the inner-pointer). But if both objects are separate (when they don't have a fixed offset between them) this trick is no longer possible.

In this case we want to move `TapeCommand` outside `CassettePlayer`. So there is no fixed inner/outer relation anymore. I propose that instead we pass a `CassettePlayer*` to the `TapeCommand` constructor, and that can be `nullptr` in case of turbor (in case of a `DummyCassettePort`). And store that pointer as a member variable in `TapeCommand`.
