### ISSUE TITLE
Magnified sprites not properly shown in sprite viewer

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1794]
See https://msx.org/forum/msx-talk/development/on-magnified-sprites-or-function-and-1px-offset

**Comment by MBilderbeek** [comment]
Apparently the game Strategic Mars uses magnified sprites in the intro demo.

**Comment by m9710797** [comment]
Thanks (all) for reporting.
Should be fixed now.

BTW: it was only the bounding box that was wrongly sized, the sprites themselves did already take magnification into account.
