### ISSUE TITLE
Uncaught exception: Failed to read settings file 'settings.xml': Error opening file "C:/Users/Sandor/Documents/openMSX/share/settings.xml": Permission denied 

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1797]
Windows users get this error. This issue is introduced between eeb10b88d7c7aa8d2f51bffc428de85fd273f362 (exclusive) and 0282e9f0eab30c7461f78c49d4ba6d7a7c1f9365 (inclusive):
> This is since build 90 of openmsx. Build 65 works just fine. 

My guess is due to the VLA removal refactorings.

See also https://www.msx.org/forum/msx-talk/openmsx/ive-ruined-my-openmsx-installation-uncaught-exception#comment-468207

**Comment by m9710797** [comment]
There was some window-specific code in the refactoring (which I couldn't test).
I've double checked that code, and made some possible fixes.
Hopefully this indeed fixes the problem.

**Comment by GyoMan** [comment]
Fixed!

**Comment by m9710797** [comment]
Thanks for confirming.
