### ISSUE TITLE
Do not remember the mapper type in the Cartridge Slot window

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1813]
We got a report from a user who once selected a mapper type manually in the Cartridge Slot A window and forgot about it. But next time he wanted to insert a game, this mapper type was still selected and the game crashed.

I think it would be better if the dialog always starts with 'Auto detect' instead of remembering the override of the previous time it was used, because most of the time you want it auto-detected and you can easily overlook the overriding mapper type selection.

Perhaps one use case where you want it remembered: you are developing your own game and it's not autodetected. Then it would be annoying to have to select the mapper type each time.
So, perhaps reset it to auto-detect when a different ROM file is inserted?

**Comment by m9710797** [comment]
Both good ideas. I have a slight preference for the latter: reset to auto-detect when a ROM file is selected.

**Comment by MBilderbeek** [comment]
@m9710797 what about this patch:
```
diff --git a/src/imgui/ImGuiMedia.cc b/src/imgui/ImGuiMedia.cc
index db6b59f09..ae5410ee1 100644
--- a/src/imgui/ImGuiMedia.cc
+++ b/src/imgui/ImGuiMedia.cc
@@ -807,7 +807,10 @@ bool ImGuiMedia::selectImage(ItemGroup& group, const std::string& title,
                        manager.openFile->selectFile(
                                title,
                                createFilter(),
-                               [&](const auto& fn) { group.edit.name = fn; },
+                               [&](const auto& fn) {
+                                       group.edit.name = fn;
+                                       group.edit.romType = RomType::UNKNOWN; // TODO: set romType only when browsing for ROMs? Or is it harmless?
+                               },
                                current);
                }
                simpleToolTip("Browse file");

```

**Comment by m9710797** [comment]
I haven't tried your patch (and it's not clear if you tried and what your results were). But at first sight this seems fine to me.
And it's indeed harmless to unconditionally set `romType` (this field is ignored for non-ROM media).
