### ISSUE TITLE
Make it possible to auto-reset when ejecting a ROM cartridge

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#1814]
Currently there is a checkbox to auto-reset the MSX when you insert a ROM, to quickly start running it.

When ejecting the ROM at run time, the MSX will hang in many cases, so you have to manually reset it (or insert another ROM).

Idea: also allow the MSX to automatically reset when ejecting the ROM. The same checkbox could be used, but it is now in the 'insert' part of the window, so it should then be moved or duplicated.

Any ideas?

**Comment by m9710797** [comment]
I don't like two check boxes. But I wouldn't mind moving the single box to a different location, and have it also apply to eject.

**Comment by MBilderbeek** [comment]
Any suggestion where?
