### ISSUE TITLE
[Feature] tcl script sub directories [sf#188]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#212]
**Reported by vampier on 2009-05-29 00:06 UTC**
We have now a lot of TCL files, some of these TCL files are core files while others are not really needed and all have a different purpose. 

I would like to see subdirectories created for all these scripts.

example:
- core
- osd
- trainers
- misc
- 3rdparty

**Comment by MBilderbeek** [comment]
I don't think this is now an issue.
