### ISSUE TITLE
[Support] How to use the MIDI support on Mac OS-X? [sf#11]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#22]
**Reported by sd-snatcher on 2012-07-21 20:57 UTC**
If I understood correctly, from v0.8.2 openMSX now supports MIDI output on Mac OS-X.

I tried the following command on the shell, but the MIDI still doesn't produce any sound:

plug msx-midi-out Virtual

Are any other commands/configuration required?

PS: It may be a good idea to update the manual with Windows and Mac examples:

http://openmsx.sourceforge.net/manual/user.html\#midi

Test configuration:
OpenMSX-0.8.2-dev12690 on Mac OS-X 10.6.8 emulating an MSX FS-A1GT
Games tested: MoonLight Saga Promo, Illusion City

**Comment by grauw** [comment]
Nowadays it’s: plug msx-midi-out Virtual\ OUT.

When you do this, you need to select openMSX as the MIDI source in the connected synthesizer. You can also specify a specific MIDI device in openMSX, but only if it was available when openMSX started, it doesn’t rescan.

I made some improvements on Mac OS X MIDI last year, amongst others adding MIDI IN support, and am using it frequently myself on OS X, so there should be no major issues.

There’s not much more to it. I suggest closing this issue.
