### ISSUE TITLE
[Feature] toggle_vdpobjecstinfo_overlay [sf#196]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#220]
**Reported by sd-snatcher on 2010-01-17 22:56 UTC**

It would be very useful for MSX development to have an overlay showing the info of all objects on screen. The idea is to have an script very similar to the toggle_mog_overlay, but more generic. The info would be showed as labels side-by-side to each object, like this:

Info:
- Sprites: sprite#, coordinates
- Blitted-Shapes (content displayed using the blitter): VDP command used, parameters used (backbuffer operations must not need to be shown)
- Tiled-Shapes: This one could be tricky: It would show information on scr1/2 games that move a block of tiles, but not the entire screen or an entire line. The info shown could be: each tile #, address on VRAM of the upper-leftmost tile.
- SCR2 shapes: This is the trickiest of them all. The idea is to track zx-spectrum converted objects on screen. Since all of them work on RAM and transfer the entire buffer to the VRAM each frame, the only way I can imagine this can be done is doing a diff between each frame and showing the coordinates/size of each difference found.

The usecase for this script would be:

\- Speed up debugging
- Game hacking scenario

The effect itself of the script running probably will be as awesome as the toggle_mog_overlay

**Comment by MBilderbeek** [comment]
I think this has now been obsoleted by the VDP debugger features, which as all that info.
