### ISSUE TITLE
[Feature] More user-friendly selection of default MSX machines [sf#210]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#234]
**Reported by sd-snatcher on 2010-07-18 20:41 UTC**
Currently the default MSX machines selected for the default MSX models is very european-centric:

msx1 -&gt; Toshiba_HX-10
msx2 -&gt; Philips_NMS_8250
msx2plus -&gt; Panasonic_FS-A1FX

But this brings problems of their own:

1) The majority of the MSX games are japanese, designed to run at 60Hz
2) European MSX&gt;=2 games/demos always select 50Hz or allows the user to select between 50/60Hz. On the other hand, most of the japanese games usually leave the fps setting untouched

This means that:

1) An user who don't know specific MSX models will have a wrong MSX experience unless he chooses MSX2+ or an MSX Turbo-R as his desired model.
2) Japanese games will almost always run slower than intented.

As the MSX standard is in fact Japanese, I suggest the following defaults:

msx1 -&gt; National_CF-3000
msx2 -&gt; Sony_HB-F1XD
msx2plus -&gt; Panasonic_FS-A1WSX
msxTurbo-R -&gt; Panasonic_FS-A1GT
msx1_50Hz -&gt; Philips_VG_8020
msx2_50Hz -&gt; Philips_NMS_8250

I changed the msx1_50Hz to the Philips_VG_8020, because when the bug #2552579 gets fixed the Toshiba HX-10 will not be a good default MSX1 for the average user because the games that require the mirroring will fail.
Also, the Panasonic FS-A1WSX seems a more appropriate MSX2+ because the FX model doesn't have the built-in MSX-Music.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2010-07-18 20:56 UTC**
Some comments:
1) Yes, you have a point in the 50/60Hz thing. We should discuss it.
2) The WSX might not be a good choice either, because it's annoying that it starts up with the built in software, just like the WX. Maybe we should use the Sanyo PHC-70FD2?
3) The Toshiba HX-10 doesn't have the Toshiba VDP, so it won't ever be a problem.

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2010-07-18 23:36 UTC**

Sorry, but I already used the real WSX and it only starts the internal software on boot if you turn-on the panel's switch. The machine has the same switch that the Turbo-Rs have (the case is exactly the same, but black), that by default leaves the internal software disabled also like the Turbo-R. I know this is valid for the WX and WSX, but I never used one FX.

AFAIK, the Panasonics that start the software by default without a switch are the MSX2 models. That's the reason why I selected the Sony HB-F1XD as the default MSX2. That and the fact that it has a built-in floppydrive.

IMHO, the Sanyo PHC-70FD2 isn't a good choice because the two built-in floppy disks don't allow the user to hold the CTRL key on boot to free some RAM for those games that require it. An unaware novice user will also blame the fault on the emulator because the recipe he found on a forum to run Final Fantasy didn't work.   :)

Are you sure the Toshiba HX-10 doesn't have the Toshiba VDP? I stated that based on the following site, that shows a picture of its mobo that clearly shows the toshiba VDP inside the HX-10. But maybe there were more then one type of HX-10 then?

http://www.mymsx.com/
http://www.mymsx.com/hx10/dscf0002.jpg

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2010-07-19 10:40 UTC**
About WSX/WX: you're right, the firmware switch is disabled by default on openMSX. My mistake. So, I think it's a good idea, indeed.

The Sanyo PHC-70FD2 has 2 floppy drives, but that doesn't mean the CTRL-trick won't work! This works just as well on a 2-drive machine.

The Toshiba HX-10 I have *seems* to have a normal TMS VDP. The chip contains a big cooler, so I can't read what's on it. But n_n thinks the Toshiba one has 42 pins, while mine has 40 pins. The big chip you see on that photo (with 64 pins) is also in my Toshiba, but we don't know what it is. I have a photo of the mobo of my HX-10, but it is not 100% the same as Stephan's HX-10 mobo, it seems...

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2010-07-25 03:19 UTC**
I'm changing the suggestion for the default MSX1 machine to the National_FS-1300, because some games like Eggerland Mistery 2 don't like the CF-3000's RAM placed on slot-1.

**Comment by MBilderbeek** [comment]
Defaults are now as follows:
```
                        ('National_CF-3300', 'msx1'),
                        ('Toshiba_HX-10', 'msx1_eu'),
                        ('Sony_HB-F900', 'msx2'),
                        ('Philips_NMS_8250', 'msx2_eu'),
                        ('Panasonic_FS-A1WSX', 'msx2plus'),
                        ('Panasonic_FS-A1GT', 'turbor'),
```
Please reopen if this there are better ideas...
