### ISSUE TITLE
[Support] how to enable MSX-Audio in Boosted_MSXturboR_with_IDE [sf#13]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#24]
**Reported by eadmaster on 2014-05-29 05:44 UTC**
I'm trying to enable MSX-Audio in my current machine Boosted_MSXturboR_with_IDE, so it will be used in place of MSX-Music by support games (like Xevious).

What is the easiest method to achieve this?

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-05-29 08:35 UTC**
What would you do on real hardware? If you explain that, I can give a much better answer.

**Comment by openMSX-import** [comment]
**Commented by eadmaster on 2014-06-19 23:35 UTC**
In blueMSX i plug "fs-ca1.rom" in the Cartridge Slot 1 and the game in Slot2.
(as machine i'm using Boosted Turbo-R JP)

EDIT: i've just noted that when starting openmsx i get this error:

```
warning: Conflicting input port 0xc0 for devices {Generic MSX-Audio} {OPL3 Cartridge}
warning: Conflicting input port 0xc1 for devices {Generic MSX-Audio} {OPL3 Cartridge}
```

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-06-20 06:43 UTC**
That's not an error, but a warning. It's because the machine already has an MSX-AUDIO built in and you are plugging in the OPL3 cartridge which uses the same I/O ports.

If you just select the Panasonic_FS-CA1 extension and insert the game, it should work fine, I guess?

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-06-20 14:35 UTC**
Well, it doesn't. It works fine on a normal turboR but not on the boosted one. This is probably because of the fact that slot 2 (where the game is in) is an expanded slot. (This is in fact a compatibility issue of the game, I guess...)

So, use another machine to play Xevious with MSX-AUDIO.

**Comment by MBilderbeek** [comment]
I guess we can close this.
