### ISSUE TITLE
[Feature] Replay "overwrite" mode for TASers [sf#242]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#266]
**Reported by manuelbi on 2012-11-04 22:23 UTC**
It seems the TASers would like an 'overwrite' mode in openMSX reverse. So, reversing immediately means forgetting the future. This is how all other TAS-approved emulators work...

See also http://tasvideos.org/forum/viewtopic.php?p=330398\#330398
Their workaround is to type bogus keys and their OMR file is filled with them....

The default behaviour we have now is nice if you want to play games and correcting yourself, but not for recording a TAS.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2013-05-18 13:24 UTC**
Note that I created the "reverse truncatereplay" command to clear the future (similar to typing a bogus key, but then without any recorded input).

**Comment by MBilderbeek** [comment]
I consider the issue done, after implementing that truncatereplay command.
