### ISSUE TITLE
[Feature] Set vdpiotiming=off feature [sf#251]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#275]
**Reported by sd-snatcher on 2013-07-11 20:58 UTC**
openMSX daily builds started emulating the timing of the VDP I/O ports. This is very nice as it brings openMSX emulation closer to the real hardware, but unfortunately it rendered the set z80_freq/z80_fre_locked almost useless, since all data sent to the VDP gets corrupted when these commands are used for clocks higher than 3.57MHz.

Those two commands, alongside cmdtiming=broken, was my primary way of developing safe turbofixes, since I could unleash the MSX speed to as fast as possible to do the debugging.

Please add an option, similar to the cmdtiming, to allow the access time of the VDP I/O ports to be ignored. Something like "set vdpiotiming=off".

Tested on openMSX-0.9.1-506-g6cc03ba, o windows-7.

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2013-07-12 18:43 UTC**
This seems like a useful request, however it's not very easy to implement:
Because we now emulate the VDP-VRAM access at a more low level, it's not so easy anymore to arbitrarily perform extra VRAM accesses. So we can't (easily) perform more VRAM accesses compared to the real VDP. Possibly you didn't notice it yet, but this also means that the cmdtiming=broken functionality now no longer works.

Your concern about higher than 3.5MHz clocks is certainly valid. E.g. 7MHz extensions on real HW perform I/O operations still at a clock-freq of 3.5MHz. Maybe we should now emulate this aspect as well?

Can you describe your use-case of turbo-fixes in more detail? I'd like to understand it better so that maybe we can suggest alternative workarounds.

I'll also consider re-enabling cmdtiming=broken and adding vdpiotiming=broken, but I'll have to see how easy it is to fit that in the new VRAM handling. I prefer not to complicate the VRAM access related code for an 'unrealistic' emulation-only feature.

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-07-13 04:32 UTC**
About the 7MHz homebrew kits: Indeed, the majority of the 7MHz homebrew turbo kits reduce the CPU speed to 3.57MHz when doing VDP (or even any other) I/O. But AFAIK currently openMSX do not emulate any of such extensions, so you probably don't need to worry about those right now. The ExpertTurbo does its VDP I/O with the Z80 running at full 7.14MHz, but I'll leave that explanation to the bug report #471. Let's focus on the TurboFixes use-case here then.    :)

The TurboFix use-case is based on the idea that the software should run properly without being dependent on any fixed device speed. Be it either the CPU, the blitter, the disk interface speed, etc.

That said, please keep in mind that the very low-level I/O synchronization (if needed) must be provided by hardware. From waitstate generators to lowering the CPU clock, there are many ways that this can be done, but is out of the scope of a TurboFix because, as mentioned, this is a hardware requirement.

The only notable exceptions are FM (OPLL and OPL1 to 3) chips. Those chips are so slow that in any architecture I ever met they always decided to resort to software sync, and the MSX Turbo-R was no exception. I guess that probably the logic for doing such sync smartly inside a chipset like the the S1990 would be too complex/expensive for the 80's. Nowadays there are cheap FPGAs/CPLDs and this would probably be different.

But even with the hardware assuring that the communication between the chips never gets corrupted, many software will present issues when running at turbo speeds.

Most of the method I use with openMSX is detailed on the following wiki article, so I'll concentrate on the pure use-cases.  http://www.msx.org/wiki/Compatibility_testing

While TurboFixing a software, I have to test each one of the following possibilities. Keep in mind that the tests are done with extreme speeds (Z80 goes as fast as my PC can emulate: currently 40MHz, and cmdtiming=broken) to assure that they really don't have any issues:
- Turbo-CPU only: Does the game always run at the correct speed? Or it improperly speeds up too much? Does it show any other problems, like reading disks, or other devices?
- Turbo-CPU vs Normal-Blitter: Some programmers forgot to check if the blitter was ready before sending new commands. This means that for these software the blitting operations get corrupted if the CPU speed increases and the VDP still has the standard V9938/58 blitting speed.
- Turbo-CPU + Turbo-Blitter: Sometimes the "CPU only" test isn't enough to detect if the game will be speed safe, because the bottleneck is on the blitter. By accelerating both the CPU and the blitter I can quickly find where those bugs occur and fix them properly.

I think the description above summarizes the three required scenarios I need to test on the TurboFix use-case. The forth scenario is related to the FM chips, but you don't need to worry about it: these days I fix the FM sound by modifying the code to use the BIOS instead of direct I/O. This compliance to the MSX coding guidelines assures not only the Turbo safety, but it has the additional advantage that the BIOS layer also allows hardware independence (very different chips can be used), just like it happened on the MSX disk or serial interfaces. This means that the FM chip can be changed by a different one and the BIOS will have the drivers accommodate the differences. This is exactly how the MSX-Audio BIOS v1.3 is able to be compatible with the MSX-Music BIOS.

Last, but not least, I just remembered that there is another use-case related to the cmdtiming=broken feature that isn't related with turbofixes: This feature is certainly a bless when debugging blitting code in step-by-step. Because sometimes you know that the CPU-blitter sync is properly done, but somehow a tile-blitting routine is bugged somewhere else, and needs to be run in step-by-step. I used this a lot when optimizing the King's Valley 2 routines so that the screen elements wouldn't flicker anymore. If I had to wait for the CPU-blitter synchronization manually while on step-by-step probably the King's Valley 2 patches would have required me a lot more time to do the same job, because properly coded blitting routines try to maximize the parallel processing between the CPU and the blitter. That's only one example, I also had to use the cmdtiming=broken many many times after that for similar reasons. Another such example was a game that used the HMMC command to load its graphics to the VRAM.

**Comment by openMSX-import** [comment]
**Updated by m9710797 on 2014-01-02 21:35 UTC**
- **status**: open --> closed

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2014-01-02 21:35 UTC**
There now is a setting "too_fast_vram_access". If this setting is give the value "ignore", we ignore the timing aspect of VRAM accesses (meaning it will go correctly even if done way too fast, e.g. because an overclocked Z80 is used).

So for now you'll have to manually enable this setting when using turbo-Z80 machines. In the future we should also emulate the hardware circuit that automatically switches back to a lower Z80 speed when performing IO accesses. But there's already another ticket for this. So I'm closing this one.

**Comment by jvidalw** [comment]
how can this setting be made permanent? I have to set it every time I start openMSX or else  I get corruption

**Comment by m9710797** [comment]
You mean how to make `too_fast_vram_access=ignore` permanent?

Most, but not all, settings are automatically saved/restored when you exit/restart openMSX (unless you have set `save_settings_on_exit=false`). But `too_fast_vram_access` is one of those settings that we explicitly don't want to be automatically restored.

The reason for this is that `too_fast_vram_access` is meant as a debug option. It should not be used for "normal" operation. This setting makes openMSX deviate from how a real MSX machine behaves, so it shouldn't be needed to run existing MSX software. It also shouldn't be used to develop new MSX software (because then that software won't work correctly on real MSX machines). Could you explain why you want `too_fast_vram_access` to be permanent? You say you get corruption, but in what scenario? Maybe we overlooked some important use case?

Anyway, currently `too_fast_vram_access` cannot be automatically restored. But what you can do is automatically re-enable this setting each time openMSX starts. To do that create a file "too_fast_vram_access.tcl" (the filename can arbitrary) with contents:
```
set too_fast_vram_access ignore
```
and place it in the openMSX `scripts` subdirectory (`~/.openMSX/share/scripts` on Linux).

**Comment by jvidalw** [comment]
HI. since adding \<setting id="too_fast_vram_access"\>ignore\</setting\> "

didn't work and got deleted by OpenMSX every time I launched, I found that setting the CPU speed to 4.0 down from 4.7 actually fixes the issue, and that setting can be made permanent, so I guess problem solved, not getting currupted display when -for example- running the dir command on DOS. Before fixing it running dir on DOS went well, until it started scrolling up,off the screen, after that it all went to hell, started repeating letters and numbers and ended up with a completely unreadably directory list.

**Comment by m9710797** [comment]
So your scenario was to increase emulation speed?

You can indeed do that by increasing the CPU clock frequency (you mean the `z80_freq` setting, right?). This increases (only) the CPU emulation speed, but leaves the speed of all other components unchanged. And then indeed this (relatively) faster CPU may access the (relatively) slower VDP too fast, leading to corruption.

An alternative (and safer) way to speedup the whole emulation is via the `speed` setting (normal value = 100, e.g. a value 150 increases speed to 150%). This changes the speed of all components together. Then the CPU and VDP keep talking to each other at the same relative speed, and then there shouldn't be any corruption. This `speed` setting is automatically saved.

You may also want to lookup the [fastforward](https://openmsx.org/manual/commands.html#fastforward) setting in the manual. By default toggling this setting is bound to the `F9` key.

**Comment by jvidalw** [comment]
no, I decreased the Z80 speed and that fixed the issue. for some reason, the Z80 was set to run at 4.7 and I lowered it to 4 (a bit faster than the default 3,58, but it seems to work just fine at 4)

**Comment by MBilderbeek** [comment]
I expect you set it higher for some reason once... (it won't happen by itself...) I recommend to set it back to normal (e.g. by locking the Z80 speed again). What you have now is not a realistic MSX and may still give you problems like you saw earlier.

**Comment by jvidalw** [comment]
I don't rememner rasing the CPU clock, maybe one of the"boosted" machines raised the cpu clock and it just stuck. it works fine now. If I find any more issues, I'll lower it to the default 3.58, thanks!

**Comment by MBilderbeek** [comment]
Selecting a machine doesn't affect this setting. You can only change it manually... who knows, maybe a forgotten experiment?

**Comment by jvidalw** [comment]
maybe, but I really don't recall doing it. Maybe my memory is just not what it used to be...
