### ISSUE TITLE
[Feature] While openMSX seeks in a timeline (fastforwarding), openMSX seems to hang up [sf#260]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#284]
**Reported by manuelbi on 2014-04-27 19:22 UTC**
While fastforwarding when seeking in the timeline (load a very long replay and click just before a savestate snapshot (or load a replay without extra savestate snapshots)), update the reversebar periodically, to give the user feedback. Currently it is as if openMSX hangs up.

**Comment by MBilderbeek** [comment]
This has been implemented a long time ago in e152d678d1e38c487d17b800d160e48257ea4acc, probably we forgot to close this issue. There is a message that the system is fast-forwarding.
