### ISSUE TITLE
[Feature] Debugger generic bug/improvement [sf#277]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#301]
**Reported by eugeny-brychkov on 2015-04-27 22:01 UTC**
Hello, I just started working with OpenMSX debugger, and will be logging all the wishes/problems I notice. Bear with me I am the user of BlueMSX, and probably will be writing some stuff which I think was very useful for me in BlueMSX debugger.
I use windows platform.
1. in the main debugger window, I can not resize panels. If I make debugger full screen, I have long tall section for code, and small sections for regs, dum, stack, flags etc. It would be great if I can resize the sections to fit the screen, and the debugger remember these settings.
2. it would be really helpful if I can change values of flags in the flags window. For now the only way I found to change flags is to go to registers and change hex value of AF. That's uneasy because I need to remember what original AF was, and need to make bitmap hex value of flag I need to change to put it in hex. That would be solved if I can just doubleclick onto flags state (e.g. there's "(C)", I double click on it, and it changes to "(NC)"). This is needed for emulating/debugging of the proper flow for devices which are not supported by OpenMSX yet.
3. the same way as (2) it would be great if I can change DI to EI and back with doubleclick.
4. I noticed when I press F8 (step over) debugger does not highlight changed registers with red. It works when I use F7 (step into). It would be very helpful if F8 would do that too - so that I instantly see (without tracing whole sub) which registers it changed.
5. I tried to load .SYM file generated by LINK (MSX linker), it did not work. Probably symbols need some other format.
6. I added debuggable viewer - "memory". I am currently troubleshooting device which changes pages on write to specific address. So I put "internal" dump window onto location I write page# byte to, and watch "memory" debuggable view. When I write byte to internal dump window, debuggable view does not change its contents (however there's now other data in the location being displayed). Only when I take "memory" window by its slider and move top/down a little, view changes to proper contents of the memory.

That's all for now... Thank you!

**Comment by openMSX-import** [comment]
**Commented by eugeny-brychkov on 2015-04-30 12:39 UTC**
Wish: I find backtrace feature very useful. I do not know if it's possible, but would be great having backrace to specific breakpoint. One time I pressed F8 on call, and it did wrong thing. I was doing backtrace for 20 minutes pressing the button, but was able to roll back only 1/5 of execution progress...

**Comment by MBilderbeek** [comment]
@Eugeny1 I think you added this comment 9 years ago, am I right? Which of these things are still valid? Have you tried the new openMSX debugger which is built into the main application? You can try it out by downloading a recent development build of openMSX.

**Comment by MBilderbeek** [comment]
@Eugeny1 If there are still points valid of this issue please reopen a new issue for each separate point. We should not combine several issues into one tracked issue, that makes it hard to see what is solved and what is not.
