### ISSUE TITLE
[Feature] MIDI emulation in Philips Music Module [sf#15]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#39]
**Reported by manuelbi on 2002-06-03 08:45 UTC**
For at least a complete Music Module emulation.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2007-06-19 19:53 UTC**
- **summary**: full MIDI emulation --> MIDI emulation in Philips Music Module

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2009-03-07 18:01 UTC**
You have my vote on this request.

Otherwise I'll never be able to implement this MIDI support on the MSX-Audio BIOS.

**Comment by MBilderbeek** [comment]
Implemented now, see commit 47dadf1b2e9c05a51f1ec02b1c3eebc6363e1e5a

Thanks to Wouter and grauw for their help!
