### ISSUE TITLE
[Bug] Space Manbow on tR has flickering top line  [sf#126]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#427]
**Reported by manuelbi on 2003-11-26 21:34 UTC**
Just below the screensplit of the score, you can see
that when the graphics of the lower part get close to
that split, the line is blinking. You can see that
quite quickly in level 1. Only occurs on TurboR.
On real turboR, it does flicker once in a while, but
not as often as here.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2004-01-13 20:18 UTC**
Logged In: YES 
user_id=78178

I see the same effect now in SDLLo and SDLHi on a normal
8250. Not at the same place as on the turboR, but very
clearly in level 1 with the big space ships. When they are
on the screensplit, you can see a blinking line.

**Comment by MBilderbeek** [comment]
This has been improved a lot with 547064a for #1310. As it also blinks every now and then on real hardware, I think we can consider this fixed now.
