### ISSUE TITLE
[Bug] VDP timing bugs collection [sf#169]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#470]
**Reported by manuelbi on 2004-11-02 21:02 UTC**
In this bug report I will keep a list of VDP timing
bugs, which are visible as flickering lines, or
unstable screen splits.

Here's the list for now, updates will be appended later:
- Space Manbow, top line (see bug 849883)
- Dawn of Time, top and bottom lines of copper area in
copper part (last real part)
- Woei demo, bottom part of the checkerboard pattern
- Hydefos screen split, bottom right

There are more VDP bugs that may be related with
timing, but I'm only listing the ones in which it's
really clear in this bug report.
Please add updates and new problems.

**Comment by openMSX-import** [comment]
**Commented by dvik on 2004-11-16 20:16 UTC**
Logged In: YES 
user_id=1021645

Here are two more:
- No-Waste demo first line of display area
- Psycho World, screensplit in the game

**Comment by openMSX-import** [comment]
**Commented by arnoldmnl on 2005-11-05 21:43 UTC**
Logged In: YES 
user_id=1084156

Another one, which is only relevant for testing msx software
in openmsx:

On a real 9938 the switching off and on of the display as is
done by cc.com and make.com (see
http://msxbanzai.tni.nl/dev/software.html\) sometimes leads
to garbage being displayed on the bottom part of the screen
for a very small time. 
It occurs in all text modes. I have not explored the scope
of this vdp bug any further.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2006-04-22 07:42 UTC**
Logged In: YES 
user_id=78178

\- another one: Blade Lords intro, see bug 689038

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2006-04-28 17:31 UTC**
Logged In: YES 
user_id=78178

Update:
- Space Manbow, top line (see bug 849883) -> #427 
- Dawn of Time, top lines of copper area in copper part
(last real part) -> #1313
- Woei demo, bottom part of the checkerboard pattern
(unstable screensplit, half a line too late)
- Hydefos screen split, bottom right
- No-Waste demo first line of display area -> #388 
- Psycho World, screensplit in the game -> #1310 

Not checked: Arnold's bug report.

Blade Lords is fixed.

**Comment by MBilderbeek** [comment]
547064a for #1310 fixed obviously Psycho World, but also Hydefos, the Woei demo and improved Space Manbow top line and Dawn of Time.

**Comment by MBilderbeek** [comment]
Arnold's issue is now in #1314. With that, all issues in this ticket are solved or have their own ticket. Closing this one, as it's much easier to track individual items.
