### ISSUE TITLE
[Bug] Ashiguine 3 sprite bug [sf#196]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#497]
**Reported by vampier on 2005-04-23 19:17 UTC**
A green 16x16 sprite is displayed n the intro screen all 
the way trough the name input screen. This shouldn't be 
there as far as I know. I cannot confirm if this also 
occurs on a real MSX, but for some reason I don't think 
so (i've played the hacked game on a real MSX and 
never saw that sprite)

Tested on a1GT and nms8255

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2005-10-12 18:13 UTC**
Logged In: YES 
user_id=78178

Strangely enough, this bug does not occur when using C-BIOS :)

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2009-06-07 10:07 UTC**
Tested on real MSX2 and turboR: the sprite isn't visible there.

**Comment by MBilderbeek** [comment]
![](http://i67.tinypic.com/ra93yw.jpg)
![](http://i65.tinypic.com/2dh8fop.jpg)
