### ISSUE TITLE
[Patch] set3 of icons for openMSX [sf#5]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#5]
**Reported by sd-snatcher on 2011-03-13 03:16 UTC**
This is a mix between the set1 and set2, intended for debugging.

1) Uses icons from set2
2) Displaced horizontally as set1
3) It's arranged in a way it stays only over the MSX border and never over the main image
4) It's always on (icons don't fade out), which is better for debugging

I hope you like it.

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2011-03-13 03:16 UTC**
Set3 of icons for openMSX
Attached file set3.zip:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/patches/_discuss/thread/877f7ad4/3eb8/attachment/set3.zip

**Comment by MBilderbeek** [comment]
It feels kind of bad that this set (which I would call differently, e.g. "debugging") is just plainly copying the icons from another set. Perhaps we should first see how we can avoid that, to make something cleaner.

**Comment by MBilderbeek** [comment]
I just added it anyway. It's not that much of data and we can see later how we can solve the duplication between sets. I don't think many people use the non-default OSD icon sets anyway.

**Comment by MBilderbeek** [comment]
(See eb89aad46e40e0065cc94121d73e926c80810f94)
