### ISSUE TITLE
[Bug] joystick problems [sf#221]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#522]
**Reported by guyver800 on 2005-12-25 21:34 UTC**
Several games in the MSXdev'05 competition have
problems with the joystick in openMSX. The following
games have been tested with openMSX 0.5.2 using several
configurations.

\- Caverns of Titan only works in port 2

\- Namake's Bridgedome works in port 1 until the
titlescreen. If you input a password on the
titlescreen, joystick port 1 will continue to work
throughout the game. But if you start the game straight
away, joystick in port 1 fails to work and must be
replugged into port 2 for the rest of the game.

These games have been disassembled and no erroneous
code has been found, both using BIOS calls as per the
BIOS specifications. Both have been verified on real
MSX machines to work correctly.

Curiously, using C-BIOS configs there is no problem.

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2005-12-27 10:59 UTC**
Logged In: YES 
user_id=356949

I only checked "Caverns of Titan". The game writes the value
56 to PSG register 7. So it programs portB as input! Because
of this the joystick select bit doesn't work anymore and
thus only joystick port B is read.

If I change the openMSX code to always use the normal MSX
port directions, both joystick ports work fine.

On what type of real MSX machines has this been tested? On
machines with a real AY8910 chip it will also go wrong.
Newer MSX machine often have the AY8910 integrated in some
other chip and there the port direction selection is usually
omitted.

We already forced portA to input to fix games like "Match
Manic". I'll also force portB to output to fix these games.
We need to make this configurable in the future.

**Comment by openMSX-import** [comment]
**Updated by m9710797 on 2005-12-27 10:59 UTC**
- **status**: open --> closed-fixed

**Comment by openMSX-import** [comment]
**Commented by guyver800 on 2005-12-27 11:48 UTC**
Logged In: YES 
user_id=1004619

Thanks, I completely forgot to check PSG R#7 writes. It
didn't occur to me that this would be the side-effect it
produces.

It appears all these games use the PT3 tracker, which was
ported from Spectrum. Apparantly the porter was a bit
careless or just didn't realise.

Would it be possible to make openMSX give a big flashy
warning when a program writes these hazardous values to R#7?
It's known to cause hardware crashes and possible permanent
damage.

**Comment by openMSX-import** [comment]
**Commented by guyver800 on 2005-12-27 11:56 UTC**
Logged In: YES 
user_id=1004619

Additionally, why doesn't this affect C-BIOS?
The R#7 values are still wrong using it and according to
BiFi the C-BIOS GETSTCK routine (which these games use) does
not correct them.

**Comment by MBilderbeek** [comment]
A bit late, but still... Coming back to this after https://www.msx.org/forum/msx-talk/emulation/psg-register-7-and-joystick-in-openmsx 

I implement a "port B forced as output" flag in the hardware config, see patch
[portBforced.patch.txt](https://github.com/openMSX/openMSX/files/2943645/portBforced.patch.txt).

I can confirm that removing the forcing indeed breaks the joystick in Caverns of Titan, and enabling it back makes it work again. I can also confirm that even without the forcing, it works fine in C-BIOS_MSX2+. 

@m9710797 Can you explain why it does work without forcing in C-BIOS_MSX2+? There must be something else going on as well, but I couldn't find it in the C-BIOS code, although I'm not sure where to look. It's definitely not in the wrtpsg routine.

By the way, we have a warning for port A, but not for port B. I guess port B is not dangerous to misconfigure. Can someone confirm?

**Comment by MBilderbeek** [comment]
I added the configurability for port directions being ignored or not in cff846e369f423eb3246d89e3aa880fcef90f39f

**Comment by MBilderbeek** [comment]
I checked a bit more on C-BIOS. In Caverns of Titan, both joysticks are supported. But with C-BIOS (when not ignoring port direction bits), only joystick 1 works (and not joystick 2), whilst on a machine like Toshiba HX-10, only joystick 2 works and not joystick 1 (as reported originally). So in both cases the joystick selection bit is stuck, but on a different value.
