### ISSUE TITLE
[Bug] SDLGL-PP, scale 3, glow and fullscreen: ghost images show up [sf#231]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#532]
**Reported by kanima on 2006-07-21 21:07 UTC**
Running 0.6.1 beta on Windows XP (SP2), Catalyst 06.5
and Sapphire 9600XT.

When using the SDLGL-PP renderer, with a scale of 3
only (2 and 4 work just fine) and going fullscreen
there are several problems:

First: the msx screen isn't positioned correctly (moved
down and left)
Second: the more "glow" is increased, the more ghost
images are shown vertically (yes, not just for moving
objects, but also for static images). Same settings
with SDL and SDLGL work just fine. Scale 2 and 4 look
just fine as well and in a window everything looks
dandy too.

**Comment by openMSX-import** [comment]
**Commented by kanima on 2006-07-21 21:07 UTC**
Nemesis "intro" screen, SDLGL-PP, fullscreen, scale 3 and glow 50
Attached file nemesis_sdlgl-pp_scale3_glow50_fullscreen.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/c689054b/637e/attachment/nemesis_sdlgl-pp_scale3_glow50_fullscreen.png

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2006-07-21 21:12 UTC**
Logged In: YES 
user_id=78178

&lt;kanima&gt; btw, the offset between the frames grows as i
increase glow
&lt;kanima&gt; but, the amount of desktop doesn't change

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2006-07-21 21:12 UTC**
- **labels**:  --> Graphics
- **summary**: SDLGL-PP, scale 3, glow and fullscreen --> SDLGL-PP, scale 3, glow and fullscreen: ghost images show up

**Comment by MBilderbeek** [comment]
@kanima Please try full screen with the latest development version (3f390b404486f3c082a83914f29e294dc1308fb4 or later).
It should work much better now.

**Comment by MBilderbeek** [comment]
Assuming this has been fixed in the meantime... no confirmation received from @kanima (and not sure this is his account either), so just closing.
