### ISSUE TITLE
[Bug] OUT timing on machines with Toshiba MSX Engine is slower [sf#262]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#563]
**Reported by manuelbi on 2007-03-23 19:34 UTC**
VDP out timing in MSX2+ and turboR machines (with T9769B and T9769C MSX-engines) takes one extra cpu cycle. Some programs rely on this and some programs don't work on these machines because of this.

openMSX doesn't emulate this.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2010-07-18 18:55 UTC**
Update from Wouter: openMSX already emulates this on turboR's, but not on the other machines using such an MSX-ENGINE.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-09-18 20:18 UTC**
Mar 23 2007 20:27:40 <dvik>     ok, just wanted to know what to expect. I'm test
ing our new demo
Mar 23 2007 20:28:02 <dvik>     its supposed not to run on MSX2+ and TR machines
 but it seems to do so in openMSX

....

Mar 23 2007 20:30:51 <dvik>     its kindof nice to have that emulated. I think t
here are some (not many) apps that needs it
Mar 23 2007 20:31:21 <Quibus>   Can you name some?
Mar 23 2007 20:31:28 <dvik>     there is I think a turbor video player that needs it (can't remember the name)
Mar 23 2007 20:32:20 <dvik>     That player was one of the reasons white cat fixed the timing on a couple of instructions a month or two ago. but I think it requires correct out timing as well
Mar 23 2007 20:32:33 <dvik>     so I guess it will play slightly too fast in openMSX
Mar 23 2007 20:32:40 <Quibus>   would be nice to have that soft
Mar 23 2007 20:32:47 <dvik>     I can ask him
Mar 23 2007 20:32:53 <Quibus>   please do
Mar 23 2007 20:32:59 <Quibus>   it's good to have test cases
Mar 23 2007 20:33:06 <BiFiMSX>  the eva player or something?
Mar 23 2007 20:33:13 <dvik>     sounds familiar
Mar 23 2007 20:33:38 <dvik>     it supports scsi (not sure if it supports ide as well)

So, I guess we'll have to ask dvik for the test cases :S

**Comment by MBilderbeek** [comment]
This delay on MSX2+ sounds like it's the fixed delay mentioned in #989 .
It's even possible our "Matsushita" device is actually just representing the T9769B MSX-ENGINE. The fact that some functionality overlaps with the S1985 certainly suggests this...

**Comment by MBilderbeek** [comment]
This has been implemented now, so closing.
