### ISSUE TITLE
[Feature] FAC MIDI Interface [sf#47]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#71]
**Reported by bifimsx on 2003-05-31 12:10 UTC**
How about supporting the FAC MIDI Interface? It uses the 8251 
chip (just like MSX MIDI) and has MIDI-in, MIDI-out and a switch. 
This switch is connected to the interrupt signal leading to the 
MSX. The ports used (need to check if these are mirrored over a 
certain range):

I/O port 2: MIDI data port
I/O port 3: MIDI command(out) or status(in) port

**Comment by openMSX-import** [comment]
**Commented by bifimsx on 2003-05-31 13:17 UTC**
Logged In: YES 
user_id=790845

Port mirroring info:

port 2 is mirrored on 0, 4 and 6
port 3 is mirrored on 1, 5 and 7

**Comment by MBilderbeek** [comment]
Done, see 63cced9de5c265f0612cfc93d8ec9afaffcd4567 (and a few behind that).

Thanks for all the info BiFi!

The switch is not emulated, but on BiFi's device it isn't even connected, so let's just forget about it (at least for now).
