### ISSUE TITLE
[Bug] hq/hqlite scaling of 512-pixel-wide modes to 3x or 4x not working [sf#353]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#747]
**Reported by manuelbi on 2009-07-27 21:56 UTC**
Scaling a screen 7 image to 3x or 4x scalefactor with hq and hqlite isn't working (it's not implemented according to wouter). This is unexpected, as it works fine in SDL, but there you don't have the benefit of hardware acceleration...

**Comment by MBilderbeek** [comment]
One of our users who was using SDL with hq on 3x scaling also noticed this and reported it as a regression. Look at the difference:
SDL 3x hq:
![image](https://github.com/user-attachments/assets/539d818f-8252-4444-b103-3b677f5b41a7)
and on SDLGL-PP:
![image](https://github.com/user-attachments/assets/c4d3a156-d257-4af6-add5-b3bb7fd4b117)

Can we do something to fix this regression?
