### ISSUE TITLE
[Bug] Small TCL script makes openMSX crash [sf#356]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#750]
**Reported by vampier on 2009-08-12 04:56 UTC**
the following script has 3 possible outcomes for openMSX.

proc crash {} {
vpoke 1 23
crash
}
1) Exit without a warning
2) Crash
3) Give a warning from TCL (endless loop)

**Comment by MBilderbeek** [comment]
When I run this, I get 3:
"too many nested evaluations (infinite loop?)"

There's no crash. So I think this issue is (somehow) solved.
