### ISSUE TITLE
[Bug] Impact Musix disk 4 crashes [sf#359]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#753]
**Reported by manuelbi on 2009-10-02 19:30 UTC**
http://www.msxblue.com/wp-content/plugins/download-monitor/download.php?id=79 is Impact Musix Disk 4.

This crashes when you start the first tune (on the blue screen) by pressing the play button. On 0.7.2 it works fine as does it on blueMSX and, more importantly, my real turboR. It only fails when MSX-AUDIO is inserted (the music disk is also made for that).

When I have some time I'll bisect it.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2009-10-02 20:59 UTC**
Hmm, no regression... The following weird observation can be made:

\- it works if you keep CTRL pressed until the title screen
- it fails if you stop pressing CTRL until just after the beep (for all openMSX versions I tried)

Retesting on real machine I couldn't reproduce this effect. It just always works there, using the same configuration, also if you release CTRL just after the beep...

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2009-10-02 20:59 UTC**
- **summary**: Impact Musix disk 4 crashes (regression) --> Impact Musix disk 4 crashes

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2009-10-03 22:20 UTC**
More info: you don't need to press any key to let it happen or not happen... It seems to depend on when you press the space bar in the title screen. This event log reproduces the problem:
91735730971 keyb SPACE unicode32
92078308005 keyb SPACE,RELEASE
93996542906 keyb RIGHT
94407634867 keyb RIGHT,RELEASE
94750125172 keyb RIGHT
95229726726 keyb RIGHT,RELEASE
96668415060 keyb SPACE unicode32
97764955148 keyb SPACE,RELEASE

when I run it like this:

$ openmsx -machine turbor -ext audio /tmp/impact4.zip -replay /tmp/crash.events

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2009-10-03 22:20 UTC**
- **priority**: 7 --> 5

**Comment by MBilderbeek** [comment]
Well, I just tested this again and it all works fine now... so I guess this issue is gone.... not sure what happened, of course... Let's just close it until we get proof it's not gone after all.
