### ISSUE TITLE
[Bug] Joystick axes incorrectly mapped on Mac-OS-X [sf#361]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#755]
**Reported by sd-snatcher on 2009-10-30 22:53 UTC**
I do have a playstation-like USB joystick, but openMSX is not reading its axes correctly. The buttons seems to work fine.

As almost all playstation-like USB joysticks, it has the following configuration:

Button #1 : Minimum = 0, Default = 0, Maximum = 1
Button #2 : Minimum = 0, Default = 0, Maximum = 1
Button #3 : Minimum = 0, Default = 0, Maximum = 1
Button #4 : Minimum = 0, Default = 0, Maximum = 1
Button #5 : Minimum = 0, Default = 0, Maximum = 1
Button #6 : Minimum = 0, Default = 0, Maximum = 1
Button #7 : Minimum = 0, Default = 0, Maximum = 1
Button #8 : Minimum = 0, Default = 0, Maximum = 1
Button #9 : Minimum = 0, Default = 0, Maximum = 1
Button #10 : Minimum = 0, Default = 0, Maximum = 1
Button #11 : Minimum = 0, Default = 0, Maximum = 1
Button #12 : Minimum = 0, Default = 0, Maximum = 1
Page: 0xff00, Usage: 0x1 : Minimum = 0, Default = 0, Maximum = 0
Z-Axis : Minimum = 1, Default = 1, Maximum = 1
Z-Axis : Minimum = 0, Default = 128, Maximum = 255
Z-Rotation : Minimum = 0, Default = 128, Maximum = 255
X-Axis : Minimum = 0, Default = 128, Maximum = 255
Y-Axis : Minimum = 0, Default = 128, Maximum = 255
Hatswitch : Minimum = 0, Default = 15, Maximum = 15

This is mapped as follows (on analog mode):

Digital stick = Hatswitch
Left Analog stick = Axes X and Y
Right Analog stick = Z-Axis and Z-Rotation

When working on digital mode, both the Digital stick and Left Analog stick are both mapped to use the axes X and Y. The right analog stick is mapped to the buttons 1-4.

The openMSX reacts to the joystick as this:

Digital Mode: the game reacts as if the joystick is pointing left always.
Analog Mode: The right-stick works for up/down and the game still reacts as if the joystick is pointing left always.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2009-10-31 10:54 UTC**
My guess would be that this is an SDL bug... openMSX uses the information it gets from SDL for joystick.

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2009-11-04 00:44 UTC**
The bug only seems to affect the Mac OS X version. The windows version works fine.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2009-11-04 18:18 UTC**
As I also asked in the other thread: what kind of version/build are you using? Which SDL version is included?

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2009-11-05 00:12 UTC**
I'm using the stock openMSX 0.7.2 downloaded from the openMSX site, installed inside the NekoLauncher ppenMSX.App v0.9.

How do I get the included SDL version?

**Comment by openMSX-import** [comment]
**Commented by mthuurne on 2009-11-05 01:29 UTC**
SDL 1.2.13 (the latest release at this time) was used to build openMSX 0.7.2. There is no easy way to get this information from the binary.

I'll try to reproduce this problem on my Mac and post when I have the results. I have used joysticks with openMSX under Linux without problems and you reported it works fine under Windows, so there is something Mac specific going on here. Maybe we use SDL in the wrong way and that only leads to problems on Mac. Or maybe there is a bug in the Mac specific code of SDL.

Did this problem occur on an Intel or PowerPC Mac?

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2009-11-08 18:39 UTC**
Mac OS X v10.5.8
iMac 24", Intel Core 2 Duo 2.66GHz

Aditional info: ZSNES uses SDL on Mac OS X. I tested it and the joystick do work fine.

**Comment by openMSX-import** [comment]
**Commented by mthuurne on 2011-10-22 15:30 UTC**
I can't reproduce this problem. I tested today with an actual PlayStation controller attached to a PSX to USB converter on Mac OS X. In digital mode the d-pad works as expected, in analog mode the d-pad acts as buttons but the stick works.

I did see the player character move to the right (not left) when I started the game, but as soon as I pressed direction buttons that stopped. Maybe it's some kind of auto-calibration that needs to see the minimum and maximum value before it is usable?

What program did you get the joystick statistics from? I'd like to compare them to what my joystick produces.

**Comment by sdsnatcher** [comment]
I think this bug report can be closed. That joystick broke a long time ago.  Nowadays I'm using a PS2 controller connected to a PS2->PS3 USB adapter from DX and everything works fine.  I can't be sure it SDL was fixed or if this adapter works better than that previous joystick.

**Comment by MBilderbeek** [comment]
Closing, there's nothing we can do here.
