### ISSUE TITLE
[Bug] SDL 3x without effects still shows blur [sf#362]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#756]
**Reported by manuelbi on 2009-11-15 21:27 UTC**
When doing these settings:
set scale_factor 3
set renderer SDL
set noise 0
set scanline 0
set glow 0
set blur 0

you expect razor sharp images. But when taking a screenshot of the 8250 logo screen, you can still see vertical blurriness in the image.
When using SDLGL-PP all works as expected: razor sharp, no blurring. Wrong (SDL) and correct (SDLGL-PP) images attached.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2009-11-15 21:27 UTC**
3x scaling of logo screen of 8250 without effects on SDL renderer
Attached file bad.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/9f8fbbed/cd15/attachment/bad.png

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2009-11-15 21:28 UTC**
- **labels**:  --> Graphics

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2009-11-15 21:48 UTC**
Oh, all of this was on the simple scaler, of course.

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2009-11-15 21:57 UTC**
There are two parts in this problem:

First, the screenshot of SDLGL-PP is taken at scale_factor4, the SDL one at 3x (because there is no 4x for SDL). The boot logo is using msx resolution 512x212, to stretch that to 768x636 (scale factor 3, both resolutions don't include borders), you have to stretch by a non-integer ratio, so it cannot be 'razor sharp'. Either there is some blurring or not all source pixels are stretched (repeated) by the same amount. For scale factor 4 there is no such problem.

The second problem is a real difference between SDL and SDLGL-PP. SDL will always draw the 'scanline' as an interpolation between MSX pixels. SDLGL-PP does the same except for the special case of blur=0/scanline=0. So this means there is a big visual difference between e.g. blur=0/scanline=0 and blur=0/scanline=1. I'm not sure which of these two is better. Probably the latter.

**Comment by openMSX-import** [comment]
**Updated by m9710797 on 2009-11-15 21:57 UTC**
- **priority**: 5 --> 4

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2009-11-15 22:12 UTC**
3x scaling of logo screen of 8250 without effects on SDLGL-PP renderer (OK)  
Attached file good.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/9f8fbbed/af44/attachment/good.png

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2009-11-15 22:13 UTC**
Oops, I attached the wrong SDLGL-PP screenshot. Fixed now.

**Comment by MBilderbeek** [comment]
SDL renderer has been removed, so closing this issue.
