### ISSUE TITLE
[Bug] screenshots aren't correct in SDLGL-XXXXX renderers [sf#371]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#765]
**Reported by vampier on 2010-01-10 18:16 UTC**
When having using either of the following renderers the screenshots don't come out right:
- SDLGL-FB16
- SDLGL-FB32
- SDLGL-PP

The unused scale factor is irrelevant to reproduce this for me.

BifiMSX reported crashes while trying to make a screenshot

Also the problem only occurs with 'screenshot' only and not with the the following switches: 
- screenshot -raw
- screenshot -doublesize -raw
- screenshot -with-osd

The discoloration seems to be random sometimes green seems to be missing and sometimes red seems to be missing.

Bonus report :P
SDLGL-FB16 seems to have scan-lines on the first section of the screen which are also included in the screenshots (and on the openMSX video output window)

**Comment by openMSX-import** [comment]
**Commented by vampier on 2010-01-10 18:16 UTC**
255 colors in screen 8
Attached file openmsx0178.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/d7a8f3c8/e2d0/attachment/openmsx0178.png

**Comment by openMSX-import** [comment]
**Commented by vampier on 2010-01-10 18:18 UTC**
color 15,4,4 standard screen
Attached file openmsx0179.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/d7a8f3c8/258d/attachment/openmsx0179.png

**Comment by openMSX-import** [comment]
**Commented by vampier on 2010-01-10 18:20 UTC**
with parameters to the screenshot command all works fine (see report)
Attached file openmsx0194.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/d7a8f3c8/e177/attachment/openmsx0194.png

**Comment by openMSX-import** [comment]
**Commented by vampier on 2010-01-10 18:21 UTC**
too red
Attached file openmsx0196.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/d7a8f3c8/032f/attachment/openmsx0196.png

**Comment by openMSX-import** [comment]
**Commented by vampier on 2010-01-10 18:21 UTC**
too blue
Attached file openmsx0176.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/d7a8f3c8/c953/attachment/openmsx0176.png

**Comment by MBilderbeek** [comment]
I can't reproduce this on Windows 8 and I haven't heard anyone complain about it, so I'll close this for now.
