### ISSUE TITLE
[Bug] Gnome Ranger and Ingrid's Back wav dumps don't work [sf#372]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#766]
**Reported by manuelbi on 2010-01-20 22:31 UTC**
OeiOeiVogeltje made recordings of his tapes Gnome Ranger and Ingrid's Back!, but when playing the wavs in openMSX, the cassette headers aren't picked up (the MSX ignores the data). At least Ingrid's Back! side A could be converted with wav2cas (Vincent van Dam's) to a CAS file, so at least the data is valid. The wav files look pretty good as well. 

openMSX is the only emulator with wav support, so it's hard to test on other emulators.

&lt;wouter_&gt; Quibus: can you make a bug report for it?  I'll look into it. But not that soon (prob not before the release)

**Comment by MBilderbeek** [comment]
https://www.dropbox.com/sh/60czifi522c17rw/AAAoTZ3xweTd2Jbhj9_zKgAra?dl=0 the GP.WAV there is another one, it works on real Gradiente XP-800, but the header isn't picked up in openMSX.

**Comment by MBilderbeek** [comment]
And another one: https://mega.nz/#!HV1yQSpR!3TZ44WykhkNS4curVPaQYpy2W2AFt3sKkCtBgfSUZQA
(BIT2MULTITIMBRAL.wav)

mars2000you managed to convert it to CAS and then it works fine. But when openMSX tries to load this wav file, the header is not picked up.

**Comment by MBilderbeek** [comment]
p_gimeno on IRC tried these wavs on his real VG 8020, but none of them worked on it, out of the box. See also https://www.msx.org/forum/msx-talk/general-discussion/nandemo-piga-the-binary-wav-converter-for-tapes?page=3

**Comment by MBilderbeek** [comment]
I have the feeling we can just as well close this bug, until someone comes up with a case where playing the WAV to a real MSX works and playing it on openMSX does not.

**Comment by MBilderbeek** [comment]
These wavs now work with 8f52062221029b8986aacb5402e136fcbf71f184 and 46c7264f2cdf5a69f8a9db874b3359380b7e9621. Thanks to @m9710797 and p_gimeno!
