### ISSUE TITLE
[Bug] Interference between the MENU and PAUSE shortcuts [sf#374]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#768]
**Reported by sd-snatcher on 2010-01-23 15:33 UTC**

There's some strange interference between the MENU and PAUSE shortcuts.

Steps to reproduce:

1) Boot the MSX
2) Press the shortcut to open the internal openMSX MENU (cmd+O on a Mac)
3) Press the shortcut to pause the emulation (cmd+P on a Mac). The PAUSE icon will show up as desired.
4) When you press again the MENU shortcut, the PAUSE icon will be gone and the emulation will continue as it was never paused.
5) Now every time you open the MENU, the PAUSE icon will show up again, but the emulation will be paused only while the MENU is open

Testbed information:
- openMSX-0.7.2-dev11023 on Mac OS-X v10.5.8

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2010-01-25 20:05 UTC**
I'm not sure what the problem is. When opening and closing the menu, openMSX is also automatically paused and unpaused.

We do want to pause the emulation when opening the menu. Should we restore the pause state at menu exit? Is that what this is about?

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2010-01-26 01:14 UTC**
&gt; Should we restore the pause state at menu exit? Is that what this is about?

I think so, as on the Mac I usually trip cmd+O while pressing the cmd+P and then it unpauses it without my request because I closed the menu.

What is very weird is the fact that if you press cmd+P while the menu is on, the emulation continues normally. So, why do the MENU really needs to pause the emulation? Opening the console doesn't behave this way.. Shouldn't the MENU work the same way for interface consistence?

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2013-02-08 21:10 UTC**
The menu pauses emulation for convenience (usually you do not need/want it to continue).

The user is free to override that. But indeed, the menu is also overriding the pause state that the user desired. This has been a choice. Not sure what to do here.... should this behaviour be changed? I haven't heard other complaints. Are there serious use cases that are broken because of this behaviour?

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2013-02-08 21:10 UTC**
- **priority**: 5 --> 3

**Comment by MBilderbeek** [comment]
I don't think we'll ever change this, so closing...
