### ISSUE TITLE
[Feature] Default extensions [sf#54]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#78]
**Reported by manuelbi on 2003-08-14 20:19 UTC**
It would be very nice to have a mechanism to have
certain extensions (including ROM cartridges) inserted
in a machine (or in any machine that is used) by
default, without modifying the hardware configuration
of a machine.

A first step could be the use of DefaultExtensions,
similar to DefaultMachine. We can't specify ROM
cartridges there though. And of course only existing
extensions can be used. This is then just a convenience
feature, you don't have to type the extensions on the
ocmmand line all the time. Disadvantage is that the
amount of extensions is limited to the number of free
cartridge slots.

A more general thing, more realistic like the real MSX
is the use of a slot expander mechanism. For this, we
need to have a 'thing' that can be used as a slot
expander. This could be an XML file that can be used as
a cartridge, in which you can specify extensions or
ROMs. This is what Bifi proposed. You could insert as
many slot expanders as you have external slots on your
MSX (as long as those are not expanded, of course).
But, one slot expander can have only 4 extensions/roms
that have memory, of course.

I think we will have to go for option one for
convenience and move along to option two as we get to
it. Maybe we should wait before the new XML is designed.

**Comment by openMSX-import** [comment]
**Commented by atarulum on 2004-02-25 20:28 UTC**
Logged In: YES 
user_id=641511

I agree.
I wish slot expander will be very nice to emulate on openMSX

This is sample part *.xml of slot expander.

&lt;config id="Slot Expander"&gt;
&lt;parameter name="slota0"&gt;1-0&lt;/parameter&gt;
&lt;parameter name="slota1"&gt;1-1&lt;/parameter&gt;
&lt;parameter name="slota2"&gt;1-2&lt;/parameter&gt;
&lt;parameter name="slota3"&gt;1-3&lt;/parameter&gt;
&lt;parameter name="slotb0"&gt;1-0&lt;/parameter&gt;
&lt;parameter name="slotb1"&gt;1-1&lt;/parameter&gt;
&lt;parameter name="slotb2"&gt;1-2&lt;/parameter&gt;
&lt;parameter name="slotb3"&gt;1-3&lt;/parameter&gt;
&lt;/config&gt;

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2004-09-21 19:18 UTC**
- **summary**: Default extensions/slotexpander --> Default extensions

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2004-09-21 19:18 UTC**
Logged In: YES 
user_id=78178

A slot expander has now been implemented by Wouter, but the
default extensions still have not. Should not be very
difficult though, but maybe we should wait until the
'inserting extensions at run time' is implemented.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2005-12-07 21:06 UTC**
Logged In: YES 
user_id=78178

Please read also the mostly duplicate RFE 882469.

https://sourceforge.net/tracker/index.php?func=detail&aid=882469&group\_id=38274&atid=421864

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2007-09-12 16:40 UTC**
Logged In: YES 
user_id=78178
Originator: YES

Another use case related to this:
- a user does a certain session configuration with the existing (old) Catapult, including ROMs, extensions and a machine
- a user wants to run openMSX directly (without Catapult), but with the configuration he just made in Catapult.

This was the story ("I wish it worked like this") of OeiOeiVogeltje.

**Comment by openMSX-import** [comment]
**Commented by mthuurne on 2007-09-12 16:55 UTC**
Logged In: YES 
user_id=358343
Originator: NO

Bundling extensions or a machine and extensions sounds like a good idea to me. It's likely power users will want to have more than one of those though, so I think it's better to save it in a dedicated XML format instead of storing it as defaults.

If we give those dedicated XML files a special file name extension, that file type can be associated with openMSX, so activating one in the file manager starts openMSX in the desired configuration.

I'm not sure what to think of default extensions though. What would happen if you switch machines? Inserting the same extensions in another machine may not make sense, but erasing the default extensions list is probably not what the user expects either.

**Comment by oh-ren** [comment]
[RFE 882469](#issuecomment-114010183) -> #96

**Comment by MBilderbeek** [comment]
Let's track this in #1583 , which is basically the same.
