### ISSUE TITLE
[Bug] Compiled in DATADIR incorrect for staticbindist builds [sf#389]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#783]
**Reported by manuelbi on 2010-05-19 21:42 UTC**
&lt;mth&gt; static const std::string DATADIR = "derived/mipsel-dingux-devel-3rd/bindist/install/share";
&lt;mth&gt; this seems to be the problem: if you build staticbindist, DATADIR is set to the installation location of the build, not the installation location on the target

**Comment by MBilderbeek** [comment]
This doesn't seem to be happening anymore, this is from a `make staticbindist`:
`static const char* const DATADIR = "/share";`
