### ISSUE TITLE
[Bug] Audio device opened twice on startup [sf#390]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#784]
**Reported by mthuurne on 2010-05-23 15:15 UTC**
When openMSX is starting up, we first open the audio device with the default settings and later reopen it with the loaded user settings. It would be more efficient to open it once, with the loaded user settings. This would probably require some changes in the startup sequence.

Below are the backtraces of the two times that the audio device (via SDLSoundDriver in this case) is opened on startup:

#0  openmsx::SDLSoundDriver::SDLSoundDriver (this=0x27f77b0, wantedFreq=44100, wantedSamples=1024) at src/sound/SDLSoundDriver.cc:14
#1  0x000000000060671b in openmsx::Mixer::reloadDriver (this=0x27f6a90) at src/sound/Mixer.cc:87
#2  0x000000000060737e in openmsx::Mixer::Mixer (this=0x27f6a90, commandController_=&lt;value optimized out&gt;) at src/sound/Mixer.cc:61
#3  0x00000000004578d8 in openmsx::Reactor::Reactor (this=0x7fffffffd860) at src/Reactor.cc:218
#4  0x0000000000465207 in openmsx::main (argc=1, argv=0x7fffffffdce8) at src/main.cc:68
#5  0x0000000000465729 in main (argc=41908144, argv=0xac44) at src/main.cc:120

#0  openmsx::SDLSoundDriver::SDLSoundDriver (this=0x27f77b0, wantedFreq=48000, wantedSamples=1024) at src/sound/SDLSoundDriver.cc:14
#1  0x000000000060671b in openmsx::Mixer::reloadDriver (this=0x27f6a90) at src/sound/Mixer.cc:87
#2  0x00000000005e91bf in openmsx::Subject&lt;openmsx::Setting&gt;::notify (this=0x27f70e8) at src/utils/Subject.hh:78
#3  0x00000000005e90c4 in openmsx::Setting::notify (this=0x27f70e0) at src/settings/Setting.cc:48
#4  0x00000000005e7286 in setValue2 (check=&lt;value optimized out&gt;, newValue=48000, this=&lt;value optimized out&gt;) at src/settings/SettingImpl.hh:180
#5  openmsx::SettingImpl&lt;openmsx::IntegerSettingPolicy&gt;::setValueString2 (check=&lt;value optimized out&gt;, newValue=48000, this=&lt;value optimized out&gt;)
at src/settings/SettingImpl.hh:239
#6  0x00000000004852fa in openmsx::Interpreter::traceProc (clientData=0xd, interp=0x27cc350, part1=0x27f3a00 "frequency", flags=33) at src/commands/Interpreter.cc:390
#7  0x00007ffff72add8c in TclCallVarTraces () from /usr/lib64/libtcl8.5.so
#8  0x00007ffff72b4989 in ?? () from /usr/lib64/libtcl8.5.so
#9  0x00007ffff72b6053 in Tcl_ObjSetVar2 () from /usr/lib64/libtcl8.5.so
#10 0x00007ffff72b616d in Tcl_SetVar2Ex () from /usr/lib64/libtcl8.5.so
#11 0x00007ffff72b61df in Tcl_SetVar2 () from /usr/lib64/libtcl8.5.so
#12 0x000000000048439e in openmsx::setVar (interp=0x27f77b0, name=0xbb80 &lt;Address 0xbb80 out of bounds&gt;, value=0x400 &lt;Address 0x400 out of bounds&gt;)
at src/commands/Interpreter.cc:231
#13 0x00000000005e9afa in openmsx::SettingsManager::loadSettings (this=&lt;value optimized out&gt;, config=&lt;value optimized out&gt;) at src/settings/SettingsManager.cc:138
#14 0x0000000000490c2b in openmsx::SettingsConfig::loadSetting (this=0x27f4000, context=&lt;value optimized out&gt;, filename=&lt;value optimized out&gt;) at src/config/SettingsConfig.cc:85
#15 0x0000000000415a47 in openmsx::CommandLineParser::parse (this=0x7fffffffd9b0, argc=&lt;value optimized out&gt;, argv=0x2c99f80) at src/CommandLineParser.cc:323
#16 0x0000000000465277 in openmsx::main (argc=1, argv=0x7fffffffdce8) at src/main.cc:78
#17 0x0000000000465729 in main (argc=41908144, argv=0xbb80) at src/main.cc:120

**Comment by m9710797** [comment]
Fixed in de3dc8cd834.
