### ISSUE TITLE
[Bug] FireHawk HDD beta9a freezes real hardware, but not openMSX [sf#393]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#787]
**Reported by sd-snatcher on 2010-05-30 19:00 UTC**
Dear openMSX dev team,

I'm working on FireHawk HDD and came to a showstopper. It freezes the real MSX hardware (tested on FS-A1ST, FS-A1GT and HB-F1XV+256KB mapper) both using Sunrise IDE, Padial's LPE-MMC-V6 and sharksym's SD interface, but openMSX runs the code without freezing. Because of this I'm not able to use openMSX to debug the problem.

Steps to reproduce the problem:

1) Get The FireHawk HDD beta-9a here:  http://frs.badcoffee.info/files/WIP/FHAWKHD-beta9a.7z
2) Uncompress it under a directory (say, FHB9A) on a partition containing the MSX-DOS2 v2.41
3) Run FIREHAWK.COM under that directory
4) Don't press any key and wait until the demo starts
5) On a real MSX, it will freeze when the demo would begin. But openMSX begins the demo without freezing.

Testbed configuration:

\- OpenMSX v0.7.2-dev11023 on Mac-OS-X 10.5.8 (emulated: FS-A1GT+Sunrise IDE)
- Panasonic FS-A1ST, 512KB RAM, Sunrise IDE
- Panasonic FS-A1ST, 512KB RAM, LPE-MMC-V6
- Panasonic FS-A1GT, LPE-MMC-V6
- Sony HB-F1XV, ASCII 256KB mapper cartridge, Sharksym's SD interface

**Comment by MBilderbeek** [comment]
sd-snatcher: is it possible for you to attach a disk image (zipped) to this ticket so we can test whether it still occurs? The link is down.

**Comment by sdsnatcher** [comment]
Sorry, that was 6 years ago. I don't have the file anymore. I guess this means that ticket can be closed.

**Comment by MBilderbeek** [comment]
OK, that leaves me no other choice than to close this ticket, as there's no way we can ever verify this issue anymore.
