### ISSUE TITLE
[Bug] Reversed cymbal too short on MoonSound wave [sf#394]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#788]
**Reported by manuelbi on 2010-05-30 19:26 UTC**
Meits reports:

May 29 2010 14:49:33 &lt;Meits&gt;    reversed cymbal is too short in openmsx
May 29 2010 14:50:23 &lt;Wolf_&gt;    it may have to do with envelope scaling
May 29 2010 14:50:46 &lt;Wolf_&gt;    if it\'s not done properly then at low and high pitches the time is off
May 29 2010 14:50:57 &lt;Wolf_&gt;    but, dunno how wel it\'s been done :D
May 29 2010 14:51:21 &lt;Meits&gt;    fair enough... but the fact remains... just listening to something old reversed cybal followed by a normal cymbal... there\'s a gap between them, which ofcourse shouldn\'t be there

&lt;Meits&gt; played 1 position with just a revcymbal and then a position with a rev cymbal followed by a crash cymbal...
&lt;Meits&gt; some intermezzos in tunes might have that second position... then it\'s not nice if there\'s a gap between the two sounds

May 30 2010 21:16:54 &lt;Wolf_&gt;    it may be envelope scaling not being implemented
May 30 2010 21:17:35 &lt;Wolf_&gt;    meaning that low notes have a longer envelope than higher notes
May 30 2010 21:17:48 &lt;Quibus&gt;   For wave?
May 30 2010 21:17:49 &lt;Wolf_&gt;    if that artifact is used in the original sound but it isn\'t emulated then the envelope is off
May 30 2010 21:17:51 &lt;Wolf_&gt;    yes
May 30 2010 21:18:39 &lt;Wolf_&gt;    dunno if that\'s it though, apart from a real bug (e.e. plain wrong code) it\'s the only thing I could think of
May 30 2010 21:18:46 &lt;Wolf_&gt;    just an ommision of a feature :P

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2010-05-30 19:26 UTC**
How it sounds on real MSX
Attached file %20-%20reversed%20cymbal%20MSX.mp3:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/692fd225/b0d6/attachment/%20-%20reversed%20cymbal%20MSX.mp3

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2010-05-30 19:27 UTC**
How it sounds on openMSX
Attached file %20-%20reversed%20cymbal%20openMSX.mp3:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/692fd225/694f/attachment/%20-%20reversed%20cymbal%20openMSX.mp3

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2010-05-30 19:27 UTC**
The Moonblaster Wave file that gives the output of the other files
Attached file REVCYMBL.MWM:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/692fd225/849d/attachment/REVCYMBL.MWM

**Comment by MBilderbeek** [comment]
Please check after processing #1114.

**Comment by MBilderbeek** [comment]
Confirmed by Meits that it is fixed with 6453d5c606f9b12691f6b22831e233d54dfa12c2
Thanks!
