### ISSUE TITLE
[Bug] Dingux start up very slow if many/large system roms inst'd [sf#396]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#790]
**Reported by manuelbi on 2010-06-06 17:11 UTC**
Start up was suddenly very slow. Stopping openMSX and restarting was also slow. It used to start up right after the text-mode screen disappeared, but it now takes another 10 seconds with a black screen after that happens. Also when starting a 2nd time. Also when loading a save state this happens. But when loading the savestate again or another savestate, it's very fast (within seconds).

&lt;Quibus&gt; Maybe it doesn't like that I unzipped a gazillion system roms
&lt;mth&gt; in share/systemroms?
&lt;Quibus&gt; yes
&lt;mth&gt; shouldn't it cache those?
&lt;mth&gt; or is validating whether the cache is up-to-date already heavy?
&lt;Quibus&gt; no idea, but I'm going to try out removing most of them
&lt;mth&gt; the cache is one level up here
&lt;mth&gt; .filecache
&lt;Quibus&gt; where?
&lt;mth&gt; ~/.openMSX/share/.filecache
&lt;Quibus&gt; ah, found
&lt;Quibus&gt; it's about 32kb
&lt;mth&gt; the native Dingoo OS resets the RTC
&lt;Quibus&gt; let's try now, with reduced ROM set
&lt;mth&gt; so that would invalidate the entire cache
&lt;mth&gt; still I'd expect that to cause a slowdown only once, not twice
&lt;mth&gt; although it could depend on which ROMs are used for the default machine vs the loaded save state
&lt;mth&gt; do save states of ROM games look for the ROM in the cache first or at the last known location first?
&lt;Quibus&gt; Startup is loads faster now
&lt;Quibus&gt; So, it's definitely the cache
&lt;Quibus&gt; aha
&lt;Quibus&gt; I used an adapted Boosted MSX2 EN
&lt;Quibus&gt; without large roms like the yrw801.rom
&lt;Quibus&gt; this is kind of killing, huge roms

Apparently something is going wrong with the filecache on Dingoo, because it was supposed to prevent this situation.

**Comment by MBilderbeek** [comment]
Dingoo isn't supported anymore, so this can be closed.
