### ISSUE TITLE
[Bug] C-BIOS upgrade breaks save states [sf#397]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#791]
**Reported by mthuurne on 2010-06-07 22:06 UTC**
I have a lot of save states made with a development version of openMSX 0.7.2. After I installed openMSX 0.8.0, the save state was loaded, but the game started acting weird. It turns out that a save state made with C-BIOS 0.23 will not run correctly on C-BIOS 0.24. This cannot be fixed in C-BIOS unless we would adopt restrictions that are so severe that it will paralyze development.

To fix it in openMSX, we have to ensure that save states will use the same C-BIOS version after loading as was used when saving. This of course requires that version of C-BIOS to be present. We could have openMSX include all C-BIOS versions ever shipped with openMSX since the save state feature was introduced.

If the required C-BIOS version is present, we also need a way to locate it. Inside the save state, the SHA1 sum of the system ROMs is stored. At the moment this is only used to verify whether the same ROMs are used when loading the state. However, the SHA1 sum could be used to automatically locate the right system ROM.

**Comment by MBilderbeek** [comment]
I think this is solved now, as openMSX uses the sha1sum to find back the used ROM. @mthuurne can you easily verify this?

**Comment by MBilderbeek** [comment]
All older C-BIOS versions are now included, as per 3748ea4c5bd74491f1c4360b92dcfd4c67aa2161
@mthuurne This issue is now resolved, right? Please reopen if it isn't.

**Comment by mthuurne** [comment]
Yes, we include all historic versions of C-BIOS exactly for that reason: to avoid old save states from breaking.

Funny that I apparently filed a bug for that but didn't remember it. It was over 8 years before senquack ran into the same issue.
