### ISSUE TITLE
[Bug] Initial values of PSG not correct [sf#415]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#809]
**Reported by joxy on 2011-06-26 23:00 UTC**
Openmsx produces no sound when the real MSX hardware did produce.

This is inputted right after MSX2 BASIC 2.1 bootup:

10 fori=0to255:sound0,i:sound0,255-i:next
run
Ok

Command line:
openmsx -machine Yamaha_YIS-503IIIR

As far as I remember (this must be verified on real hardware - I don't have a real hardware) - this program produces a sound on real hardware. But in openmsx, it stays silent: probably, the PSG register 8 contains a value of 0. Probably, on real hardware right after MSX BASIC 2.1 bootup, the PSG reg.8 value must be nonzero (again, this must be verified on real hardware).

$ openmsx --version
openMSX 0.8.1
flavour: i686
components: CORE GL
$

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2011-06-27 13:14 UTC**
This also produces no sound on my real MSXturboR (in Z80 mode). So, I think this is normal behaviour.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2011-06-27 13:14 UTC**
- **status**: open --> pending

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2011-06-27 13:52 UTC**
I tested again on a Yashica YC-64 (real machine), which has no disk drive, so does no beep and does not reset any PSG registers.

Result of: out &Ha0,8:?inp(&Ha2) is 127
Same for register 13.

On openMSX I get 191 in both cases.

But, on both real MSX and openMSX, you can't hear any sound after typing in that line of MSX-BASIC.

So, there is a small bug regarding initial values of the PSG register, I think.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2011-06-27 13:53 UTC**
- **priority**: 5 --> 2
- **summary**: openmsx produces no sound when it has to --> Initial values of PSG not correct
- **status**: pending --> open

**Comment by MBilderbeek** [comment]
I don't know what happened earlier, but when I try this now on openMSX, I get 0. And Leonard Oliveira tried on his VG 8020 and he also gets 0. So let's just close this ticket.
