### ISSUE TITLE
[Bug] Mirror I/O ports don't work openMSX [sf#420]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#814]
**Reported by sd-snatcher on 2011-08-24 04:32 UTC**

Currently, openMSX implements the I/O ports "by the book", placing the hardware exactly on their described I/O ports. But it isn't like the real world machines. Real hardware have much cheaper I/O port address decoders, which result in mirroring of the I/O ports on other unofficial ports, usually a subsequent set of ports.

For example, run this program on a real MSX. It will produce a beep on the PSG of all machines with the S1985 chipset, and also on most TTL-based (like the Gradiente Expert 1.0 & 1.1, Sharp Hotbit and the CIEL Expert Turbo). I tested it on a real Sony HB-F1XDJ and a real Gradiente Expert 1.1, and the schematics of the other mentioned machines shows that they will have this behavior too.

5 Rem Test the PSG I/O port mirroring. Will produce sound on most MSX machines
10 VDP(1)=VDP(1)AND&HDF
20 OUT&HA4,0:OUT&HA5,254
30 OUT&HA4,1:OUT&HA5,0
40 OUT&HA4,8:OUT&HA5,15
50 VDP(1)=VDP(1)OR&H20


Note1: The test program does not produce any sound on MSX Turbo-R machines and probably on other machines with the T9769x chipsets. These chipsets seem to have a more elaborated I/O address decoder.
Note2: The VDP, the PSG, the PPI and the Printer port are always subject to this type of mirroring, as most machines do reserve 8 consecutive I/O ports for each one.

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2011-08-24 09:38 UTC**
You're right that (for most openMSX machines) I/O port mirroring isn't implemented. Though to make it work we don't need to make any changes to the C++ code, only to the machine description files (share/machines/&lt;machine-name&gt;/hardwareconfig.xml).
For example, for the Sony HB-F1XDJ, you can add these 2 lines:
&lt;io base="0xA4" num="2" type="O"/&gt;
&lt;io base="0xA6" num="1" type="I"/&gt;
inside the &lt;PSG&gt; tag and the ports will be mirrored. This works because openMSX itself (the c++ part) for the PSG ports, for writes it only looks at the lowest 2 bits, for reads it doesn't check any bits at all.

So fixing these type of I/O port mirroring 'bugs' is certainly possible. Though it's a lot of work to verify on the real machines (and I don't blindly trust your note2 that on _all_ machines VDP, PSG, PPI and printer ports are mirrored).

IMHO this is also lower priority because except for very specific test-programs (BTW thanks for including such a test prog), no existing MSX software is affected by this. That's said, if you can give us fixed machine description files for specific machines we'd be very happy to include them in openMSX. But please always verify such changes  on a real machine.   (Another way to put this: I don't have time to work on this myself, but I'd gladly accept your help.)

Thanks.

Wouter

**Comment by openMSX-import** [comment]
**Updated by m9710797 on 2011-08-24 09:38 UTC**
- **priority**: 5 --> 3

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2011-08-24 18:02 UTC**
On Note2, I didn't wanted to mean that *all* machines will have this type of mirroring, but only mean that VDP, PSG, PPI and Printer-Port have a high probability of having the mirroring on many machines. Sorry for the ambiguity.

Don't worry if you don't have time: it's your hobby. I'll argument bellow not to try to change your decision, but only to give you a better context on the problem.

The problem I wanted to expose isn't related to affecting existing software, but to the use-case of developing new software using openMSX+debugger. I discovered this bug and the #3397166 when developing a game enhancement, then the PSG music sound completely weird on the real Sony HB-F1XDJ and the same symptom didn't happened on openMSX or on the real MSX Turbo-R. I even tough that the Sony machine was defective and tested a run of other software to check it.

It ended up that I had a routine on the INT handler that did a IN A,(C) and somewhere in the code the value of the register C was incorrectly overwritten to A5h. It wasn't an important I/O, so openMSX didn't showed any perceivable symptom at all. But with the PSG registers being corrupted at 60Hz, you can imagine the kind of distortion that this caused on the music played by the HB-F1XDJ.

It was somewhat hard to find the bug, as the emulator wasn't behaving like the real hardware. If I only had openMSX and my Turbo-R to test the software, probably the bug would go out unnoticed.

One important aspect of having so many different machines emulated on openMSX is exactly being able to test on as many configurations as possible without having to own each hardware. Off course this isn't the same as testing on the real thing, but at least I can send software with a lot less bugs to my fellow betatesters to try it.   :)

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-07-23 15:50 UTC**
I actually implemented a few of these mirrorings for machines on which they were confirmed (by Leonard Oliveira). If people find more of these on real machines, I'll happily adjust the machine configs.

See commits
778dce5cde58dc4ba24adc5184ca7f383fbc7d56
(oh, I thought there were more, but at least this one).

**Comment by MBilderbeek** [comment]
Let's close this until we find more concrete missing issues. Feel free to reopen if there's anything to add.
