### ISSUE TITLE
[Bug] does not meet a de facto world standards for keys [sf#423]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#817]
**Reported by joxy on 2011-09-04 05:29 UTC**
this is open and minor question, please take lightly!

(14:08:26) buguldey1: the usual F11 (toggle fullscreen) is bound to toggle muted in openmsx
(14:08:39) user2: no, F12 is fullscreen toggle
(14:09:06) user2: has been like that from the start
(14:09:07) buguldey1: in many programs except for openmsx F11 is toggle fullscr
(14:09:27) buguldey1: And there is a Multimedia button mute sound
(14:09:33) buguldey1: on some of kbds
(14:09:51) user2: it's a default, you can change keyboard binding
(14:10:07) user2: you can put fullscreen toggle on F11
(14:10:52) buguldey1: hehe. no mute button on my kbd.
(14:10:57) user2: and if that mute multimedia key has an SDL key event code, you can bind that to mute toggle
(14:13:18) buguldey1: ...but i have mute switch inside the acoustic system's variable resistor
(14:15:06) user2: with mute in openMSX you can only mute the openMSX sound
(14:15:13) user2: with that switch you mute EVERYTHING
(14:17:13) buguldey1: world standard for fullscr toggle is having both F11 and Alt Enter to link to this action.
(14:17:37) user2: afaik there is no world standard for that
(14:17:55) buguldey1: it was created initially by IE
(14:17:57) user2: it has become common, but that doesn't make it a 'world standard'
(14:18:02) buguldey1: de-facto world standard
(14:18:14) buguldey1: it does make a defacto world st.
(14:18:22) user2: which moron still uses IE?
(14:18:32) buguldey1: firefox uses F11 for that
(14:18:42) buguldey1: many movie apps use F11 for that
(14:18:52) buguldey1: virtualbox does the same
(14:18:55) user2: THAT DOES NOT MAKE IT A WORLD STANDARD
(14:19:06) buguldey1: gedit uses F11 for that
(14:19:14) buguldey1: it does. de facto one.
(14:19:24) buguldey1: well
(14:19:53) buguldey1: user2: the best way is to have "MUTE_TOGGLE" trigger in OS layers, and to link to this trigger instead of kbd keys
(14:20:11) buguldey1: and FULLSCREEN_TOGGLE trigger, too
(14:21:17) user2: that would require EVERY KEYBOARD to have such a key
(14:21:24) user2: which they don't
(14:21:59) buguldey1: user2: or just a kbd way, which may involve key combinations or emacsish stuff
(14:24:30) user2: mac is an apple standard... of course those keyboards are always the same

**Comment by openMSX-import** [comment]
**Updated by joxy on 2011-09-04 05:30 UTC**
- **priority**: 5 --> 1

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2011-09-05 13:12 UTC**
I agree it would have been better to use F11 for 'toggle fullscreen'. If we were to re-develop openMSX from scratch we should certainly change this.

I did some digging through SVN history and we've used F11 for 'toggle mute' since 2001/12/15 (SVN revision 759). That's almost 10 years ago! (I don't know if F11=fullscreen was already popular at that time). So I'm not sure we should still change this:
- For new users this is probably useful, they don't care about openMSX history
- For existing users it may be annoying, since they are probably used to it by now.

Based on the above paragraph I prefer to keep the default keybindings as they are. OTOH not making (small) improvements only because "it's been like that forever" may not be the best choice either. So I'd like to hear other peoples opinion on this topic.

**Comment by openMSX-import** [comment]
**Commented by mthuurne on 2011-09-05 14:29 UTC**
About the mute media key: this should mute all audio of the PC, not just the current application. The mute function in openMSX should mute openMSX alone. This is useful if for example you want to listen to a radio stream instead of game sfx/music while playing an MSX game. So this part works as desired in my opinion.

About fullscreen: most applications I use have F or CTRL-F for full screen, but that is not an option in openMSX because it would conflict with MSX controls. As far as I know we do use Cmd-F on Mac, because Cmd has no MSX mapping and the function keys are increasingly claimed by OS X itself. I don't really mind swapping F11 and F12 on Windows and Linux/BSD though if it will make users happy.

**Comment by MBilderbeek** [comment]
@m9710797 If we release openMSX 1.0.0 soon, wouldn't that be a good moment to change it? even after 18 years...
