### ISSUE TITLE
[Bug] AltGr key broken with recent version of SDL 1.2.x [sf#444]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#838]
**Reported by awulms on 2012-11-25 10:28 UTC**
It is no longer possible to enter characters into MSX that require AltGr key like the @ or # characters on an AZERTY host keyboard.

**Comment by MBilderbeek** [comment]
@m9710797 I think this got fixed with e906b33f7318503f14dda718f47c6ff847bf4038 right?
Closing... if I made a mistake here, please reopen, as I can't test this myself.
