### ISSUE TITLE
[Bug] Android: performance not as expected [sf#450]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#844]
**Reported by manuelbi on 2012-12-03 10:00 UTC**
I saw that it doesn't get full framerate (although you hardly notice). That's a bit disappointing, as the Dingoo on 400MHz seems to get about the same or better framerate than my Gio at 800MHz.

**Comment by openMSX-import** [comment]
**Commented by awulms on 2013-11-03 15:36 UTC**
A Dingoo uses a MIPS CPU. The Gio an ARM CPU. They can not be compared by simply looking at the clockspeed of the CPU. Another difference is probably the GPU which is used in the Dingoo versus the one used in the Gio. The Android port relies on the GPU for the scaling from the framebuffer used by openMSX to the framebuffer of the physical screen. This might be the bottleneck.

I don't know how I can fix expectations that are based on comparing two completely different hardware devices and in that comparison looking at only one single metric that impacts the speed and power of the device.

**Comment by openMSX-import** [comment]
**Commented by awulms on 2013-11-03 20:45 UTC**
Settings that impact performance:
set horizontal_stretch=320 for best performance
set resampler=fast or resampler=blip  (blip sounds much better but is slightly slower)
set auto_enable_reverse=off

TODO: implement these values as defaults for Android flavour and make them configureable through OSD menu

**Comment by MBilderbeek** [comment]
All these things are implemented (years ago), except that you can set auto_enable_reverse via the OSD menu.
I don't think we will do anything about this bug anymore, so let's just close it.
