### ISSUE TITLE
[Bug] Delta Soft Tool Disc crashes in openMSX in bootsector [sf#467]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#861]
**Reported by manuelbi on 2013-04-03 13:48 UTC**
Attached disk image works fine on real machine (tested with nowind on GT), but crashes on emulated machine in openMSX (either di; halt (MSX2), or other hangup (turboR)).

So far Wouter found out:
-  if i copy the files to another disk (with original bootsector) it seems to work
-  bootsector loads msxdos.sys at address 0x100 and then jumps to 0x100 .. but the program loaded at 0x100 does not correspond to the content of the msxdos.sys file ... no idea yet why not

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2013-04-03 13:48 UTC**

Attached file tooldisc.dsk.gz:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/5e9fe5f0/1e91/attachment/tooldisc.dsk.gz

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2013-05-25 20:11 UTC**
Just checked: this 720kB disk image has an F8 media descriptor (which is used for single sided 360kB images). I guess this is confusing openMSX.

**Comment by MBilderbeek** [comment]
Yep, that's the problem, copying only the first 360kB of the disk image makes it work. So this is not a bug in openMSX, it's a wrong disk image. (openMSX uses the size to determine how many sides it has.)
