### ISSUE TITLE
[Bug] Trackball emulation overflow values too easily [sf#477]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#871]
**Reported by sd-snatcher on 2013-07-23 03:39 UTC**
The current trackball emulation tries to mimic the real hardware implementation: b0-b2,b7 connected to the MSX.

The MSX-trackball was mechanically designed to avoid easy overflows: some turns were needed on the trackball to make that.

Also, the original device clearly had a much lower resolution than the current PC mouses/touchpads used on current PCs. Selecting something on the menus requiring to fine movements on the PC mouse.

The result in current emulation is that the trackball offsets on openMSX overflow pretty easily and the resulting emulation is unpleasant to use (no offense meant). Try to draw something on the Eddy2 graphic editor, or play Space Trouble, to see what I mean.

Probably the best approach is:

1) Saturate the offsets instead of letting them overflow. This will better reproduce was was achieved by mechanical constraints on the real device. In pseudo code:

If offsetx <-8 then offsetx=8 else if offsetx>7 then offsetx=7
If offsety <-8 then offsety=8 else if offsety>7 then offsety=7

2) Divide the offset received from the PC by two, halving the PC mouse resolution. This will allow easier manipulation of the menus from HAL Laboratory softwares.

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-08-31 01:54 UTC**
Werner was kind to test his Sony GB-6 and it became clear that the built-in chip features saturation arithmetic support. Even under heavy revving as he did on the video, the trackball never overflows the offsets as openMSX does. Please check the attached video for the results on real hardware.

This means that the openMSX trackball emulation is indeed bugged.

Attached file MSX%20SONY%20GB-6%20HAL%20EDDY2%20Overflow%20Test.wmv:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/9e82227a/cbe2/attachment/MSX%20SONY%20GB-6%20HAL%20EDDY2%20Overflow%20Test.wmv

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-08-31 01:55 UTC**
More about Saturation arithmetics:
http://en.wikipedia.org/wiki/Saturation_arithmetic

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2013-08-31 11:22 UTC**
Fix confirmed with Wouter's commit fddca395d2829f3ce51b2fcd9c9903681c184f2f

Thanks for reporting and fixing!

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2013-08-31 11:24 UTC**
- Description has changed:

Diff:

```

--- old
+++ new
@@ -1,4 +1,3 @@
-
 The current trackball emulation tries to mimic the real hardware implementation: b0-b2,b7 connected to the MSX.

 The MSX-trackball was mechanically designed to avoid easy overflows: some turns were needed on the trackball to make that.

```
- **status**: open --> closed-fixed
- **assigned_to**: Wouter Vermaelen

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-08-31 16:18 UTC**
Thanks!   :)

**Comment by openMSX-import** [comment]
**Updated by m9710797 on 2013-11-19 20:24 UTC**
- **status**: closed-fixed --> pending-works-for-me

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2013-11-19 20:24 UTC**
Reopening this bug. (triggered by feedback on MRC: http://www.msx.org/forum/msx-talk/openmsx/wanted-feedback-mac-os-x-users?page=4)

@sd-snatcher: I can reproduce the issue in Eddy2: moving the host mouse reasonably fast results in fast motion of the emulated cursor (controlled via emulated trackball). When the moving the host mouse much faster, the emulated cursor speed is instead slower.

I double checked the implementation in openmsx (Trackball emulation, but in the end the whole mouse event stuff) but I couldn't find anything wrong with it. Then I checked a few other MSX programs that use the trackball. I could not reproduce the issues in those programs! So I suspect this is an issue in Eddy2 itself.

The following is just a guess: when the host mouse is moved very fast, after clipping, the msx trackball always returns a constant value. Is it possible that Eddy2 has some kind of joystick-port protocol-detection mechanism that gets confused when it constantly sees the same large value??

@sd-snatcher: Can you please verify my findings. E.g. can you reproduce this issue in another program? (Did you originally see this issue in Eddy2?).

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2013-11-20 21:13 UTC**
Tested in some more programs, for example Graph Saurus v2.0 (suggested by sd-snatcher on MRC). This program also behaves fine, but Eddy2 indeed shows the weird behavior. So it's likely an issue in Eddy2 itself. I consider this bug solved.
@sd-snatcher: agreed?

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2013-11-21 21:18 UTC**
I can reproduce this issue easily with GS2... so I'm not sure why Wouter couldn't. There's a very clear difference between mouse and Trackball behaviour in GS2.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2013-11-21 21:19 UTC**
- **status**: pending-works-for-me --> open

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2013-11-21 22:12 UTC**
Actually, I tried again. And I couldn't reproduce the issue. There is quite a small maximum in the speed of the trackball and so it maxes out very easily. When moving very fast with the mouse, it seems like the trackball controlled cursor is moving slower. But it's actually ust moving at the max speed. Very tricky, but when recording a movie (or using reverse and looking back) and measuring the cursor speed, it's actually the same in all cases.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2013-11-21 22:12 UTC**
- **status**: open --> pending-works-for-me

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-11-23 01:24 UTC**
Since Wouter couldn't reproduce the problem, I was afraid that it could be a OS-X only problem. But I downloaded the and tested the Windows version, and the same problem happens on GS2 in Windows too.

Wouter: It's much easier to notice the problem if you test GS2 in screen-7 mode under either OS-X or Windows. I just don't know if the problem will show up in Linux.

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-11-23 01:50 UTC**

Edited: A second test showed that the bug indeed happens. The less inclined lines in the screenshot were drawn while moving the mouse at a slower speed, while the more inclined (closer to vertical) lines where drawn while moving the mouse at maximum speed.

Attached file openmsx0004.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/9e82227a/5481/attachment/openmsx0004.png

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-11-23 02:04 UTC**
Another screenshot on how to reproduce the problem:

Use GS2 in screen-7 mode. All lines must be drawn from top-left to bottom-right

1) Select black color, draw while moving the mouse as fast as possible
2) Select dark-green color, draw while moving the mouse an almost maximum speed
3) Select dark-blue color, draw while moving the at an average speed

The results will be shown as this screenshot, in angles that are the exact opposite as one would expect.

Attached file openmsx0005.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/9e82227a/2618/attachment/openmsx0005.png

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-11-23 02:59 UTC**
I did a second test, just to be sure. This time I used a more controlled approach, to make sure that it wasn't my perception that was distorting the tests. 

Use GS2 in screen-5 mode. All lines will be drawn from top-left to bottom-right.

1) Put your mouse inside a drawer or any other guide that makes sure that it only mover horizontally.
2) Incline your mouse 45 degrees to the left, like this:   \
3) Select black color, draw while moving the mouse to the right as fast as possible. This will be your reference line
4) Select dark-green color, draw while moving horizontally to the right, following the guide. Move the mouse slower, while trying to draw a line that is less inclined than the black one.
3) Select dark-blue color, draw while moving to the right, following the guide. Move the mouse even slower, while trying to draw a line that is even less inclined than the dark-green one.

The results will be shown as this screenshot, in angles that are the exact opposite as one would expect.

Attached file openmsx_trackball2.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/9e82227a/cb67/attachment/openmsx_trackball2.png

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-11-23 03:00 UTC**

BTW, this was the result when I tried to draw the same test using the MSX-mouse emulation. The lack of clipping caused the black line to be drawn completely erratic.

Attached file openmsx-mouse1.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/9e82227a/e5fc/attachment/openmsx-mouse1.png

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-11-23 03:03 UTC**

This is the 2nd try using the MSX-mouse. The lack of clipping indeed seems to be a problem when moving the host mouse quickly.

Attached file openmsx-mouse2.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/9e82227a/7542/attachment/openmsx-mouse2.png

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2013-11-24 09:30 UTC**
I'm sorry, but I don't understand. To me that black line indicates that clipping is working perfectly, no?

Can you please explain what the angles of these lines are supposed to indicate? And why did you expect them to be opposite? (What does 'opposite' mean in this case? Below the black line?) It's also not clear to me how an angle of a line can tell anything about the speed at which that line was drawn.

So please explain in more detail. But anyway, _if_ there's still something wrong with trackball emulation it will we a very minor thing, because general movement seems to work fine. Clipping seems to work fine. The only thing that's _maybe_ wrong is some behavior when moving the mouse super fast (and we've already dismissed one such test as a misinterpretation). So for now I still consider this issue solved (and if there's still some detail wrong, it's certainly a low priority issue).

**Comment by openMSX-import** [comment]
**Commented by sd-snatcher on 2013-11-25 22:35 UTC**
The angles were supposed to show that the horizontal speed was being higher for the green and blue lines, subsequently.

I got some time to think a bit more about the test and the results this weekend. In fact, it isn't indeed possible to test it reliably this way, since any minor angle difference in the mouse placement will influence the results.

That said, the current clipping code seems to be working fine. It's probably an optical illusion that causes the feeling that the mouse is going slower when the clipping kicks in.

Maybe a way to minimize this illusion is adapt a logarithmic scale. Lines 145 & 146 of Trackball.cc would become something like this, in pseudocode:

```
float dx = log(mev.getX()/3+1,1.4);
    float dy = log(mev.getY()/3+1,1.4); 
```

But using the logarithmic scale would be something to be implemented in the future. For now the trackball emulation is good enough.

**Comment by MBilderbeek** [comment]
So, um, that means we could just as well close this issue :)
