### ISSUE TITLE
[Bug] Broken support for cyrillic characters when setting a consolefont containing cyrillic characters in openMSX [sf#478]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#872]
**Reported by joxy on 2013-07-24 00:40 UTC**
In Ubuntu, when I do <set consolefont /usr/share/fonts/truetype/freefont/FreeMono.ttf>, the cyrillic chars show up as rectangles.

When I open this font from (MATE's, http://mate-desktop.org) `caja' program (a renamed Nautilus), the font viewer shows cyrillic characters okay.

$ openmsx --version
openMSX 0.9.1
flavour: i686
components: AO CORE GL LASERDISC

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.2 LTS
Release:    12.04
Codename:   precise

**Comment by openMSX-import** [comment]
**Commented by joxy on 2013-07-24 00:41 UTC**
Hmm. I do "set consolefont /usr/share/fonts/truetype/freefont/FreeMono.ttf"

**Comment by openMSX-import** [comment]
**Commented by joxy on 2013-07-24 00:44 UTC**
BTW, the "Copyright" string for this font reads "Copyleft 2002, 2003, 2005, 2008, 2009, 2010 Free Software Foundation."

**Comment by openMSX-import** [comment]
**Commented by joxy on 2013-07-24 00:52 UTC**
This is a "seems-to-be" bug, as I didn't investigate whether this font actually supports the cyrillic chars.

**Comment by openMSX-import** [comment]
**Commented by joxy on 2013-07-24 01:01 UTC**
I restarted openmsx, the console's font started to show cyrillic chars, though the letter spacing is incorrect. CHanging title for this bug report

**Comment by openMSX-import** [comment]
**Commented by joxy on 2013-07-24 01:04 UTC**
The actual bug is: the blinking cursor shows at incorrect place with a custom consolefont. Is is (approximately) at the hand-drawn redline at the screenshot.
Attached file shot_incorrect_letter_spacing.png:

Attachment at http://damad.be/joost/openmsx/attach/p/openmsx/bugs/_discuss/thread/df737e6c/f45f/attachment/shot_incorrect_letter_spacing.png

**Comment by openMSX-import** [comment]
**Commented by joxy on 2013-07-24 01:06 UTC**
Also, the doc at http://openmsx.sourceforge.net/manual/commands.html#consolefont should mention that restart of openmsx is necessary to actually reflect the consolefont change.

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2013-07-25 07:53 UTC**
The console font should be changed immediately after changing the 'consolefont' setting, similarly for the 'consolefontsize' setting. This was a bug. It should be fixed in git revision 7f01975.
I _believe_ the rendering artifacts you saw were caused by using a non-monospaced font. I've added a check for this in the code, now openMSX refuses to use such fonts (in the console).
Please update to latest git revision and retest. Thanks.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2013-10-05 12:04 UTC**

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2013-10-05 12:04 UTC**
Joxy, please confirm whether this is fixed now, so we can close this ticket.

**Comment by MBilderbeek** [comment]
Nothing heard anymore, so let's assume the issue is fixed, as we have no way to reproduce it now.
