### ISSUE TITLE
[Bug] Can't browse to network shares on Windows in OSD menu [sf#507]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#901]
**Reported by manuelbi on 2013-12-29 09:23 UTC**
Reported by FRS:
Browsing worked fine for local drives and USB thumb drives, but didn’t work on a network drive. This network drive works fine with everything else on Windows. Curiously enough, the tab completion of the openMSX shell seemed to have some quirks to do its job under some directories of that drive, but otherwise the shell loaded ROMs just fine on the net drive.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2013-12-29 09:23 UTC**
- **labels**: Windows --> Windows, OSD-menu

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-01-07 20:24 UTC**
I tried this on a Windows XP machine with a samba share. I had no problems to browse it at all... perhaps it is a local thing after all?

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-01-07 20:24 UTC**
- Description has changed:

Diff:

```

--- old
+++ new
@@ -1 +1,2 @@
+Reported by FRS:
 Browsing worked fine for local drives and USB thumb drives, but didn’t work on a network drive. This network drive works fine with everything else on Windows. Curiously enough, the tab completion of the openMSX shell seemed to have some quirks to do its job under some directories of that drive, but otherwise the shell loaded ROMs just fine on the net drive.

```

**Comment by MBilderbeek** [comment]
I just tested it on Windows 8. I mapped network drive can be browsed fine and the console seems to work fine with it too. You can't browse to a network drive that's not mapped, as it is not a root entry somewhere in the file hierarchy. Isn't that expected?

**Comment by MBilderbeek** [comment]
No response and it works as expected for me, so closing. Please reopen if you feel the need to :)
