### ISSUE TITLE
[Bug] OPL4 bug not emulated [sf#523]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#915]
**Reported by manuelbi on 2014-03-06 21:02 UTC**
See http://www.msx.org/news/challenges/en/gmc-19-salamander-starfield-omega:

When playing samples there's two modes from a software perspective: a single sample with an end or a looped sample. However in hardware there's only one: a single sample is padded with a few zero bytes and those bytes are used in a loop. In both ways, with a relatively short loop or a sample with a zero'd loop, playing high frequencies (like C7) the OPL4 can skip past the end of a loop address and continue playing whatever is in the address space after that position.

In this case, that results in some nasty noise

This OPL4 bug is not emulated.

MBM/MWM files attached.

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-03-08 15:26 UTC**
<hap> the noise is at 0:51

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2014-04-12 11:30 UTC**
Perhaps this is the same: (Quoted from: http://www.msx.org/forum/msx-talk/development/moonsound-problem-custom-samples-real-machine?page=1#comment-236765 )

Anyway, I found another thing that OpenMSX does differently than a real OPL4. As far as I know, there's no way to tell the OPL4 that there is no looping of any kind, so for non-looping samples I have to set a very short loop at the end of the sample. If I set the Loop address field of the wave header to exactly the length of the sample, then the real OPL4 seems to continue reading past the end or something, but OpenMSX stops there nicely. I need to set the Loop address to the length minus one, to make the real OPL4 not play random garbage.

By the way, I wonder if it's possible to utilize this glitch for having samples longer than 64k samples.

**Comment by MBilderbeek** [comment]
See also  #1114.

**Comment by MBilderbeek** [comment]
Also, this could be the same as #1000 - but we can treat it separately.

**Comment by MBilderbeek** [comment]
yzi confirms the loop stuff is now emulated, see https://www.msx.org/comment/reply/44889/343551

So, this bug is fixed with 6453d5c.
