### ISSUE TITLE
[Bug] MBFM doesn't work correctly in R800 mode on openMSX [sf#550]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#941]
**Reported by manuelbi on 2014-08-03 13:09 UTC**
When starting MBFM 1.03 (attached) in openMSX on turboR (boots in R800  mode), it doesn't work correctly. For example:
- 'blink' color (red bars) not shown e.g. when playing the song with F1 nothing is seen
- pressing F4 should open the Voice menu, but what happens is that the cursor disappears for a while and then comes back. Nothing else.

It works fine on real GT (tested via Nowind). 

In openMSX it works fine when booting with the 1 key pressed, so Z80 mode.

**Comment by MBilderbeek** [comment]
i just tried again with attached (this time for real; one which boots in DOS2 and one which boots in DOS1, so for that you need to boot without this disk inserted or from IDE

[mbfm103.zip](https://github.com/openMSX/openMSX/files/239193/mbfm103.zip)

) disk image, and it works fine now. So closing.
