### ISSUE TITLE
[Bug] Crash when quitting while connected to debugger and breaked [sf#551]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#942]
**Reported by grauw on 2014-08-12 19:58 UTC**
When I quit openMSX while connected the the debugger, and when openMSX is breaked, openMSX gives me one of the following four results:
1. Nothing.
2. Error message “Assertion failed: (ec == 0), fun”
3. Error message “Assertion failed: (ec == 0), function unlock, file /Source”
4. Crash, and error message “Assertion failed: (ec == 0), function unlock, file /SourceCache/libcxx/libcxx-120/src/mutex.cpp, line 45.”

The issue is quite intermittent, I would say 50% of the time I get no error at all, and the actual crash only happens 1% of the time. The attached crash report is from the fourth case.

My interpretation is that there is some kind of race condition between the assertion happening, and the program terminating before the error has been fully processed. I am using a current development build on Mac OS X 10.9, the debugger is built with Qt4.

Steps to reproduce:
1. start openmsx
2. start debugger
3. connect debugger
4. break debugger
5. close openmsx

**Comment by openMSX-import** [comment]
**Commented by grauw on 2014-08-13 19:51 UTC**
If I put sleep(10) at the end of the CliConnection destructor I get a reliable crash reproduction.

**Comment by grauw** [comment]
I’m not sure but I /think/ it went away after I upgraded OS X, though it could’ve also been something else. It’s no longer occurring anyway, though I haven’t tried to reapply the sleep(10).
