### ISSUE TITLE
[Bug] "Applause B" MoonSound sample does not fade out [sf#561]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#952]
**Reported by manuelbi on 2014-12-16 20:44 UTC**
This ROM sample should fade out, but it doesn't in openMSX.

To easily test:
1) start mbwave
2) go to instrument menu (F3) and select the "Applause B" sound for instrument 1
3) press M to play the sound and keep the key pressed
4) on real MSX, the sound will fade out after a while, in openMSX it does not. Here is what happens on real hardware: http://meits.nl/files/msx/applause.wav

Reported by Meits.

**Comment by MBilderbeek** [comment]
See also  #1114.

**Comment by MBilderbeek** [comment]
[music0004.vgm.gz](https://github.com/openMSX/openMSX/files/2412943/music0004.vgm.gz)

**Comment by ValleyBell** [comment]
Same VGM, except fixed (the old one lacked initialization commands and did not produce any sound) and stripped of unnecessary data.

[applause_fixed.vgm.gz](https://github.com/openMSX/openMSX/files/2417076/applause_fixed.vgm.gz)
