### ISSUE TITLE
[Feature] Default extension options in settings.xml [sf#72]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#96]
**Reported by grauw on 2004-01-22 22:05 UTC**
Subject says it all, really...

Currently, there is a 'default machine' setting in
settings.xml. This makes starting openMSX easier, not
having to type -machine, etc. on the commandline.
However, such a setting does not exist for extensions.
So, in order to make permanent use of a particular
extension, I would have to edit the machine's
hardwareconfig.xml.

I would like to keep the machine definitions intact
when adding some custom data though... They describe a
particular machine (for example Philips NMS 8250) into
every detail, and changing the xml would invalidate
that. Besides, I don't think extensions like the
MoonSound or IDE interface 'belong' in the machine
config, as IRL they are not built-in either. Another
thing is, the settings.xml is a lot easier to find than
the hardwareconfig.xml's.

Also, some extensions I would want to use on all
machines by default. Suppose I have am developing a
program using the debugdevice, and I want to test it on
a variety of machines. I would want to keep the
debugdevice permanently enabled. Currently, I either
have to edit all machine configs, or have to use the
commandline parameter (which is longer to type).

Another example is the IDE interface. If I were to use
openMSX like I use my MSX right now, I would want to
have it always connected. Always typing it on the
commandline is a bother, and having it in my machine
definition is, I think, not appropriate.

One other thing which would be useful to add to the
commandline, when this is realized, is a -next option
(No Extension), with which extensions set by default
(like IDE interface/DOS2) can be disabled.

Anyways, that's about it :).

~Grauw

**Comment by openMSX-import** [comment]
**Commented by grauw on 2004-01-22 22:12 UTC**
Logged In: YES 
user_id=798154

Gah, duplicate (somewhat) of
http://sourceforge.net/tracker/index.php?func=detail&aid=788926&group\_id=38274&atid=421864

**Comment by openMSX-import** [comment]
**Commented by grauw on 2004-01-22 22:35 UTC**
Logged In: YES 
user_id=798154

Note: the slot number of such an extension can ofcourse be
given with a &amp;lt;slot&amp;gt; parameter, but if skipped, you
could use a default algorithm to place it. I think something
like that already happens when adding extensions using -ext
on the commandline.

An example algorithm would be to allocate the highest
possible slot for extensions (IF they have a ROM, for I/O
devices it ofcourse doesn't matter), and enabling
slotexpanders when needed. By the way, when specifying a
specific slot with a &amp;lt;slot&amp;gt; (or similar) tag, it could
auto detect whether a slot expander is needed. So I don't
know if there is a need for a special slot expander tag.
OTOH, it might be consistent with the way things work on MSX
to do so...

~Grauw

**Comment by openMSX-import** [comment]
**Commented by manuelbi on 2005-12-07 21:07 UTC**
Logged In: YES 
user_id=78178

Closed because it's basically also in RFE 788926. See there.

**Comment by openMSX-import** [comment]
**Updated by manuelbi on 2005-12-07 21:07 UTC**
- **labels**:  --> General/misc
- **status**: open --> closed

**Comment by oh-ren** [comment]
RFE 788926 -> #78
