### ISSUE TITLE
Joytest v2.3 reads bogus values for the trackball and touchpad

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#964]
JOYPORT v2.3b is working fine on my real Sony HB-F1XDJ, but it's going nuts on openMSX-0.11.0!!

To reproduce the error, just run any MSX2/MSX2+ and JOYTEST on openMSX. Them plug
either a touchpad or a trackball and the results will be completely bogus. At least on Mac OS-X 10.9.5.

Joytest can be obtained here:
http://frs.badcoffee.info/tools.html

**Comment by MBilderbeek** [comment]
What happens with this program on real MSX with touch pad and track ball can be seen in this video: http://youtu.be/RP1ji709uGM

**Comment by m9710797** [comment]
The trackball and touchpad were two separate issue. Respectively fixed in revision adf3e87f and 495f4de5. See those commit message for more details.
