### ISSUE TITLE
[Bug] Panasonic MSX2+ machines block the reading of external memory mapper registers

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#966]
Panasonic MSX2+ machines have a behavior that currently isn't being emulated by openMSX: they block the reading of external memory mapper registers.

Steps to reproduce the error:

1) Boot a Panasonic FS-A1WX with the extension ram1mb connected to slot-1
2) On MSX-BASIC, type:

?HEX$(INP(&HFF))

3) The result on a real Panasonic MSX2+ machine is "FC". On openMSX, the result will be "C0".

This emulation bug affects how software that read the memory mapper registers will behave. On the real machine with an external memory mapper those softwares will freeze. But on openMSX they'll run.

Try running the "Unknown Reality" demo, for example.

**Comment by mthuurne** [comment]
Oops... 4 was not the right number, but with 2 it does read back as FC.
Should be fixed now. Thanks for reporting!

**Comment by mthuurne** [comment]
By the way, do we know which component in the machines causes this behavior? If it is the T9769 engine, more machine models could be affected.

**Comment by MBilderbeek** [comment]
See https://github.com/openMSX/openMSX/issues/989#issuecomment-182355387
According to FRS, it's not the T9769 but the gate array that implements the MSXMatsushita device, which is also present in more machines. For instance the Sanyo PHC-70FD/FD2.

**Comment by sdsnatcher** [comment]
Yes. But be aware that the gate-array of the Panasonic machines is bigger (has more logic gates) than the one on the Sanyos. This means it has more functions, like the turbo clock generator and (probably) the memory mapper port blocker.

IIRC, the Sanyos don't block the external memory mapper port readings. That would prove that the T9769 is innocent in this case.
