### ISSUE TITLE
[Bug] Talent DPF-550 isn't working

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#967]
The Talent DPF-550 disk interface doesn't seem to be working. It doesn't boot disks, and gives an "disk I/O error" when you try the command "files".

Tested with: openMSX-0.11.0 on Mac OS-X 10.9.5.

Steps to reproduce the error:

1) Boot a Sanyo PHC-23J(B) with the Talenf_DPF-550 extension connected, and -diska with an MSX-DOS 1 operating system.

2) The MSX-DOS1 will not be booted and the machine will go straight to MSX-BASIC

3) Type the command "FILES" to try to list the directory contents

4) The error "Disk I/O error" will be shown

**Comment by MBilderbeek** [comment]
Works fine here, but it seems to be picky on the exact format. If I create a 360kB disk image, and format it with the Talent DPF-550, it works fine. I could even write MSX-DOS to it and then it boots fine. Booting an existing SS disk image with DOS1 did not work properly, indeed.

But anyway, I think the extension is fine.

I'll attach an example disk image which works (formatted with the Talent DPF-550).
![test dsk gz](https://cloud.githubusercontent.com/assets/12675978/8894403/21bae37e-33b6-11e5-82e5-c631bb09022a.png)

(rename to test.dsk.gz)

**Comment by sdsnatcher** [comment]
openMSX-0.11.0 crashes when I try this disk image.

If it works in the latest build, I think there still two other bugs here:

1) openMSX should refuse to run (or give a warning) if a disk-image bigger than the drive support is selected. Just as it refuses the -dska parameter if there's no disk interface present.

2) Dir-as-disk isn't aware of the maximum disk size supported by the interfaces, so it's creating a 720KB image for a drive that only supports 360KB disks.

**Comment by grauw** [comment]
I tried the disk image, doesn’t crash for me. OS X 10.10.4, openMSX 0.11.0-282-g8e6af20-dirty [devel].

Re. 1), what does a real MSX do when you put a 720K floppy in a 360K drive? Either says “Disk offline” or “Disk I/O error” I imagine…
