### ISSUE TITLE
[Enhancement] The DDX 3.0 disk interface is using a ROM with 16KB of overdump

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#969]
The current DDX_3.0.xml extension asks for a ROM with the following checksum:

<sha1>9e8256c90c37619dccdc2c8a6aa4539fb742a4b3</sha1>

But this is a 32KB ROM that has 16KB of overdump.

There are other better ROM dumps available for this interface, and should be used preferably in this order:
            <sha1>a363015286341ffabcdc38ef0d890897ed51e322</sha1>  
            <sha1>124126cee840e43c7668c11c2bec2f34b3d00c68</sha1>

**Comment by MBilderbeek** [comment]
Fixed, see commit 10557d6a15d421d766e5e549e20e5a3d95263164
