### ISSUE TITLE
[Feature] Beer-IDE emulation

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#970]
Beer-IDE is a simple and affordable IDE interface intended for computers that can't run MSX-DOS2, like MSX1 computers with only 64KB of RAM.
http://msx.hansotten.com/index.php?page=beer-ide

Feature suggestion: Please consider adding support for this interface.

**Comment by MBilderbeek** [comment]
OK, I'm doing an attempt :)

**Comment by MBilderbeek** [comment]
Hmm, I can't find the Beer FDISK program. Only a basic version which doesn't include the BIN file... any idea?

**Comment by MBilderbeek** [comment]
OK, results so far are here: http://www.msx.org/forum/msx-talk/hardware/beer-ide-fdisk
But now I'm stuck. No idea what's going wrong now... do you know if there's someone who can help?

**Comment by sdsnatcher** [comment]
Here's the Beer IDE utility kit. Just rename the file to .zip.

![beer-ide_utilities](https://cloud.githubusercontent.com/assets/13080763/8919719/243ff0ac-3498-11e5-9e63-ad487ac06220.png)

**Comment by MBilderbeek** [comment]
Well, it's implemented as far as I could. As the software isn't really working well, and no one can tell me if that's OK or not (see that MRC thread), I'd better just close this ticket until someone files a bug report against that emulation :P
