### ISSUE TITLE
[bug] Speed throttle and set speed >100 don't work with set frameskip=0

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#973]
Speed throttle (CMD+T on OS-X) doesn't seem to work when frameskip is set to zero. "set speed 200" doesn't work either.

Tested on: openMSX-0.11.0 on Mac OS-X 10.9.5.

Steps to reproduce the problem:

1) Boot a Sanyo PHC-70FD
2) open the console and type "set frameskip 0"
3) Press CMD+T (F9 on PC) to try to throttle the emulation speed. Even with only 20% of the host CPU being used, the emulator refuses to run any faster.
4) Press CMD+T (F9 on PC) to disable the throttle mode
5) open the console again, and type "set speed 200". Again, even with only 20% of the host CPU being used, the emulator refuses to run any faster.

I also tried switching between the SDLGL-PP and the SDL renderer, but that didn't make any difference.

**Comment by MBilderbeek** [comment]
I have the same problem. Looks like SDL is using the maximum framerate that the video driver allows. And my driver is by default set to allow a maximum frame rate which is equal to the frame rate of my monitor: 60Hz. But this only happens on SDLGL-PP renderer here. With SDL renderer, I can go to much higher than 60fps. Also, I used to be able to disable this by unchecking "Sync to Vblank" in the nvidia-settings tool. But that doesn't seem to be of influence anymore.

Anyway, just a me-too here.

Also, I guess you meant 'maxframeskip' setting? There is no plain 'frameskip' setting anymore as of April 2004 :) Anyway, I set it now to 100, so I can still easily use fast-forward.

I don't know if something can be done about this. Perhaps SDL can be persuaded to change this behaviour with some tweaks, no idea.

**Comment by MBilderbeek** [comment]
Or is the issue that you used the wrong setting name? (frameskip instead of maxframeskp)

**Comment by sdsnatcher** [comment]
It was in fact maxframeskip. I was away from my machine when I opened the ticked and recalled the incorrect keyword for the setting.

I vaguely remember that the problem had something to do with using the rendered SDL instead of SDLGL.

I tested again and it seems to be working fine on openMSX-0.12.0 with either SDL and SDLGL renderers, so I guess this issue can now be closed.
