### ISSUE TITLE
[feature] Printer port debuggable

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#984]
Please consider adding a debuggable for the printer port.

Unlike the joystick ports, the printer port currently has no debuggable of its own.

Without such debuggable it's not possible to know the current state of the printer port latches (either DATA port or the strobe port), thus making it very difficult to debug programs that use this port.

**Comment by m9710797** [comment]
Implemented in revision 74abb7c37d9.

**Comment by sdsnatcher** [comment]
Thanks, Wouter!    :)
