### ISSUE TITLE
[bug] Panasonic/Sanyo Switched I/O ports emulation

### ISSUE THREAD

**Issue by sdsnatcher** [openMSX/openMSX#988]
After reverse engineering, I discovered some things missing in the Panasonic and Sanyo switched I/O ports emulation.

The Sanyo MSX2+ machines also feature the same switched I/O ports as the Panasonic MSX2+ machines. In fact they have almost the same gate array controlling the bus, with the exactly the same pinout. The only difference is that the turbo function seems to have been stripped out of the gate array on Sanyo machines.

But the rest of the gate array is fully functional. And it can be written/read via switched I/O ports just like on the Panasonic machines.

So, the first part of the bug report is that the switched I/O port emulation is missing on Sanyo MSX2+ machines on openMSX.

The second part, openMSX only emulates the bit7 of the I/O port 41h read. But it has other bits. This is its format:

• Bit0: Turbo status. 0=on
• Bit2: 0=Turbo feature is available?   (this means 0 on Panasonic and 1 on Sanyo)
• Bit7: Firmware switch

Note: the turbo status will behave normally on Sanyo machines. It just won't activate any clock change. We even tried injecting a turbo clock in the proper pin, but the array just ignored it.

**Comment by MBilderbeek** [comment]
Hi,

According to the current emulation in the  MSXMatsushita device, the SwitchedIO implementation in the Panasonics (which has this name, as it has Maker ID 0x08):
Read:
port 0x41: firmware switch status
port 0x43: a pattern
port 0x49: increase SRAM address by 1
Write:
port 0x41: bit0 = 1: 3.58MHz, bit0=0: 5.37MHz
port 0x43: color nibbles
port 0x44: pattern value
port 0x47: set SRAM address (low)
port 0x48: set SRAM address (high)
port 0x49: write SRAM

So if I understand correctly, the turbo status and feature are also available when reading port 0x41?

On the Sanyo, what maker ID do you get? 
For which Sanyo machines are you sure this is applicable?
For these Sanyos, can you confirm all of the above functionality is present on them? (If yes, what would for instance that firmware switch stuff do on it?)

**Comment by sdsnatcher** [comment]
> So if I understand correctly, the turbo status and feature are also available when reading port 0x41?

Yes.

> On the Sanyo, what maker ID do you get? 

Maker ID=8.  Yes, this means Matsushita.

> For which Sanyo machines are you sure this is applicable?

For sure, the Sanyo PHC-70FD and PHC-70FD2. I'm almost sure that this is also applicable for the PHC-35J.

> For these Sanyos, can you confirm all of the above functionality is present on them?
> (If yes, what would for instance that firmware switch stuff do on it?)

The Sanyo machines have no firmware switch, so the respective pin in the gate array is unconnected and the respective bit on I/O port 41h always reads 1. They also have no built-in SRAM, as this is used only by the built-in firmware on Panasonic MSX2+ machines.

I have no idea how to test the other ports, specially the color and patterns ports. How do they work and how can I test them?

**Comment by MBilderbeek** [comment]
Looking at the code:
port & 0x0F = 3: read it and you get:
                result = (((pattern & 0x80) ? color2 : color1) << 4)
                        | ((pattern & 0x40) ? color2 : color1);
write it and this will happen to the value:
                color2 = (value & 0xF0) >> 4;
                color1 =  value & 0x0F;
write the next port and it will store the pattern there.

If you wish I can run any test program you send me on my PHC-35J.

**Comment by sdsnatcher** [comment]
But what I still don't get is where this patterns and colors come from? The VRAM? What's this feature used for?

I created a small BASIC utility to help those who gather info/roms to create openMSX machines. It was included in the "openMSX Reverse Engineering utility package".

The tool scans the switched I/O ports and reports any devices it finds. Try running it on your PHC-35J to see if it finds anything.

[SWIOSCAN.zip](https://github.com/openMSX/openMSX/files/121518/SWIOSCAN.zip)

**Comment by MBilderbeek** [comment]
OK, I ran it on my PHC-35J and it detects indeed a Switched I/O device with ID 8.

**Comment by MBilderbeek** [comment]
So, now I wonder what is exactly featured on the National FS-4500 and FS-4700 there. It seems it needs a Matsushita switched I/O device for the internal word processor to work properly. Without it, it doesn't show the 12x12 font ROM. But what is exactly present in these machines of this device? Does it really have the SRAM too? (It seems to work fine without it.)

**Comment by sdsnatcher** [comment]
The pictures of the FS-4600 & FS-4700 on usbsecretbase shows a Z80A in each, so they can't have the turbo.  Unless, well, it's a 4MHz turbo that wouldn't do much of a difference.

Probably the GA only does the Kanji I/O logic and the other functions like the GA of the NMS-8245 as I mentioned in the other thread.

(Except the FS-4700 disk interface, as the picture show it's made with discrete components)

**Comment by MBilderbeek** [comment]
I think I've implemented this ticket now. Please confirm. You can reopen if it's not correct :)
