### ISSUE TITLE
step_back gives Internal error: overshot destination on turboR

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#990]
`<grauw> when I enter step_back in the console, it gives the error "Internal error: overshot destination"`

Only happens on a turboR.

`<wouterv> can you bisect it?`
`<grauw> sure`
`<grauw> culprit is` cf0dff1813b8bccc156bb8369fc3af40cfd01715 `Improved R800 timing for the CALL instruction`

**Comment by grauw** [comment]
I noticed because the debugger was acting up on latest dev build when stepping back.

Not sure it only happens on turboR btw, that’s just the only machine I tried it on.

**Comment by MBilderbeek** [comment]
It worked fine on Boosted MSX2 EN, that's why I think it only happens on turboR. Also seems kind of logical if we look at that culprit... but I didn't test any other machines, so you never know.
