### ISSUE TITLE
FM Voice Data isn't loaded for some programs

### ISSUE THREAD

**Issue by MBilderbeek** [openMSX/openMSX#996]
See http://www.msx.org/forum/msx-talk/general-discussion/converting-cx5m-cassettes-cas-format for the original discussion.

Summary:
- FM Voice Data is a set of cassettes with voice data for the Yamaha FM module programs.
- This data can be loaded from several of these programs using a specific command
- In some programs the data is loaded fine, e.g. in FM Music Macro (witih _CLDV) and in YRM-102 (FM Voicing Program) with: CL. However, only (most of) the CAS images work. This tells me: the CAS images are OK. The original WAV files are not picked up at all (see another ticket regarding WAV files not always working)
- In other programs, the data is ignored (not picked up). Examples: FM Voicing Program II (YRM-502, which is also built in in the Yamaha CX5MII): first enter CALL FMV, then enter TR in the application, then CL in the Load/Save menu and it also doesn't load in FM Music Composer (using: cload=voice)

The tapes work fine on real YRM-502 (but only the original tape has been confirmed, not the CAS converted back to WAV).

All images and manuals are here: https://drive.google.com/folderview?id=0Bxdaz0FiI5PuQnJpQ3ctSXJiWUE&usp=sharing

**Comment by MBilderbeek** [comment]
When I change the WAV file from:
1Amono.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
to
1Amono2.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 8 bit, mono 44100 Hz

it suddenly gets picked up!

**Comment by MBilderbeek** [comment]
In the mean time I can also reproduce it with a WAV file. So, just ignore the WAV vs CAS difference, it doesn't seem to matter.

**Comment by prismprocess** [comment]
"The tapes work fine on real YRM-502 (but only the original tape has been confirmed, not the CAS converted back to WAV)"

The cas converted back to wav works on a real CX5MII/128 with YRM-502.

See here.......

http://www.msx.org/forum/msx-talk/general-discussion/converting-cx5m-cassettes-cas-format?page=3

(At the very bottom)

**Comment by MBilderbeek** [comment]
However, in that thread you also say the original WAV played back to MSX does NOT work, right?

**Comment by prismprocess** [comment]
I have not tried that. I only tried on the real CX5M/ii 128 the original tapes (which should and do work) and the reworked wav as you asked me to this morning. I am guessing that the original wav will work too. It seems there is something that OpenMSX does not like about the original wav until it has been wav2cas then cas2way. It also does not like my KORG microkey much either btw.

**Comment by prismprocess** [comment]
Correction, I did try the unprocessed wav and it did not work on the real CX5MI/128.

**Comment by MBilderbeek** [comment]
Oh, well, that's then quite consistent :) Now we should try the postprocessed CAS2WAV file in openMSX. If it works, openMSX did nothing wrong at all :)

**Comment by MBilderbeek** [comment]
Aha, no openMSX bug indeed, as prismprocess wrote on MRC:

" I have worked out how to load the cas in OpenMSX. Still cant make it load in BlueMSX.....

The trick is not to select the cas file until you have typed in CL. So CALL FMV, TR then CL (dont hit return)."

Apparently these programs start the cassette motor too early or something. Better close this bug then.
